### ISSUE TITLE
How to parse NV-InferResponse header fastly in HTTP response?

### ISSUE THREAD

**Issue by zxgm** [NVIDIA/tensorrt-inference-server#1010]
I have retrieved NV-InferResponse header content by used response.headers.get("NV-InferResponse") ,but it's a string type.For result example:

> model_name: "serving_model" model_version: 1 batch_size: 1 output { name: "prediction" raw { dims: 2 batch_byte_size: 8 } }

I want get batch_byte_size value,so i must to parse the header content,but i want not to call string find  function to retrieve it,Can i use api.proto convert to api_pb2.py to retrieve it? The code follows:

>     res_buffer=b'model_name: "serving_model" model_version: 1 batch_size: 1 output { name: "prediction" raw { dims: 2 batch_byte_size: 8 } }'
> 
>     irh = InferResponseHeader()
>     irh.ParseFromString(res_buffer)
>     server_dict = protobuf_to_dict(irh)
But exec uteParseFromString function, hit the error:

> google.protobuf.message.DecodeError: Error parsing message

How to use protobuf ParseFromString function to parse the NV-InferResponse header content?

**Comment by deadeyegoodwin** [comment]
In the TRTIS c++ client library a built-in protobuf function is used... there should be something equivalent in Python.

https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/c%2B%2B/library/request_http.cc#L1700
