### ISSUE TITLE
deploying model using trtis is much slower than using frozen model directly

### ISSUE THREAD

**Issue by HoangTienDuc** [NVIDIA/tensorrt-inference-server#1019]
after optimizing yolov3 using tf-tensorrt optimization, i infer in two way.
1. using trtis (~20fps) + bellow warning
```
layout failed: Invalid argument: The graph is already optimized by layout optimizer.
```
2. using frozen directly (~54 fps)

**Comment by deadeyegoodwin** [comment]
We need more information about the model configuration you are using and how you are invoking TRTIS.

**Comment by HoangTienDuc** [comment]
my model configuration:
```
name: "vehicle-detector"
platform: "tensorflow_graphdef"
max_batch_size: 8

input [
    {
        name: "Placeholder"
        data_type: TYPE_FP32
        dims: [416, 416, 3 ]
    }
]
output [
   {
      name: "concat_9"
      data_type: TYPE_FP32
      dims: [ 10647, 4 ]
      label_filename: "labels.txt"
   },
   {
      name: "mul_9"
      data_type: TYPE_FP32
      dims: [ 10647, 80 ]
      label_filename: "labels.txt"
   }
]
instance_group [
   {
      kind: KIND_GPU
      count: 1
      gpus: [ 0 ]
   }
]
```
i invoke trtis like bellow:
```
request_ids.append(ctx.async_run(
        { input_name : [img_resized]},
        { output_name_1 : (InferContext.ResultFormat.RAW),
          output_name_2 : (InferContext.ResultFormat.RAW)}, 1))

for i, request_id in enumerate(request_ids):
    vals = ctx.get_async_run_results(request_id, True) 
```

**Comment by deadeyegoodwin** [comment]
Are you actually providing a labels.txt? Given the dimension of those outputs the file would need to have 10647*80=850k+ entries... but that isn't related to your issue.

So you are using the offline TF-TRT conversion to create a graphdef, and then running that in TRTIS and also using some script that uses the TF API to load and run it directly?

What version of TRTIS are you using? Have you tried using perf_client with TRTIS and see what performance that gives you for various concurrency levels? Make sure you read this section of the documentation: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/optimization.html

**Comment by HoangTienDuc** [comment]
Are you actually providing a labels.txt? Given the dimension of those outputs the file would need to have 10647*80=850k+ entries... but that isn't related to your issue.
```
I don't use the label.txt file
```
So you are using the offline TF-TRT conversion to create a graphdef, and then running that in TRTIS and also using some script that uses the TF API to load and run it directly?
```
yes
```
What version of TRTIS are you using?
```
I have tried many versions of TRTIS (03, 04, 05, 06, 07, 10, 11 and 12)
```
 Have you tried using perf_client with TRTIS and see what performance that gives you for various concurrency levels? Make sure you read this section of the documentation: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/optimization.html
```
No, I've never used a perf_client
```
It seems that using the direct optimizer on trtis is available in recent versions. I didn't update documents so I don't know yet. I think the offline optimizer is not the problem.

**Comment by deadeyegoodwin** [comment]
Closing. Please reopen with perf_client results if those still show a problem
