### ISSUE TITLE
Failed to deserialize trt model.

### ISSUE THREAD

**Issue by dcmrlee** [NVIDIA/tensorrt-inference-server#1020]
**Description**
I build a simple mnist tensorrt model and want to do inference by using TRTIS. But an error comes out when load model:
```
trtserver: engine.cpp:1104: bool nvinfer1::rt::Engine::deserialize(const void*, std::size_t, nvinfer1::IGpuAllocator&, nvinfer1::IPluginFactory*): Assertion `size >= bsize && "Mismatch between allocated memory size and expected size of serialized engine."' failed.
```

**TRTIS Information**
I am using TRTIS container with version: nvcr.io/nvidia/tensorrtserver:19.05-py3

**To Reproduce**
The config.pbtxt is like this:
```
name: "mnist_trt"
platform: "tensorrt_plan"
max_batch_size: 1
input [
  {
    name: "image"
    data_type: TYPE_FP32
    dims: [28, 28]
  }
]
output [
  {
    name: "probabilities"
    data_type: TYPE_FP32
    dims: [10]
  }
]
instance_group [
  {
    kind: KIND_GPU
    count: 1
    gpus: [0]
  }
]
```

The model I use can be downloaded in the:
[Link](https://pan.baidu.com/s/1JDpTDiPUSSw-3bLqQnLDBg), retrieve code: p6y9

**Comment by deadeyegoodwin** [comment]
What version of TensorRT did you use to generate the model. TensorRT is not backward-compatible so you must use the same version of TensorRT to generate the model as is being used by TRTIS that you are running. See the README for pointers to release notes where there is version information.

I also suggest that you update to a more recent TRTIS.

**Comment by dcmrlee** [comment]
Thanks for the advice! Fixed by using the same version of TensorRT with TRTIS container.
