### ISSUE TITLE
How to optimize config file for MaskRCNN trt model on V100?

### ISSUE THREAD

**Issue by rtrobin** [NVIDIA/tensorrt-inference-server#1021]
**Description**
I am running TensorRT MaskRCNN model, which is given by nvidia [TensorRT repo](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN). How to optimize this kind of models' config file to fully utilize gpu usage?

**TRTIS Information**
nvcr.io/nvidia/tensorrtserver:19.12-py3

**To Reproduce**
Based on nv [TensorRT repo](https://github.com/NVIDIA/TensorRT/tree/master/samples/opensource/sampleUffMaskRCNN), I built and serialized both fp32/ fp16 TensorRT engines on V100. I have tried dynamic batch and multiple model instances and mixed two features also. Measuring by `perf_client --concurrency-range 1:64` command, fp32 engine has highest 15.2 infers/sec, and fp16 engine has highest 24.4 infers/sec.

To compare, I also reproduced the same procedure on 1080ti. Here, fp32 engine has highest 12.8 infers/sec, and fp16 engine has highest 13.4 infer/sec. 1080ti doesn't have tensor core or fp16 precision support. So it's a reasonable result on 1080ti.

Comparing results on V100 and 1080ti, V100 doesn't perform well enough as expected. I observed the gpu usage by `watch -n 1 nvidia-smi`. During perf running on 1080ti, the gpu could keep usage on 95-100%. However on V100, the gpu could only run on 50% more or less.

Could anyone share some experience on how to fully utilize gpu usage on V100?

**Comment by deadeyegoodwin** [comment]
Have a look at the optimization section of the documentation: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/optimization.html#optimization

There is a new section on tracing that you can use to find out more information about where the time is being spent in TRTIS. It may give more insight into why V100 is not reaching higher GPU utilization:  https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/optimization.html#server-trace

**Comment by rtrobin** [comment]
@deadeyegoodwin Thanks for the advice. I'm in the middle of an urgent task. I will make a try later and post feedback.

**Comment by deadeyegoodwin** [comment]
Closing. Re-open with feedback when it is available.
