### ISSUE TITLE
How can we share variables between distinct custom backends in the ensemble-model ?

### ISSUE THREAD

**Issue by hnishi** [NVIDIA/tensorrt-inference-server#1026]
Hello. Thank you for the work on this project.
I have a problem.

I want to use yolov3 model (with pre-trained wieghts, tensorflow-backend) with [ensemble-model](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/models_and_schedulers.html?highlight=ensemble#ensemble-models) implementing pre- and post-processes.

My ensemble model would be

preprocess (custom backend) --> yolov3 (tensorflow backend) --> postprocess (custom backend).

In the preprocess, input images are resized to the input of yolov3.
In the postprocess, outputs of yolov3 (detection boxes) are resized to the (original) input image.

How can I pass the size of input image from preprocess-backend to postprocess-backend ?

**Comment by deadeyegoodwin** [comment]
You can have an output tensor of shape [ 2 ] and type UINT32 on your preprocess-backend that communicates the size of the image and a corresponding input tensor on the postprocess-backend. In the ensemble just connect the output to the input.

**Comment by hnishi** [comment]
@deadeyegoodwin
Thank you for your comment.

Does it mean my preprocess-backend have two outputs ?
1. preprocessed image (dims: [ 416, 416, 3 ])
2. size of image (dims: [ 2 ])

In that case, my postprocess-backend have two inputs ?
1. output of yolov3 (dims: [ 10647, 85 ])
2. size of image (dims: [ 2 ])

**Comment by deadeyegoodwin** [comment]
Yes, that is what I'm suggesting. I don't know what you mean by the last statement.

**Comment by hnishi** [comment]
Thank you. I will try it !

**Comment by hnishi** [comment]
It worked! many thanks !

my config.pbtxt of the ensemble looks like

```protobuf
name: "ensemble_darknet"
platform: "ensemble"
max_batch_size: 128
input [
  {
    name: "INPUT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "OUTPUT"
    data_type: TYPE_FP32
    dims: [ -1, 6 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "preprocess_darknet"
      model_version: -1
      input_map {
        key: "INPUT"
        value: "INPUT"
      }
      output_map {
        key: "OUTPUT0"
        value: "preprocessed_image"
      }
      output_map {
        key: "OUTPUT1"
        value: "size_orig_image"
      }
    },
    {
      model_name: "darknet_graphdef"
      model_version: -1
      input_map {
        key: "inputs"
        value: "preprocessed_image"
      }
      output_map {
        key: "output_boxes"
        value: "out_darknet"
      }
    },
    {
      model_name: "postprocess_darknet"
      model_version: -1
      input_map {
        key: "INPUT0"
        value: "out_darknet"
      }
      input_map {
        key: "INPUT1"
        value: "size_orig_image"
      }
      output_map {
        key: "OUTPUT"
        value: "OUTPUT"
      }
    }
  ]
}
```
