### ISSUE TITLE
Tensorflow 2.0 models with TRTIS

### ISSUE THREAD

**Issue by mhunsake** [NVIDIA/tensorrt-inference-server#1029]
**Description**
I trained a inception model on my own data starting from tf.keras.applications.InceptionV3.  The model was saved with tf.saved_model.save.  I copied the model into repository directory.
```
models/
    hello_world/
        config.pbtxt
        labels.txt
        1/
            model.saved_model/
                saved_model.pb
                variables/
                assets/
```
When I try to start TRTIS server, I get error 
_E0115 03:15:16.215663 1 model_repository_manager.cc:832] failed to load 'hello_world' version 1: Internal: unable to find model 'model.savedmodel' for hello_world_

**TRTIS Information**
I"m using nvcr.io/nvidia/tensorrtserver:19.12-py3

**To Reproduce**
Train model in tensorflow 2.0, save with tf.saved_models.save, add to repository. follow quick start guide for starting tensorrt instance server 

**Expected behavior**
Tensorflow 2.0 models should be supported by TRTIS

**Comment by nieksand** [comment]
The message says: " unable to find model 'model.savedmodel' for hello_world"

You have a directory with an underscore: "model.saved_model/"

Try removing that underscore perhaps?

**Comment by mhunsake** [comment]
Thanks!! That did it.  Too many hours staring at a computer today... didn't catch the _.

**Comment by luvwinnie** [comment]
Hi! I'm trying to use savedmodel with TRTIS, is it my directory correct? i got the error as below when i have the following directory tree.
```
models/
    classifier/
        1/
            model.saved_model/
                saved_model.pb
                variables/
                assets/
```

```
2020-03-20 09:48:40.825799: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1767] Adding visible gpu devices: 0, 1
2020-03-20 09:48:40.826127: I tensorflow/cc/saved_model/loader.cc:332] SavedModel load for tags { serve }; Status: fail. Took 308139 microseconds.
I0320 09:48:40.834432 1 autofill.cc:140] TensorFlow SavedModel autofill: Internal: unable to autofill for 'classifier', unable to find savedmodel directory.
I0320 09:48:40.840851 1 autofill.cc:151] TensorFlow GraphDef autofill: Internal: unable to autofill for 'classifier', unable to find graphdef file named 'model.graphdef'
I0320 09:48:40.840879 1 autofill.cc:164] PyTorch autofill: Internal: unable to autofill for 'classifier', unable to find PyTorch file named 'model.pt'
I0320 09:48:40.840895 1 autofill.cc:177] Caffe2 NetDef autofill: Internal: unable to autofill for 'classifier', unable to find netdef files: 'model.netdef' and 'init_model.netdef'
I0320 09:48:40.840919 1 autofill.cc:200] ONNX autofill: Internal: unable to autofill for 'classifier', unable to find onnx file
I0320 09:48:40.840935 1 autofill.cc:213] TensorRT autofill: Internal: unable to autofill for 'classifier', unable to find a compatible plan file.
W0320 09:48:40.840939 1 autofill.cc:238] Proceeding with simple config for now
I0320 09:48:40.840942 1 model_config_utils.cc:276] autofilled config: name: "classifier"
```

**Comment by deadeyegoodwin** [comment]
Why are you asking a question on an existing, closed, unrelated issue? Can you open a new issue with the question?
