### ISSUE TITLE
How to transfer request to sequence model on trtis by http?

### ISSUE THREAD

**Issue by zxgm** [NVIDIA/tensorrt-inference-server#1032]
I transfer request to sequence model by http protocol.
Now,first NV-InferRequest is:

> flags:1 correlation_id:123 batch_size:1 input { name:'INPUT' dims:1 } output { name:'OUTPUT' }

request body: > b'\t\x00\x00\x00'

Second NV-InferRequest is:

> flags:0 correlation_id:123 batch_size:1 input { name:'INPUT' dims:1 } output { name:'OUTPUT' }

request body: > b'\x0b\x00\x00\x00'

The first request is work,and return OK,but the second request hit error,the error message:

> {"error": "code: INVALID_ARG msg: \"inference request for sequence 123 to model \\'serving_model\\' must specify the START flag on the first request of the sequence\" server_id: \"inference:0\" request_id: 23"}
I found the source code is follow: 

> auto sb_itr = sequence_to_batchslot_map_.find(correlation_id);
>   auto bl_itr = sequence_to_backlog_map_.find(correlation_id);
> 
>   // If this request is not starting a new sequence its correlation ID
>   // should already be known with a target in either a slot or in the
>   // backlog. If it doesn't then the sequence wasn't started correctly
>   // or there has been a correlation ID conflict. In either case fail
>   // this request.
>   if (!seq_start && (sb_itr == sequence_to_batchslot_map_.end()) &&
>       (bl_itr == sequence_to_backlog_map_.end())) {
>     OnComplete(Status(
>         RequestStatusCode::INVALID_ARG,
>         "inference request for sequence " + std::to_string(correlation_id) +
>             " to model '" + request_provider->ModelName() +
>             "' must specify the START flag on the first request of the "
>             "sequence"));
>     return;
>   }
Now i not know why sb_itr == sequence_to_batchslot_map_.end(),and how to set the value of the request flags param?

**Comment by GuanLuo** [comment]
Are you sending two requests in parallel? And can you tell me what version of TRTIS are you using?

**Comment by GuanLuo** [comment]
Can you also provide the verbose server log (start server with `--log-verbose=1`)? And can you also provide your client code for sending the requests?

**Comment by zxgm** [comment]
When I have opened verbose option, then accessed 'http://localhost:8000/api/status',that error happended.

> ConnectionError:HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/status?format=binary (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1a7aa7198>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by zxgm** [comment]
When I have opened verbose option, If TRTIS log file have "Starting Metrics Service" lines on images version 19.09,I think the TRTIS have started,it can be work.then accessed 'http://localhost:8000/api/status' ,that error happended.

> ConnectionError:HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /api/status?format=binary (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa1a7aa7198>: Failed to establish a new connection: [Errno 111] Connection refused',))
