### ISSUE TITLE
What format is the status in?

### ISSUE THREAD

**Issue by whillas** [NVIDIA/tensorrt-inference-server#1038]
**Description**
I want to parse the status message and use the info in a TRTIS client. what format does it follow? 

**TRTIS Information**

What version of TRTIS are you using?
19.10

Are you using the TRTIS container or did you build it yourself?
container

**Comment by GuanLuo** [comment]
The status will be text protobuf formatted [RequestStatus](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/protobuf_api/request_status.proto.html#_CPPv4N6nvidia15inferenceserver13RequestStatusE) message.

**Comment by deadeyegoodwin** [comment]
There are both C++ and Python examples that show how to read the status in src/clients.

**Comment by whillas** [comment]
Yeah, thats great if you have the model names up front. I have 108 models and don't have a list.
