### ISSUE TITLE
unexpected shape for input 'input' for model 'lp-detector'

### ISSUE THREAD

**Issue by tienduchoang** [NVIDIA/tensorrt-inference-server#104]
i write a client code for my model. But i got this issue. need a help

*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /api/status/lp-detector?format=binary HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*

< HTTP/1.1 200 OK
< Content-Type: application/octet-stream
< NV-Status: code: SUCCESS server_id: "inference:0" request_id: 37
< Date: Thu, 21 Feb 2019 16:11:31 GMT
< Content-Length: 215
< 
* Connection #0 to host localhost left intact
id: "inference:0"
version: "0.12.0dev"
uptime_ns: 5898616829963
model_status {
  key: "lp-detector"
  value {
    config {
      name: "lp-detector"
      platform: "tensorflow_graphdef"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      max_batch_size: 8
      input {
        name: "input"
        data_type: TYPE_FP32
        dims: 3
      }
      output {
        name: "concatenate_1_output"
        data_type: TYPE_FP32
        dims: 2
        label_filename: "labels.txt"
      }
      instance_group {
        name: "lp-detector_0"
        count: 4
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "model.graphdef"
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
        infer_stats {
          key: 0
          value {
            failed {
              count: 8
              total_time_ns: 791063
            }
          }
        }
      }
    }
  }
}
ready_state: SERVER_READY

image.dims:  3
scaled.ndim:  3
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api/infer/lp-detector?format=binary HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*
Content-Type: application/octet-stream
NV-InferRequest:batch_size: 8 input { name: "input" dims: 1000 dims: 800 dims: 3 } output { name: "concatenate_1_output" }
Content-Length: 9600000

* We are completely uploaded and fine
< HTTP/1.1 400 Bad Request
< NV-InferResponse: 
< NV-Status: code: INVALID_ARG msg: "unexpected shape for input \'input\' for model \'lp-detector\'" server_id: "inference:0"
< Content-Type: application/octet-stream
< Date: Thu, 21 Feb 2019 16:11:31 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
Traceback (most recent call last):
  File "clients.py", line 27, in <module>
    8)
  File "/usr/local/lib/python3.5/dist-packages/tensorrtserver/api/__init__.py", line 844, in run
    self._last_request_id = _raise_if_error(c_void_p(_crequest_infer_ctx_run(self._ctx)))
  File "/usr/local/lib/python3.5/dist-packages/tensorrtserver/api/__init__.py", line 183, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: [inference:0 0] unexpected shape for input 'input' for model 'lp-detector'

**Comment by deadeyegoodwin** [comment]
In your model configuration it looks like the "input" tensor shape is  [ 3 ].
But the numpy array you passed for that tensor seems to have shape [ 1000, 800, 3 ].
