### ISSUE TITLE
Where to find the model def for image_preprocess_nchw_3x224x224_inception?

### ISSUE THREAD

**Issue by gyang274** [NVIDIA/tensorrt-inference-server#1043]
Docker pulled TRTIS 19.12-py3 image from NGC.

Git cloned the master repo and checked out r19.12.

Trying the run the server with ensemble_model_repository. Downloaded the resnet50_netdef using fetch_models.sh, created an empty folder named `1` under preporcess_resnet50_ensemble. But where to find the model def for image_preprocess_nchw_3x224x224_inception?

```
$ tree ensemble_model_repository/
ensemble_model_repository/
├── image_preprocess_nchw_3x224x224_inception
│   ├── 1 <--- ??? where to get model def file?
│   └── config.pbtxt
├── preprocess_resnet50_ensemble
│   ├── 1
│   └── config.pbtxt
└── resnet50_netdef
    ├── 1
    │   ├── init_model.netdef
    │   └── model.netdef
    ├── config.pbtxt
    └── resnet50_labels.txt

6 directories, 6 files
```

```
$ docker run --gpus all -p 8000:8000 -p 8001:8001 -p 8002:8002 \
  --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 \
  -v /absolute/path/to/tensorrt-inference-server/docs/examples/ensemble_model_repository:/models \
  nvcr.io/nvidia/tensorrtserver:19.12-py3 trtserver --model-repository=/models
```

Thank you!

**Comment by mhunsake** [comment]
there is not model per se, but rather the .so generated by the custombackend.  Check docs for custom backend.    What I did was build the docker image defined in tensorrt-inference-server/Dockerfile.custombackend, open the container (while mapping in a folder with -v), and then copy libimagepreprocess.so from /workspace/install/custom-backend-sdk/lib to my mapped in volume to get it out of the container. Dockerfile.custombackend shows the details of cmake/install.    Copy the libimagepreprocess.so to ensemble_model_directory/image_prococess_nchw_3x224x224_inception/1/.

**Comment by gyang274** [comment]
@mhunsake Thanks. It should work, built the docker image, copied the libimagepreprocess.so out from docker to //ensemble_model_directory/image_prococess_nchw_3x224x224_inception/1/, get message:

```
E0121 01:14:41.830431 1 model_repository_manager.cc:832] failed to load 'image_preprocess_nchw_3x224x224_inception' version 1: Not found: unable to load custom library: libopencv_imgcodecs.so.3.2: cannot open shared object file: No such file or directory
```

This should related to the opencv. Will follow up.

**Comment by zhouxuan009** [comment]
Have you found any solution ? I met the same problem -- "unable to load custom library: libopencv_imgcodecs.so.3.2"

**Comment by deadeyegoodwin** [comment]
That backend requires OpenCV, so you need to install the OpenCV libraries on your system. The following is probably sufficient (or just the non-dev packages should work):

$ apt-get install libopencv-dev libopencv-core-dev

**Comment by zhouxuan009** [comment]
@deadeyegoodwin I have installed opencv 3.2 from source code, got libopencv_imgcodecs.so.3.2 and put it under /docs/examples/ensemble_model_repository/image_preprocess_nchw_3x224x224_inception/1.
However, It still does not work.

**Comment by deadeyegoodwin** [comment]
Is it on your library path (via LD_LIBRARY_PATH or other mechanism?).

**Comment by zhouxuan009** [comment]
Yes. Opencv libraries are under ~/Softwares/opencv-install/lib. I wrote "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/Softwares/opencv-install/lib
" into ~/.bashrc. What's more, I wrote the same path into /etc/ld.so.conf.d/opencv.conf 

After I run "docker run --gpus all --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/home/zhouxuan/tensorrt-inference-server/docs/examples/ensemble_model_repository:/models nvcr.io/nvidia/tensorrtserver:20.01-py3 trtserver --model-repository=/models" .

The terminal gave me error message -- "I0206 21:12:50.565055 1 custom_backend.cc:194] Creating instance image_preprocess_nchw_3x224x224_inception_0_gpu0 on GPU 0 (7.5) using libimagepreprocess.so
E0206 21:12:50.565540 1 model_repository_manager.cc:832] failed to load 'image_preprocess_nchw_3x224x224_inception' version 1: Not found: unable to load custom library: libopencv_imgcodecs.so.3.2: cannot open shared object file: No such file or directory
"

**Comment by deadeyegoodwin** [comment]
libimageproprocess.so is just a shared library and it resolves its dependencies like any other shared library. Did you run "ldd libimagepreprocess.so" in the same environment/shell as you are running trtserver? Did it show the libopencv_imgcodecs.so.3.2 as being found?

**Comment by zhouxuan009** [comment]
Yes. it show the libopencv_imgcodecs.so.3.2 as being found.

Below is part of the print message

~/tensorrt-inference-server/docs/examples/ensemble_model_repository/image_preprocess_nchw_3x224x224_inception/1$ ldd libimagepreprocess.so
	linux-vdso.so.1 (0x00007ffc47eb2000)
	libopencv_imgcodecs.so.3.2 (0x00007f082ecc6000)
	libopencv_imgproc.so.3.2 => /home/zhouxuan/Softwares/opencv-install/lib/libopencv_imgproc.so.3.2 (0x00007f082d4ae000)
	libopencv_core.so.3.2 => /home/zhouxuan/Softwares/opencv-install/lib/libopencv_core.so.3.2 (0x00007f082c025000)

**Comment by zhouxuan009** [comment]
@deadeyegoodwin  Should I install opencv inside the container or outside ?

**Comment by deadeyegoodwin** [comment]
You need to install it inside the container.

**Comment by zhouxuan009** [comment]
OHHHHHH  thank you very much ! That's the key. I can run it now

**Comment by zf921022** [comment]
> OHHHHHH thank you very much ! That's the key. I can run it now

how to install opencv inside the container? I am confused about which container to install the opencv inside.

**Comment by flyingmrwang** [comment]
@deadeyegoodwin 
Hi, I succeed to install opencv whtin docker. To avoid installing everytime I run the docker, I moved the .so out of container and to  "ensemble_model_repository/image_preprocess_nchw_3x224x224_inception/1". 

When running the server again, it still says "unable to load custom library: libopencv_imgcodecs.so.3.2". 

And ldd shows: warning: you do not have execution permission for `docs/examples/ensemble_model_repository/image_preprocess_nchw_3x224x224_inception/1/libopencv_imgcodecs.so.3.2'. 

Any suggestion?
