### ISSUE TITLE
What does userp mean?

### ISSUE THREAD

**Issue by npuichigo** [NVIDIA/tensorrt-inference-server#1053]
Can any explain what's userp mean in this repository?  The code shows userp is a pointer to an async rpc state, so what's the full name of it?

**Comment by deadeyegoodwin** [comment]
userp is short for "user pointer". It is typically used as a void* parameter in a callback function and allows the implementer of the callback function to have some arbitrary state passed into the callback.

Is there a particular instance of userp that you are asking about?

**Comment by npuichigo** [comment]
Thanks!
