### ISSUE TITLE
No postprocessing in case of aync call in image_client example

### ISSUE THREAD

**Issue by ma-siddiqui** [NVIDIA/tensorrt-inference-server#1054]
In case of async trt call, post processing step has been skipped where as in case of sync call it is there. I believe there is no need of else case at line#321 (https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/examples/image_client.py)

The code indentation should be one step back (from line#321 to 324) and else case should be removed.

**Comment by deadeyegoodwin** [comment]
I think you are correct. Looks like in async mode no results will be printed. We will take a look

**Comment by ma-siddiqui** [comment]
Thank you. Much appreciated.
