### ISSUE TITLE
Thread-safety of CustomGetNextInputFn and CustomGetOutputFn

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/tensorrt-inference-server#1062]
I was not able to find any information about the thread-safety of the `CustomGetNextInputFn` and `CustomGetOutputFn` (and their V2s) that are handed to the `Execute` function of a custom backend. Is it safe to concurrently call, e.g., two `CustomGetNextInputFn`'s for different `input_context` arguments?

**Comment by GuanLuo** [comment]
Yes, you can call `CustomGetNextInputFn` on different contexts concurrently as different `input_context`s are independent to each other.
