### ISSUE TITLE
Add support for unidirectional streaming inference

### ISSUE THREAD

**Issue by npuichigo** [NVIDIA/tensorrt-inference-server#1063]
**Is your feature request related to a problem? Please describe.**
Sometimes we send a unary request to the server but get streaming response, for example, we send a sequential tensor and using a sequential model to process the input and constantly send streaming response back to the client. Another example may be speech synthesis like tacotron, where we send one sentence with a single request, but hope to get streaming media like mp3 constantly. In such cases, unidirectional streaming inference is necessary.

**Describe the solution you'd like**
I tried to implement that with something like UniStreamInferHandler, but it's not so easy to determine the state transition loop. I mean, unlike bidirectional streaming handler, we need to split the input into different events (states) with shared context (ServerAsyncWriter). So once we get the unary request, we need to spawn new events and push the first event (state) to the completion queue. In that we haven't really process the request, I can't find a good way to submit these new events, although we can just use ServerAsyncWriter.Write with empty method or ServerAsyncWriter.SendInitialMetadata to trigger the async call so that we can get the state later with CompletionQueue.Next.

**Describe alternatives you've considered**
Maybe anyone can give me some advice on how to properly trigger new events with current request.

**Additional context**
```c++
bool UniStreamInferHandler::Process(Handler::State* state, bool rpc_ok) {
  VLOG(1) << "Process for " << Name() << ", rpc_ok=" << rpc_ok
                 << ", context " << state->context_->unique_id_ << ", "
                 << state->unique_id_ << " step " << state->step_;

  // We need an explicit finish indicator. Can't use 'state->step_'
  // because we launch an async thread that could update 'state's
  // step_ to be FINISH before this thread exits this function.
  bool finished = false;

  if (state->step_ == Steps::START) {
    // A new stream connection... If RPC failed on a new request then
    // the server is shutting down and so we should do nothing.
    if (!rpc_ok) {
      state->step_ = Steps::FINISH;
      return false;
    }

    // Start a new request to replace this one...
    StartNewRequest();

    // Add extra_data_ to state->context and restore the split results of
    // current request. The following part can be called async.
    for (int i = 0; i < 10; ++i) {
      void* extra_data = reinterpret_cast<void*>(new int(i));
      state->context_->EnqueueForExtraData(extra_data);
    }

    // Since this is the start of a connection, 'state' hasn't been
    // used yet so use it to read a request off the connection.
    state->step_ = Steps::WRITTEN;
    //state->context_->responder_->Write(state->response_, state);
    state->context_->responder_->SendInitialMetadata(state);
  } else if (state->step_ == Steps::WRITTEN) {
    // If the write failed (for example, client closed the stream)
    // mark that the stream did not complete successfully but don't
    // cancel right away... need to wait for any pending inferences
    // and writes to complete.
    if (!rpc_ok) {
      VLOG(1) << "Write for " << Name() << ", rpc_ok=" << rpc_ok
                     << ", context " << state->context_->unique_id_ << ", "
                     << state->unique_id_ << " step " << state->step_
                     << ", failed";
      state->context_->finish_ok_ = false;
    }

    void* data = nullptr;
    // Pop the next extra_data for processing until the queue is empty
    if (!state->context_->PopForExtraData(&data)) {
      state->context_->step_ = Steps::COMPLETE;
      state->step_ = Steps::COMPLETE;
      state->context_->responder_->Finish(
          state->context_->finish_ok_ ? grpc::Status::OK
                                      : grpc::Status::CANCELLED,
                                        state);
    } else {
      DCHECK(data);
      // Async call the worker.
      state->step_ = Steps::ISSUED;
      pool_->ScheduleCallback([state, data] {
        // We can get current extra data for processing
        VLOG(1) << "Data: " << *reinterpret_cast<int*>(data);
        auto& response = state->response_;

        std::string content_type = "application/json";
        response.set_content_type(content_type);
        std::string value = "{\"key1\":\"value1\"";
        response.set_data(value.c_str(), value.size());

        state->step_ = WRITTEN;
        state->context_->responder_->Write(response, state);
      });
    }
  } else if (state->step_ == Steps::COMPLETE) {
    state->step_ = Steps::FINISH;
    finished = true;
  }

  return !finished;
}
```

**Comment by deadeyegoodwin** [comment]
The GRPC server handling is indeed difficult and unfortunately the GRPC project does not provide clear documentation or examples. It looks like you have found grpc_server.cc where we have our implementation. We have considered having a single-request, multiple-response mode in the server but we haven't done anything to date so I can't help on the specifics of the implementation. One thing to note is that even if you get the GRPC implementation correct, the rest of TRTIS does not have the capability of sending multiple responses for a single request.

We have encounter use-cases similar to what you describe for a project using a custom backend. For each inference request, they wanted to incrementally send response (or perhaps even change an earlier response based on a new request). One way to do this with a custom backend is to used shared memory for the output tensor(s). Your client sends a request and can then monitor the shared memory buffer to see when new output is produced. The custom backend can communicate with the client directly through the shared-memory buffer to send incremental output.

**Comment by npuichigo** [comment]
@deadeyegoodwin Thanks for your reply. But it seems that it depends on the client to support such use-case. In fact, I'm using something like grpc-gateway to transcode the grpc api to a restful api. In that case we may want to have a restful counterpart of such unidirectional grpc request, where the http response is with chunked transfer encoding. It's handy to implement that with sync version of grpc, where each writing to the ServeWriter can be transcoded into a chunked http package. But with async version, ServerAsyncWriter is async and each writing is driven by a new event from completion queue. That's what bothers me.

**Comment by deadeyegoodwin** [comment]
TRTIS internally is set up to generate one response for each request. Fixing the GRPC (or HTTP) endpoints to allow multiple responses for each request will not be useful until the rest of TRTIS is updated... and we have no design or plan for that kind of update. We may do something in the future but we don't have any solution for now.
