### ISSUE TITLE
trtserver uses more than 20 CPUs

### ISSUE THREAD

**Issue by lxl910915** [NVIDIA/tensorrt-inference-server#1080]
**Description**
Model: Tensorflow [EAST ](https://github.com/argman/EAST) model
Convert saved_model to onnx: `python -m tf2onnx.convert --saved-model /tmp/SavedModel --output model.onnx --outputs feature_fusion/concat_3,feature_fusion/Conv_7/Sigmoid  --opset 10`
Result of convert saved_model to onnx: `After optimization: Add -3 (19->16), Const -59 (379->320), Gather +3 (0->3), Identity -18 (18->0), Reshape +2 (0->2), Transpose -262 (264->2) `

trtserver loads this model.onnx. When a client using gRPC to connect to the trtserver.  The trtserver will use more than 20 CPUs and use less GPU.
![img](https://user-images.githubusercontent.com/8842010/73604036-cbe6dd00-45c5-11ea-84bb-63ebcd6eb439.png)

However, when we add `--fold_const` to convert saved_model to onnx by `python -m tf2onnx.convert --saved-model /tmp/SavedModel --output model.onnx --outputs feature_fusion/concat_3,feature_fusion/Conv_7/Sigmoid  --opset 10 --fold_const`. 
Result of convert saved_model to onnx: `After optimization: Add -63 (79->16), Const -10 (145->135), Identity -18 (18->0), Reshape +2 (0->2), Transpose -138 (140->2)`

Now, the trtserver only uses 1 CPU and uses more GPU.

**TRTIS Information**
What version of TRTIS are you using?  20.01
Are you using the TRTIS container or did you build it yourself?   build it ourself

**To Reproduce**

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
TRTIS uses ONNX Runtime to execute ONNX models https://github.com/microsoft/onnxruntime. I think this is more of an ONNX Runtime question as to why CPU vs GPU is used to execute the model. Are you setting any instance_group or optimization options in your model configuration?
@GuanLuo do we have a script to run ONNX models directly with ONNX runtime so we can compare behavior?

**Comment by lxl910915** [comment]
> TRTIS uses ONNX Runtime to execute ONNX models https://github.com/microsoft/onnxruntime. I think this is more of an ONNX Runtime question as to why CPU vs GPU is used to execute the model. Are you setting any instance_group or optimization options in your model configuration?
> @GuanLuo do we have a script to run ONNX models directly with ONNX runtime so we can compare behavior?

@deadeyegoodwin  Our config.pbtxt is:
```
name: "east"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input_images:0"
    data_type: TYPE_FP32
    dims: [1,256,256,3]
  }
]
output [
  {
    name: "feature_fusion/Conv_7/Sigmoid:0"
    data_type: TYPE_FP32
    dims: [1,64,64,1]
  },
  {
    name: "feature_fusion/concat_3:0"
    data_type: TYPE_FP32
    dims: [1,64,64,5]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
optimization { execution_accelerators {
  gpu_execution_accelerator : [ { name : "tensorrt" } ]
}}
```

We run ONNX models directly with ONNX runtime, and it only uses 1 cpu.

**Comment by GuanLuo** [comment]
@deadeyegoodwin I have a Dockerfile that builds ONNX Runtime and an sample executable to load / run model in ONNX Runtime directly, but that is out-of-date (before ONNX Runtime v1.0.0)... I can revisit it and post it here later this week.

**Comment by lxl910915** [comment]
@GuanLuo
It seems that the onnxruntime_c_api.h cause this problem.

We test the following code:
```
  const OrtApi* g_ort = OrtGetApiBase()->GetApi(ORT_API_VERSION);
  OrtEnv* env;
  g_ort->CreateEnv(ORT_LOGGING_LEVEL_WARNING, "test", &env);

  OrtSessionOptions* session_options;
  g_ort->CreateSessionOptions(&session_options);
  g_ort->SetIntraOpNumThreads(session_options, 1);
  g_ort->SetSessionGraphOptimizationLevel(session_options, ORT_ENABLE_BASIC);

  OrtSessionOptionsAppendExecutionProvider_CUDA(session_options, 0);
  OrtSessionOptionsAppendExecutionProvider_Tensorrt(session_options);

  OrtSession* session;
  const char* model_path = "/tmp/east_model.onnx";
  printf("Using Onnxruntime C API\n");
  RETURN_IF_ORT_ERROR(g_ort->CreateSession(env, model_path, session_options, &session));
  printf("Created Session");
  while(true) {
    printf("Run Session\n");
    RETURN_IF_ORT_ERROR(g_ort->Run(
      session, NULL, input_names.data(),
      (const OrtValue* const*)input_tensors_.data(), input_tensors_.size(),
      output_names.data(), output_names.size(), output_tensors_.data()));
  }
```
It works well.

**Comment by GuanLuo** [comment]
@lxl910915 What is the ONNX Runtime version that you are using? The above code is similar to how we invoke the ORT APis, except that for now we always set disable in `SetSessionGraphOptimizationLevel`.

By the way, the order you call `OrtSessionOptionsAppendExecutionProvider_XXX` affects the priority of assigning ops to the execution provider. Your example prioritize CUDA over TensorRT, but TRTIS will prioritize TensorRT over CUDA if TensoRT EP is specified.

**Comment by lxl910915** [comment]
@GuanLuo Our ONNX Runtime version is 1.1.0.

**Comment by GuanLuo** [comment]
I assume you achieve 3. by changing the source code? Otherwise I think TRTIS always prioritize other GPU accelerator over CUDA. If so, can you share the code change? It is strange that the order changes causes exception on TRTIS side.

Are you building TRTIS on 20.01 branch or master? The master is now rolled forward to use ONNX Runtime 1.1.0. If you already built on master, then we should investigate further...

**Comment by lxl910915** [comment]
@GuanLuo  In onnx_backend.cc file, we changed
```
  if (gpu_device != Context::NO_GPU_DEVICE) {
#ifdef TRTIS_ENABLE_GPU
    if (Config().optimization().has_execution_accelerators()) {
      ...
    }
    RETURN_IF_ORT_ERROR(OrtSessionOptionsAppendExecutionProvider_CUDA(
        session_options, gpu_device));
    LOG_VERBOSE(1) << "CUDA Execution Accelerator is set for " << instance_name
                   << " on device " << gpu_device;
#else
    return Status(RequestStatusCode::INTERNAL, "GPU instances not supported");
#endif  // TRTIS_ENABLE_GPU
  }
```
to 
```
  if (gpu_device != Context::NO_GPU_DEVICE) {
#ifdef TRTIS_ENABLE_GPU
    RETURN_IF_ORT_ERROR(OrtSessionOptionsAppendExecutionProvider_CUDA(
        session_options, gpu_device));
    LOG_VERBOSE(1) << "CUDA Execution Accelerator is set for " << instance_name
                   << " on device " << gpu_device;

    if (Config().optimization().has_execution_accelerators()) {
      ...
    }
#else
    return Status(RequestStatusCode::INTERNAL, "GPU instances not supported");
#endif  // TRTIS_ENABLE_GPU
  }
```

**Comment by lxl910915** [comment]
> @GuanLuo In onnx_backend.cc file, we changed
> 
> ```
>   if (gpu_device != Context::NO_GPU_DEVICE) {
> #ifdef TRTIS_ENABLE_GPU
>     if (Config().optimization().has_execution_accelerators()) {
>       ...
>     }
>     RETURN_IF_ORT_ERROR(OrtSessionOptionsAppendExecutionProvider_CUDA(
>         session_options, gpu_device));
>     LOG_VERBOSE(1) << "CUDA Execution Accelerator is set for " << instance_name
>                    << " on device " << gpu_device;
> #else
>     return Status(RequestStatusCode::INTERNAL, "GPU instances not supported");
> #endif  // TRTIS_ENABLE_GPU
>   }
> ```
> 
> to
> 
> ```
>   if (gpu_device != Context::NO_GPU_DEVICE) {
> #ifdef TRTIS_ENABLE_GPU
>     RETURN_IF_ORT_ERROR(OrtSessionOptionsAppendExecutionProvider_CUDA(
>         session_options, gpu_device));
>     LOG_VERBOSE(1) << "CUDA Execution Accelerator is set for " << instance_name
>                    << " on device " << gpu_device;
> 
>     if (Config().optimization().has_execution_accelerators()) {
>       ...
>     }
> #else
>     return Status(RequestStatusCode::INTERNAL, "GPU instances not supported");
> #endif  // TRTIS_ENABLE_GPU
>   }
> ```
> 
> We build the master branch, and problem still exist.

Same problem with https://github.com/onnx/tensorflow-onnx/issues/784#issuecomment-586866327

**Comment by GuanLuo** [comment]
So the root cause of the issue is from ONNXRuntime?

**Comment by lxl910915** [comment]
> So the root cause of the issue is from ONNXRuntime?

It seems that.
