### ISSUE TITLE
torch/script.h: No such file or directory

### ISSUE THREAD

**Issue by lxl910915** [NVIDIA/tensorrt-inference-server#1099]
Build TRTIS with -DTRTIS_ENABLE_PYTORCH=ON, and we have set the path of script.h in DTRTIS_PYTORCH_INCLUDE_PATHS.

In file included from /tensorrt-inference-server/src/backends/pytorch/libtorch_backend.cc:27:0:
/tensorrt-inference-server/build/trtis/../../src/backends/pytorch/libtorch_backend.h:28:10: fatal error: torch/script.h: No such file or directory
 #include <torch/script.h>  // One-stop header.
          ^~~~~~~~~~~~~~~~
compilation terminated.
src/backends/pytorch/CMakeFiles/libtorch-backend-library.dir/build.make:88: recipe for target 'src/backends/pytorch/CMakeFiles/libtorch-backend-library.dir/libtorch_backend.cc.o' failed

**Comment by CoderHam** [comment]
You are most likely setting the include path incorrectly. The path must container the headers and libraries. 
https://github.com/NVIDIA/tensorrt-inference-server/blob/master/Dockerfile#L252
You can follow a similar approach if you are using the python build process to build a custom version of pytorch. 

Note: if you don't need a specific version of pytorch you can simply use the one we ship in our container.

**Comment by lxl910915** [comment]
@CoderHam  Rebuild pytorch and set -DTRTIS_PYTORCH_INCLUDE_PATHS="/usr/local/lib/python3.6/dist-packages/torch/include/"  and -DTRTIS_EXTRA_LIB_PATHS="/tmp/pytorch_a5b4d78/build/lib" solved out problem.
