### ISSUE TITLE
Linking TRTIS as a library

### ISSUE THREAD

**Issue by ryanolson** [NVIDIA/tensorrt-inference-server#110]
Add the ability to bring TRTIS as a library into Bazel project.

Primarily, this will allow an external application easier access to the .protos needed to customize a client to talk to TRTIS.

gRPC example:
```http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com/grpc/grpc/archive/v1.16.1.tar.gz",
    ],
    strip_prefix = "grpc-1.16.1",
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
```

This allows one to create a grpc dependency `@com_github_grpc_grpc//:grpc++_unsecure`.

The TRTIS example might be:
```
http_archive(
    name = "com_github_nvidia_trtis",
    urls = [
        "https://github.com/NVIDIA/tensorrt-inference-server/archive/v0.10.0.tar.gz",
    ],
    strip_prefix = "tensorrt-inference-server-0.10.0",
)

# this part is missing - there are now top-level dependencies - they are hardcoded into the workspace which is not accessible
load("@com_github_nvidia_trtis//baze:trtis_deps.bzl, "trtis_deps")
```

This would allow one to build the protos: `@com_github_nvidia_trtis//:src/core/api_proto`.

**Comment by deadeyegoodwin** [comment]
Note that TRTIS build itself is no longer based on bazel, but cmake. But in the same spirit we could make sure that TRTIS is easy to use as a cmake external project.

**Comment by deadeyegoodwin** [comment]
We have no plans to support bazel builds. We do support CMake and it should be easy to integrate TRTIS build into an existing cmake build.
