### ISSUE TITLE
golang client input of TYPE_STRING

### ISSUE THREAD

**Issue by mhunsake** [NVIDIA/tensorrt-inference-server#1100]
**Description**
Simple custom backend that takes as input string, converts it to cv::Mat and returns as output the h,w,c of the image.  (a one off of image_preprocess.cc)  I run this with the python client and get results as expected.   When I try to use goclient, I get error for unexpected input size. 

```
request_status:<code:INVALID_ARG msg:"unexpected size 11364 for input 'INPUT', expecting 0 for model 'mkhgo1'" server_id:"inference:0" request_id:12 > meta_data:<> 
```
Server status shows the expected dimensions.  Any idea why it expects 0 for the INPUT size?

```
model_status {
  key: "mkhgo1"
  value {
    config {
      name: "mkhgo1"
      platform: "custom"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      max_batch_size: 32
      input {
        name: "INPUT"
        data_type: TYPE_STRING
        dims: 1
      }
      output {
        name: "OUTPUT"
        data_type: TYPE_FP32
        dims: 3
      }
      instance_group {
        name: "mkhgo1"
        count: 1
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "libimagego1.so"
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
        ready_state_reason {
        }
      }
    }
  }
}

```
I started with grpc_simple_client.go and modified for my purpose.

[grpc_client.go.txt](https://github.com/NVIDIA/tensorrt-inference-server/files/4183689/grpc_client.go.txt)

**Comment by CoderHam** [comment]
@mhunsake TRTIS expects string inputs to be in the following format: **4-byte length followed by the actual string. No null terminator.**

The sample code that does this for the python client is here: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/library/__init__.py#L270

**Comment by mhunsake** [comment]
Thanks!  My first pixel in the image is black, and since I missed the size, it was reading this as size 0.

**Comment by mhunsake** [comment]
@CoderHam  I  have added the 4-byte length followed by the actual string, but am still getting an error.   ```request_status:<code:INVALID_ARG msg:"unexpected size 11368 for input 'INPUT', expecting 0 for model 'mkhgo1'" server_id:"inference:0" request_id:16 > meta_data:<> ```
