### ISSUE TITLE
Concurrency problem due to allocation of output buffers on device

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/tensorrt-inference-server#1106]
**Description**
Recently, I noticed a performance regression running multiple TensorRT models (3 models, 2 instances each) concurrently on a single GPU (Titan V). They are ensembled and fed through a single custom backend. However I feed them, the average GPU utilization remains around 60%. I know that it was easy to reach full utilization with this setup a while ago.

So I turned to the nvidia profiler, and was surprised to see that after each execution of a TensorRT model, the corresponding thread calls `cudaMalloc` for each output. Of course, `cudaMalloc` synchronizes all work on the device, and hence severely limits concurrency.
The culprit appears to be here:
https://github.com/NVIDIA/tensorrt-inference-server/blob/9bbfdb8f9c90616f2a6a165e27a9059660a1b6d2/src/core/backend_context.cc#L378-L382
By default, this allocates an output buffer on the same device that `output` is located on, resulting in a `cudaMalloc` call and hence in synchronization of the device.

To confirm my suspicion, I patched the above location to always request allocation of an output buffer with `TRTSERVER_MEMORY_CPU`, and the CPU utilization returned to the expected high level.

**TRTIS Information**
What version of TRTIS are you using?
master, 19.12, 20.01,...
Are you using the TRTIS container or did you build it yourself?
both

**Comment by GuanLuo** [comment]
Yeah, the `cudaMalloc` / `cudaFree` call shouldn't be called in this fashion, that is an oversight when implementing the memory buffer class. We probably need to preallocate GPU memory for all uses like what we do for pinned system memory.

**Comment by GuanLuo** [comment]
We will look into a fix for the issue.

**Comment by mrjackbo** [comment]
Great, thanks!

**Comment by GuanLuo** [comment]
Created PR #1180

**Comment by mrjackbo** [comment]
Thanks. I gave the changes a quick try, and it seems the `cudaMalloc`s and `cudaFree`s are gone. However, my GPU utilization is still significantly higher using the patch I mentioned in the initial post (force TRTIS to go through the CPU). 
In the situation of an ensemble `GPU-Model -> CPU-Model`, it seems that it would be more efficient for TRTIS to do the `cudaDeviceToHost` copy, as this could overlap with other operations, while if I do the copy in my custom backend, it will have to start and finish in `CustomInstance::Execute`.

In my custom backend, I do request the inputs as `CUSTOM_MEMORY_CPU`, but TRTIS does not always honor this, correct?

Is there a way to force TRTIS to provide input buffers in CPU memory, in the `GPU-Model->CPU-Model`-situation?

**Comment by GuanLuo** [comment]
> it seems that it would be more efficient for TRTIS to do the cudaDeviceToHost copy, as this could overlap with other operations

Is your GPU model executing a batch of multiple requests? If so, it will first copy the output to a contiguous pinned memory buffer, then copy from the pinned memory buffer to the actual output buffer, which may explain the speed up.

> In my custom backend, I do request the inputs as `CUSTOM_MEMORY_CPU`, but TRTIS does not always honor this, correct?

Currently Triton will just return the memory type of the buffer regardless of the preferred type.

> Is there a way to force TRTIS to provide input buffers in CPU memory, in the `GPU-Model->CPU-Model-situation`?

The ensemble scheduler doesn't understand the context between models in the ensemble, so it won't recognize `GPU-Model->CPU-Model-situation`. For now, one workaround is setting `--cuda-memory-pool-byte-size` to 0, then all GPU buffer allocation will fall back to CPU buffer allocation. But that will affect some backends which also use the pool for preparing input on GPU (currently TensorFlow and LibTorch)
