### ISSUE TITLE
Error while loading shared libraries: libtensorflow_framework.so.1

### ISSUE THREAD

**Issue by nikibor** [NVIDIA/tensorrt-inference-server#1112]
**Description**
Error on execution of Tensorrt inference server docker image (20.01-py3 4fe0fddfcef2) caused by tensorflow library. Build, with the same settings runs on version 19.11-py3 (8f802511f84c)

**TRTIS Information**
TensorRt **19.11-py3** info:

> {
  "Id": "sha256:8f802511f84c52bfd5d5b90cd9199d3633140e1edd3cc12f62084a73d51ed5cd",
  "RepoTags": [
    "nvcr.io/nvidia/tensorrtserver:19.11-py3"
  ],
  "RepoDigests": [
  ],
  "Parent": "",
  "Comment": "",
  "Created": "2019-11-14T21:44:30.894643708Z",
  "Container": "d2623ff772e7d4d770a1588bc55c37773897f52c5b0c8a4fe3473f21ede575a0",
  "ContainerConfig": {
    "Hostname": "d2623ff772e7",
    "Domainname": "",
    "User": "",
    "AttachStdin": false,
    "AttachStdout": false,
    "AttachStderr": false,
    "Tty": false,
    "OpenStdin": false,
    "StdinOnce": false,
    "Env": [      "PATH=/opt/tensorrtserver/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "CUDA_VERSION=10.2.89",
      "CUDA_DRIVER_VERSION=440.30.00",
      "CUDA_CACHE_DISABLE=1",
      "_CUDA_COMPAT_PATH=/usr/local/cuda/compat",
      "ENV=/etc/shinit_v2",
      "BASH_ENV=/etc/bash.bashrc",
      "NVIDIA_REQUIRE_CUDA=cuda>=9.0",
      "NCCL_VERSION=2.5.6",
      "CUBLAS_VERSION=10.2.2.89",
      "CUDNN_VERSION=7.6.5.32",
      "TRT_VERSION=6.0.1.8",
      "NSIGHT_SYSTEMS_VERSION=2019.5.2",
      "DALI_VERSION=0.15.0",
      "DALI_BUILD=947079", "LD_LIBRARY_PATH=/opt/tensorrtserver/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64",
      "NVIDIA_VISIBLE_DEVICES=all",
      "NVIDIA_DRIVER_CAPABILITIES=compute,utility,video",
      "MOFED_VERSION=4.4-1.0.0",
      "IBV_DRIVERS=/usr/lib/libibverbs/libmlx5",
      "OPENMPI_VERSION=3.1.4",
      "OMPI_MCA_btl_vader_single_copy_mechanism=none",
      "LIBRARY_PATH=/usr/local/cuda/lib64/stubs:",
      "TENSORRT_SERVER_VERSION=1.8.0",
      "NVIDIA_TENSORRT_SERVER_VERSION=19.11",
      "TF_ADJUST_HUE_FUSED=1",
      "TF_ADJUST_SATURATION_FUSED=1",
      "TF_ENABLE_WINOGRAD_NONFUSED=1",
      "TF_AUTOTUNE_THRESHOLD=2",
      "MKL_THREADING_LAYER=GNU",
      "TENSORRT_SERVER_USER=tensorrt-server",
      "INTEL_CVSDK_DIR=/opt/openvino_scripts/openvino_2019.1.144",      "PYTHONPATH=/opt/openvino_scripts:/opt/openvino_scripts/openvino_2019.1.144:/opt/openvino_scripts/openvino_2019.1.144/deployment_tools/model_optimizer:/opt/openvino_scripts/openvino_2019.1.144/tools:",
      "NVIDIA_BUILD_ID=8810908"
    ],
    "Cmd": [
      "/bin/sh",
      "-c",
      "#(nop) ",
      "LABEL com.nvidia.build.ref=059956c4e9a6b4da30e53712ba8535fb88c8c7b1"
    ],
    "ArgsEscaped": true,
    "Image": "sha256:40e28abf617bf48c9cba0b4e3dfbffb1ba7e842c0c910749f71bed16c93185c9",
    "Volumes": null,
    "WorkingDir": "/opt/tensorrtserver",
    "Entrypoint": [
      "/opt/tensorrtserver/nvidia_entrypoint.sh"
    ],
    "OnBuild": null,
    "Labels": {
      "com.nvidia.build.id": "8810908",
      "com.nvidia.build.ref": "059956c4e9a6b4da30e53712ba8535fb88c8c7b1",
      "com.nvidia.cublas.version": "10.2.2.89",
      "com.nvidia.cuda.version": "9.0",
      "com.nvidia.cudnn.version": "7.6.5.32",
      "com.nvidia.nccl.version": "2.5.6",
      "com.nvidia.nsightsystems.version": "2019.5.2",
      "com.nvidia.tensorrt.version": "6.0.1.8",
      "com.nvidia.tensorrtserver.version": "1.8.0",
      "com.nvidia.volumes.needed": "nvidia_driver"
    }
  },
  "DockerVersion": "18.06.0-ce",
  "Author": "",
  "Config": {
    "Hostname": "",
    "Domainname": "",
    "User": "",
    "AttachStdin": false,
    "AttachStdout": false,
    "AttachStderr": false,
    "Tty": false,
    "OpenStdin": false,
    "StdinOnce": false,
    "Env": [      "PATH=/opt/tensorrtserver/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "CUDA_VERSION=10.2.89",
      "CUDA_DRIVER_VERSION=440.30.00",
      "CUDA_CACHE_DISABLE=1",
      "_CUDA_COMPAT_PATH=/usr/local/cuda/compat",
      "ENV=/etc/shinit_v2",
      "BASH_ENV=/etc/bash.bashrc",
      "NVIDIA_REQUIRE_CUDA=cuda>=9.0",
      "NCCL_VERSION=2.5.6",
      "CUBLAS_VERSION=10.2.2.89",
      "CUDNN_VERSION=7.6.5.32",
      "TRT_VERSION=6.0.1.8",
      "NSIGHT_SYSTEMS_VERSION=2019.5.2",
      "DALI_VERSION=0.15.0",
      "DALI_BUILD=947079",      "LD_LIBRARY_PATH=/opt/tensorrtserver/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64",
      "NVIDIA_VISIBLE_DEVICES=all",
      "NVIDIA_DRIVER_CAPABILITIES=compute,utility,video",
      "MOFED_VERSION=4.4-1.0.0",
      "IBV_DRIVERS=/usr/lib/libibverbs/libmlx5",
      "OPENMPI_VERSION=3.1.4",
      "OMPI_MCA_btl_vader_single_copy_mechanism=none",
      "LIBRARY_PATH=/usr/local/cuda/lib64/stubs:",
      "TENSORRT_SERVER_VERSION=1.8.0",
      "NVIDIA_TENSORRT_SERVER_VERSION=19.11",
      "TF_ADJUST_HUE_FUSED=1",
      "TF_ADJUST_SATURATION_FUSED=1",
      "TF_ENABLE_WINOGRAD_NONFUSED=1",
      "TF_AUTOTUNE_THRESHOLD=2",
      "MKL_THREADING_LAYER=GNU",
      "TENSORRT_SERVER_USER=tensorrt-server",
      "INTEL_CVSDK_DIR=/opt/openvino_scripts/openvino_2019.1.144",      "PYTHONPATH=/opt/openvino_scripts:/opt/openvino_scripts/openvino_2019.1.144:/opt/openvino_scripts/openvino_2019.1.144/deployment_tools/model_optimizer:/opt/openvino_scripts/openvino_2019.1.144/tools:",
      "NVIDIA_BUILD_ID=8810908"
    ],
    "Cmd": null,
    "ArgsEscaped": true,
    "Image": "sha256:40e28abf617bf48c9cba0b4e3dfbffb1ba7e842c0c910749f71bed16c93185c9",
    "Volumes": null,
    "WorkingDir": "/opt/tensorrtserver",
    "Entrypoint": [
      "/opt/tensorrtserver/nvidia_entrypoint.sh"
    ],
    "OnBuild": null,
    "Labels": {
      "com.nvidia.build.id": "8810908",
      "com.nvidia.build.ref": "059956c4e9a6b4da30e53712ba8535fb88c8c7b1",
      "com.nvidia.cublas.version": "10.2.2.89",
      "com.nvidia.cuda.version": "9.0",
      "com.nvidia.cudnn.version": "7.6.5.32",
      "com.nvidia.nccl.version": "2.5.6",
      "com.nvidia.nsightsystems.version": "2019.5.2",
      "com.nvidia.tensorrt.version": "6.0.1.8",
      "com.nvidia.tensorrtserver.version": "1.8.0",
      "com.nvidia.volumes.needed": "nvidia_driver"
    }
  },
  "Architecture": "amd64",
  "Os": "linux",
  "Size": 6151916503,
  "VirtualSize": 6151916503
}

TensorRt **20.01-py3** info:

> {
  "Id": "sha256:4fe0fddfcef2d23ceeb838a2c002fa14d6cb254e06d8f73585e08880cbc7302b",
  "RepoTags": [
    "nvcr.io/nvidia/tensorrtserver:20.01-py3"
  ],
  "RepoDigests": [   "nvcr.io/nvidia/tensorrtserver@sha256:2b9284c65e70a261fbbef5b526ff01c476ba52bcd530814f5554d57e95263c01"
  ],
  "Parent": "",
  "Comment": "",
  "Created": "2019-12-20T19:16:52.622264465Z",
  "Container": "ee77ec1d427710a4675084910563813c5a126bdc6de2d5841ae80d10be40a012",
  "ContainerConfig": {
    "Hostname": "ee77ec1d4277",
    "Domainname": "",
    "User": "",
    "AttachStdin": false,
    "AttachStdout": false,
    "AttachStderr": false,
    "Tty": false,
    "OpenStdin": false,
    "StdinOnce": false,
    "Env": [     "PATH=/opt/tensorrtserver/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "CUDA_VERSION=10.2.89",
      "CUDA_DRIVER_VERSION=440.33.01",
      "CUDA_CACHE_DISABLE=1",
      "_CUDA_COMPAT_PATH=/usr/local/cuda/compat",
      "ENV=/etc/shinit_v2",
      "BASH_ENV=/etc/bash.bashrc",
      "NVIDIA_REQUIRE_CUDA=cuda>=9.0",
      "NCCL_VERSION=2.5.6",
      "CUBLAS_VERSION=10.2.2.89",
      "CUDNN_VERSION=7.6.5.32",
      "TRT_VERSION=7.0.0.11",
      "NSIGHT_SYSTEMS_VERSION=2019.6.1",
      "NSIGHT_COMPUTE_VERSION=2019.5.0.14",
      "DALI_VERSION=0.17.0",
      "DALI_BUILD=1030354",
      "LD_LIBRARY_PATH=/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64",
      "NVIDIA_VISIBLE_DEVICES=all",
      "NVIDIA_DRIVER_CAPABILITIES=compute,utility,video",
      "MOFED_VERSION=4.6-1.0.1",
      "OPENMPI_VERSION=3.1.4",
      "OMPI_MCA_btl_vader_single_copy_mechanism=none",
      "LIBRARY_PATH=/usr/local/cuda/lib64/stubs:",
      "TENSORRT_SERVER_VERSION=1.10.0",
      "NVIDIA_TENSORRT_SERVER_VERSION=20.01",
      "TF_ADJUST_HUE_FUSED=1",
      "TF_ADJUST_SATURATION_FUSED=1",
      "TF_ENABLE_WINOGRAD_NONFUSED=1",
      "TF_AUTOTUNE_THRESHOLD=2",
      "MKL_THREADING_LAYER=GNU",
      "TENSORRT_SERVER_USER=tensorrt-server",
      "INTEL_CVSDK_DIR=/opt/openvino_scripts/openvino_2019.1.144",     "PYTHONPATH=/opt/openvino_scripts:/opt/openvino_scripts/openvino_2019.1.144:/opt/openvino_scripts/openvino_2019.1.144/deployment_tools/model_optimizer:/opt/openvino_scripts/openvino_2019.1.144/tools:",
      "NVIDIA_BUILD_ID=9326846"
    ],
    "Cmd": [
      "/bin/sh",
      "-c",
      "#(nop) ",
      "LABEL com.nvidia.build.ref=25611c8732dfa73f289033800e1f04ccba5130e9"
    ],
    "Image": "sha256:0c1aaecfaa5bcd7440e74eb48513072df80a624749c236aabc35bd7c02f19bab",
    "Volumes": null,
    "WorkingDir": "/opt/tensorrtserver",
    "Entrypoint": [
      "/opt/tensorrtserver/nvidia_entrypoint.sh"
    ],
    "OnBuild": null,
    "Labels": {
      "com.nvidia.build.id": "9326846",
      "com.nvidia.build.ref": "25611c8732dfa73f289033800e1f04ccba5130e9",
      "com.nvidia.cublas.version": "10.2.2.89",
      "com.nvidia.cuda.version": "9.0",
      "com.nvidia.cudnn.version": "7.6.5.32",
      "com.nvidia.nccl.version": "2.5.6",
      "com.nvidia.nsightcompute.version": "2019.5.0.14",
      "com.nvidia.nsightsystems.version": "2019.6.1",
      "com.nvidia.tensorrt.version": "7.0.0.11",
      "com.nvidia.tensorrtserver.version": "1.10.0",
      "com.nvidia.volumes.needed": "nvidia_driver"
    }
  },
  "DockerVersion": "19.03.5",
  "Author": "",
  "Config": {
    "Hostname": "",
    "Domainname": "",
    "User": "",
    "AttachStdin": false,
    "AttachStdout": false,
    "AttachStderr": false,
    "Tty": false,
    "OpenStdin": false,
    "StdinOnce": false,
    "Env": [     "PATH=/opt/tensorrtserver/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
      "CUDA_VERSION=10.2.89",
      "CUDA_DRIVER_VERSION=440.33.01",
      "CUDA_CACHE_DISABLE=1",
      "_CUDA_COMPAT_PATH=/usr/local/cuda/compat",
      "ENV=/etc/shinit_v2",
      "BASH_ENV=/etc/bash.bashrc",
      "NVIDIA_REQUIRE_CUDA=cuda>=9.0",
      "NCCL_VERSION=2.5.6",
      "CUBLAS_VERSION=10.2.2.89",
      "CUDNN_VERSION=7.6.5.32",
      "TRT_VERSION=7.0.0.11",
      "NSIGHT_SYSTEMS_VERSION=2019.6.1",
      "NSIGHT_COMPUTE_VERSION=2019.5.0.14",
      "DALI_VERSION=0.17.0",
      "DALI_BUILD=1030354",
      "LD_LIBRARY_PATH=/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64",
      "NVIDIA_VISIBLE_DEVICES=all",
      "NVIDIA_DRIVER_CAPABILITIES=compute,utility,video",
      "MOFED_VERSION=4.6-1.0.1",
      "OPENMPI_VERSION=3.1.4",
      "OMPI_MCA_btl_vader_single_copy_mechanism=none",
      "LIBRARY_PATH=/usr/local/cuda/lib64/stubs:",
      "TENSORRT_SERVER_VERSION=1.10.0",
      "NVIDIA_TENSORRT_SERVER_VERSION=20.01",
      "TF_ADJUST_HUE_FUSED=1",
      "TF_ADJUST_SATURATION_FUSED=1",
      "TF_ENABLE_WINOGRAD_NONFUSED=1",
      "TF_AUTOTUNE_THRESHOLD=2",
      "MKL_THREADING_LAYER=GNU",
      "TENSORRT_SERVER_USER=tensorrt-server",
      "INTEL_CVSDK_DIR=/opt/openvino_scripts/openvino_2019.1.144",     "PYTHONPATH=/opt/openvino_scripts:/opt/openvino_scripts/openvino_2019.1.144:/opt/openvino_scripts/openvino_2019.1.144/deployment_tools/model_optimizer:/opt/openvino_scripts/openvino_2019.1.144/tools:",
      "NVIDIA_BUILD_ID=9326846"
    ],
    "Cmd": null,
    "Image": "sha256:0c1aaecfaa5bcd7440e74eb48513072df80a624749c236aabc35bd7c02f19bab",
    "Volumes": null,
    "WorkingDir": "/opt/tensorrtserver",
    "Entrypoint": [
      "/opt/tensorrtserver/nvidia_entrypoint.sh"
    ],
    "OnBuild": null,
    "Labels": {
      "com.nvidia.build.id": "9326846",
      "com.nvidia.build.ref": "25611c8732dfa73f289033800e1f04ccba5130e9",
      "com.nvidia.cublas.version": "10.2.2.89",
      "com.nvidia.cuda.version": "9.0",
      "com.nvidia.cudnn.version": "7.6.5.32",
      "com.nvidia.nccl.version": "2.5.6",
      "com.nvidia.nsightcompute.version": "2019.5.0.14",
      "com.nvidia.nsightsystems.version": "2019.6.1",
      "com.nvidia.tensorrt.version": "7.0.0.11",
      "com.nvidia.tensorrtserver.version": "1.10.0",
      "com.nvidia.volumes.needed": "nvidia_driver"
    }
  },
  "Architecture": "amd64",
  "Os": "linux",
  "Size": 6158496866,
  "VirtualSize": 6158496866
}

**To Reproduce**
docker run --rm --gpus all --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864  -v '/home/meetingnotes/tensorrt/castom_ops:/castom_ops' -p 8000:8000 -p 8001:8001 -p 8002:8002 -v '/home/meetingnotes/tensorrt/model_rep:/models' -eLD_PRELOAD="/castom_ops/coref_kernels.so" e9f1a32f9cad trtserver --model-repository=/models

**Expected behavior**
Same container launch as in previous version

**Comment by deadeyegoodwin** [comment]
Did you rebuild your custom operations using the same version of TensorFlow as is contained in TRTIS 20.01? You can find that information in the TRTIS release notes. https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_20-01.html#rel_20-01

**Comment by nikibor** [comment]
Custom operation and model were rebuild by tf 1.15

**Comment by deadeyegoodwin** [comment]
What is the error?

**Comment by deadeyegoodwin** [comment]
In 20.01 we changed the container to not use LD_LIBRARY_PATH to locate the various libraries. Instead if uses RUNPATH when building the exes and libraries. That likely means that your coref_kernels.so is no longer finding libtensorflow_framework.so.1 on the library path. You can find the libraries in /opt/tensorrtserver/lib.

To fix you can either build your shared library with the appropriate RUNPATH. Or set LD_LIBRARY_PATH in the env when you start the container. You want /opt/tensortserver/lib/tensorflow on the library path.
