### ISSUE TITLE
clientsdk: gnutls "non-properly terminated" error in git clone interrupts build (v1.10.0)

### ISSUE THREAD

**Issue by mvpel** [NVIDIA/tensorrt-inference-server#1113]
Following the [web instructions for building a custom backend](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/build.html#section-building-a-custom-backend) in the latest 20.01 / 1.10.0 container, the git clone in the make process which attempts to retrieve the GRPC repo and others hits the aforementioned error:

> Singularity> make -j8 trtis-custom-backends
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /user/pelletm/condor/aiml/tensorrt/tensorrt-inference-server/build
> [  0%] Performing download step (git clone) for 'grpc-repo'
> Cloning into 'grpc'...
> **error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.**
> Cloning into 'grpc'...
> error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
> Cloning into 'grpc'...
> error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
> -- Had to git clone more than once:
>           3 times.
> CMake Error at /user/pelletm/condor/aiml/tensorrt/tensorrt-inference-server/build/grpc-repo/tmp/grpc-repo-gitclone.cmake:66 (message):
>   Failed to clone repository: 'https://github.com/grpc/grpc.git'
> 

Upgrading the version of libgnutls30 in the container doesn't fix the problem:

> Singularity> git clone https://github.com/grpc/grpc.git
> Cloning into 'grpc'...
> remote: Enumerating objects: 22, done.
> remote: Counting objects: 100% (22/22), done.
> remote: Compressing objects: 100% (4/4), done.
> remote: Total 498844 (delta 19), reused 18 (delta 18), pack-reused 498822
> Receiving objects: 100% (498844/498844), 235.24 MiB | 7.66 MiB/s, done.
> **error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.**
> Resolving deltas: 100% (391392/391392), done.
> Singularity>

The curl and git version in the container are the latest available.

Thanks for any suggestions for a workaround or resolution!

**Comment by mvpel** [comment]
I should mention that like most corporate users, I'm behind a proxy. I haven't encountered this issue before.

**Comment by mvpel** [comment]
My workaround was to rebuild Git with OpenSSL rather than GnuTLS in accordance with the instructions at this Stackoverflow article: **[GnuTLS recv error (-110): The TLS connection was non-properly terminated](https://stackoverflow.com/questions/52529639/gnutls-recv-error-110-the-tls-connection-was-non-properly-terminated)**.

> Singularity> !make
> make -j8 trtis-custom-backends
> [  0%] Performing download step (git clone) for 'grpc-repo'
> Cloning into 'grpc'...
> Checking out files: 100% (8148/8148), done.
> Note: checking out 'v1.19.0'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> ...

Various other suggestions I found to address the issue, such as increasing the Git receive buffer size or turning off sslVerify, didn't help.

**Comment by deadeyegoodwin** [comment]
I don't think this has anything to do with TRTIS itself and since you have found a WAR we'll close.

**Comment by mvpel** [comment]
Is there an issue tracker for the NGC container images? The issue makes it impossible to follow the build instructions using the standard TRTIS SDK container supplied at the NGC. I'm not sure whether it's tied to the presence of the firewall and the proxy - presumably not since I would assume NVIDIA has one as well.

**Comment by deadeyegoodwin** [comment]
We build the NGC containers so you can file issues related to the containers themselves here. The NGC SDK container has been used successfully in many locations, which is why I don't think it is related to the container itself. Have you tried running just the git clone command from your host command line? From within the docker container? It could be that you can see a more interesting error message that way.
