### ISSUE TITLE
How to get the versioned model path when implementing a custom backend (Context)

### ISSUE THREAD

**Issue by nicklhy** [NVIDIA/tensorrt-inference-server#1114]
Hi,
I am new to trtis and recently working on a project that need to implement a custom backend in trtis.

I read the example code like `addsub.cu` or `identity.cc`, and found the versioned model path seems not to be available when constructing model instance with `Context::Context(const std::string& instance_name, const ModelConfig& config, const int gpu_device);`.

Here is a simple usecase that needs this feature: If I want to make `image_preprocess.cc` accepts external mean/std matrix files (i.e. h*w*c numpy/opencv matrix), the mean/std matrix files would be in the versioned model path. The model directory structure could be like below:
```
.
├── 1
│   ├── libimage_preprocess_v2.so
│   └── mean.mat
│   └── std.mat
└── config.pbtxt
```

**Comment by deadeyegoodwin** [comment]
A parameter is available in the model configuration that gives the path to the model repository and is available through the custom backend API: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/backends/custom/custom.h#L64
See the param custom backend example for how to access the parameters: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/custom/param/param.cc

I don't believe the API currently reports the model version to the custom backend.

**Comment by nicklhy** [comment]
@deadeyegoodwin I did use the "parameter" in `ModelConfig` in my project now, but the file path has to be absolute path rather than relative path.

As you mentioned, the custom backend can not get the model directory or version info right now, is this a special design ? If not, maybe we can add this feature in the future.

**Comment by deadeyegoodwin** [comment]
The parameter should give you the full path to the root of the model repository. From that you can append your model name and version number to get the version directory. I agree that we should provide the name and version information to the custom backend in some way. We will file a ticket to track that request.
