### ISSUE TITLE
"Error details: OK" error message from autofill.cc 

### ISSUE THREAD

**Issue by mvpel** [NVIDIA/tensorrt-inference-server#1125]
I'm experimenting with ensemble models, and have set up a workflow which accepts an input image into the libimagepreprocess.so custom backend and then passes it along to five TensorFlow models. There are two custom backends in the workflow - one simply scales the RGB values, while the other scales as well as resizes the input image.

> **W0220 20:05:57.168793 21475 autofill.cc:234] Autofiller failed to retrieve model. Error Details: OK:
> W0220 20:05:57.168846 21475 autofill.cc:238] Proceeding with simple config for now**
> I0220 20:05:57.169232 21475 server_status.cc:55] New status tracking for model 'preprocess_5models_ensemble'
> I0220 20:05:57.174834 21475 model_repository_manager.cc:675] loading: preprocess_5models_ensemble:0
> I0220 20:05:57.175443 21475 model_repository_manager.cc:829] successfully loaded '**preprocess_5models_ensemble**' version 0

"Error Details: OK:" isn't terribly useful. It's not even strictly clear as to which model it's complaining about, though it's evident that it's this preprocess_5models_ensemble model. And as you see, it does claim that the model is successfully loaded.

One difference between this model and a previous one it's based on, which is not showing this error, is that the raw input image is configured in the ensemble steps as the input for two separate image_preprocess custom-backend models configured with different parameters, e.g.:

```XML
name: "preprocess_5models_ensemble"
platform: "ensemble"
max_batch_size: 128
input [
  {
    name: "INPUT"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
   ...etc...
]
ensemble_scheduling {
  step [
    {
      model_name: "image_preprocess_nhwc_494x648x3_one255"
      model_version: -1
      input_map {
        key: "INPUT"
        value: "INPUT"
      }
      output_map {
        key: "OUTPUT"
        value: "preprocessed_image"
      }
    },
    {
      model_name: "image_preprocess_nhwc_494x648x3_one255_unet_256x512x3"
      model_version: -1
      input_map {
        key: "INPUT"
        value: "INPUT"
      }
      output_map {
        key: "OUTPUT"
        value: "unet_preprocessed_image"
      }
    },
```
... and so on ...

The reason for this approach is that I'm passing the image through four models which can accept the 494x648x3 dimensions, plus a UNet model which needs 2^n-factor dimensions of 256x512x3. The first custom model applies a 1/255.0 RGB scaling, while the second applies that scaling as well as doing the resize.

I was able to get the first four models to work properly with a single preprocess to apply the RGB value scaling - I have that set up as "preprocess_4models_ensemble."

I assume it's permissible to direct the input of the ensemble to two separate models. From what I can tell from the code, the libimagepreprocess.so will only accept a raw image, rather than its own output, so I don't think I can feed the output of image_preprocess_nhwc_494x648x3_one255 into image_preprocess_nhwc_494x648x3_one255_unet_256x512x3 in order to have a single point of entry for the ensemble workflow.

**TRTIS Information**
Version 1.10.0
Using NVIDIA container with additional opencv packages needed by libimagepreprocess.so, plus a curl compiled with OpenSSL instead of GnuTLS to address the firewall proxy problem in Git.

**To Reproduce**

**Expected behavior**
A clear descriptive error message, if there's actually a problem with the ensemble configuration, and no error if there isn't.

**Comment by mvpel** [comment]
Changing the ensemble input name to "RAW_IMAGE" instead of "INPUT" and updating the key-value pairs of the two preprocessing custom backend models did not change the behavior, so it's apparently not a name collision.

```
    {
      model_name: "image_preprocess_nhwc_494x648x3_one255"
      model_version: -1
      input_map {
        key: "INPUT"
        value: "RAW_IMAGE"
      }
      output_map {
        key: "OUTPUT"
        value: "preprocessed_image"
      }
    },
```

**Comment by mvpel** [comment]
Should have taken a closer look at the log files - lurking well above the latest lines of the log file where I was focused is another set of these errors which appeared around my previous ensemble workflow.

It appears that the errors arise when the model platform is specified as "ensemble." This is because the PLATFORM_ENSEMBLE and PLATFORM_CUSTOM from the Platform enum defined in core/model_config.h are not recognized by core/autofill.cc  and so the code falls through to a non-unknown/unrecognized-value state at line 223 and generates the "Error: OK" message.

**Comment by GuanLuo** [comment]
Thanks for the reporting, recently we improve the autofill message for ensemble / custom (#1101, #1107), do you mind to check if it helps on the issue.

**Comment by mvpel** [comment]
Splendid! Looks like this issue could be closed before it was opened. :D Thanks!
