### ISSUE TITLE
Ensemble model only delivers the first of its configured outputs

### ISSUE THREAD

**Issue by mvpel** [NVIDIA/tensorrt-inference-server#1126]
**Description**
Similar to the example found in the documentation at "[Models and Schedulers : Ensemble Models](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/models_and_schedulers.html#ensemble-models)," my ensemble model has multiple output tensors, as shown here from the ensemble's configuration:

```
name: "preprocess_5models_ensemble"
platform: "ensemble"
max_batch_size: 128
input [
  {
    name: "RAW_IMAGE"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "unet_output"
    data_type: TYPE_FP32
    dims: [ 5 ]
  },
  {
    name: "inceptionnet_output"
    data_type: TYPE_FP32
    dims: [ 5 ]
  },
  {
    name: "inceptionresnet_output"
    data_type: TYPE_FP32
    dims: [ 5 ]
  },
  {
    name: "resnet_output"
    data_type: TYPE_FP32
    dims: [ 5 ]
  },
  {
    name: "vgg19_output"
    data_type: TYPE_FP32
    dims: [ 5 ]
  }
]
```

However, using the ensemble_image_client.py script to submit an image to this model, I only get the first result, as shown in the verbose output from a run:

```
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api/infer/preprocess_5models_ensemble?format=binary HTTP/1.1
Host: localhost:8000
User-Agent: libcurl-agent/1.0
Accept: */*
Content-Type: application/octet-stream
NV-InferRequest:batch_size: 1 input { name: "RAW_IMAGE" dims: 1 batch_byte_size: 27224 } output { name: "unet_output" cls { count: 10 } }
Content-Length: 27224

* We are completely uploaded and fine
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< NV-InferResponse: model_name: "preprocess_5models_ensemble" batch_size: 1 output { name: "unet_output" batch_classes { cls { value: 0.999879837 label: "Other_Defect" } cls { idx: 1 value: 4.0419487e-05 label: "AI_PTM_BRIDGE" } cls { idx: 3 value: 3.28561764e-05 label: "AI_PROBE_DEFECT" } cls { idx: 2 value: 2.53879261e-05 label: "AI_WAFER_EDGE" } cls { idx: 4 value: 2.1448639e-05 label: "AI_PTM_CIRCLE" } } }
< NV-Status: code: SUCCESS server_id: "inference:0" request_id: 80
< Content-Type: application/octet-stream
< Content-Length: 168
<
* Connection #0 to host localhost left intact
Image './tr46image.jpg':
    0 (Other_Defect) = 0.9998798370361328
    1 (AI_PTM_BRIDGE) = 4.041948704980314e-05
    3 (AI_PROBE_DEFECT) = 3.285617640358396e-05
    2 (AI_WAFER_EDGE) = 2.5387926143594086e-05
    4 (AI_PTM_CIRCLE) = 2.1448639017762616e-05
```

Note that the NV-InferResponse shown only contains the results from the first output of the ensemble, and the Content-Length header being only 168 indicates that there's no additional outputs which are not being shown.

If I change the order of the outputs, the first output is always delivered.

Is this an issue in the ensemble_image_client.py code that only asks for and accepts a single output tensor, or is it the server which is not delivering the other four outputs?

**TRTIS Information**
TRTIS 1.10.0
NVIDIA container with added opencv packages needed by libimagepreprocess.so, and a curl recompiled with OpenSSL instead of GnuTLS to address Git failure.

**To Reproduce**

**Expected behavior**
All five outputs listed in the ensemble's outputs array should be delivered.

**Comment by GuanLuo** [comment]
You need to specify the outputs you want in the request header, which can be any subset of the outputs provided by the model.
From your request header, it appears that you only requested for one output:
`NV-InferRequest:batch_size: 1 input { name: "RAW_IMAGE" dims: 1 batch_byte_size: 27224 } output { name: "unet_output" cls { count: 10 } }`

**Comment by mvpel** [comment]
Thanks for the information! Let me take a look at the ensemble_image_client.py and figure out how to do that. I vaguely thought the "-c" command line option would handle that, but I guess that only applies to the classifications within a single output, rather than multiple outputs.

**Comment by mvpel** [comment]
Got it:

```
Singularity> ./ensemble_image_client.py -m preprocess_5models_ensemble ./tr46image.jpg
Output 'unet_output' for image './tr46image.jpg':
    0 (Other_Defect) = 0.9998798370361328
Output 'inceptionnet_output' for image './tr46image.jpg':
    0 (Other_Defect) = 0.9830048084259033
Output 'inceptionresnet_output' for image './tr46image.jpg':
    2 (AI_WAFER_EDGE) = 0.735027551651001
Output 'resnet_output' for image './tr46image.jpg':
    0 (Other_Defect) = 0.8990674018859863
Output 'vgg19_output' for image './tr46image.jpg':
    2 (AI_WAFER_EDGE) = 0.9811496734619141

```
And for multiple files:

```
Singularity> ./ensemble_image_client.py -m preprocess_5models_ensemble ./img
--
Output 'unet_output' for image './img/tr46image.jpg':
    0 (Other_Defect) = 0.9998798370361328
Output 'unet_output' for image './img/tr46image2.jpg':
    2 (AI_WAFER_EDGE) = 0.9996404647827148
--
Output 'inceptionnet_output' for image './img/tr46image.jpg':
    0 (Other_Defect) = 0.9830048084259033
Output 'inceptionnet_output' for image './img/tr46image2.jpg':
    2 (AI_WAFER_EDGE) = 0.9999428987503052
--
...etc...
```
I'll post a patch presently. I also added a "--model-name"and a "--batch-size" command line option, and show timing stats at the end:

> Inference time: 2095.876 ms for 32 images, 65.496 ms per image, ~15.3 images per second

**Comment by GuanLuo** [comment]
Closing the issue as the original problem is resolved
