### ISSUE TITLE
perf_client unable to allocate memory on gpu

### ISSUE THREAD

**Issue by zhm9484** [NVIDIA/tensorrt-inference-server#1138]
## trtserver start cmd
```shell
sudo nvidia-docker run -d  --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/root/models:/models tensorrtserver:20.01-py3 trtserver --model-repository=/models
```  
## perf_client cmd
```shell
./perf_client -m inception_graphdef -b 1 --shared-memory=cuda
```
## output
```shell
[ 0] INTERNAL - unable to allocate memory of 4004bytes on gpu for output InceptionV3/Predictions/Softmax
```

Anything else should I provide?

**Comment by deadeyegoodwin** [comment]
We will take a look...

**Comment by tanmayv25** [comment]
I didn't see the exact error but hit across a different error with HTTP protocol. The model contains "/" in its output name which was generating unsupported shared memory region names. Have a look at PR #1141 for the fix and the messages encountered. After these changes I don't see any problem.

Coming back to this error, the message is generated when cudaMalloc fails to allocate memory on the GPU. 4Kb doesn't look like too much of memory to allocate on GPU, especially a V100. Can you monitor the Memory-Usage from nvidia-smi while running the perf_client? Additionaly, can you try running: `./perf_client -m inception_graphdef -b 1 --shared-memory=cuda -i grpc` and share the ouput?

**Comment by zhm9484** [comment]
> I didn't see the exact error but hit across a different error with HTTP protocol. The model contains "/" in its output name which was generating unsupported shared memory region names. Have a look at PR #1141 for the fix and the messages encountered. After these changes I don't see any problem.
> 
> Coming back to this error, the message is generated when cudaMalloc fails to allocate memory on the GPU. 4Kb doesn't look like too much of memory to allocate on GPU. Can you monitor the Memory-Usage from nvidia-smi while running the perf_client? Additionaly, can you try running: `./perf_client -m inception_graphdef -b 1 --shared-memory=cuda -i grpc` and share the ouput?

The output of `nvidia-smi`:
![image](https://user-images.githubusercontent.com/12964346/75506414-e7a0a000-5a18-11ea-9cf8-15cd717d279b.png)

The output of `./perf_client -m inception_graphdef -b 1 --shared-memory=cuda -i grpc`:
```shell
[ 0] INTERNAL - unable to allocate memory of 4004bytes on gpu for output InceptionV3/Predictions/Softmax
```

**Comment by zhm9484** [comment]
> I didn't see the exact error but hit across a different error with HTTP protocol. The model contains "/" in its output name which was generating unsupported shared memory region names. Have a look at PR #1141 for the fix and the messages encountered. After these changes I don't see any problem.
> 
> Coming back to this error, the message is generated when cudaMalloc fails to allocate memory on the GPU. 4Kb doesn't look like too much of memory to allocate on GPU. Can you monitor the Memory-Usage from nvidia-smi while running the perf_client? Additionaly, can you try running: `./perf_client -m inception_graphdef -b 1 --shared-memory=cuda -i grpc` and share the ouput?

I rebuilt the trtis-clients with ubuntu16.04 and cuda10.0, and the new perf_client fixed the problem.
Thanks.
