### ISSUE TITLE
How to send multiple input tensor by rest api

### ISSUE THREAD

**Issue by buttonman** [NVIDIA/tensorrt-inference-server#1144]
**Description**
How to send rest api request with multiple input

**TRTIS Information**
19.11

**To Reproduce**
-------**following is my config file.**
name: "yolo"
platform: "onnxruntime_onnx"
max_batch_size: 0 
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [ 1, 3, 416, 416 ]
  },
  {
    name: "image_shape"
    data_type: TYPE_FP32
    dims: [ 1, 2 ]
  }

]
output [
  {
    name: "yolonms_layer_1/ExpandDims_1:0"
    data_type: TYPE_FP32
    dims: [ 1, -1, 4 ]
  },
  {
    name: "yolonms_layer_1/ExpandDims_3:0"
    data_type: TYPE_FP32
    dims: [ 1, 80, -1 ]
  },
  {
    name: "yolonms_layer_1/concat_2:0"
    data_type: TYPE_INT32
    dims: [ -1, -1 ]
  }
]

----------**following is my python client code to send rest api**

def preprocesstr(img, format, dtype, c, h, w, scaling):
    """
    Pre-process an image to meet the size, type and format
    requirements specified by the parameters.
    """
    #np.set_printoptions(threshold='nan')

    if c == 1:
        sample_img = img.convert('L')
    else:
        sample_img = img.convert('RGB')

    resized_img = sample_img.resize((w, h), Image.BILINEAR)
    resized = np.array(resized_img)
    if resized.ndim == 2:
        resized = resized[:,:,np.newaxis]

    typed = resized.astype(dtype)

    if scaling == 'INCEPTION':
        scaled = (typed / 128) - 1
    elif scaling == 'VGG':
        if c == 1:
            scaled = typed - np.asarray((128,), dtype=dtype)
        else:
            scaled = typed - np.asarray((123, 117, 104), dtype=dtype)
    else:
        scaled = typed

    # Swap to CHW if necessary
    if format == "FORMAT_NCHW":
        ordered = np.transpose(scaled, (2, 0, 1))
    else:
        ordered = scaled

    # Channels are in RGB order. Currently model configuration data
    # doesn't provide any information as to other channel orderings
    # (like BGR) so we just assume RGB.
    return ordered

def test_yolov3():
    image = Image.open("./dogs.jpg")
    c = 3 
    h = 416 
    w = 416 
    format = "FORMAT_NHWC"
    dtype = np.float32
    image_data = preprocesstr(image, format, dtype, c, h, w, 'INCEPTION') 

    data = image_data.tobytes()
    shape = [int(image.size[1]), int(image.size[0])]
    shape_data =  np.array(shape).tobytes()

    addr = "http://localhost:8000/api/infer/yolo"
    start = time.time()
    headers = {"Authorization": "Bearer " + TOKEN,
               "NV-InferRequest": 'batch_size: 1 input [{ name: "input_1" }, { name: "image_shape"}] output [{ name: "yolonms_layer_1/ExpandDims_1:0" }, { name: "yolonms_layer_1/ExpandDims_3:0"}, { name: "yolonms_layer_1/concat_2:0"}]'}
    res = requests.post(
        addr,
        #data=image_data.tobytes(),
        #data=bts,
        data=data+shape_data,
        headers=headers)
    end = time.time()
    if res.ok:
        response = res.content
        print("headers:" + str(res.headers))
        print("result: " + response)
    else:
        res.raise_for_status()

test_yolov3()

Error is in server
: **unexpected additional input data for model 'yolo'**

This is for yolov3. model was loaded successfully.
There are two inputs, but i am not sure it is right way.

**Comment by GuanLuo** [comment]
Can you can the size of `shape_data` and `data` are expected? And one thing I noticed is that the model expect the `image_shape` to be tensor in FP32, and I don't think `shape_data` is converted from a float array.

**Comment by buttonman** [comment]
yes..

you are right, it was because of size of shape_data.

I change the code like **shape_data =  np.array(shape, np.float32).tobytes()**

and then it works

Thank you for help

**Comment by zhangluustb** [comment]
> yes..
> 
> you are right, it was because of size of shape_data.
> 
> I change the code like **shape_data = np.array(shape, np.float32).tobytes()**
> 
> and then it works
> 
> Thank you for help

Hi, my res.content output is b'~\xe7XB\x7f\xfd\x19C\xada{C\x0c\x18\xa0C\xf2U\x08C\x06\x8f\x03C\x1807C\x90\xeePCd\x8fNC\x1c\xddJC\xde\xf6\x8bC&#rC\xd9\x9fRC\x04\x8...noutput {\n  name: "prob"\n  raw {\n    dims: 1\n    batch_byte_size: 4\n  }\n}\n'
How can i read this buffer to numpy?
