### ISSUE TITLE
HTTP API:  Access-Control-Allow-Origin etc.

### ISSUE THREAD

**Issue by JianbingDong** [NVIDIA/tensorrt-inference-server#1147]
Hi, 
I want to communicate with TRTIS through HTTP API (**using html XMLHttpRequest**) from cross domain, but the **Chrome** blocked this request because of CORS policy, and the error is like :
`XMLHttpRequest cannot load http://xxxxx. No 'Access-Control-Allow-Origin' header is present on the requested resource. 
`

So I wandering is there any chance I can modify the server response header to solve this problem?

**Comment by deadeyegoodwin** [comment]
The response or request? The client API provides a way for you to add HTTP headers to your request.

**Comment by JianbingDong** [comment]
@deadeyegoodwin I would like to communicate with TRTIS using **HTML** rather than C++ or Python application, therefore HTTP API is what I needed. Any suggestions?

**Comment by deadeyegoodwin** [comment]
You can talk directly to the server using the HTTP API described here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/http_grpc_api.html#http-and-grpc-api

See also issue #1129 

Admittedly the existing HTTP API is not standard and is a little difficult to use. We are rolling out a a V2 API (both HTTP/REST and GRPC) that is more standard over the next couple of releases. That API is the community-standard API from the KFServing project (you can find the PR here: https://github.com/kubeflow/kfserving/pull/709.

It will take us some time to get the entire V2 implemented with all the existing TRTIS features but it should be must easier to use directly. So depending on your timeline you can implement the current HTTP API and then convert to the new V2 when it becomes the default, of just wait for the V2.

**Comment by montardon** [comment]
Inference server does not seem to reply correctly to preflight OPTIONS request, even if headers for CORS are correclty set. 
So, trying to use the HTTP API with a javascript call in an HTML page, within a navigator is currenlty not well supported.

**Comment by wojciak** [comment]
Bump from 2022 :) Currently to get this rolling requires a CORS termination along the way, or using web-grpc + envoy. Would be nice if we could talk to Triton directly from the browser.
