### ISSUE TITLE
Is there any way to access the build script except pulling the image?

### ISSUE THREAD

**Issue by snowpeakz** [NVIDIA/tensorrt-inference-server#1149]
hi,
I am trying to compile TRTIS with tensorflow, but failed to pull `nvcr.io/nvidia/tensorflow:20.01-tf2-py3` bacause of network reason.  However, the doc of TRTIS says, "You can build and install a different version of the TensorFlow library but you must build with the equivalent options indicated by the patches used in the Dockerfile". 
So, Is there any way to access the files under this line except pulling the image?
```
/opt/tensorflow/nvbuild.sh
/opt/tensorflow/nvbuildopts
/opt/tensorflow/bazel_build.sh
```
What's more, I also can't find where is patches for tf2.0, Since files in tools\patch\tensorflow is for 1.x.
Thanks.

**Comment by deadeyegoodwin** [comment]
Starting in 20.02 there are no longer any patches... the changes are already applied in the tensorflow:20.01-tf1-py3 container on NGC (and in that release the build docs are updated to indicate that). So you must pull the container to be able to build TF yourself. Why does the download fail? I can ask about some alternative download path if I have more details.

As for TF 2, we do not yet support and applying the TF1 patches is unlikely to work correctly.

**Comment by snowpeakz** [comment]
@deadeyegoodwin 
Thanks. 
For reasons of download failure, it might because i am located in China mainland. 
I built TRTIS with tf2.1 after applying the patches manually, and it seems worked.

**Comment by deadeyegoodwin** [comment]
Thanks for the feedback on TF2.
Unfortunately there is currently no alternate way to get the NGC containers. We do get a lot of pulls from China but perhaps your ISP or connection doesn't allow such large downloads.
