### ISSUE TITLE
Multiple instance of the same model will load multiple copies of the model data in memory

### ISSUE THREAD

**Issue by snowpacer** [NVIDIA/tensorrt-inference-server#1153]
**Background description:**
I am testing tensorrt inference server 19.12 with tensorflow saved_model backend. I find that if I set the config.pbtxt as follows:
`instance_group [
  {
    count: 3
    kind: KIND_CPU
  }
]`

the model will be loaded three times during, and in memory there will be three copies of the same model. I understand the logic is to use one seperate session for each context, each handling its own requests coming from BatchScheduler. For GPU this makes sense as different instances should be clearly separated; but for CPU, this unnecessary number of memory copies will cause memory waste. 
I will give an application scenario showing why this matters. For example, I have an ensemble model with two steps. The model of first step is data preprocessing, which has very big model size (>30 GB) and has many memory intensive ops. The model of second step is an inference model which is very computation intensive. I can deploy the first model in CPU as it is IO bound, and the second on GPU as it is computation bound. For the first step, I set "count: 3" as I need to use three threads to speed up. The internal session parallelism of tensorflow (like inter_op_parallelism_threads) is not sufficient as first step is IO bound. However, if I use three instances to speed up, the memory usage will be 30*3=90G, which is unacceptable for deployment.

**Solution proposal:**
I think for CPU, multiple instances of the same model should use the same tensorflow session to avoid unnecessary memory waste.

**Comment by deadeyegoodwin** [comment]
I agree that we could likely be more efficient by sharing Tensorflow sessions. This sharing may also be helpful for GPUs. We have an open item on this but haven't schedule it. We'd appreciate a contribution to the Tensorflow backend.

But note that by sharing the session we should be able to share the model weights, but would still need 3 sets of the "activation" values when performing 3 inferences at the same time, and so you likely would have memory usage somewhere between 30G and 90G.

**Comment by snowpacer** [comment]
> 
> 
> I agree that we could likely be more efficient by sharing Tensorflow sessions. This sharing may also be helpful for GPUs. We have an open item on this but haven't schedule it. We'd appreciate a contribution to the Tensorflow backend.
> 
> But note that by sharing the session we should be able to share the model weights, but would still need 3 sets of the "activation" values when performing 3 inferences at the same time, and so you likely would have memory usage somewhere between 30G and 90G.

Thanks for the reply, I will try to see whether I can find a good solution to it.
