### ISSUE TITLE
Error when running TRTIS-20.01 built from source code--"Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.so"

### ISSUE THREAD

**Issue by zhouxuan009** [NVIDIA/tensorrt-inference-server#1154]
I am trying to build TRTIS-20.01 from source code with Caffe backend.
I copied the include files and libraries from container of tensorrtserver:20.01-py3 to a folder called 'libs_and_includes 'outside the container
Then I started to compile TRTIS
```
mkdir buildcaffe
cd buildcaffe
cmake -DTRTIS_EXTRA_LIB_PATHS="~/libs_and_includes/lib/pytorch" ../build
make -j128 trtis
```
After successful compilation, I put some library paths to my bashrc 
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/zhouxuan/libs_and_includes/local/mpi/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/zhouxuan/libs_and_includes/usr/lib/x86_64-linux-gnu
```
After that , I tried to run TRTIS
```
cd ~/tensorrt-inference-server/buildcaffe/trtis/install/bin
./trtserver --model-repository=/home/zhouxuan/tensorrt-inference-server/docs/examples/model_repository
```
However, I gave me the error info as:

>I0303 22:36:26.672772 41069 model_repository_manager.cc:675] loading: resnet50_netdef:1
I0303 22:36:26.672896 41069 model_repository_manager.cc:675] loading: resnet50_netdef_dyna:1
I0303 22:36:26.919968 41069 netdef_backend.cc:199] Creating instance resnet50_netdef_dyna_0_0_gpu0 on GPU 0 (7.5) using init_model.netdef and model.netdef
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
I0303 22:36:26.921154 41069 netdef_backend.cc:199] Creating instance resnet50_netdef_0_gpu0 on GPU 0 (7.5) using init_model.netdef and model.netdef
Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.so.

libmkl_intel_thread.so does not exist in the container.
The trtserver can be run in the container without libmkl_intel_thread.so, but cannot be run outside the container. Could u help give me some tips about how to solve it ?
Thx !

**Comment by deadeyegoodwin** [comment]
I assume you mean Caffe2, TRTIS doesn't support Caffe.
Did you build Caffe2 as described in the build section of the documentation and using a command like what is in Dockerfile?
You can see in the container at /opt/tensorrtserver/lib/pytorch that libmkl_gpu_thread.so is available and used by TRTIS. If you build a version that needs libmkl_intel_thread.so you should be able to get that library from your build and install it in the container.

**Comment by zhouxuan009** [comment]
I look at the [Dockerfile](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/Dockerfile) and It says that 

> \# Needed by Caffe2 libraries to avoid:
\# Intel MKL FATAL ERROR: Cannot load libmkl_intel_thread.so
ENV MKL_THREADING_LAYER GNU

**Comment by deadeyegoodwin** [comment]
Set that envvar before running TRTIS and it should resolve the load error.

**Comment by zhouxuan009** [comment]
Now I remove this error by adding "export MKL_THREADING_LAYER=GNU
" into ~/.bashrc.
However, when I run the server, after the TRTIS loads the models, It just unload the models without printing any error messages. Could you please help me give some advice about how to solve this situation ?

> ./trtserver --model-repository=/home/zhouxuan/tensorrt-inference-server/docs/examples/model_repository
I0304 19:47:58.346367 45352 metrics.cc:162] found 2 GPUs supporting NVML metrics
I0304 19:47:58.352033 45352 metrics.cc:171]   GPU 0: GeForce RTX 2080 Ti
I0304 19:47:58.357956 45352 metrics.cc:171]   GPU 1: GeForce RTX 2080 Ti
I0304 19:47:58.358193 45352 server.cc:112] Initializing TensorRT Inference Server
E0304 19:47:58.569984 45352 server.cc:139] failed to enable peer access for some device pairs
E0304 19:47:58.571174 45352 model_repository_manager.cc:1505] unexpected platform type onnxruntime_onnx for densenet_onnx
E0304 19:47:58.571268 45352 model_repository_manager.cc:1505] unexpected platform type tensorflow_graphdef for inception_graphdef
E0304 19:47:58.573709 45352 model_repository_manager.cc:1505] unexpected platform type tensorflow_graphdef for simple
E0304 19:47:58.573783 45352 model_repository_manager.cc:1505] unexpected platform type tensorflow_graphdef for simple_string
I0304 19:47:58.573803 45352 server_status.cc:55] New status tracking for model 'resnet50_netdef'
I0304 19:47:58.573814 45352 server_status.cc:55] New status tracking for model 'resnet50_netdef_dyna'
I0304 19:47:58.573850 45352 model_repository_manager.cc:675] loading: resnet50_netdef:1
I0304 19:47:58.573967 45352 model_repository_manager.cc:675] loading: resnet50_netdef_dyna:1
I0304 19:47:58.700096 45352 netdef_backend.cc:199] Creating instance resnet50_netdef_dyna_0_0_gpu0 on GPU 0 (7.5) using init_model.netdef and model.netdef
[E init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
I0304 19:47:58.701001 45352 netdef_backend.cc:199] Creating instance resnet50_netdef_0_gpu0 on GPU 0 (7.5) using init_model.netdef and model.netdef
I0304 19:48:00.884811 45352 netdef_backend.cc:199] Creating instance resnet50_netdef_0_gpu1 on GPU 1 (7.5) using init_model.netdef and model.netdef
I0304 19:48:00.887470 45352 netdef_backend.cc:199] Creating instance resnet50_netdef_dyna_0_1_gpu0 on GPU 0 (7.5) using init_model.netdef and model.netdef
I0304 19:48:01.922263 45352 model_repository_manager.cc:829] successfully loaded 'resnet50_netdef_dyna' version 1
I0304 19:48:02.716350 45352 model_repository_manager.cc:829] successfully loaded 'resnet50_netdef' version 1
I0304 19:48:02.733159 45352 model_repository_manager.cc:808] successfully unloaded 'resnet50_netdef_dyna' version 1
I0304 19:48:02.746322 45352 model_repository_manager.cc:808] successfully unloaded 'resnet50_netdef' version 1
error: creating server: INTERNAL - failed to load all models

**Comment by deadeyegoodwin** [comment]
It does give an error, it says "error: creating server: INTERNAL - failed to load all models"

And if you look up in the log at the lines starting with "E" you see errors saying that you are trying to load models with platforms that the server doesn't understand. For example,

E0304 19:47:58.571174 45352 model_repository_manager.cc:1505] unexpected platform type onnxruntime_onnx for densenet_onnx

You can load densenet_onnx unless you have built TRTIS with support for onnx.

**Comment by zhouxuan009** [comment]
Sorry, I made a stupid mistake. I thought that it will run some of the models under the folder. The truth is that it will run only when all of the models under the folder are runnable.
Now I can successfully run it. Thank you !
