### ISSUE TITLE
20.02 model load err

### ISSUE THREAD

**Issue by 121786404** [NVIDIA/tensorrt-inference-server#1157]
**Description**
model load err

**TRTIS Information**
20.02

**To Reproduce**

**Expected behavior**

i use onnx-tensorrt convert onnx to trt model；（set Max batch size:  32）
i meet error with version 20.02。
but version 19.10（tensorrt 6）can work

failed to load 'mfnb_trt' version 1: Invalid argument: unexpected configuration maximum batch size 32 for 'mfnb_trt_0_0_gpu0', model maximum is 1 as model does not contain an implicit batch dimension nor the explicit batch-dimension of 'data_input' is a wildcard.

`name: "mfnb_trt"
platform: "tensorrt_plan"
max_batch_size : 32
dynamic_batching {
  preferred_batch_size: [ 4, 8 , 16, 24 ,32]
  max_queue_delay_microseconds: 100
}

input [
  {
    name: "data_input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [3, 112, 112 ]
  }
]
output [
  {
    name: "fc1_Y" 
    data_type: TYPE_FP32
    dims: [1, 512 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
`

**Comment by deadeyegoodwin** [comment]
Take a look at https://github.com/NVIDIA/tensorrt-inference-server/issues/1105. Especially this comment https://github.com/NVIDIA/tensorrt-inference-server/issues/1105#issuecomment-586474508 and the following one.

**Comment by 121786404** [comment]
> Take a look at #1105. Especially this comment [#1105 (comment)](https://github.com/NVIDIA/tensorrt-inference-server/issues/1105#issuecomment-586474508) and the following one.

 ./onnx2trt fr_mfnb.onnx -b -1 -o fr_mfnb.plan
----------------------------------------------------------------

Building TensorRT engine, FP16 available:1
    Max batch size:     18446744073709551615
    Max workspace size: 1024 MiB
[2020-03-05 01:47:08   ERROR] Parameter check failed at: ../builder/builder.cpp::setMaxBatchSize::113, condition: batchSize > 0 && batchSize <= MAX_BATCH_SIZE

**Comment by deadeyegoodwin** [comment]
onnx2trt is a utility included with TensorRT optimizer/runtime. You should ask you question there and they should be able to help: https://github.com/NVIDIA/TensorRT
