### ISSUE TITLE
S3 file system should support remote minio server as well

### ISSUE THREAD

**Issue by 24hours** [NVIDIA/tensorrt-inference-server#1173]
**Is your feature request related to a problem? Please describe.**
I have setup a remote minio server at my organization, I tried to execute server with 
trtserver --model-repository s3://10.0.0.0:9000/model-bucket 
it just crash with "Could not find bucket with name 10.0.0.0"

**Describe the solution you'd like**
trtis should support s3 server with remote address

**Describe alternatives you've considered**
n/a

I find that the feature can be added by modifying 

https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/filesystem.cc#L608

s3://([0-9a-z-.]+):([0-9]+)/([0-9a-z.-]+)(((/[0-9a-z.-_]+)*)?)")

**Comment by CoderHam** [comment]
@24hours Sure, I will make these changes and test support for remote minio s3 buckets as well.
