### ISSUE TITLE
How to make dynamic requests?

### ISSUE THREAD

**Issue by buttonman** [NVIDIA/tensorrt-inference-server#1174]
**Description**
I load a model with dynamic batch config
**dynamic_batching {
  preferred_batch_size: [ 2, 4 ]
  max_queue_delay_microseconds: 2000
}**

And I send a request to http rest api with following header

**headers = {
               "NV-InferRequest": 'batch_size: 2 input { name: "%s" } output { name: "%s" cls { count: 1 } }' % (input_name, output_name) }**

The tensorrt server return following

**model_name: "inception_graphdef"
model_version: 1
batch_size: 2
output {
  name: "InceptionV3/Predictions/Softmax"
  batch_classes {
    cls {
      idx: 505
      value: 0.826383293
      label: "COFFEE MUG"
    }
  }
  batch_classes {
    cls {
      idx: 505
      value: 0.826383293
      label: "COFFEE MUG"
    }
  }
}**

The tensorrt document said "Dynamic batching is a feature of the inference server that allows inference requests to be combined by the server"

How is it works?

I expected the combined result, but it return all responses without combine
I try to change batch_size in header to 1 or 3, the result is same.

How to make server to combine for each request?

**Comment by deadeyegoodwin** [comment]
You will always get a response for each request you make. The dynamic batcher combines multiple requests together for inference processing to improve throughput, but it does not actually combine the results. You will still get a response for each request. This presentation talks about the dynamic batcher: https://on-demand-gtc.gputechconf.com/gtcnew/sessionview.php?sessionName=s9438-maximizing+utilization+for+data+center+inference+with+tensorrt+inference+server
