### ISSUE TITLE
image client build error

### ISSUE THREAD

**Issue by pwlazy** [NVIDIA/tensorrt-inference-server#118]
sudo docker build -t tensorrtserver_clients --target trtserver_build  --build-arg "BUILD_CLIENTS_ONLY=1" .

then the error is as below

`ERROR: no such package '@local_config_cuda//crosstool': The repository could not be resolved`

some env information is as below

> Docker version 18.09.0, build 4d60db4
> tensorrtserver 18.11-py3
> cuda 10
> cudnn 7.3
> cuda Driver Version: 410.48
> bazel  version : Build label: 0.20.0- (@non-git)

**Comment by deadeyegoodwin** [comment]
Is there a reason you are using 18.11 branch. The 19.02 branch was just released, can you try with that.

**Comment by pwlazy** [comment]
i tried the the 19.02 branch, it works,  thanks!
