### ISSUE TITLE
Access to shared memory & CUDA shared memory through HTTP REST API

### ISSUE THREAD

**Issue by JianbingDong** [NVIDIA/tensorrt-inference-server#1188]
Hi,
As mentioned in the title, is there any way i can register and use the system shared memory and cuda shared memory through **HTTP REST API** rather than c++ or python clients?

**Comment by deadeyegoodwin** [comment]
Yes, there is an HTTP/REST API for shared memory register/unregister but it is not documented. If you use the HTTP client library with verbose option you can see what it is doing. We are working on a version 2 of the REST API that will be fully documented. Expect to see that in the next 1-2 months.
