### ISSUE TITLE
Problem with ssd 

### ISSUE THREAD

**Issue by zoidburg** [NVIDIA/tensorrt-inference-server#12]
Hi, I'm trying to serve a TRT plan which is generated from the TensorRT ssd sample. It looks like something went wrong while deserializing plugins like PriorBox, Normalize and NMS.
`E1213 11:48:24.882317 1602 logging.cc:44] getPluginCreator could not find plugin                                                                                                         Normalize_TRT version 1 namespace
E1213 11:48:24.882339 1602 logging.cc:44] Cannot deserialize plugin Normalize_TR                                                                                                        T
E1213 11:48:24.882427 1602 logging.cc:44] getPluginCreator could not find plugin                                                                                                         PriorBox_TRT version 1 namespace
E1213 11:48:24.882442 1602 logging.cc:44] Cannot deserialize plugin PriorBox_TRT
E1213 11:48:24.882496 1602 logging.cc:44] getPluginCreator could not find plugin                                                                                                         PriorBox_TRT version 1 namespace
E1213 11:48:24.882515 1602 logging.cc:44] Cannot deserialize plugin PriorBox_TRT
E1213 11:48:24.883639 1602 logging.cc:44] getPluginCreator could not find plugin                                                                                                         PriorBox_TRT version 1 namespace
E1213 11:48:24.883659 1602 logging.cc:44] Cannot deserialize plugin PriorBox_TRT
E1213 11:48:24.884158 1602 logging.cc:44] getPluginCreator could not find plugin                                                                                                         PriorBox_TRT version 1 namespace
E1213 11:48:24.884172 1602 logging.cc:44] Cannot deserialize plugin PriorBox_TRT
E1213 11:48:24.884213 1602 logging.cc:44] getPluginCreator could not find plugin                                                                                                         PriorBox_TRT version 1 namespace
E1213 11:48:24.884228 1602 logging.cc:44] Cannot deserialize plugin PriorBox_TRT
E1213 11:48:24.885036 1602 logging.cc:44] getPluginCreator could not find plugin                                                                                                         PriorBox_TRT version 1 namespace
E1213 11:48:24.885051 1602 logging.cc:44] Cannot deserialize plugin PriorBox_TRT
E1213 11:48:24.885119 1602 logging.cc:44] getPluginCreator could not find plugin                                                                                                         NMS_TRT version 1 namespace
E1213 11:48:24.885133 1602 logging.cc:44] Cannot deserialize plugin NMS_TRT
`

backtrace is like:
`
#0  0x00007f309e28772b in nvinfer1::rt::cuda::PluginV2Layer::allocateResources(nvinfer1::rt::CommonContext const&) () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.5
[Current thread is 1 (Thread 0x7f2ca7f40700 (LWP 1812))]
(gdb) bt
#0  0x00007f309e28772b in nvinfer1::rt::cuda::PluginV2Layer::allocateResources(nvinfer1::rt::CommonContext const&) () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.5
#1  0x00007f309e25367f in nvinfer1::rt::Engine::initialize() () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.5
#2  0x00007f309e256d14 in nvinfer1::rt::Engine::deserialize(void const*, unsigned long, nvinfer1::IGpuAllocator&, nvinfer1::IPluginFactory*) ()
   from /usr/lib/x86_64-linux-gnu/libnvinfer.so.5
#3  0x00007f309e23fc43 in nvinfer1::Runtime::deserializeCudaEngine(void const*, unsigned long, nvinfer1::IPluginFactory*) () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.5
#4  0x00007f30b435d3d9 in nvidia::inferenceserver::PlanBundle::CreateExecutionContext(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<char, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<char, std::allocator<char> > > > > const&) ()
#5  0x00007f30b435e34b in nvidia::inferenceserver::PlanBundle::CreateExecutionContexts(std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<char, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<char, std::allocator<char> > > > > const&) ()
#6  0x00007f30b43569ae in nvidia::inferenceserver::(anonymous namespace)::CreatePlanBundle(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<nvidia::inferenceserver::PlanBundle, std::default_delete<nvidia::inferenceserver::PlanBundle> >*) ()
#7  0x00007f30b4355177 in std::_Function_handler<tensorflow::Status (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<nvidia::inferenceserver::PlanBundle, std::default_delete<nvidia::inferenceserver::PlanBundle> >*), tensorflow::Status (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<nvidia::inferenceserver::PlanBundle, std::default_delete<nvidia::inferenceserver::PlanBundle> >*)>::_M_invoke(std::_Any_data const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<nvidia::inferenceserver::PlanBundle, std::default_delete<nvidia::inferenceserver::PlanBundle> >*&&)
    ()
#8  0x00007f30b435526c in std::_Function_handler<tensorflow::Status (std::unique_ptr<nvidia::inferenceserver::PlanBundle, std::default_delete<nvidia::inferenceserver::PlanBundle> >*), tensorflow::serving::SimpleLoaderSourceAdapter<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nvidia::inferenceserver::PlanBundle>::Convert(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::unique_ptr<tensorflow::serving::Loader, std::default_delete<tensorflow::serving::Loader> >*)::{lambda(std::unique_ptr<nvidia::inferenceserver::PlanBundle, std::default_delete<nvidia::inferenceserver::PlanBundle> >*)#1}>::_M_invoke(std::_Any_data const&, std::unique_ptr<nvidia::inferenceserver::PlanBundle, std::default_delete<nvidia::inferenceserver::PlanBundle> >*&&) ()
#9  0x00007f30b4356eaa in tensorflow::serving::SimpleLoader<nvidia::inferenceserver::PlanBundle>::Load() ()
#10 0x00007f30b43be159 in std::_Function_handler<tensorflow::Status (), tensorflow::serving::LoaderHarness::Load()::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#11 0x00007f30b43c0577 in tensorflow::serving::Retry(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, long long, std::function<tensorflow::Status ()> const&, std::function<bool ()> const&) ()
#12 0x00007f30b43bf496 in tensorflow::serving::LoaderHarness::Load() ()
#13 0x00007f30b43bb7dd in tensorflow::serving::BasicManager::ExecuteLoad(tensorflow::serving::LoaderHarness*) ()
#14 0x00007f30b43bbbfc in tensorflow::serving::BasicManager::ExecuteLoadOrUnload(tensorflow::serving::BasicManager::LoadOrUnloadRequest const&, tensorflow::serving::LoaderHarness*) ()
#15 0x00007f30b43bd456 in tensorflow::serving::BasicManager::HandleLoadOrUnloadRequest(tensorflow::serving::BasicManager::LoadOrUnloadRequest const&, std::function<void (tensorflow::Status const&)>) ()
#16 0x00007f30b43bd54f in std::_Function_handler<void (), tensorflow::serving::BasicManager::LoadOrUnloadServable(tensorflow::serving::BasicManager::LoadOrUnloadRequest const&, std::function<void (tensorflow::Status const&)>)::{lambda()#2}>::_M_invoke(std::_Any_data const&) ()
#17 0x00007f30ba1769e9 in Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
#18 0x00007f30ba174b87 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&)
    ()
#19 0x00007f301fb3ac80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#20 0x00007f30207426ba in start_thread (arg=0x7f2ca7f40700) at pthread_create.c:333
#21 0x00007f301f5a941d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
`

So is the serialized engine plan broken? Or is something wrong with my config. How to solve this problem?

**Comment by deadeyegoodwin** [comment]
I believe that the SSD example requires custom plugins that are provided with the example, is that correct. If so that is the problem, because TRTIS does not yet support TRT models with custom plugins. It is on the roadmap. I've filled issue #16 to track the TensorRT plugin request. Please give a "thumbs-up" on that issue and explain why you are blocked so we can prioritize.

**Comment by zoidburg** [comment]
I'll close this issue and we can discuss it in #16
