### ISSUE TITLE
Potential GPU memory leak for TensorFlow models?

### ISSUE THREAD

**Issue by qianl15** [NVIDIA/tensorrt-inference-server#122]
Hi,

I was testing with `tensorrtserver:19.02-py3`. However, I found the GPU memory usage became near 100% after running one TensorFlow savedmodel. The memory usage didn't go down even when I unloaded that model. Moreover, I have set `--tf-gpu-memory-fraction=0.1` but it didn't help.

So is it possible that trtserver has GPU memory leak for TensorFlow models? Because the memory usage looks good with tensorrt plans.

Thanks

**Comment by deadeyegoodwin** [comment]
Thanks for the report, we will take a look.

**Comment by qianl15** [comment]
Thank you.

I forgot to mention that if you just load a TensorFlow model, the GPU memory would just go up by a fraction of 0.1. The memory usage will ramp up only after sending one request to the model and never go down after that. More precisely, after showing `"successfully opened CUDA library libcublas.so.10.0 locally" `.

**Comment by GuanLuo** [comment]
Do you mind to post the command you use to start the server? Also, if possible, which model are you using?

**Comment by qianl15** [comment]
Sure, the command is:
```
nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 \
-p8000:8000 -p8001:8001 -p8002:8002 -v/tmp/models:/models \
nvcr.io/nvidia/tensorrtserver:19.02-py3 trtserver --model-store=/models \
--strict-model-config=false --repository-poll-secs=1 --tf-gpu-memory-fraction=0.1
```

And the model I used was a saved model from keras.applications.resnet. ResNet50, using `SavedModelBuilder `. I provided the file [saved_model.pb](https://s3-us-west-2.amazonaws.com/trtis-tf-models/resnet50/1/model.savedmodel/saved_model.pb). Since TRTIS is able to auto generate the config file, I didn't use the config.pbtxt.

To reproduce the issue, you could start TRTIS and put the model under `/tmp/models` directory. Before any queries, the GPU memory usage should be pretty low. Then use `perf_client` or so to generate a bunch of queries and probably you'll find GPU memory usage became 100%. 

The GPU I tested on was `Tesla V100-SXM2-16GB`.

Thank you again for helping on this!
