### ISSUE TITLE
Encountered out of memoryError when using perf_client test with various batch sizes

### ISSUE THREAD

**Issue by leeyoung48** [NVIDIA/tensorrt-inference-server#13]
I am trying test Tesla P4 performance with TRT inference server. My GPU memory is 8GB.
I tested using perf_client c++ sample and resetnet50_netdef model, starting with batchsize=1 , and then double the batchsize and go on.
I found test result is OK when batchsize = 8 and test failed when batchsize = 16 due to out of memory error.
what make me confused is the batchsize=4 and batchsize=8 test also failed after the batchsize16 test got bad result. As my thought batchsize < 16 tests should be always OK.
Could you give me some explanation for that? Thanks.

**Comment by deadeyegoodwin** [comment]
Can you give the exact steps that lead to the failure (command-line invocation of TRTIS and perf_client). We can use these steps to attempt to reproduce the failure.

**Comment by leeyoung48** [comment]
server start command: nvidia-docker run --rm --network=host --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/workspace/github/tensorrt-inference-server/docs/examples/model_repository:/models nvcr.io/nvidia/tensorrtserver:18.11-py3 trtserver --model-store=/models

**Comment by leeyoung48** [comment]
[perf_client_log.txt](https://github.com/NVIDIA/tensorrt-inference-server/files/2684390/perf_client_log.txt)

**Comment by deadeyegoodwin** [comment]
Thanks for the log. It looks like the netdef backend is not recovering gracefully after getting an OOM. We will look into the issue and update once we have new information.
