### ISSUE TITLE
Does TRTIS support model parallelism?

### ISSUE THREAD

**Issue by vilmara** [NVIDIA/tensorrt-inference-server#131]
Hi all, does TRTIS support model parallelism?, I mean, if a single model is copied in several GPUs to maximize inference throughput. Thanks,

**Comment by deadeyegoodwin** [comment]
Yes, you can serve multiple different models, multiple instances of the same model, or multiple instances of multiple models, on one or more CPUs and GPUs, simultaneously. 

The docs discuss it here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_configuration.html?highlight=batching#instance-groups

As does this blog post (in the Performance section): https://devblogs.nvidia.com/nvidia-serves-deep-learning-inference/

**Comment by vilmara** [comment]
@deadeyegoodwin, thanks for your prompt reply

**Comment by shanshanpt** [comment]
> @deadeyegoodwin for a large model that doesn't fit on a single GPU, how does triton split the model onto mutlple GPUs then?

Triton may not support this case based on my experience.
