### ISSUE TITLE
How to deploy serialized models?

### ISSUE THREAD

**Issue by PeopleComeAndGo** [NVIDIA/tensorrt-inference-server#133]
My inference task will need go through a detection model first and then use the detection result as the input of classification model.
is there any way  to put detection and classification in one request,so they can pass the data using share-memory?  To avoid the overhead of passing data through http request.

**Comment by deadeyegoodwin** [comment]
We use the term "ensembling" for what you are describing. We have already started on an implementation of ensembling and plan to have it complete for the 19.04 release (~ April 25th). 

We have already pushed the model configuration change on master. You can see it here: https://github.com/NVIDIA/tensorrt-inference-server/commit/e926b8590e73631292757d5ece619729dce00feb

**Comment by PeopleComeAndGo** [comment]
great, happy to know, thanks!

**Comment by PeopleComeAndGo** [comment]
great, happy to know, thanks!

**Comment by SlipknotTN** [comment]
Does the ensemble already works? I managed to create a valid configuration, but if try to do a client call I get the error "Unexpectedly invoked EnsembleBundle::Run()".

**Comment by deadeyegoodwin** [comment]
@SlipknotTN No, the ensembling solution is "in progress". We are aiming to have it complete before the end of the month so it can be included in the 19.04 release.
