### ISSUE TITLE
Unable to collect inference metrics for nullptr servable

### ISSUE THREAD

**Issue by nieksand** [NVIDIA/tensorrt-inference-server#134]
If I shutdown TRTIS while new requests are still coming in, I get a slew of  "Unable to collect inference metrics for nullptr servable" messages near the end of the shutdown process.

This is just an annoyance.  It doesn't seem to hurt anything.

I am using the http endpoint on `tensorrtserver:19.02-py3 ` with a GTX 1060.

This gist shows the hanky panky:
https://gist.github.com/nieksand/007e70d49b2b6bba63144715d97f481e

My client script is just serially poking TRTIS: send single inference request, wait for the response, send the next/

**Comment by deadeyegoodwin** [comment]
Thanks for the report, we will take a look.

**Comment by nieksand** [comment]
I can no longer reproduce this on the 19.03 release.

This issue can probably be closed.
