### ISSUE TITLE
can not run tensorrt-inference-servere-19.02 with cuda-driver-396.26

### ISSUE THREAD

**Issue by xulizhi321** [NVIDIA/tensorrt-inference-server#139]
I pull the image nvcr.io/nvidia/tensorrtserver:19.02-py3 ,  and fail to start the server in the container.
The error msg is :      

> NVIDIA Release 19.02 (build 5627847)
> 
> Copyright (c) 2018, NVIDIA CORPORATION.  All rights reserved.
> Copyright 2018 The TensorFlow Authors.  All rights reserved.
> Copyright 2018 The TensorFlow Serving Authors.  All rights reserved.
> Copyright (c) 2016-present, Facebook Inc. All rights reserved.
> 
> Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
> NVIDIA modifications are covered by the license terms that apply to the underlying
> project or file.
> 
> ERROR: This container was built for NVIDIA Driver Release 410 or later, but
>        version 396.26 was detected and compatibility mode is UNAVAILABLE.
> 
>        [[CUDA Driver UNAVAILABLE (cuInit(0) returned 999)]]

But the container can run normally if I change my NVIDIA Driver from verion 396 to 384.
According to https://docs.nvidia.com/deeplearning/dgx/support-matrix/index.html , the container is supposed to run normally with NVIDIA Driver 384.111+.

in addition, my environment is  Ubuntu 16.04, Tesla P4/P100.

**Comment by cliffwoolley** [comment]
Hi @xulizhi321 ; sorry for the ambiguous documentation there.  I'll ask our technical writer to clarify it.  The more complete answer is that the CUDA driver's compatibility package only handles particular earlier branches, and R396 doesn't happen to be one of them.  See here https://docs.nvidia.com/deploy/cuda-compatibility/index.html#cuda-application-compatibility .
