### ISSUE TITLE
TRTIS and Kubeflow docker image

### ISSUE THREAD

**Issue by vilmara** [NVIDIA/tensorrt-inference-server#141]
hi all, is there a docker image that orchestrates TensorRT Inference Server with Kubeflow?

**Comment by deadeyegoodwin** [comment]
There is not a docker image but there is an example on the KubeFlow repo: https://github.com/kubeflow/kubeflow/tree/master/kubeflow/nvidia-inference-server

It is referenced in this blog post: https://medium.com/kubeflow/gpu-accelerated-inference-for-kubernetes-with-the-nvidia-tensorrt-inference-server-and-kubeflow-63061305fff2

**Comment by vilmara** [comment]
thanks @deadeyegoodwin, what would be the main difference ruining TRTIS only versus the orchestration with Kubeflow?

**Comment by deadeyegoodwin** [comment]
The existing Kubeflow example just launches a single pod containing a single TRTIS, so it is really just a minimal example. The example uses jsonnet which, I believe, may be on its way out. We also have an open pull requests doing a similar simple deployment using helm. You can see that here: https://github.com/NVIDIA/tensorrt-inference-server/pull/127

**Comment by deadeyegoodwin** [comment]
We do have plans to do a more advanced Helm chart that deploys an autoscaling cluster of inference server pods where the autoscaling is controlled by the prometheus metrics reported by the inference server, but we don't have any progress on that currently. That would be a great contribution to the project.

**Comment by vilmara** [comment]
thanks!
