### ISSUE TITLE
Visualization tool that shows the TensorRT Inference Server Metrics

### ISSUE THREAD

**Issue by vilmara** [NVIDIA/tensorrt-inference-server#142]
Hi all, is there some kind of visualization tool that shows the TensorRT Inference Server Metrics in real time?, something like shown in the webinar https://info.nvidia.com/tensorrt-inference-server-webinar-reg-page

**Comment by nieksand** [comment]
The metrics are just in Prometheus format.   

You typically would have something polling the metrics and storing the results in a time series database (e.g. InfluxDB).  Then you'd use something like Grafana for the dashboard visualizations.

There are a bunch of SaaS solutions that can do the gathering/visualization bit for you.  e.g. Datadog has a Prometheus integration: 
https://www.datadoghq.com/blog/monitor-prometheus-metrics/

**Comment by vilmara** [comment]
hi @nieksand thanks for your support I will explore your recommendations. On another hand, I just found this link https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/metrics.html at the Nvidia TRTIS user guide, that explains these metrics are available at http://localhost:8002/metrics; have you tied if it, if so what method do you recommend?

**Comment by deadeyegoodwin** [comment]
The metrics on port 8002 are what @nieksand  was referring to. That port presents the metrics in prometheus format (it is also a human readable format so you can just curl to that port and see the metrics yourself). You need to find some prometheus service/database that you can point at that port which will scrap and collect the metrics. Once you have the metrics in a database you can view them with tools like grafana. I would start with the links that @nieksand suggested.

**Comment by vilmara** [comment]
thanks @deadeyegoodwin / @nieksand, is there some example that illustrates the entire process using TRTIS, Prometheus and Grafana?

**Comment by nieksand** [comment]
I think you should look at getting Prometheus/Grafana up and running.  TRTIS is just another prometheus metric emitter which you should be able to scrape into Prometheus.  

That's about all I can help with on the topic.

**Comment by deadeyegoodwin** [comment]
Closing. It you find any useful tools please update this issue with what you have learned.

**Comment by vilmara** [comment]
hi @deadeyegoodwin, I found the Nvidia tool called DATA CENTER GPU MANAGER (DCGM). )http://on-demand.gputechconf.com/gtc/2018/presentation/s8505-gpu-monitoring-and-management-with-nvidia-data-center-gpu-manager-dcgm-v2.pdf)

My goal is to build A Monitoring Dashboard where I can monitor my data center with models deployed on TRTIS. Question: should I build a DCGM+Prometheus+Grafana Monitoring Dashboard or a TRTIS+Prometheus+Grafana Monitoring Dashboard? Which one will provide broader metrics of my data center?

**Comment by deadeyegoodwin** [comment]
@vilmara You likely want to use both. DCGM provides a lot of lower-level, "generic" metrics for GPUs, but DCGM doesn't provide any inference-specific metrics. TRTIS provides inference metrics and also some GPU metrics which are likely redundant with DCGM. TRTIS does this because not everyone using TRTIS will want to use DCGM.
