### ISSUE TITLE
TRTIS should support TensorRT models that require custom plugins

### ISSUE THREAD

**Issue by deadeyegoodwin** [NVIDIA/tensorrt-inference-server#16]

**Comment by zoidburg** [comment]
As mentioned in #12 , I got some problem with SSD TRT plan distribution on TRTIS. And yes, there are several custom plugins in the SSD sample such as NMS, Normalize, PriorBox and so on. While serving with the engine plan serialized from the SSD sample, it seems that TRTIS did not deserialize these part correctly.  

It would be great if the TRT plugin mechanism were fully supported in TRTIS. And I think a complete tutorial with SSD TRT plan might be helpful, as detection task is quite common in these days.

**Comment by deadeyegoodwin** [comment]
As a work-around for TRTIS not yet having TRT plugin support, you should be able to use LD_PRELOAD in many cases. For example, assuming your TRT plugins are compiled into trtplugins.so.

  $ LD_PRELOAD=trtplugins.so trtserver --model-store=/tmp/models ...

You can load multiple plugin libraries with LD_PRELOAD. The limitation of this approach is that the plugins must be managed separately from the model store itself. And more seriously, if there are plugin name conflicts across multiple plugin libraries there is now way to handle it. But if you have just a single plugin library this should get you unblocked.

**Comment by FamousDirector** [comment]
How would you suggest I compile plugins into trtplugins.so?

**Comment by deadeyegoodwin** [comment]
The TensorRT documentation has description and examples on how to create TensorRT plugin libraries: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#extending

**Comment by IMG-PRCSNG** [comment]
Has anyone tried using `libnvinfer_plugin.so` in `LD_PRELOAD`? I am unable to get it to work even though it has all the plugins.

**Comment by DebashisGanguly** [comment]
I am still facing the same issue:
LD_PRELOAD=libnvinfer_plugin.so /opt/tensorrtserver/bin/trtserver --model-store=/ScriptsNModels/TestModelZoo

E0612 20:28:44.454662 46 logging.cc:43] getPluginCreator could not find plugin Normalize_TRT version 1 namespace 

E0612 20:28:44.454670 46 logging.cc:43] Cannot deserialize plugin Normalize_TRT

E0612 20:28:44.454697 46 logging.cc:43] getPluginCreator could not find plugin PriorBox_TRT version 1 namespace 

E0612 20:28:44.454715 46 logging.cc:43] Cannot deserialize plugin PriorBox_TRT

E0612 20:28:44.454736 46 logging.cc:43] getPluginCreator could not find plugin PriorBox_TRT version 1 namespace 

E0612 20:28:44.454742 46 logging.cc:43] Cannot deserialize plugin PriorBox_TRT

E0612 20:28:44.454763 46 logging.cc:43] getPluginCreator could not find plugin PriorBox_TRT version 1 namespace 

E0612 20:28:44.454777 46 logging.cc:43] Cannot deserialize plugin PriorBox_TRT

E0612 20:28:44.454795 46 logging.cc:43] getPluginCreator could not find plugin PriorBox_TRT version 1 namespace 

E0612 20:28:44.454813 46 logging.cc:43] Cannot deserialize plugin PriorBox_TRT

E0612 20:28:44.454831 46 logging.cc:43] getPluginCreator could not find plugin PriorBox_TRT version 1 namespace 

E0612 20:28:44.454838 46 logging.cc:43] Cannot deserialize plugin PriorBox_TRT

E0612 20:28:44.454857 46 logging.cc:43] getPluginCreator could not find plugin PriorBox_TRT version 1 namespace 

E0612 20:28:44.454864 46 logging.cc:43] Cannot deserialize plugin PriorBox_TRT

E0612 20:28:44.454900 46 logging.cc:43] getPluginCreator could not find plugin NMS_TRT version 1 namespace 

E0612 20:28:44.454907 46 logging.cc:43] Cannot deserialize plugin NMS_TRT

Note that I have a serialized plan file for SSD from running sampleSSD in TensorRT code.

Can anyone also provide a config.pbtxt for SSD?

**Comment by clancylian** [comment]
I have implemented IPluginFactory with plugin and set
`ICaffeParser* parser = createCaffeParser();
parser->setPluginFactoryExt(&pluginFactory);`

and generate tensorrt model . when I employ it to server, it occur error
`ERROR: Not a valid serialized plugin`

And I also implemented plugin with IPluginV2 IPluginCreator. and generate lib.so 
and use LD_PRELOAD=trtplugins.so but also occur the same error!

**Comment by deadeyegoodwin** [comment]
We're working on validating TRT plugin support in TRTIS. It appears to work in some cases but not all. We'll update here once we learn more.

**Comment by CoderHam** [comment]
We will be adding support for the default provided plugins shipped with TensorRT for now. We may add custom plugins support in the future if possible.
This means that plugins mentioned [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#add_custom_layer) will be supported by default in TRTIS in the future releases.

**Comment by CoderHam** [comment]
Support for **default** plugins as mentioned [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#add_custom_layer) is added on master and will be in 19.07. Please retry your model/s to let me know if it is not fixed for you.

**Comment by seovchinnikov** [comment]
I've successfully imported custom ops imported from onnx parser and registered there via LD_PRELOAD workaround.
