### ISSUE TITLE
CUDAStreams only supported for TensorRT backend?

### ISSUE THREAD

**Issue by erickim555** [NVIDIA/tensorrt-inference-server#171]
Is it true that concurrent model execution (eg via CUDAStreams) is only supported for TensorRT executable engines? Specifically, that tensorflow and caffe2 backends do not support concurrent model execution?

**Comment by GuanLuo** [comment]
All the framework backends support concurrent model execution. This [session](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/architecture.html#concurrent-model-execution) describes some details on how it works.

**Comment by deadeyegoodwin** [comment]
There was also a talk at GTC 2019 that described how this works: "Maximizing Utilization for Data Center Inference with TensorRT Inference Server".

It will be publicly available at GTC On-Demand in about 30 days: https://on-demand-gtc.gputechconf.com/gtcnew/on-demand-gtc.php

We'll post a link to it in the README once it become available.

Closing, reopen if you have further questions.
