### ISSUE TITLE
Does TRTIS support large models that place on multiple devices？

### ISSUE THREAD

**Issue by NanYan1119** [NVIDIA/tensorrt-inference-server#18]
I noticed the description in the TRTIS documentation that "Multiple model support. The server can manage any number and mix of models (limited by system disk and memory resources)". So I want to know if TRTIS supports when my model is so large that can not load on only one device and need to split on multiple devices (GPUs). Thank you!

**Comment by deadeyegoodwin** [comment]
Currently, TRTIS only supports inferencing on a model that resides completely on 1 GPU.
