### ISSUE TITLE
Caffe2 Backend: Support models with flexible input/output shapes in batch mode

### ISSUE THREAD

**Issue by erickim555** [NVIDIA/tensorrt-inference-server#184]
Currently, eg as of 19.03, the Caffe2 TRTIS backend makes the following assumption regarding batch inference (eg batch_size > 1):

Input shape=[nb_images, dim1, dim2, ...]
Output shape=[nb_images, dim1, dim2, ...]

Specifically, it prepends a batch dimension to the input/output tensor shapes.

This works well for image classification models. However, for other models (eg object detection models from [Detectron](https://github.com/facebookresearch/Detectron), this does not work. As a concrete example, Detectron object detection models expect the following shapes:

```
Input:
  image.shape=[nb_images, nb_channels, img_height, img_width]
Outputs:
  boxes.shape=[nb_boxes, 6]
    where each row boxes[i, :] -> [x1, y1, x2, y2, float confidence, int category_index].
    notably, boxes is arranged sequentially by image
  batch_splits.shape=[nb_images]
    Denotes nb of boxes for each image in the batch.
    Example: if batch_splits = [42, 3], then the first 42 boxes in `boxes` belong to the first image, and the next 3 boxes belong to the second image.
```

Currently, the Caffe2 TRTIS backend (and possibly all other backends) do not support this output behavior. It'd be great if the backends can support this usecase. Thank you!

**Comment by deadeyegoodwin** [comment]
It's strange that the model didn't implement the output as [nb_images, nb_boxes, 6]. That would become [-1, -1, 6] as the shape of the output tensor (where the first -1 is the batch dimension) and then you wouldn't need batch_splits.

The model can be used as-is by setting max_batch_size = 0. This indicates that the model doesn't support batching.. or more precisely, it informs TRTIS to not assume that it understand how the model batches. With max_batch_size == 0, you can then explicitly manage the batch dimension:

inputs [
  {
    name: "image"
    dims:  [ -1, -1, -1, -1 ]   // assuming model handles any value for CHW
  },
  {
    name: "boxes"
    dims:  [ -1, 6 ]
  },
  {
    name: "batch_splits"
    dims:  [ -1 ]
  }
]

By using max_batch_size = 0 you do lose the ability to use the dynamic batcher... but then again it doesn't seem generally possible to teach the dynamic batcher how to split an output like boxes/batch_splits.

**Comment by erickim555** [comment]
I see - thank you for this workaround!

**Comment by erickim555** [comment]
Just an update: I modified the detection model to output boxes with shape=[nb_images, nb_boxes, 6], and TRTIS with dynamic batching works. Thank you!
