### ISSUE TITLE
Can  tensorrtservere-19.03-py3 support cuda-driver-396.26 and cuda9.0?

### ISSUE THREAD

**Issue by ivankxt** [NVIDIA/tensorrt-inference-server#185]
hello, I start the tensorrtserver by the image tensorrtserver:19.02-py3,  we get the error as:

bin/trtserver --http-port=8004 --grpc-port=8005 --model-store=/opt/examples/model_repository/example
I0328 06:28:45.880761 62 server.cc:278] Initializing TensorRT Inference Server
I0328 06:28:45.880861 62 server.cc:328] Reporting prometheus metrics on port 8002
I0328 06:28:45.882730 62 metrics.cc:150] found 1 GPUs supporting NVML metrics
I0328 06:28:45.888630 62 metrics.cc:159]   GPU 0: Tesla M40 24GB
I0328 06:28:45.889497 62 server.cc:644] Starting server 'inference:0' listening on
I0328 06:28:45.889515 62 server.cc:648]  localhost:8005 for gRPC requests
I0328 06:28:45.889625 62 grpc_server.cc:240] Building nvrpc server
I0328 06:28:45.889639 62 grpc_server.cc:246] Register TensorRT GRPCService
I0328 06:28:45.889653 62 grpc_server.cc:249] Register Infer RPC
I0328 06:28:45.889657 62 grpc_server.cc:253] Register StreamInfer RPC
I0328 06:28:45.889661 62 grpc_server.cc:257] Register Status RPC
I0328 06:28:45.889665 62 grpc_server.cc:261] Register Profile RPC
I0328 06:28:45.889669 62 grpc_server.cc:265] Register Health RPC
I0328 06:28:45.889690 62 grpc_server.cc:269] Register Executor
I0328 06:28:45.893477 62 server.cc:658]  localhost:8004 for HTTP requests
E0328 06:28:45.975537 62 server.cc:137] failed to get device count for profiling: CUDA driver version is insufficient for CUDA runtime version
W0328 06:28:47.892602 62 metrics.cc:262] failed to get energy consumption for GPU 0, NVML_ERROR 3

--------------------------------------------
As for our GPU Cluster, the cuda version is 9.0 and Driver Version is 396.26(P40 or M40). We can't change the of version cuda and Driver, but we really want to use this tensorrtservere-19.03-py3 because it support Variable-size input and output tensor. 

So, how the tensorrtserver-19.03-py3 worked in the  cuda  9.0 and Driver 396.26 (P40 or M40)?
Could you give me some advices for that? Thank you.

**Comment by bezero** [comment]
@ivankxt I think you are using tensorrtserver:19.02-py3, but you are referring to 19.03 in multiple places. According to [Driver Requirements](https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-02.html#rel_19-02) for P40 (in your case) you may use NVIDIA driver release 384. 

However, normally release 19.02 is based on CUDA 10, which requires NVIDIA Driver release 410.xx and [release 19.03 is based on CUDA 10.1, which requires NVIDIA Driver release 418.xx+](https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-03.html#rel_19-03)

**Comment by ivankxt** [comment]
> @ivankxt I think you are using tensorrtserver:19.02-py3, but you are referring to 19.03 in multiple places. According to [Driver Requirements](https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-02.html#rel_19-02) for P40 (in your case) you may use NVIDIA driver release 384.
> 
> However, normally release 19.02 is based on CUDA 10, which requires NVIDIA Driver release 410.xx and [release 19.03 is based on CUDA 10.1, which requires NVIDIA Driver release 418.xx+](https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-03.html#rel_19-03)

I using the image as:
docker pull nvcr.io/nvidia/tensorrtserver:19.03-py3

**Comment by deadeyegoodwin** [comment]
It is unfortunate that your cluster is using 396. Certain CUDA driver versions have forward and backwards compatibility that allow them to work with both CUDA 10, 10.1 and future CUDA versions. See the response in https://github.com/NVIDIA/tensorrt-inference-server/issues/139 for some informative links. In short, all the recent releases of the inference server will work with either the 384 or 410 driver, but not with 396.
