### ISSUE TITLE
Image compression

### ISSUE THREAD

**Issue by SlipknotTN** [NVIDIA/tensorrt-inference-server#187]
Is it possible to send compressed images to TRTIS server to save communication time?

**Comment by deadeyegoodwin** [comment]
It is possible to send any "binary blob" to a model by using a variable size input tensor. Of course your model needs to know what to do with it...

But I think you are likely asking if you can have TRTIS run a preprocessing pass on an image and then pass the resulting tensor representation of that image to a model. The answer is "very soon". We are working on ensembling which is a general technique to allow composition of model pipelines. Along with custom backends which allow you to create things like pre-processing passes you can likely do what you want.

A lot of ensembling is already implemented, and there is a pending PR https://github.com/NVIDIA/tensorrt-inference-server/pull/183 that uses a custom backend to perform image preprocessing and then passes the results to a resnet50 model. Take a look and let us know if that is what you are looking for.

**Comment by SlipknotTN** [comment]
Thank you, I mean exactly this kind of pipeline. Client sends compressed image -> Custom backend that decodes input and prepares data for model -> DNN Model.

**Comment by nieksand** [comment]
Some sort of light weight compression that doesn't require mucking with model inputs would be interesting for me too.  (e.g. zstd or lz4).

Right now, for each request, I evaluate 7 models each having (224x224x3) fp32 input.  That comes out to ~4MB per request.  It has not been a critical issue for me yet, but it does add up quickly at even modest request concurrencies.

**Comment by deadeyegoodwin** [comment]
@nieksand Currently we don't have any plans to implement support for compression, but I believe GRPC has some built-in compression, or options for it. Feedback on if/how we can support that would be helpful.

Assuming all 7 models require the same inputs, you could use ensembling to have a single request trigger all 7 models, that should allow you to cut bandwidth by 1/7 th.

**Comment by nieksand** [comment]
Right now the inputs are different, but could be made the same by doing more of the data preparation directly in the TF/TRT graphs.  So ensembling might indeed help.

Thanks for the pointer on gRPC compression support.  I'll see if I can get that working this coming week.

**Comment by deadeyegoodwin** [comment]
Closing. Re-open if you have GRPC compression feedback to share.

**Comment by seovchinnikov** [comment]
I think compression of tensors during communication is the duty of the grpc, not a pre/post processing steps. It's also related to #1 as it will reduce some requirements on communication channels.

But grpc supports only gzip/deflate and as I know they don't plan to add lz4 as an option  https://github.com/grpc/grpc/issues/6313. lz4 ables to process up to 800 MB/s on compression and around 5000 MB/s on decompresion per core so it can operate in real-time.
I've created a fork of grpc and added support  of lz4 and will explore benefits of lz4 for TRTIS in the next days.
