### ISSUE TITLE
i update TRT 5.0 to TRT 5.1 and it show a warning

### ISSUE THREAD

**Issue by jlygit** [NVIDIA/tensorrt-inference-server#200]
hello,
i update TRT 5.0 to TRT 5.1 and it show a warning  as follow:
WARNING: TensorRT was compiled against cuDNN 7.5.0 but is linked against cuDNN 7.0.5. This mismatch may potentially cause undefined behavior.

i run an inference on gpu and it works, but this warning confuse me. How does this warning affect?

**Comment by deadeyegoodwin** [comment]
You didn't give much context of where you updated TRT, but it seems like you just updated it while leaving all the other CUDA libraries as they were. In general that is not a good idea as the warning says.

Specific to TRTIS, you should not change TRT within the TRTIS container. If you want to get the latest version of TRT you should update to the latest version of TRTIS, 19.03.

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if you still have issues when using consistent versions of CUDA and TRT.
