### ISSUE TITLE
Run tensorrtserver failed!

### ISSUE THREAD

**Issue by ivankxt** [NVIDIA/tensorrt-inference-server#202]
Hi, I start the tensorrtserver by the image tensorrtserver:19.03-py3, we get the error as:

bin/trtserver --http-port=8004 --grpc-port=8005 --model-store=/opt/model/model_repository/
I0404 03:45:10.685058 9037 server.cc:278] Initializing TensorRT Inference Server
I0404 03:45:10.685127 9037 server.cc:328] Reporting prometheus metrics on port 8002
I0404 03:45:10.686990 9037 metrics.cc:150] found 1 GPUs supporting NVML metrics
I0404 03:45:10.692580 9037 metrics.cc:159]   GPU 0: Tesla P4
I0404 03:45:10.693092 9037 server.cc:644] Starting server 'inference:0' listening on
I0404 03:45:10.693119 9037 server.cc:648]  localhost:8005 for gRPC requests
I0404 03:45:10.693233 9037 grpc_server.cc:240] Building nvrpc server
I0404 03:45:10.693252 9037 grpc_server.cc:246] Register TensorRT GRPCService
I0404 03:45:10.693266 9037 grpc_server.cc:249] Register Infer RPC
I0404 03:45:10.693270 9037 grpc_server.cc:253] Register StreamInfer RPC
I0404 03:45:10.693274 9037 grpc_server.cc:257] Register Status RPC
I0404 03:45:10.693278 9037 grpc_server.cc:261] Register Profile RPC
I0404 03:45:10.693282 9037 grpc_server.cc:265] Register Health RPC
I0404 03:45:10.693286 9037 grpc_server.cc:269] Register Executor
I0404 03:45:10.696419 9037 server.cc:658]  localhost:8004 for HTTP requests
E0404 03:45:10.778573 9037 server.cc:137] failed to get device count for profiling: CUDA driver version is insufficient for CUDA runtime version

The cuda version is 10.1, cudnn version is 7.5.0 and Driver Version is 384.66(GPU P4). 
nvidia-smi
Thu Apr  4 11:45:00 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.66                 Driver Version: 384.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+===
|   0  Tesla P4            Off  | 00000000:06:00.0 Off |                    0 |
| N/A   32C    P8     6W /  75W |      0MiB /  7606MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

Could you give me some advices for that? Thank you.

**Comment by bezero** [comment]
The error message is clear, it tells you that your driver version is insufficient. Upgrading your driver should help. You can find more detailed explanation in the [documentation](https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-03.html#rel_19-03). It says, if you are running on Tesla (Tesla V100, Tesla P4, Tesla P40, or Tesla P100), you may use NVIDIA driver release 384.111+ or 410. However, you are using v384.66.

**Comment by ivankxt** [comment]
> The error message is clear, it tells you that your driver version is insufficient. Upgrading your driver should help. You can find more detailed explanation in the [documentation](https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-03.html#rel_19-03). It says, if you are running on Tesla (Tesla V100, Tesla P4, Tesla P40, or Tesla P100), you may use NVIDIA driver release 384.111+ or 410. However, you are using v384.66.


I change the image of tensorrtserver(tensorrtserver:19.02-py3), and cuda version is 10.0.130, cudnn version is 7.4.2 and Driver Version is 384.81 (GPU P40), but we also get the same error as:

I0404 09:22:24.700056 78 server.cc:1209]  localhost:8004 for HTTP requests
[evhttp_server.cc : 237] RAW: Entering the event loop ...
E0404 09:22:24.700896 78 server.cc:620] failed to get device count for profiling: CUDA driver version is insufficient for CUDA runtime version

# nvidia-smi 
Thu Apr  4 10:02:02 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+===
|   0  Tesla P40           On   | 00000000:04:00.0 Off |                  Off |
| N/A   21C    P8     9W / 250W |      0MiB / 24445MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

Could you give me some advices for that? Thank you.

**Comment by bezero** [comment]
@ivankxt upgrade your Driver Version to 384.111 or higher. You are using 384.81 which is older version than what is required.

**Comment by deadeyegoodwin** [comment]
@ivankxt  Please try an updated driver as suggested. Closing, reopen if you still have problems after updating.
