### ISSUE TITLE
Specifying Optimization Policy while using TensorRT Inference Server

### ISSUE THREAD

**Issue by jashshah** [NVIDIA/tensorrt-inference-server#214]
I have managed to successfully serve a Tensorflow Object Detection API model using TensorRT Inference Server and the config file (`config.pbtxt`) is as follows:

    name: "first_model"
    platform: "tensorflow_savedmodel"
    max_batch_size: 1
    input [
      {
        name: "inputs"
        data_type: TYPE_UINT8
        dims: [ -1, -1, 3 ]
      }
    ]
    output [
      {
        name: "detection_boxes"
        data_type: TYPE_FP32
        dims: [ 100, 4 ]
      },
      {
        name: "detection_scores"
        data_type: TYPE_FP32
        dims: [ 100 ]
      },
      {
        name: "detection_classes"
        data_type: TYPE_FP32
        dims: [ 100 ]
      }
    ]

I was going through the [documentation][1] and it turns out there is a way to specify [optimization settings][2] for the model in the `config.pbtxt` as well. However the documentation fails to mention how can one specify these optimization settings. I tried adding the below lines to the config file

    optimization_policy [
      {
        level:1
      }
    ]

and tried serving the model but instead got an error: `Can't parse /models/first_model/config.pbtxt as text proto`. However if I remove the lines relating to the `optimization_policy` I do not face any issues while serving.

How can I specify the optimization policy/setting in the config file? 

  [1]: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_configuration.html
  [2]: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_configuration.html#optimization-policy

**Comment by deadeyegoodwin** [comment]
You need to format your config.pbtxt using protobuf text format following the schema here: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/model_config.proto#L358

I believe what you want is:
```
optimization {  graph { level: 1 } } 
```
