### ISSUE TITLE
Object Detection Tensorflow example request

### ISSUE THREAD

**Issue by achbogga** [NVIDIA/tensorrt-inference-server#217]
Hello NVIDIA, thanks for the awesome server and making it open source. I did not find an example of tensorflow object detection in the official examples. I would really like to use the inference server for my object detection models which are predominantly in tensorflow. Please give an example/tutorial for this purpose. Thanks a million.

**Comment by bezero** [comment]
Assuming you have project called detection_prj, you should arrange your projects folder as follows:
```
models/
  detection_prj/
    config.pbtxt
    1/
      model.graphdef
```
Here I am assuming that you are using frozen tf model. And finally, you have to create your config file similar to:
```
name: "detection_prj"
platform: "tensorflow_graphdef"
max_batch_size: 5
input [
  {
    name: "image_tensor"
    data_type: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [ -1, -1, 3 ]
  }
]
output [
  {
    name: "detection_boxes"
    data_type: TYPE_FP32
    dims: [ 100, 4  ]
  },
  {
    name: "detection_scores"
    data_type: TYPE_FP32
    dims: [ 100 ]        
  },
  {
    name: "detection_classes"
    data_type: TYPE_FP32
    dims: [ 100 ]        
  }
]
```
Here I am allowing input image to have dynamic width and height. Now, you are ready to deploy your detection models on TRTIS. You can also let TRTIS to generate config file for you. For it to happen, you don't provide config file in you model repository and when running TRTIS you should set ```--strict-model-config=false```. This will allow TRTIS to try to generate missing parts of the config.pbtxt.

For your client side:
```py
# Request for the model status
ctx = ServerStatusContext(url, protocol, model_name)
server_status = ctx.get_server_status()

# Get config file
status = server_status.model_status[model_name]
config = status.config

# Get input and output names
input_name = config.input[0]
outputs = [output.name for output in config.output]

max_batch_size = config.max_batch_size

# Prepare you images
input_list = []
for b in range(batch_size):
  test = np.zeros((height, width, channels), dtype=np.uint8)
  input_list.append(test)

# Run inference
ctx = InferContext(url, protocol, model_name)
results = ctx.run(
    {input_name: input_list},
    {output: InferContext.ResultFormat.RAW for output in output_names},
    batch_size)

# How to use results
image_index = 0
print('detection_boxes: ', results['detection_boxes'][image_index].shape)         # (100, 4)
print('detection_scores: ', results['detection_scores'][image_index].shape)       # (100,)
print('detection_classes: ', results['detection_classes'][image_index].shape)     # (100,)
```

**Comment by achbogga** [comment]
@bezero I appreciate your effort, thanks a lot. But, I would really like an official working model from NVIDIA in the clients library. I am trying as suggested by you and will update if I can get it to work.

**Comment by deadeyegoodwin** [comment]
In general, the TRTIS project isn't set up to provide official models or clients. We provide some simple examples to show API use. We do provide a more-complete client example for image classification but we don't claim that it is a complete full-featured application for all image classification uses, it is just intended to illustrate the client APIs and act as an example of how the APIs can be used in your application.

If you think there is some aspect or feature of TRTIS that is not sufficiently illustrated by the existing documentation or examples then we would love to hear that feedback. We would then consider improving or creating an example, but as with the existing examples it would be designed to educate.

There is a growing model repository here: https://ngc.nvidia.com/catalog/models. Currently it is only TensorRT models and integration with TRTIS could be better (we have plans for that in the future). For TF models you can look at google's AIHub (https://aihub.cloud.google.com/) and other places on the web to try to find a trained model.

**Comment by achbogga** [comment]
@deadeyegoodwin @bezero I have tried our unit detection frozen model without any config file (but with `--strict-model-config=false`) and tried to run the performance client. I got this error from the server side:
` Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node Preprocessor/map/while/ResizeToRange/strided_slice_3. Error: Pack node (Preprocessor/map/while/ResizeToRange/stack_2) axis attribute is out of bounds: 0`

These messages are from the client side:
` ./perf_client -m unitmodel_graphdef -p23000 -t4 -v -uxx.xx.xx.xxx:8000
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 23000 msec

Request concurrency: 4
Failed to update context stat: [ 0] INVALID_ARG - Timer not set correctly.
Failed to update context stat: [ 0] INVALID_ARG - Timer not set correctly.
Failed to update context stat: [ 0] INVALID_ARG - Timer not set correctly.
[ 0] INTERNAL - No valid requests recorded within time interval. Please use a larger time window.
Thread [0] had error: [inference:0 10] INVALID_ARG - Must specify at least one target to fetch or execute.
Thread [1] had error: [inference:0 8] INVALID_ARG - Must specify at least one target to fetch or execute.
Thread [3] had error: [inference:0 9] INVALID_ARG - Must specify at least one target to fetch or execute.`

This is a fine-tuned fasterRCNN (Resnet101) version of the official models repo from tensorflow. Please help. Also @deadeyegoodwin, I am requesting an official object detection model API tutorial demonstration and not the model itself. Thanks a lot for such quick responses.

**Comment by deadeyegoodwin** [comment]
What version of TRTIS and perf_client are you using? 
The problem seems to be that the perf_client did not get any response back from the server. Are you sure the server is running an reachable from perf_client. You can just check the status API to make sure the server is running and the model is available.

**Comment by achbogga** [comment]
`curl xxx.xxx.xxx.xxx:8000/api/status/unitmodel_graphdef
id: "inference:0"
version: "1.0.0"
uptime_ns: 283505894342
model_status {
  key: "unitmodel_graphdef"
  value {
    config {
      name: "unitmodel_graphdef"
      platform: "tensorflow_graphdef"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      instance_group {
        name: "unitmodel_graphdef"
        count: 1
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "model.graphdef"
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
        infer_stats {
          key: 1
          value {
            failed {
              count: 1
              total_time_ns: 10842923778
            }
          }
        }
      }
    }
  }
}
ready_state: SERVER_READY`
Above is the api status call. Also I have increased the measurement window time and the perf client still fails to get a response. On the server side the messages indicate that it had failed to run optimizer called ArithmaticOptimizer. I am pasting the serverside messages below as well.
`New status tracking for model 'unitmodel_graphdef'
I0415 16:21:51.301286 1 server_core.cc:465] Adding/updating models.
I0415 16:21:51.301318 1 server_core.cc:562]  (Re-)adding model: unitmodel_graphdef
I0415 16:21:51.401852 1 basic_manager.cc:739] Successfully reserved resources to load servable {name: unitmodel_graphdef version: 1}
I0415 16:21:51.401908 1 loader_harness.cc:66] Approving load for servable version {name: unitmodel_graphdef version: 1}
I0415 16:21:51.401919 1 loader_harness.cc:74] Loading servable version {name: unitmodel_graphdef version: 1}
I0415 16:21:51.402662 1 base_bundle.cc:163] Creating instance unitmodel_graphdef_0_gpu0 on GPU 0 (7.0) using model.graphdef
I0415 16:21:51.521617 1 cuda_gpu_executor.cc:998] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I0415 16:21:51.522127 1 gpu_device.cc:1433] Found device 0 with properties:
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:00:04.0
totalMemory: 15.75GiB freeMemory: 15.44GiB
I0415 16:21:51.522150 1 gpu_device.cc:1512] Adding visible gpu devices: 0
I0415 16:21:58.632492 1 gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
I0415 16:21:58.632549 1 gpu_device.cc:990]      0
I0415 16:21:58.632556 1 gpu_device.cc:1003] 0:   N
I0415 16:21:58.635265 1 gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14535 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:04.0, compute capability: 7.0)
I0415 16:21:58.662480 1 service.cc:161] XLA service 0x7f02a8e4d750 executing computations on platform CUDA. Devices:
I0415 16:21:58.662523 1 service.cc:168]   StreamExecutor device (0): Tesla V100-SXM2-16GB, Compute Capability 7.0
I0415 16:21:58.686372 1 cpu_utils.cc:94] CPU Frequency: 2000120000 Hz
I0415 16:21:58.687025 1 service.cc:161] XLA service 0x7f02a8eb3c20 executing computations on platform Host. Devices:
I0415 16:21:58.687062 1 service.cc:168]   StreamExecutor device (0): <undefined>, <undefined>
I0415 16:22:00.088358 1 loader_harness.cc:86] Successfully loaded servable version {name: unitmodel_graphdef version: 1}
W0415 16:23:01.518022 1 graph_optimizer_stage.h:241] Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node Preprocessor/map/while/ResizeToRange/strided_slice_3. Error: Pack node (Preprocessor/map/while/ResizeToRange/stack_2) axis attribute is out of bounds: 0
W0415 16:23:06.330903 1 graph_optimizer_stage.h:241] Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node Preprocessor/map/while/ResizeToRange/strided_slice_3. Error: Pack node (Preprocessor/map/while/ResizeToRange/stack_2) axis attribute is out of bounds: 0`

**Comment by deadeyegoodwin** [comment]
It looks like the XLA optimizer with TF is failing. Is that the entire console output? Can you include anything additional after the above. Also, can you preserve the newlines when you paste it, otherwise it is difficult to read (insert it as code).

It could be that TRTIS should allow the model to be used even-though the optimizer failed. You could also try disabling the optimizer in your model config, see https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_configuration.html#optimization-policy

**Comment by achbogga** [comment]
@deadeyegoodwin Thanks for the tip on disabling the optimization policy. for general public FYI, I have disabled it as the following config.pbtxt (I have also fixed the input size):
`
name: "unitmodel_graphdef"
platform: "tensorflow_graphdef"
max_batch_size: 32
input [
  {
    name: "image_tensor"
    data_type: TYPE_UINT8
    format: FORMAT_NHWC
    dims: [ 800, 800, 3 ]
  }
]
output [
  {
    name: "detection_boxes"
    data_type: TYPE_FP32
    dims: [ -1, 4  ]
  },
  {
    name: "detection_scores"
    data_type: TYPE_FP32
    dims: [ -1 ]        
  },
  {
    name: "detection_classes"
    data_type: TYPE_FP32
    dims: [ 2 ]        
  }
]
instance_group [
  {
    kind: KIND_GPU,
    count: 1
  }
]
optimization {
	graph {
		level: -1
	}
}
`
 - I have got an error when I tried to specify arbitrary input width and height (-1, -1, 3). But I fixed them 800 for now which fixed this error. @deadeyegoodwin please let me know how to do **dynamic input size spec** in TRTIS.
 - Although, I have seen some error messages like the following from the server side, I have been able to get response from the performance client finally. Thanks a lot @deadeyegoodwin @bezero for your help.  Server side stdout below:
`
W0415 21:37:05.718628 1 graph_optimizer_stage.h:241] Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node Preprocessor/map/while/ResizeToRange/strided_slice_3. Error: Pack node (Preprocessor/map/while/ResizeToRange/stack_2) axis attribute is out of bounds: 0
W0415 21:37:09.869375 1 graph_optimizer_stage.h:241] Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node Preprocessor/map/while/ResizeToRange/strided_slice_3. Error: Pack node (Preprocessor/map/while/ResizeToRange/stack_2) axis attribute is out of bounds: 0
I0415 21:37:10.648957 1 dso_loader.cc:153] successfully opened CUDA library libcublas.so.10 locally
`

**Comment by deadeyegoodwin** [comment]
What error did you get? Also, did you try using --strict-model-config=false to see what configuration TRTIS generated for you? It is possible that your model doesn't allow variable-size dimensions for that input tensor.

**Comment by achbogga** [comment]
- root@d2128e1ebdb6:/opt/tensorrtserver/bin# ./perf_client -m unitmodel_graphdef -p50000 -t32 -v -b16 -uxx.xxx.xxx.xxx:8000
- *** Measurement Settings ***
-   Batch size: 16
-   Measurement window: 50000 msec
- 
- Request concurrency: 32
- [ 0] INTERNAL - No valid requests recorded within time interval. Please use a larger time window.
- Thread [0] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [1] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [2] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [3] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [4] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [5] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [6] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [7] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [8] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [9] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [10] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [11] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [12] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [13] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [14] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'
- Thread [15] had error: [ 0] INVALID_ARG - input 'image_tensor' has variable-size shape, unable to create input values for model 'unitmodel_graphdef'

These are the errors from the client side. I guess the performance client cannot send requests with dynamic input size? But the TRTIS can support the model with dynamic input size?

**Comment by deadeyegoodwin** [comment]
The server is not having any problem with your variable-sized tensors, they are fully supported. The problem is that perf_client doesn't know what to do when it encounters a variable-size dimension. It needs to send some data for that input but it doesn't know what size to use. So, as you have discovered, to use perf_client you need to change your model configuration to have the exact size that you want to use for performance testing.

**Comment by achbogga** [comment]
Got it, thanks, man.

**Comment by learn901** [comment]
@achbogga  Can you please let me know how you resolved Variable-size dimension. It'll be helpful .
Please let us know exact command to pass user data with perf_client and how to set the folder structure.

Thanks in Advance.

**Comment by kisow** [comment]
@bezero, @deadeyegoodwin

I had read that blog and have used TRTIS for image classification model 
and for feature inference of retrieval model. thank you so much!
https://devblogs.nvidia.com/nvidia-serves-deep-learning-inference/
> Trtserver works with models of all kinds: image classification, object detection, MLP, language processing, and more

But, I have a problem with object detection model, trying yolov3 on TRTIS.
How can I use `label_filename` for object detection model to predict label in TRTIS server side, 
just as for classification model? Is it possible? 

Thanks in Advance.

**Comment by achbogga** [comment]
@learn901 I did not use variable size dimension with performance client. I just fixed an avg image size for perf testing. However, TRTIS can serve variable input dims in production. The perf client cannot do so as it needs some input image size to send data to the TRTIS. Hope this helps.

**Comment by mbufi** [comment]
Hello @achbogga ! 

Thank you for this discussion. Is has helped me understand how to serve my Tensorflow obj model. 

Quick questions and clarification I am curious about from you: 
1) The model you saved was a Frozen.pb model created by export.py correct? Any specific settings you used for that?
2) You used fasterrcnn w/ res101 --> could you let me know the tensorflow config you used to train it? I am curious if different configs when exporting it will cause issues in serving using TRTIS. 
3) Have you tried doing living streaming of images to TRTIS? How was the performance? 

Thanks! :smile:

**Comment by mhs-achyut** [comment]
@bezero Can you please provide an example for C++ client which can be used for object detection?
@deadeyegoodwin If anyone from the official authors can extend this functionality for the existing image_client.cc in the src, that would be great as well.

**Comment by turowicz** [comment]
@bezero when running your example script for the same scenario I get the following error on 20.03-py3-clientsdk

```
Traceback (most recent call last):
  File "myfile.py", line 47, in <module>
    {input_name: input_list},
TypeError: unhashable type: 'ModelInput'
```

**Comment by bezero** [comment]
@turowicz can you provide your `config.pbtxt` file and if possible your `myfile.py`?

**Comment by turowicz** [comment]
Hey @bezero I've found the problem.

Solution below:

```
{input_name.name: input_list}
```

**Comment by turowicz** [comment]
I'm working with a different model, so it has different inputs. (Faster R-CNN Inception V2)

**Comment by 4nonymou5** [comment]
@bezero 
Possible give a sample config and python file for object detection tensorflow model?
Like, config file with saved model and grpc python API. I tried, but it crashes giving out some or other error
