### ISSUE TITLE
Client Examples for Several Applications

### ISSUE THREAD

**Issue by vilmara** [NVIDIA/tensorrt-inference-server#220]
hi all, could you please provide client examples for the following applications?:
- Language Modeling
- Sentiment Analysis
- Object Detection
- Speech Recognition
- Language Translation

Thanks

**Comment by deadeyegoodwin** [comment]
We will likely have some additional examples of clients that use TRTIS but doing an exhaustive implementation of all these is beyond the scope of the TRTIS project. Please share any you have and we can help curate links to them.
