### ISSUE TITLE
ready_state: MODEL_UNAVAILABLE: TensorFlow SavedModel configuration

### ISSUE THREAD

**Issue by vilmara** [NVIDIA/tensorrt-inference-server#223]
Hi all, I have a TensorFlow model saved with `estimator.export_savedmodel` (using SavedModel with Estimators) but TRTIS is throwing errors when loading the model. Does it matter the method used to save the model?

**Comment by deadeyegoodwin** [comment]
The model does need to be saved for inferencing. See https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_repository.html#tensorflow-models.

I'm not familiar with the Estimator export so I don't know if you need to do something specific there. Please share what you learn and we can update the docs.

We could provide more help if you share the console errors. Since it is saved-model the usual first step is to use the latest version of TRTIS and try running without a config.pbtxt and use the --strict-model-config=false flag to see if TRTIS can generate a valid config for you.

**Comment by vilmara** [comment]
Hi @deadeyegoodwin, it is the official TensorFlow model ResNet-50 v1 FP32 SavedModel (NCHW) (https://github.com/tensorflow/models/tree/master/official/resnet), I have used it to run inferences using only TensorRT, and now I want to run its inference with TRTIS version 19.03, I have followed your instructions running the server with the flag  --strict-model-config=false and it loaded the model but I don't see where it generated the config file.

On another hand, below is the log trace when I ran the server creating manually the config file (and flag --strict-model-config=true)

Log trace
```
I0411 19:05:57.886979 1 server_status.cc:131] Updating config for model '2_resnet50v1_gpu_NCHW_fp32_savedmodel'
I0411 19:05:57.887036 1 server_core.cc:465] Adding/updating models.
I0411 19:05:57.887051 1 server_core.cc:562]  (Re-)adding model: 1_resnet50v1_cpu_NHWC_fp32_graphdef
I0411 19:05:57.887062 1 server_core.cc:562]  (Re-)adding model: 1_resnet50v1_cpu_NHWC_fp32_savedmodel
I0411 19:05:57.887074 1 server_core.cc:562]  (Re-)adding model: 3_resnet50v1_tftrt_fp32_128_graphdef
I0411 19:05:57.887085 1 server_core.cc:562]  (Re-)adding model: 4_resnet50v1_tftrt_int8_128_graphdef
I0411 19:05:57.887097 1 server_core.cc:562]  (Re-)adding model: 2_resnet50v1_gpu_NCHW_fp32_savedmodel
I0411 19:06:12.319645 1 basic_manager.cc:739] Successfully reserved resources to load servable {name: 2_resnet50v1_gpu_NCHW_fp32_savedmodel versio
I0411 19:06:12.319685 1 loader_harness.cc:66] Approving load for servable version {name: 2_resnet50v1_gpu_NCHW_fp32_savedmodel version: 1}
I0411 19:06:12.319705 1 loader_harness.cc:74] Loading servable version {name: 2_resnet50v1_gpu_NCHW_fp32_savedmodel version: 1}
I0411 19:06:12.321337 1 base_bundle.cc:163] Creating instance 2_resnet50v1_gpu_NCHW_fp32_savedmodel_0_0_gpu0 on GPU 0 (7.5) using model.savedmodel
I0411 19:06:12.321384 1 reader.cc:31] Reading SavedModel from: /models/2_resnet50v1_gpu_NCHW_fp32_savedmodel/1/model.savedmodel
I0411 19:06:12.331474 1 reader.cc:54] Reading meta graph with tags { serve }
I0411 19:06:12.342187 1 gpu_device.cc:1512] Adding visible gpu devices: 0, 1, 2, 3, 4, 5
I0411 19:06:12.343019 1 gpu_device.cc:984] Device interconnect StreamExecutor with strength 1 edge matrix:
I0411 19:06:12.343062 1 gpu_device.cc:990]      0 1 2 3 4 5
I0411 19:06:12.343076 1 gpu_device.cc:1003] 0:   N Y Y Y N N
I0411 19:06:12.343089 1 gpu_device.cc:1003] 1:   Y N Y Y N N
I0411 19:06:12.343100 1 gpu_device.cc:1003] 2:   Y Y N Y N N
I0411 19:06:12.343111 1 gpu_device.cc:1003] 3:   Y Y Y N N N
I0411 19:06:12.343122 1 gpu_device.cc:1003] 4:   N N N N N Y
I0411 19:06:12.343133 1 gpu_device.cc:1003] 5:   N N N N Y N
I0411 19:06:12.357116 1 gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14774 MB memory) -> physila T4, pci bus id: 0000:86:00.0, compute capability: 7.5)
I0411 19:06:12.357801 1 gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 14774 MB memory) -> physila T4, pci bus id: 0000:87:00.0, compute capability: 7.5)
I0411 19:06:12.358467 1 gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:2 with 14774 MB memory) -> physila T4, pci bus id: 0000:af:00.0, compute capability: 7.5)
I0411 19:06:12.358975 1 gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:3 with 14774 MB memory) -> physila T4, pci bus id: 0000:d8:00.0, compute capability: 7.5)
I0411 19:06:12.359618 1 gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:4 with 6802 MB memory) -> physica P4, pci bus id: 0000:3b:00.0, compute capability: 6.1)
I0411 19:06:12.362244 1 gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:5 with 6802 MB memory) -> physica P4, pci bus id: 0000:5e:00.0, compute capability: 6.1)
I0411 19:06:12.423243 1 loader.cc:183] Restoring SavedModel bundle.
I0411 19:06:12.915152 1 loader.cc:133] Running initialization op on SavedModel bundle.
I0411 19:06:12.979037 1 loader.cc:298] SavedModel load for tags { serve }; Status: success. Took 657644 microseconds.
E0411 19:06:13.018854 1 retrier.cc:37] Loading servable: {name: 2_resnet50v1_gpu_NCHW_fp32_savedmodel version: 1} failed: Invalid argument: unexpeensor', allowed inputs are: input
I0411 19:06:13.018940 1 loader_harness.cc:154] Encountered an error for servable version {name: 2_resnet50v1_gpu_NCHW_fp32_savedmodel version: 1}: inference input 'input_tensor', allowed inputs are: input
E0411 19:06:13.018961 1 aspired_versions_manager.cc:358] Servable {name: 2_resnet50v1_gpu_NCHW_fp32_savedmodel version: 1} cannot be loaded: Invalence input 'input_tensor', allowed inputs are: input
```

**Comment by deadeyegoodwin** [comment]
In the console output the lines starting the E are the errors (the 0411 is the date, month/day). It looks like the line is slightly garbled, not sure why that is, but it is saying that "allowed inputs are: input", which means that in the config file there should be one input named "input". In your config file (which you did not provide) it looks like you named that input "input_tensor".

When using --strict-model-config=false you can see the config by using the status API:

$ curl localhost:8000/api/status/<model-name>

Part of the status is the model configuration being used for the model. If you want to put it in a config.pbtxt you can copy it from the status.

**Comment by vilmara** [comment]
@deadeyegoodwin the strange part is that when I named it as "input", the system threw the opposite message: `Invalence input 'input', allowed inputs are: input_tensor`. Anyway, I solved the problem just using the flag `--strict-model-config=false`

**Comment by deadeyegoodwin** [comment]
OK, closing. But it is probably interesting to look at the generated model configuration to see what the correct configuration actually is and why what you did was getting reject in a confusing way. It may be that we can improve some of the error messages.

**Comment by vilmara** [comment]
@deadeyegoodwin, the config showed by the status API doesn't expose the input and output tensors configuration detected by the system. See below:

```
model_status {
  key: "2_resnet50v1_gpu_NCHW_fp32_savedmodel"
  value {
    config {
      name: "2_resnet50v1_gpu_NCHW_fp32_savedmodel"
      platform: "tensorflow_savedmodel"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      input {
        name: "input"
        data_type: TYPE_FP32
        dims: 64
        dims: 224
        dims: 224
        dims: 3
      }
      output {
        name: "probabilities"
        data_type: TYPE_FP32
        dims: 64
        dims: 1001
      }
      output {
        name: "classes"
        data_type: TYPE_INT64
        dims: 64
      }
      instance_group {
        name: "2_resnet50v1_gpu_NCHW_fp32_savedmodel"
        count: 1
        gpus: 0
        gpus: 1
        gpus: 2
        gpus: 3
        gpus: 4
        gpus: 5
        kind: KIND_GPU
      }
      default_model_filename: "model.savedmodel"
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
      }
    }
  }
}
```

**Comment by deadeyegoodwin** [comment]
The model configuration is shown, it is the content of "config { ... }". So you could cut the following from the status output and copy it into config.pbtxt. This would allow you to modify parts of the configuration such as version_policy or instance_group if you wanted something other than the defaults.

```
      name: "2_resnet50v1_gpu_NCHW_fp32_savedmodel"
      platform: "tensorflow_savedmodel"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      input {
        name: "input"
        data_type: TYPE_FP32
        dims: 64
        dims: 224
        dims: 224
        dims: 3
      }
      output {
        name: "probabilities"
        data_type: TYPE_FP32
        dims: 64
        dims: 1001
      }
      output {
        name: "classes"
        data_type: TYPE_INT64
        dims: 64
      }
      instance_group {
        name: "2_resnet50v1_gpu_NCHW_fp32_savedmodel"
        count: 1
        gpus: 0
        gpus: 1
        gpus: 2
        gpus: 3
        gpus: 4
        gpus: 5
        kind: KIND_GPU
      }
      default_model_filename: "model.savedmodel"
```

You can compare this config with what you were trying to use when you got errors to see what the difference is.

**Comment by vilmara** [comment]
@deadeyegoodwin it looks like the system is throwing erratic errors, I ran the server again with the manual config I created (without the flag --strict-model-config=false ) to compare the config and I got a new error: 

`E0412 18:48:18.273960 1 server.cc:1062] Failed to reload modified model configurations: 1 model(s) did not become available: {{{name: 2_resnet50v1_gpu_NCHW_fp32_savedmodel version: 1} due to error: Invalid argument: unable to load model '2_resnet50v1_gpu_NCHW_fp32_savedmodel', input 'input' dims [64,224,224,3] don't match configuration dims [3,224,224]}, }
`

And here is the config generated by  status API:

```
      name: "2_resnet50v1_gpu_NCHW_fp32_savedmodel"
      platform: "tensorflow_savedmodel"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      input {
        name: "input"
        data_type: TYPE_FP32
        format: FORMAT_NCHW
        dims: 3
        dims: 224
        dims: 224
      }
      output {
        name: "softmax_tensor"
        data_type: TYPE_FP32
        dims: 1001
        label_filename: "labels.txt"
      }
      instance_group {
        name: "2_resnet50v1_gpu_NCHW_fp32_savedmodel_0"
        count: 1
        gpus: 0
        gpus: 1
        gpus: 2
        gpus: 3
        gpus: 4
        gpus: 5
        kind: KIND_GPU
      }
      default_model_filename: "model.savedmodel"
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_UNAVAILABLE


```

**Comment by vilmara** [comment]
Hi @deadeyegoodwin , have you tried to run inferences with TRTIS and some of the pre-trained official TF ResNet-50 models? (https://github.com/tensorflow/models/tree/master/official/resnet), I have tried but getting a bunch of erratic errors
