### ISSUE TITLE
Does TRTIS support MXNet and Pytorch models?

### ISSUE THREAD

**Issue by vilmara** [NVIDIA/tensorrt-inference-server#228]
Does TRTIS support MXNet and Pytorch models?. If so, what are their platform names to be configured in the config.pbtxt file?

**Comment by deadeyegoodwin** [comment]
Currently support backends are documented here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_repository.html#model-repository

We are planning to support PyTorch (via libtorch library) in the near future. We currently don't have any plans for MXNet.
