### ISSUE TITLE
Support dynamic Model Outputs

### ISSUE THREAD

**Issue by erickim555** [NVIDIA/tensorrt-inference-server#237]
In our usecase, it's useful to be able to request intermediate feature maps (ie Blobs) from a deep learning network.
For instance, for an image classification network, we'd like to extract both the classification output (class probabilities, ie output of Softmax operator) as well as the intermediate FC6 vector (image embedding). 
However, some customers don't always need the FC6 output, and just need the classification output. 

To generalize, for a single InferRequest to TRTIS, we need to be able to request arbitrary Blobs from the network.

If I'm understanding the codebase correctly, this kind of flexibility is not currently supported. The ModelConfig (eg the config.pbtxt files in the model_repository/) must explicitly define the set of allowable Outputs (eg Blob names), and each InferRequest will always copy the Blob data for each Output to the Payload(s). In other words, the set of allowable Outputs is statically defined by a config file.

A hacky way to support the "arbitrary Blobs" usecase is to list every network Blob in the ModelConfig's output array (config.pbtxt), and each InferRequest will request for *all* intermediate Blobs, and the client will pick just the Blobs that it actually needs. This incurs large overhead due to copying unnecessary data + RPC transfer overhead.

Feature Request: Allow InferRequests to dynamically specify Outputs to TRTIS.
During runtime, this may result in Exceptions where the user asks for an Output blob that doesn't actually exist.

Thanks!

**Comment by GuanLuo** [comment]
As you said, for now you will have to list all the outputs that you want the inference server to expose in the config.pbtxt file. However, you should be able to request only a subset of those outputs in your inference request.

So in your example, you can define FC6 output and classification output in your config.pbtxt file. And depending on the customers' need, they just need to specify the outputs they want to receive in `InferRequestHeader`.

**Comment by deadeyegoodwin** [comment]
Following up on @GuanLuo 's comment. TRTIS already works in the manner you want. Just list all the possibly available outputs in your config.pbtxt. Each client request can decide which of those outputs they want. TRTIS will only compute and return the requested outputs so there is no copying of unnecessary data.
