### ISSUE TITLE
Tool to convert an uff file to a plan file

### ISSUE THREAD

**Issue by vilmara** [NVIDIA/tensorrt-inference-server#238]
hi, is there a tool to convert an uff file to plan file, so it can be loaded into the TRTIS model repository?

I have run this C++ sample to generate it but wanted to know if there is a tool:  `./trtexec --uff=/workspace/tensorrt/data/resnet50/resnet50-infer-5.uff --output=GPU_0/tower_0/Softmax --uffInput=input,3,224,224 --iterations=40 --int8 --batch=128 --device=0 --avgRuns=100 --saveEngine=resnet50-infer-5_plan`

**Comment by GuanLuo** [comment]
We don't provide the tool to convert an uff file to plan file. But since TensorRT has its own [UFF parser](https://docs.nvidia.com/deeplearning/sdk/tensorrt-api/python_api/parsers/Uff/pyUff.html), you should be able to parse the file, build the engine and serialize it to plan file.

**Comment by bezero** [comment]
Here is a simple code snippet that might be helpful:
```py
import uff
import tensorrt.legacy as trt
from tensorrt.legacy.parsers import uffparser

output_layers = ['predictions']
uff_model = uff.from_tensorflow_frozen_model(frozen_file=frozen_model, output_nodes=output_layers, output_filename='trt.uff', text=False)
# Here you can load your uff_model if you already have created it

# Create a UFF parser and identify the desired input and output nodes
parser = uffparser.create_uff_parser()
parser.register_input('input', (input_c, input_w, input_h), 0)
parser.register_output('predictions')

# Now, we pass the logger, parser, uff model stream and some settings
# (max batch size and max workspace size) to a utility function that
# will build the engine for us.
# - **datatype** ``tensorrt.infer.DataType``: Operating data type of the engine, can be FP32, FP16 if supported on the platform, or INT8
engine = trt.utils.uff_to_trt_engine(G_LOGGER, uff_model, parser, max_batchsize, MAX_WORKSPACE)

# We can now get rid of the parser
parser.destroy()
# Save our engine to a file
trt.utils.write_engine_to_file(frozen_model.replace('graphdef', 'plan'), engine.serialize())
```
