### ISSUE TITLE
Custom backend and label file

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/tensorrt-inference-server#260]
Hi, thanks for the great work with custom backends and ensembling. From the documentation it is not clear to me, what’s the most elegant way to use a label file in a custom backend. Does the custom model api provide a mechanism which automatically reads a label file, if one is defined, and provides a vector or map of labels? 
Or do I get the label file path from the model config myself, read it manually and use the result in the backend?

**Comment by deadeyegoodwin** [comment]
There is nothing in the custom API that gives easier access to a labels file. If you need the labels in your custom code you will need to read the label file yourself. However, if you just want to have labels associated with a model that uses a custom backend you can just put the labels file in the model repository as you would with any other model type. Your custom model would then return the raw output vector and TRTIS would do the label lookup for you.

Note that if you are going to open the label file yourself you can get the path to the repo from the custom params as demonstrated in this example: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/custom/param/param.cc

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if you still have an issue.
