### ISSUE TITLE
Config.pbtxt and max_batch_size setting for SavedModel

### ISSUE THREAD

**Issue by Immexxx** [NVIDIA/tensorrt-inference-server#264]
I have a TRTIS serving running with fairly simple config and letting TRTIS figure out the input and output shapes with "--strict-model-config=false". 

The config.pbtxt file itself has ```max_batch_size:-1```

For any other value greater than 0, I get ```unable to autofill for 'model_name', configuration specified max-batch 100 but model signature does not support batching```

If max_batch_size is missing or if the value is set to 0, I get ```model output cannot have empty reshape for non-batching model```

Q1. But the actual question is the following: By setting max_batch_size to -1, I am able to send a client request and get the correct response - but only for some outputs.  

For an output with dim: 
```
data_type: TYPE_INT32
        dims: 1
        reshape {
        }
``` 
- I get the correct response. 

But for the other outputs with dim (for example): 
```
output {
        name: "classes"
        data_type: TYPE_FP32
        dims: -1
        dims: 1
      }
```
when I make the request, I get the following error: 
```
[inference:0 5] output 'classes' for model 'model_name' has shape [1] but model configuration specifies shape [-1,1]
```

Is there anything else that I can do to get this to work? If I change the shape, the model does not load and if I don't, the inference request does not work. 

Any suggestions or help would be great.

**Comment by deadeyegoodwin** [comment]
max_batch_size isn't allowed to have a value of -1. If TRTIS didn't flag an error on that then that is a mistake.
I'm not sure if you got autofill to work or if you just manually created the configuration. Also, you didn't mention what type of model you were using. If you start with no config.pbtxt and run with --log-verbose=1 --strict-model-config=false you can see in the console output what TRTIS saw as the model metadata and potentially more information on why it wasn't able to generate a config.

**Comment by Immexxx** [comment]
Thanks for the reply @deadeyegoodwin 
Here are more details.

1. It is an object detection model 

2. I do have a config.pbtxt which has only three lines and I rely on autofill to get the input and output dims
```
name: "model_name"
platform: "tensorflow_savedmodel"
max_batch_size:-1
```
If I have anything else, the server does not come up and the error is as follows: 
a) If the max_batch_size is > 0 (eg: 100 or 1), I get ```configuration specified max-batch 100 but model signature does not support batching```

b) Since it says model does not support batching, to disable batching if I set batch size to 0, I get ```model output cannot have empty reshape for non-batching model```

Is there something I can do while creating the Savedmodel to get around these errors if -1 is in-correct (that is the only value with which the server starts up) 

Or is there a diff config.pbtxt that I can use. If I try it with no config.pbtxt, I again get ```model output cannot have empty reshape for non-batching model for model_name```

Also, if I give it a frozen model - without a config.pbtxt - the server comes up but the status API does not show input and output dims - is autofill supported for a frozen model without a config.pbtxt supported

**Comment by deadeyegoodwin** [comment]
Since you have a TF model you should save it as a saved-model (graphdef aka frozen model is an older format that doesn't embed as much metadata and so the TRTIS autofill can't do much with it).
Then:
1. remove config.pbtxt completely
2. run trtserver with --log-verbose=1 --strict-model-config=false
3. share the console output. That output will contain information showing the saved-model metadata that the TRTIS autofiller is working with

When TRTIS says the model does not support batching, that means that the first dimension on every input and output is not -1 (or None in TF terminology). When means that TRTIS doesn't know how the model handles batching and so TRTIS doesn't allow it. The empty reshape means that as far as TRTIS can determine your model has an output that is *always*  an empty vector, [ ]. TRTIS doesn't like that...

**Comment by Immexxx** [comment]
Thanks for the information @deadeyegoodwin. 
Here is what I have: 

1. The SavedModel that I have works with TF Serving 
2. Did try ```--log-verbose=1 ``` before  but it seems to be printing the tensor values and hence the size of the output  if very large. Have tried to capture most of the useful information below:
```
 trtserver --model-store /models  --strict-model-config=false --log-verbose=1
I0506 17:00:05.443149 15213 main.cc:267] Starting endpoints, 'inference:0' listening on
I0506 17:00:05.443236 15213 main.cc:271]  localhost:8001 for gRPC requests
I0506 17:00:05.443408 15213 grpc_server.cc:265] Building nvrpc server
...


2019-05-06 17:00:05.575978: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /models/model_name/1/saved_model
2019-05-06 17:00:05.596011: I external/org_tensorflow/tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
....
external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:183] Restoring SavedModel bundle.
2019-05-06 17:00:09.457858: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:298] SavedModel load for tags { serve }; Status: success. Took 3881876 microseconds.
I0506 17:00:09.679315 15213 loader.cc:50] Loaded saved-model: meta_info_def 
......
....
...
signature_def {
  key: "serving_default"
  value {
    inputs {
      key: "in_image"
      value {
        name: "image:0"
        dtype: DT_UINT8
        tensor_shape {
          dim {
            size: 120
          }
          dim {
            size: 192
          }
          dim {
            size: 3
          }
        }
      }
    }
    outputs {
      key: "classes"
      value {
        name: "classes:0"
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: -1
          }
          dim {
            size: 1
          }
        }
      }
    }
    outputs {
      key: "detections"
      value {
        name: "detections:0"
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: -1
          }
          dim {
            size: 4
          }
        }
      }
    }
    outputs {
      key: "num_detections"
      value {
        name: "num_detections:0"
        dtype: DT_INT32
        tensor_shape {
        }
      }
    }
    method_name: "tensorflow/serving/predict"
  }
}

I0506 17:00:34.134484 15213 model_config_utils.cc:198] autofilled config: name: "model_name"
platform: "tensorflow_savedmodel"
input {
  name: "in_image"
  data_type: TYPE_UINT8
  dims: 120
  dims: 192
  dims: 3
}
output {
  name: "detections"
  data_type: TYPE_FP32
  dims: -1
  dims: 4
}
output {
  name: "classes"
  data_type: TYPE_FP32
  dims: -1
  dims: 1
}
output {
  name: "num_detections"
  data_type: TYPE_INT32
  dims: 1
  reshape {
  }
}
default_model_filename: "saved_model"

E0506 17:00:34.134557 15213 server.cc:137] model output cannot have empty reshape for non-batching  model for model_name
```

Based on your comments, I think I may be able to unblock myself by removing the num_detections output tensor. Thank you.

The issue seems to be the:
* TF Serving output: 
```
outputs {
      key: "num_detections"
      value {
        name: "num_detections:0"
        dtype: DT_INT32
        tensor_shape {
        }
      }
    }
```

* TRTIS conversion - where the error shows up with batching is not-possible: 
```
output {
  name: "num_detections"
  data_type: TYPE_INT32
  dims: 1
  reshape {
  }
}
```
TRTIS is able to respond with the right number for "num_detections" if I get around the check for empty []

**Comment by deadeyegoodwin** [comment]
What is confusing TRTIS is that the num_detections output always has zero size. Is that really true? If so why is it in the model? Anyway, if you remove the num_detections output from the model configuration you should be ok.
