### ISSUE TITLE
Inference performance hit a limit with one trtserver instance via grpc

### ISSUE THREAD

**Issue by TrojanXu** [NVIDIA/tensorrt-inference-server#269]
Client: perf_client
OS Platform and Distribution: Linux Ubuntu 16.04
TRTIS Docker image: 19.04
CUDA Driver: 418.18
GPU model and memory: 8 V100-16G
Model used: resnet50_trt_fp16

1. Deploy on one GPU,
./perf_client -m resnet50_trt_fp16 -d -c64 -l2000 -p5000 -b8 -i grpc -u localhost:8001 -t4  --max-threads=16
```
Request concurrency: 21
  Client:
    Request count: 1520
    Throughput: 2432 infer/sec
    Avg latency: 61525 usec (standard deviation 20319 usec)
    Avg gRPC time: 43874 usec ((un)marshal request/response 1534 usec + response wait 42340 usec)
  Server:
    Request count: 1825
    Avg request latency: 4787 usec (overhead 18 usec + queue 52 usec + compute 4717 usec)
```
2. But if you deploy the model to two gpus,
The total throughput is similar
```
Request concurrency: 22
Client:
Request count: 1435
Throughput: 2296 infer/sec
Avg latency: 67370 usec (standard deviation 23489 usec)
Avg gRPC time: 46339 usec ((un)marshal request/response 1772 usec + response wait 44567 usec)
Server:
Request count: 1740
Avg request latency: 3783 usec (overhead 17 usec + queue 54 usec + compute 3712 usec)
```
GPU utilization drops to ~50%

This phenomena exists for different backends and similarly, close to a upper limit ~2400 infer/sec
This can be circumvented by launching multiple trtserver instances.

Configuring grpc-infer-thread-count has no effect.

**Comment by deadeyegoodwin** [comment]
This seems related to some discussion at the end of issue #239. We'll take a look when we get a chance. There definitely seems to be some bottleneck. You can try running 2 TRTIS where each can see only 1 GPU (use CUDA_VISIBLE_DEVICES or NVIDIA_VISIBLE_DEVICES) and then run 2 perf-clients each talking to one of the TRTIS and see if that gives you higher throughput. If it doesn't then there is likely some shared resource that is saturating, like network, PCIe or CPU.

**Comment by tianhaox** [comment]
Thanks for the comment. Yes, we can get higher throughput by using multiple trtserver instance. So I'm wondering there is some bottleneck inside trtserver itself.

**Comment by deadeyegoodwin** [comment]
That does sound like there could be a bottleneck. I'll mark this as a bug and we'll look into it.

**Comment by GuanLuo** [comment]
Closing. This issue have probably been fixed, I tried to run TRTIS with 1 and 2 GPUs and to send requests to resnet model via perf_client, I was able to see 2x improvement in terms of  infer/sec. Please reopen the issue and attach your model config if the issue remains
