### ISSUE TITLE
cp: cannot stat 'bazel-bin/src/custom/addsub/libaddsub.so': No such file or directory

### ISSUE THREAD

**Issue by daemon11** [NVIDIA/tensorrt-inference-server#27]
When I run:
docker build -t tensorrtserver_clients --target trtserver_build --build-arg "PYVER=2.7" --build-arg "BUILD_CLIENTS_ONLY=1" .

I have some problems：
INFO: Elapsed time: 94.683s, Critical Path: 14.74s
INFO: 1848 processes: 1848 local.
INFO: Build completed successfully, 2001 total actions
INFO: Build completed successfully, 2001 total actions
cp: cannot stat 'bazel-bin/src/custom/addsub/libaddsub.so': No such file or directory
The command '/bin/sh -c (cd /opt/tensorflow && ./nvbuild.sh --python$PYVER --configonly) &&     (cd tools && mv bazel.rc bazel.orig &&      cat bazel.orig /opt/tensorflow/.tf_configure.bazelrc > bazel.rc) &&     bash -c 'if [ "$BUILD_CLIENTS_ONLY" != "1" ]; then                bazel build -c opt --config=cuda                      src/servers/trtserver                      src/custom/...                      src/clients/...                      src/test/...;              else                bazel build -c opt src/clients/...;              fi' &&     (cd /opt/tensorrtserver && ln -s /workspace/qa qa) &&     mkdir -p /opt/tensorrtserver/bin &&     cp bazel-bin/src/clients/c++/image_client /opt/tensorrtserver/bin/. &&     cp bazel-bin/src/clients/c++/perf_client /opt/tensorrtserver/bin/. &&     cp bazel-bin/src/clients/c++/simple_client /opt/tensorrtserver/bin/. &&     mkdir -p /opt/tensorrtserver/lib &&     cp bazel-bin/src/clients/c++/librequest.so /opt/tensorrtserver/lib/. &&     cp bazel-bin/src/clients/c++/librequest.a /opt/tensorrtserver/lib/. &&     mkdir -p /opt/tensorrtserver/custom &&     cp bazel-bin/src/custom/addsub/libaddsub.so /opt/tensorrtserver/custom/. &&     mkdir -p /opt/tensorrtserver/pip &&     bazel-bin/src/clients/python/build_pip /opt/tensorrtserver/pip/. &&     bash -c 'if [ "$BUILD_CLIENTS_ONLY" != "1" ]; then                cp bazel-bin/src/servers/trtserver /opt/tensorrtserver/bin/.;                cp bazel-bin/src/test/caffe2plan /opt/tensorrtserver/bin/.;              fi' &&     bazel clean --expunge &&     rm -rf /root/.cache/bazel &&     rm -rf /tmp/*' returned a non-zero code: 1

Can you help? Thank you

**Comment by deadeyegoodwin** [comment]
You've hit a bug in the Dockerfile for BUILD_CLIENTS_ONLY=1. That's for reporting the issue. The line that is reported as failing is from the Dockerfile. You should be able to work-around by removing the following from that line.

cp bazel-bin/src/custom/addsub/libaddsub.so /opt/tensorrtserver/custom/.

**Comment by daemon11** [comment]
thx
