### ISSUE TITLE
TRTIS crashes in GCP after the first request without any error messages when more than 10 models are loaded.

### ISSUE THREAD

**Issue by achbogga** [NVIDIA/tensorrt-inference-server#272]
Tested on GCP V100 DL optimized TF 1.13 VM using docker image 19.03py3. (26 G mem, 6 core, 300G SSDHDD)
20 inception v4 models in the repo.
The first request for the model 1 works with a very slow response time (18 seconds).
The second request for the same model 1 returns a 0.06s response time
The next request for any other model say 3, causes server crash and no error messages. Once this happens, the VM just hangs when I try to run the docker image again. I have to restart the VM again to get it to work. Can anyone please reproduce this and let me know what exactly is causing this issue(both the slow response time for the first request and server crash when requested an inference from a different model)? Also potential solutions?

**Comment by achbogga** [comment]
I guess the problem is with RAM. When I increased RAM, this issue does not occur. It would still be nice if we TRTIS can throw some warning or error if this might be a potential crash in operation.

**Comment by deadeyegoodwin** [comment]
The reason the model is slow on the first execution is that TF does some optimizations and transformations of the network at runtime. Those optimiztions cause slow response times initially but once they complete you see the "full speed" inferencing performance.

As far as the server running out of memory... what is likely happening is that the linux OOM killer is terminating the TRTIS process when memory gets low. The inference server can't do anything about that. You will get an error (and a failed inference request) if a malloc fails during execution.

**Comment by achbogga** [comment]
@deadeyegoodwin Thanks!
