### ISSUE TITLE
TRTIS in pod segfaulting

### ISSUE THREAD

**Issue by allenc97** [NVIDIA/tensorrt-inference-server#276]
Hi guys, I am trying to run a combination of 3 detection and 5 classification TF models in an Azure K8s pod. (A NC6v3 with a V100 GPU) However, my pod keeps running into segmentation faults that cause it to restart. I have attached the logs of the error below. Do you have any idea why this is happening, and any possible solutions to prevent this from happening?
 
E0508 09:33:57.291671 1 cuda_driver.cc:981] failed to synchronize the stop event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
E0508 09:33:57.291705 1 cuda_timer.cc:55] Internal: error destroying CUDA event in context 0x7fe154935e30: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
E0508 09:33:57.291715 1 cuda_timer.cc:60] Internal: error destroying CUDA event in context 0x7fe154935e30: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
E0508 09:33:57.291810 1 cuda_dnn.cc:194] Check failed: status == CUDNN_STATUS_SUCCESS (7 vs. 0)Failed to set cuDNN stream.

**Comment by deadeyegoodwin** [comment]
Have you been successful running a single TF model? Perhaps try the example one from the quickstart documentation. It looks like something is going wrong with CUDA. Make sure the CUDA, cudnn, etc. installed on the node matches what is required for the version of TRTIS you are using. See the driver requirements section of the release notes, for example for 19.04 https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-04.html#rel_19-04

Full support matrix is here. Both of these links are referenced in the README.
https://docs.nvidia.com/deeplearning/dgx/support-matrix/index.html

**Comment by deadeyegoodwin** [comment]
Closing. Please reopen if still an issue.
