### ISSUE TITLE
InferContext.ResultFormat.CLASS for RNN

### ISSUE THREAD

**Issue by akurniawan** [NVIDIA/tensorrt-inference-server#279]
Currently I am working on sequence prediction model with RNN and the output will be in the shape of `[batch_size, seq_len, tags]`. After trying with the following request format
```
ctx.run(
    {input_cfg.name: [np.array([1, 2, 3, 4]).astype("int32")]},
    {output_cfg.name: (InferContext.ResultFormat.CLASS, top_k_classes)},
    batch_size
)
```
The result is assumed as a single tensor
```
{u'111': [[(9L, 0.05252315104007721, u'')]]}
```
Is there a way to make the prediction in the form of `[batch_size, seq_len]`? Or for now we need to do it manually using RAW output?

**Comment by deadeyegoodwin** [comment]
Are you asking how to make a request with a batch-size > 1? For your input you just need to supply multiple np.array(...).astype("int32") entries in the list that you pass to ctx.run. Of course set "batch_size" to match the length of that list.

Your result array will then have multiple outputs, one for each entry in the batch.

**Comment by akurniawan** [comment]
@deadeyegoodwin nope, I’m asking on how to output multiple class in one request. So for example if I have a request with size of ‘[batch, seq_len]’. I want the output be in the same form as the input ‘[batch, seq_len]’. Imagine problem like named entity recognition or pos tagging where each words has their own prediction instead of only one prediction for the whole sentence

**Comment by deadeyegoodwin** [comment]
The inference server doesn't have that feature, it can only return one set of class results for each batch entry. You'll need to post-process the raw results yourself if you want something more.

**Comment by akurniawan** [comment]
Got it, thanks!
