### ISSUE TITLE
inference by CURL ?

### ISSUE THREAD

**Issue by jazztronomers** [NVIDIA/tensorrt-inference-server#280]
there is only python, c++ client example 
but i wonder if TRTIS supports inference by curl command 

I tried a lot but kept failing with invalid argument problem.

what i tried:

**CHECK STATUS**

r@a:~$ curl localhost:8000/api/status/mnist_savedmodel

id: "inference:0"
version: "0.11.0"
uptime_ns: 99517818720191
model_status {
  key: "mnist_savedmodel"
  value {
    config {
      name: "mnist_savedmodel"
      platform: "tensorflow_savedmodel"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      max_batch_size: 50
      input {
        name: "inputs"
        data_type: TYPE_FP32
        dims: 28
        dims: 28
      }
      output {
        name: "probabilities"
        data_type: TYPE_FP32
        dims: 10
      }
      instance_group {
        name: "mnist_savedmodel"
        count: 1
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "model.savedmodel"
    }
    version_status {
      key: 2
      value {
        ready_state: MODEL_READY
        infer_stats {
          key: 0
          value {
            failed {
              count: 113
              total_time_ns: 11686947
            }
          }
        }
        infer_stats {
          key: 1
          value {
            success {
              count: 12
              total_time_ns: 341116850
            }
            failed {
              count: 8
              total_time_ns: 18810494
            }
            compute {
              count: 12
              total_time_ns: 339262819
            }
            queue {
              count: 12
              total_time_ns: 321890
            }
          }
        }
        model_execution_count: 12
        model_inference_count: 12
      }
    }
  }
}
ready_state: SERVER_READY

**R E Q U E S T**

curl \

-X POST localhost:8000/api/infer/mnist_savedmodel \
-H "Content-Type: application/octet-stream" \
-H 'NV-InferRequest:batch_size: 1 input { name: "inputs" dims: 28 dims: 28 } output { name: "probabilities" cls { count: 1 } }' \
-v \
--data-binary "@6.png" \

**R E S P O N S E**

*   Trying localhost...
* Connected to localhost (localhost) port 8000 (#0)
> POST /api/infer/mnist_savedmodel HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/octet-stream
> NV-InferRequest:batch_size: 1 input { name: "inputs" dims: 28 dims: 28 } output { name: "probabilities" cls { count: 1 } }
> Content-Length: 259
> 
* upload completely sent off: 259 out of 259 bytes
> HTTP/1.1 400 Bad Request
> NV-Status: code: INVALID_ARG msg: "unexpected size for input \'inputs\', missing expecting 2877 bytes for model \'mnist_savedmodel\'" server_id: "inference:0"
> Content-Type: application/octet-stream
> Date: Thu, 09 May 2019 05:21:28 GMT
> Content-Length: 0
> 
* Connection #0 to host localhost left intact

------------------------------------------------------------------------------------

**T R I A L  AND E R R O R**

1) W/O NV INFERENCE HEADER 

NV-Status 	 code: INVALID_ARG msg: "inference request batch-size must be >= 1 for \'mnist_savedmodel\'" server_id: "inference:0"

2) WRONG NV INFERENCE HEADER 

NV-Status 	 code: INVALID_ARG msg: "unexpected inference input \'inputdsas\' for model \'mnist_savedmodel\'" server_id: "inference:0"

2) W/O IMAGE, WITH NV HEADER 

NV-Status 	 code: INTERNAL msg: "unexpected input index 0

3) W/ IMAGE BINARY 

NV-Status 	 code: INVALID_ARG msg: "unexpected size for input \'inputs\', missing expecting 3135 bytes for model \'mnist_savedmodel\'" server_id: "inference:0"

4) W/ IMAGE (BINARY)

NV-Status 	 code: INVALID_ARG msg: "unexpected additional input data for model \'mnist_savedmodel\'" server_id: "inference:0"

**Comment by CoderHam** [comment]
@jazztronomers the image being passed to the mnist model must be **28x28** (Only 1 channel). Are you passing an image of that dimension? If not you might want to _preprocess_ the image prior to this. You can follow the function mentioned here (should). https://github.com/NVIDIA/tensorrt-inference-server/blob/30b8b8f5b6a42d8c3d9a8576e86fae7feb4433d5/src/clients/python/grpc_image_client.py#L143
I hope this helps! Feel free to reach out if you are still facing this issue

**Comment by GuanLuo** [comment]
As mentioned by @CoderHam, the image will need to be preprocessed as your model is expecting the binary form of a 28x28 FP32 tensor, while the data you uploaded is the image encoded as "png".

Another feature you may be interested in is the ensembling https://github.com/NVIDIA/tensorrt-inference-server/issues/25#issuecomment-491038621 . We provide an example ensemble (combination of preprocessing custom model and resnet50 model) that takes "nearly raw" image and returns the classification result.

"nearly raw" because the example uses STRING data type to hold the image file, and TRTIS requires that the STRING data must be prefixed with the size of the content. You should be able to create your own preprocess model using non-string data type tensor to avoid that.

Anyway, with the ensemble example, you can infer with CURL as following:
```bash
# prepend image file size 1005970 in 4 bytes
printf "\x00\x0f\x59\x92" | cat - ./images/mug.jpg > stuff_mug

# send infer request (note that "batch_byte_size" is 1005974)
curl -X POST --data-binary @stuff_mug -H 'Expect:' -H "Content-Type: application/octet-stream" -H "Content-Length: 1005974" -H 'NV-InferRequest:batch_size: 1 input { name: "INPUT" dims: 1 batch_byte_size: 1005974 } output { name: "OUTPUT" cls { count: 1 } }' -H "Accept: */*" localhost:8000/api/infer/preprocess_resnet50_ensemble
```
And response:
```
model_name: "preprocess_resnet50_ensemble"
model_version: 1
batch_size: 1
output {
  name: "OUTPUT"
  batch_classes {
    cls {
      idx: 504
      value: 0.723991275
      label: "COFFEE MUG"
    }
  }
}
```

**Comment by jazztronomers** [comment]
@CoderHam 

--data-binary read file as binary, so i thought i passed the right binary (the image preprocessed) cause it is 28x28 grayscale image, but it seems wrong

and then i tried passing **bytes formatted, preprocessed image** and finally succeed

here's my full code:

**PREPROCESSING PYTHON CODE**

    from PIL import Image
    import numpy as np

    def preprocess(img, format, dtype, h, w, scaling):

        sample_img = img.convert('L')


        resized_img = sample_img.resize((w, h), Image.BILINEAR)
        resized = np.array(resized_img)
        resized = resized.astype(dtype)

        return resized

    # png img file
    img = Image.open('./data/6.png')

    # preprocessed img, FP32 formated numpy array
    img = preprocess(img, format, "float32", 28, 28, None)

    # to bytes
    img = img.tofile('6.binaryimage',format='binary')


**COMMAND LINE**

    rubenchu@astronomers:curl \
    -X POST localhost:8000/api/infer/mnist_savedmodel 
    -H "Content-Type: application/octet-stream" 
    -H 'NV-InferRequest:batch_size: 1 input { name: "inputs" dims: 28 dims: 28 } output { name:     "probabilities" cls { count: 1 } }'
    --data-binary "@6.binaryimage" 


    model_name: "mnist_savedmodel"
    model_version: 2
    batch_size: 1
    output {
      name: "probabilities"
      batch_classes {
        cls {
      idx: 6
      value: 1
        }
      }
    }

**Comment by jazztronomers** [comment]
@CoderHam @GuanLuo
Thanks a lot !
