### ISSUE TITLE
Transform ONNX to TensorRT Fail

### ISSUE THREAD

**Issue by GuanLianzheng** [NVIDIA/tensorrt-inference-server#281]
Number of errors: 1
File of the error:builtin_op_importers.cpp
Description of the error: Assertion failed: dims.nbDims == 3
Line where the error occurred: 1238
Error code: UNSUPPORTED_NODE
Func of the error:importMatMul
Node of the error:2
Model was not parsed successfully

**Comment by deadeyegoodwin** [comment]
TensorRT is a separate project from TensorRT Inference Server. You should ask you question on the following forum which is monitored by the TensorRT team:

https://devtalk.nvidia.com/default/board/304/tensorrt/
