### ISSUE TITLE
YOLOv3 model configuration issue

### ISSUE THREAD

**Issue by srijiths** [NVIDIA/tensorrt-inference-server#282]
Hi All,

I have taken https://github.com/YunYang1994/tensorflow-yolov3 project to convert yolo.weights to frozen pb file. But for scores(concat_11) and labels (concat_12) output doesn't have diamension. Its coming as 
```
boxes shape : (3, 4)
scores shape : (3,)
Labels shape : (3,)
```
Since tensorrt server model configuration always requires a dims configuration , its failing at the time when i try inferencing with a sample client. 

I have tried giving multiple options to dims in configuration file like -1 and reshape , but configuration file is not allowing the dims to be blank.

My model configuration file looks like below.
```
name: "yolov3"
platform: "tensorflow_graphdef"
max_batch_size: 128
input [
  {
    name: "Placeholder"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 416, 416, 3 ]
  }
]
output [
  {
    name: "concat_10"
    data_type: TYPE_FP32
    dims: [ 4 ]
  },
  {
    name: "concat_11"
    data_type: TYPE_FP32
    dims: []
    reshape: { shape: [1] }
  },
  {
    name: "concat_12"
    data_type: TYPE_INT32
    dims: []
    reshape: { shape: [1]}
    label_filename: "coco_labels.txt"
  }
]
instance_group [
  {
    kind: KIND_GPU
    count: 4
	gpus: [0]
  }
]
```

np.atleast_2d on scores and labels will make it (3,1). But before editing those output diamension changes outside of tensorrt server , would like to know whether this is possible with in the server itself.

Thank You,

**Comment by deadeyegoodwin** [comment]
Can you save the model using saved-model format? simple_save is an easy to use function for this, see https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_repository.html#tensorflow-models

Then instead of specifying the config.pbtxt you can use trtserver --strict-model-config=false and it will generate it for you (you can then copy what it does and modify it to add instance_group, etc.).
https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_configuration.html#generated-model-configuration

**Comment by srijiths** [comment]
@deadeyegoodwin Thank you. Now i am trying with saved model and the model dir structure is like "models/yolov3/1/model.savedmodel/" and under that the listed files are 

``
yolov3.ckpt.index, yolov3.weights, yolov3.ckpt.data-00000-of-00001, yolov3.ckpt.meta, yolov3_gpu_nms.pb ,  yolov3.weights6vobz1ns.tmp
``
1) First step i have not specified the config.pbtxt and executed the server as 
```
nvidia-docker run --rm -p 8000:8000 -p 8083:8083 -v /home/srijith_sasidharan/tensorrt/models:/opt/tensorrtserver/models nvcr.io/nvidia/tensorrtserver:19.04-py3 trtserver --model-store="/opt/tensorrtserver/models" --log-verbose=1 --strict-model-config=false
```
Its saying platform has to be specified. Error log is
```
I0510 06:46:34.884523 1 reader.cc:31] Reading SavedModel from: /opt/tensorrtserver/models/yolov3/1/model.savedmodel
I0510 06:46:34.884578 1 loader.cc:298] SavedModel load for tags { serve }; Status: fail. Took 63 microseconds.
I0510 06:46:34.885005 1 model_config_utils.cc:198] autofilled config: name: "yolov3"

E0510 06:46:34.885030 1 server.cc:294] must specify platform for model 'yolov3'
```
2) Second step , i have included a minimal config.pbtxt specifying the platform and input only and executed docker command as listed above
```
name: "yolov3"
platform: "tensorflow_savedmodel"
max_batch_size: 128
input [
  {
    name: "Placeholder"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ 416, 416, 3 ]
  }
]
```
Now got the exception as 
```
E0510 06:53:14.149542 1 retrier.cc:37] Loading servable: {name: yolov3 version: 1} failed: Internal: Could not find SavedModel .pb or .pbtxt at supplied export directory path: /opt/tensorrtserver/models/yolov3/1/model.savedmodel
I0510 06:53:14.149588 1 loader_harness.cc:154] Encountered an error for servable version {name: yolov3 version: 1}: Internal: Could not find SavedModel .pb or .pbtxt at supplied export directory path: /opt/tensorrtserver/models/yolov3/1/model.savedmodel
E0510 06:53:14.149601 1 aspired_versions_manager.cc:358] Servable {name: yolov3 version: 1} cannot be loaded: Internal: Could not find SavedModel .pb or .pbtxt at supplied export directory path: /opt/tensorrtserver/models/yolov3/1/model.savedmodel
```
3) Renamed above listed yolov3_gpu_nms.pb file to saved_model.pb and executed the docker again but still not successful. Exception listed below
```
I0510 06:56:42.895482 1 base_bundle.cc:162] Creating instance yolov3_0_gpu0 on GPU 0 (6.1) using model.savedmodel
I0510 06:56:42.895643 1 reader.cc:31] Reading SavedModel from: /opt/tensorrtserver/models/yolov3/1/model.savedmodel
I0510 06:56:43.101822 1 reader.cc:54] Reading meta graph with tags { serve }
I0510 06:56:43.116247 1 loader.cc:298] SavedModel load for tags { serve }; Status: fail. Took 220600 microseconds.
I0510 06:56:43.116301 1 base_bundle.cc:65] ~BaseBundle::Context
E0510 06:56:43.116333 1 retrier.cc:37] Loading servable: {name: yolov3 version: 1} failed: Internal: Could not find meta graph def matching supplied tags: { serve }. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
I0510 06:56:43.116389 1 loader_harness.cc:154] Encountered an error for servable version {name: yolov3 version: 1}: Internal: Could not find meta graph def matching supplied tags: { serve }. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
E0510 06:56:43.116401 1 aspired_versions_manager.cc:358] Servable {name: yolov3 version: 1} cannot be loaded: Internal: Could not find meta graph def matching supplied tags: { serve }. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
```
Whats going wrong here ? 
Thank You,

**Comment by srijiths** [comment]
Any pointers on this issue please?  I am stuck at this issue. 

Thank you

**Comment by deadeyegoodwin** [comment]
How did you save you model in saved-model format? It looks like what you are using is a checkpoint, not a saved-model.
Here's what the output directory should look like: https://www.tensorflow.org/guide/saved_model#structure_of_a_savedmodel_directory

**Comment by srijiths** [comment]
@deadeyegoodwin Thank You, You are right. The code which i used is different. I will check it and revert.

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if you still have issues.

**Comment by 17702513221** [comment]
@srijiths Can you give me help to using saved-model in https://github.com/YunYang1994/tensorflow-yolov3 ,thank you

**Comment by srijiths** [comment]
Soon i will publish it and write a blog.

**Comment by srijiths** [comment]
You can see the published yolo v3 model and how to run here https://medium.com/@srijith.s/deploy-yolov3-in-nvidia-tensorrt-server-eed6ba0f1b45
