### ISSUE TITLE
grpc_image_client.py example with raw output reading?

### ISSUE THREAD

**Issue by pmcgraw-lucidyne** [NVIDIA/tensorrt-inference-server#296]
Hello,

I am using the src/client/python/grpc_image_client.py as an example for interfacing with inference server, and I would like to receive the raw output from the server. I discovered in the documentation https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/protobuf_api/api.proto.html that dropping the "cls" attribute from the grpc_inference_api.src.core.api_pb2.InferRequestHeader.Output message, but I can't seem to find an example of reading the result into say a numpy array?

Thanks,
Padraic

**Comment by srijiths** [comment]
Hi Padraic,

I am also trying to solve this. Sharing what i have found.  In src/client/python/grpc_image_client.py , each response contains a structure like below.
```
request_status {
  code: SUCCESS
  server_id: "inference:0"
  request_id: 32
}
meta_data {
  model_name: "model_name"
  model_version: 1
  batch_size: 1
  output {
    name: "output_name"
    raw {
      dims: 100
      dims: 1
      dims: 4
      batch_byte_size: 1355
    }
  }
}
raw_output: "OUTPUT BYTES"
```
You can get the raw_output and output meta data by
```
for response in responses:
    print('raw output :', response.raw_output)
    out_meta_data = response.meta_data.output # will give you the complete output metadata
    output = out_meta_data[0] # will give the first output details
    print('dims : ', output.raw.dims) # will give a combined dim like [100, 1 , 4]
    print('bytes size: ', output.raw.batch_byte_size) # will give  1355
```
Like this you can access output.raw.batch_byte_size or out_meta_data.model_name, out_meta_data.model_version etc...

Thanks,
Srijith

**Comment by pmcgraw-lucidyne** [comment]
Works! Thanks for the help. I don't know if it matters in your case but when I was reshaping boxes the batch size I was using had to be prepended to the expected shape. Thanks again! Closing this issue as the @srijiths has answered my question.
