### ISSUE TITLE
caffe2_netdef InferenceServerException

### ISSUE THREAD

**Issue by bezero** [NVIDIA/tensorrt-inference-server#298]
I have a caffe model with the following config:
```proto
name: "caffe_model"
platform: "caffe2_netdef"
max_batch_size: 2
input [
  {
    name: "actual_input_1"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 1024, 1024 ]
  }
]
output [
  {
    name: "output1"
    data_type: TYPE_FP32
    dims: [ 64512, 22  ]
  }
]
```

Server loads with no error. While inference request I received ```InferenceServerException``` error:
```
---------------------------------------------------------------------------
InferenceServerException                  Traceback (most recent call last)
<timed exec> in <module>

/usr/local/lib/python3.5/dist-packages/tensorrtserver/api/__init__.py in run(self, inputs, outputs, batch_size, flags)
    868 
    869         # Run inference...
--> 870         self._last_request_id = _raise_if_error(c_void_p(_crequest_infer_ctx_run(self._ctx)))
    871 
    872         return self._get_results(outputs, batch_size)

/usr/local/lib/python3.5/dist-packages/tensorrtserver/api/__init__.py in _raise_if_error(err)
    178         _crequest_error_del(err)
    179         if not isok:
--> 180             raise ex
    181         return ex.request_id()
    182     return 0

InferenceServerException: [inference:0 3] failed to run model 'caffe_model': [enforce fail at reshape_op.h:86] . Can not reshape a non-zero size (67584) tensor to zero size.
Error from operator: 
input: "636" input: "650" output: "651" output: "OC2_DUMMY_1" name: "" type: "Reshape" device_option { device_type: 1 device_id: 1 }frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*) + 0x76 (0x7f745af9c0e6 in /opt/tensorrtserver/lib/libc10.so)
frame #1: <unknown function> + 0x2e0e673 (0x7f745dfb9673 in /opt/tensorrtserver/lib/libcaffe2_gpu.so)
frame #2: <unknown function> + 0x2e0ea2e (0x7f745dfb9a2e in /opt/tensorrtserver/lib/libcaffe2_gpu.so)
frame #3: <unknown function> + 0x27866f2 (0x7f745d9316f2 in /opt/tensorrtserver/lib/libcaffe2_gpu.so)
frame #4: caffe2::SimpleNet::Run() + 0x1c9 (0x7f74af024b49 in /opt/tensorrtserver/lib/libcaffe2.so)
frame #5: caffe2::Workspace::RunNet(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x4d (0x7f74af045a2d in /opt/tensorrtserver/lib/libcaffe2.so)
frame #6: <unknown function> + 0x15cb017 (0x7f74af0a2017 in /opt/tensorrtserver/lib/libcaffe2.so)
frame #7: <unknown function> + 0x92e89b (0x5593f0dfa89b in trtserver)
frame #8: <unknown function> + 0x92f03f (0x5593f0dfb03f in trtserver)
frame #9: <unknown function> + 0x92f5fa (0x5593f0dfb5fa in trtserver)
frame #10: <unknown function> + 0x9768e2 (0x5593f0e428e2 in trtserver)
frame #11: <unknown function> + 0xb8c80 (0x7f744bbabc80 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #12: <unknown function> + 0x76ba (0x7f744c7b36ba in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #13: clone + 0x6d (0x7f744b61a41d in /lib/x86_64-linux-gnu/libc.so.6)
```

To verify that model is working correctly I used ```nvcr.io/nvidia/pytorch:19.04-py3``` container to run model manually with the following script and it worked:

```py
from caffe2.python import core, workspace, models
import numpy as np
with open('init_model.netdef', "rb") as f:
    init_net = f.read()
with open('model.netdef', "rb") as f:
    predict_net = f.read()
p = workspace.Predictor(init_net, predict_net)
results = p.run({'actual_input_1': np.zeros((10, 3, 1024, 1024), dtype=np.float32)})
print(results[0].shape)  # (10, 64512, 22)
```
Where does this error come from?

**Comment by deadeyegoodwin** [comment]
In your code example you have an input shape of [ 10, 3, 1024, 1024 ]. Is that first 10 dimension the batch dimension, or does the model require exactly that shape. Your model config indicates that you expect that first dimension to be the batch dimension (because you set max_batch_size > 0). But in the model config you set max_batch_size to 2, which doesn't match your use of 10 in the example.

**Comment by bezero** [comment]
@deadeyegoodwin yes 10 is the batch size. Just for this example I used it, however while using trt client I was sending requests according to max_batch_size.

**Comment by deadeyegoodwin** [comment]
The error seems to be coming from an internal node within your network. Can you try the test with the exact batch size that you use in the trt client?

**Comment by bezero** [comment]
@deadeyegoodwin I tried several batch sizes both for client and simple caffe scrip provided. For client I consistently receive same error as mentioned; however, for the simple python scrip model run with no errors. Here you can find [caffe_model](https://drive.google.com/file/d/1zZgwyVmKB-T3_4EG3IXlyJJqY8roakVc/view?usp=sharing) that I am using for inference.

**Comment by deadeyegoodwin** [comment]
Ok, we will try to reproduce.

**Comment by CoderHam** [comment]
@bezero I was able to reproduce the error. You mentioned that the python script ran successfully. Was this run inside the container as well? If not which version of Caffe2/PyTorch did you use?

**Comment by bezero** [comment]
@CoderHam I used ```nvcr.io/nvidia/pytorch:19.04-py3``` container  to run the python code.

**Comment by CoderHam** [comment]
@bezero
The model runs on TRTIS on CPU mode. Is it possible that the model has some CPU only operations? Are you using some special layers in the model?

**Comment by CoderHam** [comment]
I believe the issue is that TRTIS runs the caffe2 model entirely on GPU or CPU but your model has some operations that are set to run on CPU. This is why the python caffe2 interface is able to run the GPU model successfully but the TRTIS GPU execution fails.

**Comment by CoderHam** [comment]
#147
