### ISSUE TITLE
why the uff parser is so slow ?

### ISSUE THREAD

**Issue by argman** [NVIDIA/tensorrt-inference-server#308]
when i load a 110MB model with uffParser, it spends about 3minutes to do this job
![image](https://user-images.githubusercontent.com/15120999/58408819-3774c400-80a1-11e9-88eb-6d9b1f18e1b1.png)

**Comment by deadeyegoodwin** [comment]
TensorRT is a compiler/runtime for TensorRT models.
TensorRT Inference Server is a "microservice" that execute TensorRT models (as well as TF, Caffe2, and other frameworks).
Your question seems to be about TensorRT (UFF is part of TensorRT). You should ask your question on the TensorRT developer forum: https://devtalk.nvidia.com/default/board/304/tensorrt/
