### ISSUE TITLE
Looser coupling against TensorRT versions

### ISSUE THREAD

**Issue by nieksand** [NVIDIA/tensorrt-inference-server#310]
Feature request...

Right now it looks like I have to recompile all my TensorRT plans every time TRTIS does a release.  

```
E0527 10:06:47.414891 1 logging.cc:43] The engine plan file is not compatible with this version of TensorRT, expecting library version 5.1.5 got 5.1.2, please rebuild.
```

This is annoying operationally because, besides having to recompile all our models, we also have to revalidate TensorRT outputs vs. our original Tensorflow results.

(This issue actually kept us on TRTIS 19-02 for some time because TRT 19-03 introduced a bug causing invalid outputs for one of our networks.  We finally found a workaround and bumped to 19-04 last week.  Happily, our validation scripts caught that naughtiness before it ever made it to production).

It would be nice if TRTIS was less picky about TRT version.

**Comment by deadeyegoodwin** [comment]
I agree that TensorRT's lack of backwards compatibility is annoying. But TRTIS doesn't have any control over it and currently our monthly release always builds with a latest available version of TensorRT. We are working on a more modular CMake-based build that will allow you to install the tensorRT version you want and then build against that version. At that point you should be able to build new versions of TRTIS without invalidating your existing TRT models.

**Comment by nieksand** [comment]
That's unfortunate but understandable.  This ticket can probably be closed.
