### ISSUE TITLE
How to pass placeholders other than input - MTCNN

### ISSUE THREAD

**Issue by srijiths** [NVIDIA/tensorrt-inference-server#312]
Hi All,

I am trying to convert    [https://github.com/blaueck/tf-mtcnn](url)   MTCNN tensorflow implementation to tensorrt server. My configuraiton looks like below.
```
name: "mtcnn"
platform: "tensorflow_graphdef"
max_batch_size: 128
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: -1
    dims: -1
    dims: 3
  }
]
output [
  {
    name: "box"
    data_type: TYPE_FP32
    dims: -1
    dims: 4
   },
   {
    name: "prob"
    data_type: TYPE_FP32
    dims: -1
   },
   {
     name: "landmarks"
     data_type: TYPE_FP32
     dims: -1
     dims: 10
   }
]
instance_group [
  {
    kind: KIND_GPU
    count: 1
	gpus: [0]
  }
]
```
But along with input , it expects a "min_size" parameter also. Please check [https://github.com/blaueck/tf-mtcnn/blob/master/mtcnn.py#L26](url) .How to pass multiple parameters other than input to tensorrt server.

The arguments which needs to pass below, 
```
        feeds = {
            self.graph.get_operation_by_name('input').outputs[0]: img,
            self.graph.get_operation_by_name('min_size').outputs[0]: self.min_size,
            self.graph.get_operation_by_name('thresholds').outputs[0]: self.thresholds,
            self.graph.get_operation_by_name('factor').outputs[0]: self.factor
        }
```
Also i would like to understand what changes required to make it work in grpc_image_client.py on request side.

Thank You
Srijith

**Comment by GuanLuo** [comment]
You should be able to specify those additional placeholders as inputs in `config.pbtxt`, and providing the values for them in the same way as for placeholder "input" when you send the request to inference server.

**Comment by srijiths** [comment]
Thank you @GuanLuo I am able to put multiple inputs in the model configuration. Now i am trying grpc_image_client example to connect to it like below
```
request = grpc_service_pb2.InferRequest()
request.model_name = FLAGS.model_name
request.model_version = 1
request.meta_data.batch_size = FLAGS.batch_size
request.meta_data.input.add(dims=[w,h,c], name="input")
request.meta_data.input.add(dims=[40], name="min_size")
request.raw_input.extend([image_bytes])
```
Now there is an exception from server saying "Expecting 2 set of inputs but got 1". Is the above statements correct ? Please help me to form a grpc client request with multiple inputs. 

Thank You,
Srijith

**Comment by GuanLuo** [comment]
@srijiths note that the [raw_input](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/protobuf_api/grpc_service.proto.html#_CPPv4N6nvidia15inferenceserver12InferRequest9raw_inputE) field is repeated filed, you should also add the data for the second input.

**Comment by srijiths** [comment]
Thank you @Guan..it works..

**Comment by jiapinai** [comment]
@srijiths  would you kindly share your config.pbtxt and client changes? I'm stacking here. please help, thank you

**Comment by srijiths** [comment]
You can find more details here https://github.com/srijiths/YOLOv3_tensorrt_server

**Comment by jiapinai** [comment]
> You can find more details here https://github.com/srijiths/YOLOv3_tensorrt_server

Thank you :)

**Comment by jiapinai** [comment]
@GuanLuo  hi, 
I'm using MTCNN tensorflow model: [https://github.com/blaueck/tf-mtcnn](https://github.com/blaueck/tf-mtcnn) as mentioned above.

An error occur: `The second input must be a scalar, but it has shape [1,1]`

How to  config to make sure `input must be a scalar`?

Thank you

## config.pbtxt

```
name: "face_detect_tf_mtcnn"
platform: "tensorflow_graphdef"
max_batch_size: 128
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [ -1, -1, 3 ]
  },
  {
    name: "min_size"
    data_type: TYPE_FP32
    dims: [1]
    is_shape_tensor: false
  },
  {
    name: "thresholds"
    data_type: TYPE_FP32
    dims: [3]
  },
  {
    name: "factor"
    data_type: TYPE_FP32
    dims: [1]
    is_shape_tensor: false
  }
]
output [
  {
    name: "box"
    data_type: TYPE_FP32
    dims: -1
    dims: 4
   },
   {
    name: "prob"
    data_type: TYPE_FP32
    dims: -1
   },
   {
     name: "landmarks"
     data_type: TYPE_FP32
     dims: -1
     dims: 10
   }
]
```

## client request

```
...

        request.meta_data.input.add(dims=[224,224,3], name=input_name)
        request.meta_data.input.add(dims=[1], name='min_size')
        request.meta_data.input.add(dims=[3], name='thresholds')
        request.meta_data.input.add(dims=[1], name='factor')
...
        request.raw_input.extend([ input_bytes ])
        request.raw_input.extend([min_size])
        request.raw_input.extend([thresholds])
        request.raw_input.extend([factor])

```

## triton server error log

```
I0422 06:45:55.337605 1 base_backend.cc:643] Running face_detect_tf_mtcnn_0_0_gpu0 with 1 request payloads
I0422 06:45:55.337683 1 base_backend.cc:455] input 'thresholds' is GPU tensor: 0
I0422 06:45:55.337754 1 base_backend.cc:455] input 'factor' is GPU tensor: 0
I0422 06:45:55.338217 1 base_backend.cc:455] input 'input' is GPU tensor: 0
I0422 06:45:55.338419 1 base_backend.cc:455] input 'min_size' is GPU tensor: 0
I0422 06:45:55.729119 1 trtserver.cc:1677] Infer failed: 2 root error(s) found.
  (0) Invalid argument: The second input must be a scalar, but it has shape [1,1]
	 [[{{node pnet/while/Switch}}]]
	 [[box/_109]]
  (1) Invalid argument: The second input must be a scalar, but it has shape [1,1]
	 [[{{node pnet/while/Switch}}]]

```
