### ISSUE TITLE
can the server docker built from source on jetson baord with aarch64 cpu ?

### ISSUE THREAD

**Issue by abczhaoling** [NVIDIA/tensorrt-inference-server#323]

**Comment by deadeyegoodwin** [comment]
I think  you are asking if TRTIS can be built for jetson (ARM arch). We currently do not build or test for that platform but fundamentally there shouldn't be any reason it will not work. On master (and starting with the 19.07 release) we are now using a modular cmake-based build. It should be much easier to modify the cmake to target jetson/aarch64 that our previous bazel-based build.

We are generally interested in cmake improvements that enable builds on other platforms so please share your experience.
