### ISSUE TITLE
Support model repositories on s3 or azure blob

### ISSUE THREAD

**Issue by rakelkar** [NVIDIA/tensorrt-inference-server#324]
The inference server currently supports model repository on GCS and local directory. Would be great if it could also support downloading from S3 or Azure BLOBs. Incidentally I couldnt find the GCS code anywhere? I only see an implementation of LocalFileSystem...

**Comment by deadeyegoodwin** [comment]
We have these in our backlog so I will mark this as an enhancement so others can comment.

Prior to release 19.07 the GCS code we used is from the TensorFlow source. 
Starting with release 19.07 we will use a cmake build and in src/core/filesystem.cc you will see the GCS implementation. This work is going on right now on master so expect to see it merged soon.

**Comment by xprotobeast2** [comment]
We now have support for GCS. S3 support is currently in PR #533 .

**Comment by deadeyegoodwin** [comment]
S3 support will be in the 19.09 release. Azure support is not yet scheduled. Closing this since S3 is done and we are already tracking azure.
