### ISSUE TITLE
dims [-1] don't match configuration dims [-1]

### ISSUE THREAD

**Issue by tienduchoang** [NVIDIA/tensorrt-inference-server#325]
Hello everyone, i server tensorflow saved model. My model configuration is:
```
  inputs['input_1'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, -1, -1, 3)
      name: serving_default_input_1:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['yolo_nms_0'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 100, 4)
      name: StatefulPartitionedCall:0
  outputs['yolo_nms_1'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 100)
      name: StatefulPartitionedCall:1
  outputs['yolo_nms_2'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, 100)
      name: StatefulPartitionedCall:2
  outputs['yolo_nms_3'] tensor_info:
      dtype: DT_INT32
      shape: (-1)
      name: StatefulPartitionedCall:3
```
So my config file is:
```
input [
    {
        name: "input_1"
        data_type: TYPE_FP32
        dims: [ 320, 320, 3 ]
    }
]

output [
   {
      name: "yolo_nms_0"
      data_type: TYPE_FP32
      dims: [ 100, 4 ]
      label_filename: "labels.txt"
   },
   {
      name: "yolo_nms_1"
      data_type: TYPE_FP32
      dims: [ 100 ]
      label_filename: "labels.txt"
   },
   {
      name: "yolo_nms_2"
      data_type: TYPE_FP32
      dims: [ 100 ]
      label_filename: "labels.txt"
   },
   {
      name: "yolo_nms_3"
      data_type: TYPE_INT8
      dims: [-1 ]
   }

]
```
But when i server model using tensorrt inference server. i got error: 
E0602 10:52:59.510099 1 retrier.cc:37] Loading servable: {name: vehicle-detection ve
rsion: 1} failed: Invalid argument: unable to load model 'vehicle-detection', output
 'yolo_nms_3' dims [-1] don't match configuration dims [-1]                         

How can i solve this problem?

**Comment by bezero** [comment]
@tienduchoang  I think it should be:
```
{
  name: "yolo_nms_3"
  data_type: TYPE_INT8
  dims: [ 1 ]
 }
```

**Comment by tienduchoang** [comment]
@bezero i also try this. but i got the same error: 
```
E0602 11:31:50.221376 1 aspired_versions_manager.cc:358] Servable {name: vehicle-det
ection version: 1} cannot be loaded: Invalid argument: unable to load model 'vehicle
-detection', output 'yolo_nms_3' dims [-1] don't match configuration dims [1]       
```
when i use flags: --strict-model-config=false. i got error below:
```
E0602 11:33:25.691332 1 aspired_versions_manager.cc:358] Servable {name: vehicle-det
ection version: 1} cannot be loaded: Invalid argument: model output must specify 'di
ms'
```

**Comment by GuanLuo** [comment]
It seems like 'yolo_nms_3' only has batch dimension, what if you add reshape to 'yolo_nms_3' so that it looks like:
```
{
  name: "yolo_nms_3"
  data_type: TYPE_INT8
  dims: [ 1 ]
  reshape: { shape: [] }
 }
```

**Comment by tienduchoang** [comment]
hello @GuanLuo   thank for your help. now, i can serve my model. but i got this error: 
```
2019-06-04 02:58:55.785173: W external/org_tensorflow/tensorflow/core/kernels/partitioned_function_ops.cc:197] Grappler optimization failed. Error: Op type not registered 'CombinedNonMaxSuppression' in bi
nary running on 1984ec4fe5aa. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) 
`tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
2019-06-04 02:58:55.806209: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at partitioned_function_ops.cc:118 : Not found: Op type not registered 'CombinedNonMax
Suppression' in binary running on 1984ec4fe5aa. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib,
 accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```
So, Do you know why?

**Comment by GuanLuo** [comment]
Is "CombinedNonMaxSuppression" being added recently in TensorFlow? From [here](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/core/ops/ops.pbtxt) it seems like it is added in r1.14. So maybe the TRTIS you are using is linked with an older version of TensorFlow.

**Comment by tienduchoang** [comment]
i already update my trtis to 19.05. but got the same error. Is that mean i cannot server my model using trtis?

**Comment by GuanLuo** [comment]
For 19.05, it is likely to be the case. However, there is a pending PR #333 that decouples TF build from TRTIS build, with this change, you should be able to modify the Dockerfile to use the TensorFlow version that is proper for your model.

**Comment by tienduchoang** [comment]
So, That mean i need to wait for next trtis version. 
Thanks for your enthusiasm

**Comment by deadeyegoodwin** [comment]
The current 19.05 release uses TensorFlow 1.13.1 and it looks like the upcoming 19.06 release also uses Tensorflow 1.13.1. So you likely need to wait until 19.07 to get TensorFlow 1.14 support. As @GuanLuo mentioned an alternative is to use the master branch which now has a cmake-based build where you can build your own version of TensorFlow and use it in the TRTIS build. The online docs have not yet been updated with the new instructions but you can find them here: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/docs/build.rst

If you decide to try the cmake build yourself be sure to let us know if you run into difficulties.
