### ISSUE TITLE
is_training/keep_prob tensor with 19.05

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/tensorrt-inference-server#326]
I tried my model again with 19.04 and 19.05. Different settings were made when I generate the tf savedmodel.  The cases are as below:

- case 1, Reshape is_training tensor and keep_prob tensor using tf.reshape to [-1,1], the /api/status shows the model is available. I try to access the server, it returns "You must feed a value for placeholder tensor 'keep_prob with dtype float'".

- case 2, No reshape operation for is_training and keep_prob. The trtis stopped and returned "model input cannot have empty reshape for non-batching model". This case is like the title which using 19.03.

- case 3, Reshape is_training tensor and keep_prob tensor to [1,], th /api/status shows the model is available but the input tensor for picture data has a dim of -1. I tried to access the server, it returns "model supports variable size for input 'input', request must specify input shape for model".

- case 4,Remove the keep_prob and is_training when I define the signature. The /api/status shows the model is available. I tried to access the server, it returns "You must feed a value for placeholder tensor 'keep_prob with dtype float'".

@deadeyegoodwin 

> ,
The problem seems to be that your model requires "reshape" which is available in 19.04 but the autofill (--strict-model-config=false) support for reshape was not added until 19.05.

I don't know what you mean about the autofill (--strict-model-config=false) support for reshape was not added until 19.05.  Do you mean use tf.reshape when generate the savedmodel ? 
It seems like some improvement was made in the latest release because I can deployment my models in a health status, but I never access it successfully. The case 1 3 4 both tell me the model is available but bad responses they were made. So I have two question to ask:

1. Does the server must be accessible when the /api/status show the model ready ?
2. If question 1's answer is yes. I want to have a further discuss with my code of accessing the server. If question 1's answer is no. I want to figure out what to do to make my server really available.

_Originally posted by @ligonzheng in https://github.com/NVIDIA/tensorrt-inference-server/issues/294#issuecomment-498167667_

**Comment by GuanLuo** [comment]
Yes. And actually, the server has its own server state and it is shown at the end of the `/api/status` response.

Are you using the same config.pbtxt for all 4 cases? And what is the client code you use to access the server?

**Comment by ligonzheng** [comment]
@GuanLuo I use autofill(--strict-model-config=false) for all 4 cases. This is my python client code:
`import requests,struct
from PIL import Image
import numpy as np
import struct
WIDTH  = 299
HEIGHT = 299
def ImageToMatrix(filePath):
    img = Image.open(filePath)
    img = img.convert('RGB')
    width, height = img.size
    if (width != WIDTH or height != HEIGHT):
        print("image size is not equal to 299*299,then will resize it")
        img = img.resize((WIDTH,HEIGHT),Image.BILINEAR)
    data = np.array(img,dtype='float32')/255.0
    return data

data = ImageToMatrix("image.jpg").tobytes()

keep_prob = 1.0
data = data + struct.pack('f',keep_prob)
is_training = False
data = data + struct.pack('?',is_training)

headers = {'content-type':'application/octet-stream','NV-InferRequest': 'batch_size: 1 input { name: \'input\'} input {name: \'keep_prob\' } input{name: \'is_training\'} output { name: \'output\' cls { count: 3 }}'}

ret = requests.post("http://127.0.0.1:8000/api/infer/inception_new",data=data,headers=headers)
print(ret)`

Is there any problem with my client code ?

**Comment by ligonzheng** [comment]
I use autofill(--strict-model-config=false) for my 4 cases.
I think the key is the way the trtis works. Firstly, trtis does not support a input without dim message now. Something like is_training and keep_prob is defined in tensorflow using tf.placeholder with the shape unknown. So  the trtis need to convert the shape message from unknown to dim [1,], then using reshape  to make the shape back to None.
 Another thing need to mention, controlling input which will not has a batch dim even in a model supported batching should be removed or covered from the savedmodel's signature. No good solution to find except  rewriting the graph for me. Using placeholder_with_default or cut those nodes off from the graph are the only ways found.   
@GuanLuo , is there anything wrong with my summary ? 
Actually, I hope there is another method to deal with point 2. Because rewriting the graph is not a graceful solution.

**Comment by GuanLuo** [comment]
Right, the inference server doesn't recognize tensors that only have batch dimension, and that is the reason why reshape is introduced to convert such tensors from shape recognized by the server to its actual shape.

And the other point you mentioned is also true, currently the server can't handle control input that is "global" (which doesn't have batch dimension). That is because we believe the concurrency and hardware utilization can increase if we can group multiple requests as one single larger batch so that one execution of the model can fulfill all requests (dynamic batcher), and a "global" control input will raise the concern on which request should be in charge of setting the value.

Regarding your concern, I am afraid there is no immediate solution other than modifying the graph. I am curious about what is your intended use of the global control input? It is going to be set to a fix value when you serve it or you want to be able to change the value at any given moment?

**Comment by GuanLuo** [comment]
@ligonzheng After a discussion with @deadeyegoodwin, what you can try is to provide a config.pbtxt that sets the max_batch_size to be 0 and specify your inputs / outputs with full shape (i.e. including batch dimension if any). With this, each request sent to your model should have the proper shapes for the inputs.

<details><summary>example config.pbtxt</summary><p>

```
...
max_batch_size: 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [ -1, 299, 299, 3]
  },
  {
    name: "keep_prob"
    data_type: TYPE_FP32
    dims: [ -1 ]
  },
  {
    name: "is_training"
    data_type: TYPE_BOOL
    dims: [ -1 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ -1, 5 ]
  }
]
```
</p></details>

**Comment by ligonzheng** [comment]
Really thank you for your reply !
I pay much attention to control input because I know tensorflow server can deal with it which has a column and row ways and I always deploy my server with the model supplied by others which means sometimes I have no right to modify the graph.

I tried your config, it returned me : 
Failed to poll model repository: 1 model(s) did not become available: {{{name: inception_new version: 1} due to error: Internal: unable to load model 'inception_new', tensor 'keep_prob' shape expected by framework [] doesn't match model configuration shape [-1]},
But it does not matter.At least I know the right way to solve my problem Even it not graceful as I thought.

**Comment by GuanLuo** [comment]
The error message you got is strange, it said the framework is expecting empty shape. I wonder if you kept the autofill on (`--strict-model-config=false`) even though you were providing the config.pbtxt file?

And I also wonder if you are comfortable to share the model you are using, so that we can investigate further if the server is able to inspect arbitrary models in a proper way.

**Comment by ligonzheng** [comment]
My model is there: 
[10.240.131.4:9000](url)

**Comment by ligonzheng** [comment]
This is my model:
https://drive.google.com/open?id=1ekEFvAPlbh_IfbvodI1x4IbgY11SiyC3
Thank you.

**Comment by GuanLuo** [comment]
Thanks for sharing the model, just want to double check with my earlier comment:

> Failed to poll model repository: 1 model(s) did not become available: {{{name: inception_new version: 1} due to error: Internal: unable to load model 'inception_new', tensor 'keep_prob' shape expected by framework [] doesn't match model configuration shape [-1]}

Did you turn on autofill (`--strict-model-config=false`) when you received this error message? If so, does the error message disappear if you provide the config.pbtxt file while autofill is off?

**Comment by ligonzheng** [comment]
This is the result when I turn on autofill and with a config.pbtxt inside:
2019-06-11 01:35:17.811899: E external/tf_serving/tensorflow_serving/core/aspired_versions_manager.cc:358] Servable {name: inception_new version: 1} cannot be loaded: Internal: unable to load model 'inception_new', tensor 'input' shape expected by framework [299,299,3] doesn't match model configuration shape [-1,299,299,3]
This is my result when I turn off autofill:
2019-06-11 01:38:10.677822: E external/tf_serving/tensorflow_serving/core/aspired_versions_manager.cc:358] Servable {name: inception_new version: 1} cannot be loaded: Internal: unable to load model 'inception_new', tensor 'keep_prob' shape expected by framework [1] doesn't match model configuration shape [-1]
The result of turning on autofill without config.pbtxt seems like OK, but when I try to access, I get a response 400. 
The error message is : "You must feed a value for placeholder tensor \\\'keep_prob\\\' with dtype float\\n\\t [[{{node keep_prob}}]]\\n\\t [[{{node InceptionV3/Predictions/Softmax}}]]" server_id: "inference:0" request_id: 3', 'Content-Type': 'application/octet-stream', 'Content-Length': '0'.
My client code is there:

[main_inception.txt](https://github.com/NVIDIA/tensorrt-inference-server/files/3274484/main_inception.txt)

**Comment by ligonzheng** [comment]
Actually, I don't think there is necessary to discuss the way I deploy this model because I tried many cases including autofill , different config files , different ways to generate savedmodel. I am sure no way was work except modify the predict graph using remove this kind of controlling nodes or resize this kind of nodes or using placeholder_with_default instead of placeholder. The key is to analyse how to make this kind of model work without modify graph. 
Here we assume the graph has a inputs/outputs like:
[
    input1:[-1,299,299,3]
    input2:unknown   
    output1:[-1,5]
]
The input2's shape is unknown because it's a scale which always means controlling input.
The final config using by trtis no matter in autofill mode or not is like:
max_batch_size: 0
input [
{
name: "input0"
data_type: TYPE_FP32
dims: [-1,299,299,3]
},
{
name: "input1"
data_type: TYPE_FP32
dims: [1]
reshape:{shape:[]}
},
]
output [
{
name: "output"
data_type: TYPE_FP32
dims: [-1,5]
}
But an error I can not avoid is : "model input cannot have empty reshape for non-batching model for inception_new".
So the key is the usage of reshape. In my primary assumption, I can use the reshape to make the shape change from [1] to [] which would distinguish by tensorflow. But the result tells me it's not simple.
What does reshape really mean ? If I reshape [1] to [], the [] means no shape or no data ? How should I make trtis knows this is a scale in non-batching model ?

**Comment by GuanLuo** [comment]
Regarding the error message you mentioned in the earlier comment: "You must feed a value for placeholder tensor \'keep_prob\' with dtype float\n\t [[{{node keep_prob}}]]\n\t [[{{node InceptionV3/Predictions/Softmax}}]]"

It is error coming from running the saved model, so I tried to see if I could run the model directly using TensorFlow, and I received the same error. Could you take a look on my code snippet below and see if I have done something wrong?

```Python
import tensorflow as tf
export_dir = "/data/one_model/inception_new/1/model.savedmodel/"
# Using helper function you provided
data = ImageToMatrix("/data/mug.jpg")

sess = tf.Session(graph=tf.Graph())
tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], export_dir)
# Using the Tensor names
output_tensor = sess.graph.get_tensor_by_name("InceptionV3/Predictions/Softmax:0")
predictions, = sess.run(output_tensor, {"input:0" : [data], "Reshape_2:0": np.zeros(shape=1, dtype=np.bool), "Reshape_3:0": np.ones(shape=(1,), dtype=np.float32)})
````
Exception received:
```Python
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'keep_prob' with dtype float
	 [[{{node keep_prob}}]]
	 [[{{node InceptionV3/Predictions/Softmax}}]]
```

**Comment by ligonzheng** [comment]
So sorry I pass a wrong message for you !
I had figure it out why I got this kind of error of feeding a value. I try to reshape my input tensor after  import_meta_graph which will not really have an affect on original graph but construct a fake input.
I updated my model which no fake input was constructed.
https://drive.google.com/open?id=1kvCd8sSIh1YFBrGs9dr5stvnmCR_uTJo
All cases I had tried indicated me a conclusion posted in my last comment. I think this would be my last question of this issue.

**Comment by GuanLuo** [comment]
@ligonzheng The updated files still give me the same error...

Regarding your last comment
> What does reshape really mean ? If I reshape [1] to [], the [] means no shape or no data ? How should I make trtis knows this is a scale in non-batching model ?

As you mentioned, reshape [1] to [] will not have any actual meaning if there is no batch dimension, to [] is for the tensor shape that is expected as [ batch size ] by the underlying framework. That's why you receive the error when you tried to do so on non-batching model.

And I am confused about "the input2's shape is unknown because it's a scale which always means controlling input". You should be able to get shape and data type of an input from the model's signature_def and use it in your config.pbtxt file (which is how we verify if the config.pbtxt is accurate). If there is no information about the input shape and type, how do you run the model even without TRTIS?

**Comment by ligonzheng** [comment]
If I have the tensorflow code as blow:
import tensorflow as tf
a = tf.placeholder(tf.float32)
print(a.get_shape())

It will print 'unknown'
That why input2's shape is unknown.
