### ISSUE TITLE
ppc64le, TensorRT Inference Server Release 19.05

### ISSUE THREAD

**Issue by Eloring** [NVIDIA/tensorrt-inference-server#331]
Can the docker container  TensorRT Inference Server run on ppc64le (Power 8)?

The image nvcr.io/nvidia/tensorrtserver:19.05-py3 was pulled, however when I run the container, I got the error:

 _standard_init_linux.go:190: exec user process caused "exec format error"_

**Comment by deadeyegoodwin** [comment]
Currently we only have pre-build docker images for x86. Very soon now master will be moving to a CMake-based build and then it should be easier to port to power. Keep an eye out for the CMake announcement and then it should be possible to try building TRTIS on power.
