### ISSUE TITLE
how do i calculate the overlap of two class?

### ISSUE THREAD

**Issue by wanghetongtt** [NVIDIA/tensorrt-inference-server#352]
this is very important to me!!
i want to count the overlap of two classes, if the overlap is big (Say 50%) i want to label the larger box as a new class.
anyone help plz!

**Comment by deadeyegoodwin** [comment]
I'm not sure what you mean by "overlap of two classes". TRTIS returns the raw output tensors from your model, any post-processing must be performed by the client (or by a custom backend that you provide). The classification output that TRTIS can optionally return is just simple labels (like you would find in image classification models).
