### ISSUE TITLE
On demand Polling

### ISSUE THREAD

**Issue by allenc97** [NVIDIA/tensorrt-inference-server#356]
Hi, I was wondering if there are plans to support on demand polling in the future. We currently use TRTIS by mounting Azure file shares. The problem is that TRT will often poll and recognize changes to the model repository before the entire model.graphdef is fully copied, resulting in it trying to load an incomplete model, which will cause the server to complain and shutdown. If it were possible to poll on demand through an HTTP API, that would greatly help with the above situation.

**Comment by GuanLuo** [comment]
An experimental feature is added recently which allows user to load / unload a model via [model control API endpoints](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_management.html#model-control-mode-explicit)
