### ISSUE TITLE
TRTIS stops serving all models when uploading a new model

### ISSUE THREAD

**Issue by achbogga** [NVIDIA/tensorrt-inference-server#363]
The server crashes/stops serving all the models while a new model is being uploaded to the server. Part of the reason might be the server detects a new model change even before the full upload is complete, and fails to parse the part model file. This, however, should not result in a crash/stop to serving all the other models which are already there being served.

Please let me know how to fix this issue. Thanks.
@deadeyegoodwin

**Comment by deadeyegoodwin** [comment]
Yes, that doesn't sound like the right behavior. We'll have a look.

**Comment by whataride** [comment]
Do we have an update? Looks like it is still happening.

**Comment by deadeyegoodwin** [comment]
Can you provide detailed repro steps.

**Comment by whataride** [comment]
@deadeyegoodwin I appologize. It seems that the problem goes away now. We will report if we encounter it again. You can close the issue.
