### ISSUE TITLE
How the tensorflow savedmodel worked in TRTIS?

### ISSUE THREAD

**Issue by ivankxt** [NVIDIA/tensorrt-inference-server#37]
Our tensorflow savedmodel exported by tf.saved_model.simple_save method and its contains the following files:
1/
    saved_model.pb
    variables

When we run the tensorflow savedmodel by TRTIS, we get the error as:
tensorrtserver.api.InferenceServerException: [inference:0 4] Attempting to use uninitialized value w1

So, how the  tensorflow savedmodel (include variables file) worked in TRTIS?

Could you give me some explanation for that? Thank you.

**Comment by ivankxt** [comment]
> Not sure what that error means. But if you were sending the model repo version directory in your message then it is incorrect. Take a look here to see how the model repo needs to be set up for saved model: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_repository.html#tensorflow-models

For the savedmodel repo as:
models/
  <model-name>/
    config.pbtxt
    1/
      model.savedmodel/
         <saved-model files>

I want to know which files are included in <saved-model files>？

**Comment by deadeyegoodwin** [comment]
When you save in saved-model format it creates a directory which contains a couple of files (a protobuf file and one or more files containing variable values (weights, biases, etc.)). Those files should be put into model.savedmodel.

**Comment by ivankxt** [comment]
> When you save in saved-model format it creates a directory which contains a couple of files (a protobuf file and one or more files containing variable values (weights, biases, etc.)). Those files should be put into model.savedmodel.

Our savedmodel repo is:
models/
    config.pbtxt
    1/
         model.savedmodel/
               saved_model.pb
               variables

However, we get the error as:
tensorrtserver.api.InferenceServerException: [inference:0 4] Attempting to use uninitialized value w1,

here 'w1' is defined in python file like:
w1 = tf.get_variable("w1", shape=[1000,hidden_size], initializer = tf.ones_initializer)

So, I suspect that the directory of variables in model.savedmodel does not work.

Could you give me some examples for how to run tensorflow savedmodel (include variables) in TRTIS?

**Comment by deadeyegoodwin** [comment]
Did you run the global initializer before saving your model?

with tf.Session() as sess:
  sess.run(tf.initializers.global_variables())
  ...
  tf.saved_model.simple_save(sess, ...

**Comment by ivankxt** [comment]
> Did you run the global initializer before saving your model?
> 
> with tf.Session() as sess:
> sess.run(tf.initializers.global_variables())
> ...
> tf.saved_model.simple_save(sess, ...

I have try, but it doesn't work.

**Comment by ankitshah009** [comment]
Any solution to how to use the saved model after saving it with TensorRT? 
I am also hitting the same error.
