### ISSUE TITLE
[feature request] Publish Python Client Library to PyPi

### ISSUE THREAD

**Issue by gaocegege** [NVIDIA/tensorrt-inference-server#384]
Now we have to build the client library and setup it if we want to install the python library locally. Is it possible to publish the client library `tensorrtserver` to PyPi to simplify the installation of client library?

**Comment by deadeyegoodwin** [comment]
You can build the client library yourself as described in the documentation and we also include the wheel file in each release in the client *.tar.gz. https://github.com/NVIDIA/tensorrt-inference-server/releases

The python is 2 and 3 compatible but it is not 100% python... it contains a shared library that will only sort on specific platform (the release currently contains Ubuntu 16.04 and Ubuntu 18.04 versions).

**Comment by deadeyegoodwin** [comment]
See also https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/client.html#download-from-github
