### ISSUE TITLE
curl example for simple-server

### ISSUE THREAD

**Issue by rakelkar** [NVIDIA/tensorrt-inference-server#385]
Is there an example that uses curl instead of the published clients? I guess I could reverse engineer the payload since the C++ client uses the curl lib, just wondering if this is already available somewhere?

This is for KFServing TensorRT example:
https://github.com/kubeflow/kfserving/issues/163
https://github.com/kubeflow/kfserving/pull/134

**Comment by deadeyegoodwin** [comment]
The "raw" http API for the server is documented here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/http_grpc_api.html#inference-server-api

See also #280.
