### ISSUE TITLE
Support specifying host header in example clients

### ISSUE THREAD

**Issue by rakelkar** [NVIDIA/tensorrt-inference-server#386]
It is difficult to use the example clients with a Kubeflow KFServing set up since KFServing creates routes based on host name. To get this to work one has to edit etc/hosts with a mapping. Would be nice if we could pass the host name (or better additional headers) via a command line option.

For context see README.md in https://github.com/kubeflow/kfserving/pull/134

**Comment by deadeyegoodwin** [comment]
What example are you trying to run? Most examples have a -u  option where you can specify any URL you want (defaults to localhost:8000).

**Comment by rakelkar** [comment]
Yes am using -u to specify the URL.. the issue is that the hostname is not real, so need to put ingress IP address in URL and pass host header for istio routing to work..

**Comment by deadeyegoodwin** [comment]
So you need an option in the client library to explicitly specify a host name? That is something we should be able to add. Marking as enhancement.

**Comment by rakelkar** [comment]
Yes. To effectively achieve this:
curl -v -H "Host: ${SERVICE_HOSTNAME}" http://$CLUSTER_IP/v1/models/$MODEL_NAME:predict -d $INPUT_PATH

**Comment by rakelkar** [comment]
(but using your client)

**Comment by deadeyegoodwin** [comment]
Fixed with #417 and #419
