### ISSUE TITLE
Cannot deserialize plugin RPROI_TRT

### ISSUE THREAD

**Issue by daemon11** [NVIDIA/tensorrt-inference-server#40]
I0111 07:26:47.327792 1 server.cc:701] Initializing TensorRT Inference Server
I0111 07:26:47.327845 1 server.cc:751] Reporting prometheus metrics on port 8002
I0111 07:26:47.328767 1 metrics.cc:148] found 1 GPUs supporting NVML metrics
I0111 07:26:47.334173 1 metrics.cc:158]   GPU 0: GeForce GTX 1080 Ti
I0111 07:26:47.334408 1 server.cc:1121] Starting server 'inference:0' listening on
I0111 07:26:47.334416 1 server.cc:1125]  localhost:8001 for gRPC requests
I0111 07:26:47.334676 1 server.cc:1029] Building nvrpc server
I0111 07:26:47.334689 1 server.cc:1035] Register TensorRT GRPCService
I0111 07:26:47.334695 1 server.cc:1038] Register Infer RPC
I0111 07:26:47.334702 1 server.cc:1042] Register Status RPC
I0111 07:26:47.334706 1 server.cc:1046] Register Profile RPC
I0111 07:26:47.334709 1 server.cc:1050] Register Health RPC
I0111 07:26:47.334713 1 server.cc:1054] Register Executor
I0111 07:26:47.335855 1 server.cc:1135]  localhost:8000 for HTTP requests
[warn] getaddrinfo: address family for nodename not supported
[evhttp_server.cc : 237] RAW: Entering the event loop ...
I0111 07:26:48.090098 1 logging.cc:49] Glob Size is 638866496 bytes.
I0111 07:26:48.162693 1 logging.cc:49] Added linear block of size 96000000
I0111 07:26:48.162704 1 logging.cc:49] Added linear block of size 96000000
I0111 07:26:48.162707 1 logging.cc:49] Added linear block of size 12032000
I0111 07:26:48.162726 1 logging.cc:49] Added linear block of size 221184
I0111 07:26:48.162729 1 logging.cc:49] Added linear block of size 110592
E0111 07:26:48.166348 1 logging.cc:43] getPluginCreator could not find plugin RPROI_TRT version 1 namespace 
E0111 07:26:48.166355 1 logging.cc:43] Cannot deserialize plugin RPROI_TRT

Could you help me? Thank you.

**Comment by deadeyegoodwin** [comment]
It looks like the TRT model you are using requires a custom plugin. Please vote (with a thumbs-up on the initial comment) in issue #16 if that feature is important to you.
If you want to try modifying TRTIS yourself, look in plan_bundle.cc and you should see where the ONNX plugins are currently be loading any you can instead load the plugins you require for the model (this is just a work-around, not a full solution... but will work for the case where you have a single model that requires TRT plugins).
