### ISSUE TITLE
Config proto formatting

### ISSUE THREAD

**Issue by philnguyenresson** [NVIDIA/tensorrt-inference-server#409]
Hi, I'm generating the config.pbtxt for my file using the model_config.proto, but the format seems slightly off.   
```
import model_config_pb2
model_config = model_config_pb2.ModelConfig()
```
(filling model_config here)
```
with open(config_pbtxt_path, "w") as f:
    f.write(text_format.MessageToString(model_config,
                                        use_short_repeated_primitives=True,
                                        ))
```
Here is an example:
```
name: "model_name"
platform: "tensorflow_graphdef"
max_batch_size: 135
input {
  name: "image_tensor_x"
  data_type: TYPE_FP32
  format: FORMAT_NHWC
  dims: [225, 225, 3]
}
output {
  name: "resnet50/fc1000/Softmax"
  data_type: TYPE_FP32
  dims: [6]
}
```
The expected config.pbtxt format requires the input and output to formatted as a list, for example:
```
input [
{
  name: "image_tensor_x"
  data_type: TYPE_FP32
  format: FORMAT_NHWC
  dims: [ 225, 225, 3 ]
}
]
```
So  if you have multiple inputs in my config it will create another input block, whereas in the expected format, you'll be appending another dict {} in the input brackets [].

Any ideas on why my MessageToString is coming out this way?

**Comment by GuanLuo** [comment]
Both format is acceptable, perhaps expanding [] to individual elements is how protobuf represents list internally. For instance, you can even specify the dim list: `dims: [ 225, 225, 3]` to be
```
dims: 225
dims: 225
dims: 3
```

**Comment by philnguyenresson** [comment]
Thanks, it does work in both formats
