### ISSUE TITLE
Arbitrary metadata with models

### ISSUE THREAD

**Issue by nieksand** [NVIDIA/tensorrt-inference-server#439]
Feature request:

I wish I could store arbitrary (text) metadata with each model in the TRTIS model repo and then query it via some API endpoint.

---

Right now, I must manage two different configurations:

1. The TRTIS model repository with its config.pbtxt files
2. A model inference frontend whose configuration specifies how to pull imagery inputs, prepare the data for inference (normalization, center crop, etc), invoke TRTIS, and reformat outputs.

![TRTIS Metadata](https://user-images.githubusercontent.com/1396037/60877700-a0259380-a23e-11e9-9505-f0ed8bf8f582.png)

This works fine for production where we carefully curate which models are served via TRTIS and craft a front-end config file accordingly.

However, when working with internal R&D teams, we toss lots of in-development models back and forth.  Ensuring the front-end config file is in-sync with local TRTIS instances becomes an obnoxious extra step.

With a meta data endpoint in TRTIS...
* Our front-end configuration file would go away entirely.
* TRTIS becomes the authoritative source of truth for all the models it serves.  
* Our front-end would query TRTIS for a list of available models and pull the additional configuration it needs from TRTIS's per-model metadata.

Another potential use-case for such a meta data feature would be tracking data provenance which is handy for both reproducibility and compliance.

**Comment by deadeyegoodwin** [comment]
Take a look at model configuration parameters: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/model_config.proto#L790

Currently we only support a parameter with a string value but we have plans to extend that to other datatypes in the future. For your use case it sounds like string should be enough.

The parameters should be included in the information returned via the status API.

**Comment by nieksand** [comment]
Thank you!  That's absolutely perfect.

In case anybody stumbles across this ticket needing the same thing, here is a sample snippet for config.pbtxt:
```
parameters {
    key: "cfg"
    value: { string_value: "this is some super insightful metadata!" }
}
```

This ticket can be closed I think.
