### ISSUE TITLE
the TRTIS can not load the trt model

### ISSUE THREAD

**Issue by pwlazy** [NVIDIA/tensorrt-inference-server#44]
I have successfully converted the frozen graphs(     https://storage.googleapis.com/download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz) into uff by the script convert_to_uff in the docker container(nvcr.io/nvidia/tensorflow:18.11-py3[cuda10+cudnn7.4.1+TensorRT5])

i run inference by loading the uff with the TensorRT sample code, it's ok!

but when I run inference in TRTIS,  i start TRTIS by starting the docker image(nvcr.io/nvidia/tensorrtserver:18.11-py3[cuda10+cudnn7.4.1]), 

I get the error: 
"Assertion `size >= bsize && "Mismatch between allocated memory size and expected size of serialized engine."

my model_repository is as below
plan_model/
├── 1
│   └── model.plan
├── config.pbtxt
└── inception_labels.txt

model.plan is the converted uff file,
config.pbxt is
`name: "plan_model"
platform: "tensorrt_plan"
max_batch_size: 1
input [
  {
    name: "input"
    data_type: TYPE_FP32
    ####format: FORMAT_NHWC
    dims: [ 299, 299, 3 ]
  }
]
output [
  {
    name: "InceptionV3/Predictions/Reshape_1"
    data_type: TYPE_FP32
    dims: [ 1001 ]
    label_filename: "inception_labels.txt"
  }
]
instance_group [
  {
    kind: KIND_GPU,
    count: 1
  }
]`

and GPU is the p100

**Comment by deadeyegoodwin** [comment]
The UFF file itself is not a TRT plan. You need to import the UFF file into TRT and from that generate a plan. You can then use that plan file in your model store. I think this sample shows what you are trying to do: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#mnist_uff_sample

**Comment by pwlazy** [comment]
thanks! it works by serializing the engine

**Comment by ivankxt** [comment]
> The UFF file itself is not a TRT plan. You need to import the UFF file into TRT and from that generate a plan. You can then use that plan file in your model store. I think this sample shows what you are trying to do: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#mnist_uff_sample

We got the error when transforming UFF File to TensorRT Engine:
"[TensorRT] ERROR: UFFParser: Parser error: add: The input to the Scale Layer is required to have a minimum of 3 dimensions."
our model details as:
input nodes ==:
[name: "Placeholder"
op: "Placeholder"
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
        dim {
          size: 1000
        }
      }
    }
  }
}

output nodes ==:
[name: "add"
op: "Add"
input: "MatMul_2"
input: "b"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}
attr {
  key: "_output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
        dim {
          size: 2
        }
      }
    }
  }
}
]

**Comment by deadeyegoodwin** [comment]
UFF expects tensors in the network to be 3D. There will be some documentation on this limitation in the (future) 5.1 release of TensorRT.
