### ISSUE TITLE
must map ensemble input INPUT for ensemble ensemble_model

### ISSUE THREAD

**Issue by clancylian** [NVIDIA/tensorrt-inference-server#446]
I use ensemble model but it occur error:
`E0711 07:12:09.249525 1 server.cc:294] must map ensemble input INPUT for ensemble ensemble_model` , in code version r19.04

ensemble config

> name: "ensemble_model"
platform: "ensemble"
max_batch_size: 32
input [
  {
    name: "INPUT"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 112, 112 ]
  }
]
output [
  {
    name: "Attribute"
    data_type: TYPE_FP32
    dims: [ 113, 1, 1 ]
  },
  {
    name: "Recognition"
    data_type: TYPE_FP32
    dims: [ 512, 1, 1 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "attributes_plan"
      input_map {
        key: "blob1"
        value: "INPUT"
      }
      output_map {
        key: "cat_blob1"
        value: "Attribute"
      }
    },
    {
      model_name: "insight_plan"
      input_map {
        key: "data"
        value: "INPUT"
      }
      output_map {
        key: "fc1"
        value: "Recognition"
      }
    }
  ]
}

model 1 config:

> name: "attributes_plan"
platform: "tensorrt_plan"
max_batch_size: 32
input [
  {
    name: "blob1"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 112, 112 ]
  }
]
output [
  {
    name: "cat_blob1"
    data_type: TYPE_FP32
    dims: [ 113, 1, 1 ]
  }
]
cc_model_filenames [
   {
      key: "6.1"
      value: "attributes_6_1.plan"
   }
]
instance_group [
  {
    count: 1
    gpus: [ 0 ]
  }
]
dynamic_batching {
    preferred_batch_size: [ 16, 32 ]
    max_queue_delay_microseconds: 20000
}
optimization{
    graph{
        level:9
    }
}

model 2 config:

> name: "insight_plan"
platform: "tensorrt_plan"
max_batch_size: 32
input [
  {
    name: "data"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 112, 112 ]
  }
]
output [
  {
    name: "fc1"
    data_type: TYPE_FP32
    dims: [ 512, 1, 1 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
dynamic_batching {
	preferred_batch_size: [ 16, 32 ]
	max_queue_delay_microseconds: 10000
}
optimization{
	graph{
		level:9
	}
}

**Comment by GuanLuo** [comment]
Ensemble was under development in 19.04 (official release in 19.05) and thus the usage is a bit different. In 19.04, the <key, value> pair of input map is <ensemble tensor name, model input name>. However, you should use TRTIS version >= 19.05 as the ensemble wasn't fully implemented in 19.04.
