### ISSUE TITLE
run tensorrtserver_client  on centos

### ISSUE THREAD

**Issue by diligent321** [NVIDIA/tensorrt-inference-server#452]
Hi,

as https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/client.html#performance-example-application shows, the client library and samples are installed on ubuntu system. But my servers are all centos system, so how to compile from source to send a http client on centos

@deadeyegoodwin

**Comment by diligent321** [comment]
thanks, i solved it.

**Comment by aleksa2808** [comment]
Hey @diligent321, can you share how you managed to build the clients on centos in the end?
