### ISSUE TITLE
1.3.0 documentation doesn't mention removal of GCS support

### ISSUE THREAD

**Issue by jobegrabber** [NVIDIA/tensorrt-inference-server#453]
1.3.0 dropped support for model repositories backed by Google Cloud Storage.
This is undocumented and misled at least myself (https://github.com/NVIDIA/tensorrt-inference-server/issues/448).

This removal isn't mentioned in the [release notes](https://github.com/NVIDIA/tensorrt-inference-server/releases/tag/v1.3.0), nor in the [documentation](https://docs.nvidia.com/deeplearning/sdk/inference-server-archived/tensorrt_inference_server_130/tensorrt-inference-server-guide/docs/model_repository.html).

**Comment by deadeyegoodwin** [comment]
The github release notes and product release notes (https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-06.html#rel_19-06) have been updated to mention removal of GCS in 19.06.
