### ISSUE TITLE
ModelRepositoryManager doesn't fail on zero-prefixed version directories

### ISSUE THREAD

**Issue by jobegrabber** [NVIDIA/tensorrt-inference-server#454]
I'm currently testing out the master branch version on commit https://github.com/NVIDIA/tensorrt-inference-server/commit/216b0e59c1d8ad8a862dcc266e6abf35dcb11612 due to missing GCS support in 1.3.0 (see #453).

In the current state, model version directories (their names) are validated through [`std::stoll`](https://github.com/NVIDIA/tensorrt-inference-server/blob/da1f846b7ffdfdb4797b233a426fe1192f57a271/src/core/model_repository_manager.cc#L1104).
This allows names like `01` and `0099` to be successfully validated, leading to errors because only the integer representation of the names is used.

The model repository should either be able to handle zero-prefixed version numbers, or disallow their usage (which to me seems like a good practise to enforce).

**Comment by GuanLuo** [comment]
Fixed by #455
