### ISSUE TITLE
Is there a matrix of backend version ?

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/tensorrt-inference-server#469]
Hello,
    TRTIS uses other deep learning framwork such as tensorflow tensorrt. Is there a matrix table to show the specific version of each backend version ?

**Comment by nieksand** [comment]
The release notes mention versions: https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/index.html

e.g.:
```
    The inference server container image version 19.06 is based on NVIDIA TensorRT Inference Server 1.3.0, TensorFlow 1.13.1, ONNX Runtime 0.4.0, and Caffe2 0.8.2.
    Latest version of NVIDIA CUDA 10.1.168 including cuBLAS 10.2.0.168
```

**Comment by deadeyegoodwin** [comment]
There is also a full support matrix linked from the README page.
