### ISSUE TITLE
Encountered an error while loading tensorflow savedmodel

### ISSUE THREAD

**Issue by Whitessky** [NVIDIA/tensorrt-inference-server#47]
While TRTIS loading tensorflow savedmodel,an error occurred like this:
     `Loading servable: {name: road-tensorflow version: 1} failed: Not found: Op type not registered 'PyFunc' in binary running on efa5e12b876b. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
`
what did it mean and what should i do? thanks!

**Comment by deadeyegoodwin** [comment]
It looks like your model requires a custom tensorflow operation. That operation is implemented by wrapping a python function. See https://www.tensorflow.org/api_docs/python/tf/py_func.
Currently TRTIS does not support custom tensorflow operations. Only operations that are included in the tensorflow build are included. Can you implement the custom functionality using standard TF operations?
