### ISSUE TITLE
how to accelerate docker pull?

### ISSUE THREAD

**Issue by clancylian** [NVIDIA/tensorrt-inference-server#470]
Hi,
I wanted to build the server use dockerfile, ｂｕt it would pull three images.
ARG BASE_IMAGE=nvcr.io/nvidia/tensorrtserver:19.06-py3
ARG PYTORCH_IMAGE=nvcr.io/nvidia/pytorch:19.06-py3
ARG TENSORFLOW_IMAGE=nvcr.io/nvidia/tensorflow:19.06-py3

It was very slow, I have been downloading it almost a week, and everynight it will disconnect: read tcp 192.168.18.78:58764->52.219.28.28:443: read: connection reset by peer

What can I do with it, may I download from somewhere instead of use docker pull?

Thanks.

**Comment by nieksand** [comment]
Sounds like you have a terrible internet connection.  The Nvidia registry isn't super fast, but it definitely isn't an all-day affair to download images.

As an alternative, you could try pulling the images to a host with a better connection and then saving the images to disk:
https://docs.docker.com/engine/reference/commandline/save/

Transfer those files from that host to your computer.  (e.g. with USB stick).  Then load:
https://docs.docker.com/engine/reference/commandline/load/

**Comment by deadeyegoodwin** [comment]
@clancylian What geographic region are you in? Currently NGC registry doesn't have fast mirrors in all regions and so you may need to resort to techniques like those described by @nieksand .

**Comment by clancylian** [comment]
Hi,
Thanks.
