### ISSUE TITLE
How to migrate the preprocess and postprocess to the trt server?

### ISSUE THREAD

**Issue by diligent321** [NVIDIA/tensorrt-inference-server#471]
As the official documents introduced, the preprocess and postprocess part is running on the client end. But more generally, the postprocess steps may depend on some extra library, so it's inconvenient  to  config the environment for every client users.

so, is there a way to wrap the preprocess and postprocess part inside the trt server, or run the part on the server machine ?

**Comment by deadeyegoodwin** [comment]
The documents have an example that uses a custom backend for image preprocessing and ensembling to combine that backend with a RN50 model. Does that satisfy your requirement for combining pre/post processing with a model? https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/models_and_schedulers.html#ensemble-models

**Comment by diligent321** [comment]
Thanks, i'll look at this part.

**Comment by diligent321** [comment]
@deadeyegoodwin 
Hi,  a new question occured when i run the ensemble-models, so i reopen this issue.

for the ensemble sample, i follow the document https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/build.html#build-using-custom-backend-sdk, and build the libimagepreprocess.so normally.
Then, in order to start the tensorrt server in the consolei have to copy the files(including libimagepreprocess.so and its opencv relevant files) out of the docker image  tensorrtserver_cbe.

The question is, when i run the nvidia-docker comand, it raised the following error,
"E0724 01:59:48.880827 1 model_repository_manager.cc:761] failed to load 'image_preprocess_nchw_3x224x224_inception' version 1: Not found: unable to load custom library: libopencv_highgui.so.2.4: cannot open shared object file: No such file or directory"
howerver, if i run  ldd libimagepreprocess.so command, it print the following logs,
"ldd: warning: you do not have execution permission for `ensemble_model_repository_with_so/image_preprocess_nchw_3x224x224_inception/1/libimagepreprocess.so'
ensemble_model_repository_with_so/image_preprocess_nchw_3x224x224_inception/1/libimagepreprocess.so: /data/anaconda3/lib/libuuid.so.1: no version information available (required by /data/opencv_prebuilt/x86_64-linux-gnu-centos1/libSM.so.6)
        linux-vdso.so.1 (0x00007ffca8935000)
        libopencv_highgui.so.2.4 => /data//opencv_prebuilt/x86_64-linux-gnu-centos1/libopencv_highgui.so.2.4 (0x00007fb54bcb2000)
        libopencv_imgproc.so.2.4 => /data/opencv_prebuilt/x86_64-linux-gnu-centos1/libopencv_imgproc.so.2.4 (0x00007fb54b827000)"
so, why libopencv_highgui.so.2.4 not found when i start the ensemble model server?

besides, since the environment inside/outside of the docker image is different, is there a way to call the libimagepreprocess.so directly without cp out of the docker image?

**Comment by deadeyegoodwin** [comment]
The cusstom backend SDK is provided as a convenience to help with building custom backends... but you can build your custom backend however you want, inside or outside of a docker container.

However, when you put that custom backend in a model store and try to load it into TRTIS, you must have all the library dependencies required by the backend installed on the system. In this case it looks like you don't have libopencv_highgui.so.2.4 installed inside the docker image where you are running TRTIS. You can likely install it with: "apt-get install libopencv-highgui-dev"
