### ISSUE TITLE
Missing layout specification of serialized tensors in the inference API 

### ISSUE THREAD

**Issue by jobegrabber** [NVIDIA/tensorrt-inference-server#481]
The [documentation](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/http_grpc_api.html#section-api-inference) tells us in regards to the layout of serialized tensors that
>[t]he input tensor values are communicated in the body of the HTTP POST request as raw binary in the order as the inputs are listed in the request header.

There are client libraries for C++ and Python and examples are given how to use them. The client libraries perform the actual serialization.

The gRPC and HTTP APIs seem to be designed for general access and not limited to be accessed by the C++/Python client libraries.

To implement a client in, for example, Go the format specification of the input tensor is necessary.

As far as I can tell the input format is a flattened array of the tensor values (row-major)  with each value in its little-endian representation.
For strings the utf-8 representations of the strings are stored and each value is prefixed with its size as a 32 bit unsigned integer (little endian).

Could you confirm that the gRPC and HTTP APIs are meant to be public/generic interfaces as well as the layout of the serialized tensors?

**Comment by deadeyegoodwin** [comment]
The server APIs described in the documentation you link are officially supported APIs for TRTIS and so can be used directly. For the HTTP API I agree that the the documentation could be more detailed on the exact format of the tensor data. It would be a great contribution if you provided a PR with those updates.

For GRPC the formatting of the data will depend on what GRPC does. We do show an example of using the protoc generated GRPC API directly in https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/grpc_image_client.py. You could do something similar in any language supported by GRPC.

**Comment by jobegrabber** [comment]
Thanks for the fast reply!
I will try to come up with a PR for the doc and possibly a Golang example tomorrow or the day after.

**Comment by deadeyegoodwin** [comment]
Closing
