### ISSUE TITLE
Specify which port to expose services at

### ISSUE THREAD

**Issue by damitkwr** [NVIDIA/tensorrt-inference-server#483]
Hi,

Is it possible to specify which port to expose it at? For example, the default ports are 8000-8002. We have conflicting ports in our k8s deployment so is it possible to specify different ports to expose the services at? I know that I can map the container ports to a different port in docker but am not aware of such an option on k8s.

Please let me know if it would be possible to change the service ports on the TRTServer container.

Thanks!

**Comment by GuanLuo** [comment]
You can change the ports via the following options on starting TRTIS
```
--http-port	The port for the server to listen on for HTTP requests.
--http-health-port	The port for the server to listen on for HTTP Health requests.
--grpc-port	The port for the server to listen on for GRPC requests.
```
