### ISSUE TITLE
NVIDIA Quadro M1000M GPU not supported by tensorrtserver:18.12-py3

### ISSUE THREAD

**Issue by cc911** [NVIDIA/tensorrt-inference-server#49]
After running tensorrtserver:18.12-py3 Docker container, I get the following output which indicates that my video card (NVIDIA Quadro M1000M GPU) is not supported, even though this video card is listed here https://developer.nvidia.com/cuda-gpus as being a CUDA-enabled piece of hardware.

Some environment details:
nvidia-docker version: 2.0.3
NVIDIA-SMI version: 410.79
Driver version: 410.79
CUDA version: 10.0
cudnnGetVersion() : 7402 , CUDNN_VERSION from cudnn.h : 7402 (7.4.2)

`nvidia-docker run --rm --name trtserver -p 8000:8000 -p 8001:8001 \
-v /home/temp/tensorrt_models:/models nvcr.io/nvidia/tensorrtserver:18.12-py3 trtserver \
--model-store=/models`

Ouput:
===============================
== TensorRT Inference Server ==
===============================

NVIDIA Release 18.12 (build 880120)

Copyright (c) 2018, NVIDIA CORPORATION.  All rights reserved.
Copyright 2018 The TensorFlow Authors.  All rights reserved.
Copyright 2018 The TensorFlow Serving Authors.  All rights reserved.
Copyright (c) 2016-present, Facebook Inc. All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying
project or file.
ERROR: Detected NVIDIA Quadro M1000M GPU, which is not supported by this container
ERROR: No supported GPU(s) detected to run this container

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for the inference server.  NVIDIA recommends the use of the following flags:
   nvidia-docker run --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 ...

I0122 13:43:38.969179 1 server.cc:701] Initializing TensorRT Inference Server
I0122 13:43:38.969259 1 server.cc:751] Reporting prometheus metrics on port 8002
I0122 13:43:38.971350 1 metrics.cc:148] found 1 GPUs supporting NVML metrics
I0122 13:43:38.976922 1 metrics.cc:158]   GPU 0: Quadro M1000M
I0122 13:43:38.977711 1 server.cc:1121] Starting server 'inference:0' listening on
I0122 13:43:38.977732 1 server.cc:1125]  localhost:8001 for gRPC requests
I0122 13:43:38.977914 1 server.cc:1029] Building nvrpc server
I0122 13:43:38.977940 1 server.cc:1035] Register TensorRT GRPCService
I0122 13:43:38.977963 1 server.cc:1038] Register Infer RPC
I0122 13:43:38.977980 1 server.cc:1042] Register Status RPC
I0122 13:43:38.977989 1 server.cc:1046] Register Profile RPC
I0122 13:43:38.977998 1 server.cc:1050] Register Health RPC
I0122 13:43:38.978007 1 server.cc:1054] Register Executor
I0122 13:43:38.982098 1 server.cc:1135]  localhost:8000 for HTTP requests
[warn] getaddrinfo: address family for nodename not supported
[evhttp_server.cc : 237] RAW: Entering the event loop ...
I0122 13:43:39.039619 1 server_status.cc:105] New status tracking for model 'model_1'
I0122 13:43:39.040311 1 server_core.cc:465] Adding/updating models.
I0122 13:43:39.040327 1 server_core.cc:562]  (Re-)adding model: model_1
I0122 13:43:39.140693 1 basic_manager.cc:739] Successfully reserved resources to load servable {name: model_1 version: 1}
I0122 13:43:39.140735 1 loader_harness.cc:66] Approving load for servable version {name: model_1 version: 1}
I0122 13:43:39.140752 1 loader_harness.cc:74] Loading servable version {name: model_1 version: 1}
I0122 13:43:39.143548 1 base_bundle.cc:168] Creating instance model_1_0_0_gpu0 on GPU 0 (5.0) using model.graphdef
I0122 13:43:39.208124 1 cuda_gpu_executor.cc:957] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
I0122 13:43:39.208825 1 gpu_device.cc:1432] Found device 0 with properties: 
name: Quadro M1000M major: 5 minor: 0 memoryClockRate(GHz): 1.0715
pciBusID: 0000:01:00.0
totalMemory: 1.96GiB freeMemory: 1.19GiB
I0122 13:43:39.208850 1 gpu_device.cc:1482] Ignoring visible gpu device (device: 0, name: Quadro M1000M, pci bus id: 0000:01:00.0, compute capability: 5.0) with Cuda compute capability 5.0. The minimum required Cuda capability is 5.2.
I0122 13:43:39.208862 1 gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
I0122 13:43:39.208870 1 gpu_device.cc:988]      0 
I0122 13:43:39.208888 1 gpu_device.cc:1001] 0:   N 
I0122 13:43:39.233687 1 base_bundle.cc:168] Creating instance model_1_0_1_gpu0 on GPU 0 (5.0) using model.graphdef
I0122 13:43:39.233723 1 gpu_device.cc:1482] Ignoring visible gpu device (device: 0, name: Quadro M1000M, pci bus id: 0000:01:00.0, compute capability: 5.0) with Cuda compute capability 5.0. The minimum required Cuda capability is 5.2.
I0122 13:43:39.233757 1 gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
I0122 13:43:39.233761 1 gpu_device.cc:988]      0 
I0122 13:43:39.233765 1 gpu_device.cc:1001] 0:   N 
I0122 13:43:39.234945 1 base_bundle.cc:168] Creating instance model_1_0_2_gpu0 on GPU 0 (5.0) using model.graphdef
I0122 13:43:39.234992 1 gpu_device.cc:1482] Ignoring visible gpu device (device: 0, name: Quadro M1000M, pci bus id: 0000:01:00.0, compute capability: 5.0) with Cuda compute capability 5.0. The minimum required Cuda capability is 5.2.
I0122 13:43:39.234998 1 gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
I0122 13:43:39.235016 1 gpu_device.cc:988]      0 
I0122 13:43:39.235019 1 gpu_device.cc:1001] 0:   N 
I0122 13:43:39.236214 1 base_bundle.cc:168] Creating instance model_1_0_3_gpu0 on GPU 0 (5.0) using model.graphdef
I0122 13:43:39.236237 1 gpu_device.cc:1482] Ignoring visible gpu device (device: 0, name: Quadro M1000M, pci bus id: 0000:01:00.0, compute capability: 5.0) with Cuda compute capability 5.0. The minimum required Cuda capability is 5.2.
I0122 13:43:39.236247 1 gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
I0122 13:43:39.236254 1 gpu_device.cc:988]      0 
I0122 13:43:39.236278 1 gpu_device.cc:1001] 0:   N 
I0122 13:43:39.237000 1 infer.cc:788] Starting runner thread 0 at nice 5...
I0122 13:43:39.237058 1 infer.cc:788] Starting runner thread 1 at nice 5...
I0122 13:43:39.237161 1 infer.cc:788] Starting runner thread 2 at nice 5...
I0122 13:43:39.237272 1 loader_harness.cc:86] Successfully loaded servable version {name: model_1 version: 1}
I0122 13:43:39.237268 1 infer.cc:788] Starting runner thread 3 at nice 5...
E0122 13:43:40.977806 1 metrics.cc:213] failed to get power limit for GPU 0, NVML_ERROR 3
E0122 13:43:40.978112 1 metrics.cc:225] failed to get power usage for GPU 0, NVML_ERROR 3
E0122 13:43:40.978226 1 metrics.cc:238] failed to get energy consumption for GPU 0, NVML_ERROR 3
E0122 13:43:42.979284 1 metrics.cc:213] failed to get power limit for GPU 0, NVML_ERROR 3
E0122 13:43:42.979468 1 metrics.cc:225] failed to get power usage for GPU 0, NVML_ERROR 3
E0122 13:43:42.979555 1 metrics.cc:238] failed to get energy consumption for GPU 0, NVML_ERROR 3

**Comment by cc911** [comment]
Yes, please tell me what are the changes that need to be done in order for the TRTIS build to support also CUDA capability 5.0.

**Comment by deadeyegoodwin** [comment]
In Dockerfile you need to add 5.0 to the Caffe2 TORCH_CUDA_ARCH_LIST option: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/Dockerfile#L73

Fixing the TF build is trickier.  At this point in the build, https://github.com/NVIDIA/tensorrt-inference-server/blob/master/Dockerfile#L198, the nvbuild.sh script is run to configure the build. In that script you need to change TF_CUDA_COMPUTE_CAPABILITIES to include 5.0.

Just to repeat, you will be building a non-tested configuration for TRTIS so you may run into additional problems.
