### ISSUE TITLE
ensemble model MODEL_UNAVAILABLE

### ISSUE THREAD

**Issue by clancylian** [NVIDIA/tensorrt-inference-server#497]
Hi
When I use ensemble model, it occur an error `failed sending synchronous infer request: [inference:0 0] UNAVAILABLE - Inference request for unknown model 'ensemble_model'
`

**I use 19.06 version and my ensemble config file is:**
> 
name: "ensemble_model"
platform: "ensemble"
max_batch_size: 32
input [
  {
    name: "INPUT"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 112, 112 ]
  }
]
output [
  {
    name: "Attribute"
    data_type: TYPE_FP32
    dims: [ 113, 1, 1 ]
  },
  {
    name: "Recognition"
    data_type: TYPE_FP32
    dims: [ 512, 1, 1 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "attributes_plan"
      input_map {
        key: "blob1"
        value: "INPUT"
      }
      output_map {
        key: "cat_blob1"
        value: "Attribute"
      }
    },
    {
      model_name: "insight_plan"
      input_map {
        key: "data"
        value: "INPUT"
      }
      output_map {
        key: "fc1"
        value: "Recognition"
      }
    }
  ]
}

**attributes_plan config file is:**
> 
name: "attributes_plan"
platform: "tensorrt_plan"
max_batch_size: 32
input [
  {
    name: "blob1"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 112, 112 ]
  }
]
output [
  {
    name: "cat_blob1"
    data_type: TYPE_FP32
    dims: [ 113, 1, 1 ]
  }
]
cc_model_filenames [
   {
      key: "6.1"
      value: "model.plan"
   }
]
instance_group [
  {
    count: 1
    gpus: [ 0 ]
  }
]
dynamic_batching {
    preferred_batch_size: [ 16, 32 ]
    max_queue_delay_microseconds: 20000
}
optimization{
    graph{
        level:9
    }
}

**insight_plan config file is:**
> 
name: "insight_plan"
platform: "tensorrt_plan"
max_batch_size: 32
input [
  {
    name: "data"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 112, 112 ]
  }
]
output [
  {
    name: "fc1"
    data_type: TYPE_FP32
    dims: [ 512, 1, 1 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]
dynamic_batching {
	preferred_batch_size: [ 16, 32 ]
	max_queue_delay_microseconds: 10000
}
optimization{
	graph{
		level:9
	}
}

**Comment by clancylian** [comment]
Hi
I have not used custom backend yet. It just have two models and the same input, so I use ensemble model to avoid http or grpc transfer.

Thanks.

**Comment by nieksand** [comment]
What does the output of status endpoint look like?

`curl localhost:8000/api/status`

**Comment by GuanLuo** [comment]
Could you check the server log to see if the ensemble is loaded successfully? And for the step in `ensemble_scheduling`, you should also specify the model version to be used (-1 for the latest version)

**Comment by clancylian** [comment]
Hi ,

I have tried to set the model version to -1 but still not work.

**>  the server log** 

NVIDIA Release 19.06 (build 6791108)

Copyright (c) 2018-2019, NVIDIA CORPORATION.  All rights reserved.
Copyright 2019 The TensorFlow Authors.  All rights reserved.
Copyright 2019 The TensorFlow Serving Authors.  All rights reserved.
Copyright (c) 2016-present, Facebook Inc. All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying
project or file.

I0726 01:31:31.750645 1 main.cc:325] Starting endpoints, 'inference:0' listening on
I0726 01:31:31.750831 1 grpc_server.cc:263] Starting a GRPCService at 0.0.0.0:8001
I0726 01:31:31.750843 1 grpc_server.cc:269] Register TensorRT GRPCService
I0726 01:31:31.750855 1 grpc_server.cc:272] Register Infer RPC
I0726 01:31:31.750861 1 grpc_server.cc:276] Register StreamInfer RPC
I0726 01:31:31.750866 1 grpc_server.cc:281] Register Status RPC
I0726 01:31:31.750871 1 grpc_server.cc:285] Register Profile RPC
I0726 01:31:31.750878 1 grpc_server.cc:289] Register Health RPC
I0726 01:31:31.750883 1 grpc_server.cc:301] Register Executor
I0726 01:31:31.755463 1 http_server.cc:579] Starting HTTPService at 0.0.0.0:8000
I0726 01:31:31.796669 1 main.cc:356]  localhost:8002 for metric reporting
I0726 01:31:31.797951 1 metrics.cc:149] found 1 GPUs supporting NVML metrics
I0726 01:31:31.803287 1 metrics.cc:158]   GPU 0: GeForce GTX 1080 Ti
I0726 01:31:31.803656 1 server.cc:113] Initializing TensorRT Inference Server
I0726 01:31:31.850743 1 server_status.cc:83] New status tracking for model 'attributes_plan'
I0726 01:31:31.850807 1 model_repository_manager.cc:627] loading: attributes_plan:1
**I0726 01:31:31.850887 1 server_status.cc:83] New status tracking for model 'ensemble_model'**
I0726 01:31:31.850927 1 server_status.cc:83] New status tracking for model 'insight_plan'
I0726 01:31:31.850987 1 model_repository_manager.cc:627] loading: insight_plan:1
I0726 01:31:31.851068 1 server_status.cc:83] New status tracking for model 'retinaface_plan0'
I0726 01:31:31.851198 1 model_repository_manager.cc:627] loading: retinaface_plan0:1
I0726 01:31:31.851301 1 server_status.cc:83] New status tracking for model 'retinaface_plan1'
I0726 01:31:31.851383 1 model_repository_manager.cc:627] loading: retinaface_plan1:1
I0726 01:31:31.851516 1 server_status.cc:83] New status tracking for model 'retinaface_plan2'
I0726 01:31:31.851578 1 model_repository_manager.cc:627] loading: retinaface_plan2:1
I0726 01:31:31.944938 1 plan_backend.cc:209] Creating instance retinaface_plan0_0_0_gpu0 on GPU 0 (6.1) using model.plan
I0726 01:31:33.735256 1 logging.cc:49] Glob Size is 815840 bytes.
I0726 01:31:33.735633 1 logging.cc:49] Added linear block of size 13107200
I0726 01:31:33.735645 1 logging.cc:49] Added linear block of size 13107200
I0726 01:31:33.735649 1 logging.cc:49] Added linear block of size 6553600
I0726 01:31:33.735667 1 logging.cc:49] Added linear block of size 3276800
I0726 01:31:33.735670 1 logging.cc:49] Added linear block of size 819200
I0726 01:31:33.735673 1 logging.cc:49] Added linear block of size 51200
I0726 01:31:34.588460 1 logging.cc:49] Deserialize required 853368 microseconds.
I0726 01:31:34.590076 1 plan_backend.cc:317] Created instance retinaface_plan0_0_0_gpu0 on GPU 0 (6.1) with stream priority 0
I0726 01:31:34.590475 1 model_repository_manager.cc:758] successfully loaded 'retinaface_plan0' version 1
I0726 01:31:34.590539 1 plan_backend.cc:209] Creating instance retinaface_plan1_0_0_gpu0 on GPU 0 (6.1) using model.plan
I0726 01:31:34.590652 1 logging.cc:49] Glob Size is 4823264 bytes.
I0726 01:31:34.591237 1 logging.cc:49] Added linear block of size 169869312
I0726 01:31:34.591247 1 logging.cc:49] Added linear block of size 84934656
I0726 01:31:34.591251 1 logging.cc:49] Added linear block of size 42467328
I0726 01:31:34.591254 1 logging.cc:49] Added linear block of size 11010048
I0726 01:31:34.591256 1 logging.cc:49] Added linear block of size 2752512
I0726 01:31:34.591259 1 logging.cc:49] Added linear block of size 688128
I0726 01:31:34.592285 1 logging.cc:49] Deserialize required 1726 microseconds.
I0726 01:31:34.593771 1 plan_backend.cc:317] Created instance retinaface_plan1_0_0_gpu0 on GPU 0 (6.1) with stream priority 0
I0726 01:31:34.593822 1 model_repository_manager.cc:758] successfully loaded 'retinaface_plan1' version 1
I0726 01:31:34.593974 1 plan_backend.cc:209] Creating instance retinaface_plan2_0_0_gpu0 on GPU 0 (6.1) using model.plan
I0726 01:31:34.594126 1 logging.cc:49] Glob Size is 7669888 bytes.
I0726 01:31:34.594973 1 logging.cc:49] Added linear block of size 471859200
I0726 01:31:34.594983 1 logging.cc:49] Added linear block of size 235929600
I0726 01:31:34.594986 1 logging.cc:49] Added linear block of size 117964800
I0726 01:31:34.594989 1 logging.cc:49] Added linear block of size 30146560
I0726 01:31:34.594992 1 logging.cc:49] Added linear block of size 7536640
I0726 01:31:34.594995 1 logging.cc:49] Added linear block of size 1884160
I0726 01:31:34.595983 1 logging.cc:49] Deserialize required 1963 microseconds.
I0726 01:31:34.598083 1 plan_backend.cc:317] Created instance retinaface_plan2_0_0_gpu0 on GPU 0 (6.1) with stream priority 0
I0726 01:31:34.598152 1 model_repository_manager.cc:758] successfully loaded 'retinaface_plan2' version 1
I0726 01:31:34.598313 1 plan_backend.cc:209] Creating instance attributes_plan_0_0_gpu0 on GPU 0 (6.1) using model.plan
I0726 01:31:34.598467 1 logging.cc:49] Glob Size is 61774440 bytes.
I0726 01:31:34.605405 1 logging.cc:49] Added linear block of size 25690112
I0726 01:31:34.605428 1 logging.cc:49] Added linear block of size 6422528
I0726 01:31:34.605431 1 logging.cc:49] Added linear block of size 6422528
I0726 01:31:34.605434 1 logging.cc:49] Added linear block of size 1605632
I0726 01:31:34.605437 1 logging.cc:49] Added linear block of size 12800
I0726 01:31:34.605440 1 logging.cc:49] Added linear block of size 512
I0726 01:31:34.605443 1 logging.cc:49] Added linear block of size 512
I0726 01:31:34.605446 1 logging.cc:49] Added linear block of size 512
I0726 01:31:34.605449 1 logging.cc:49] Added linear block of size 512
I0726 01:31:34.605452 1 logging.cc:49] Added linear block of size 512
I0726 01:31:34.608146 1 logging.cc:49] Deserialize required 9810 microseconds.
I0726 01:31:34.608872 1 plan_backend.cc:317] Created instance attributes_plan_0_0_gpu0 on GPU 0 (6.1) with stream priority 0
I0726 01:31:34.613171 1 model_repository_manager.cc:758] successfully loaded 'attributes_plan' version 1
I0726 01:31:34.611082 1 plan_backend.cc:209] Creating instance insight_plan_0_0_gpu0 on GPU 0 (6.1) using model.plan
I0726 01:31:34.613344 1 logging.cc:49] Glob Size is 104251392 bytes.
I0726 01:31:34.624344 1 logging.cc:49] Added linear block of size 102760448
I0726 01:31:34.624366 1 logging.cc:49] Added linear block of size 102760448
I0726 01:31:34.624369 1 logging.cc:49] Added linear block of size 25690112
I0726 01:31:34.624372 1 logging.cc:49] Added linear block of size 6422528
I0726 01:31:34.624375 1 logging.cc:49] Added linear block of size 3211264
I0726 01:31:34.629251 1 logging.cc:49] Deserialize required 16030 microseconds.
I0726 01:31:34.630393 1 plan_backend.cc:317] Created instance insight_plan_0_0_gpu0 on GPU 0 (6.1) with stream priority 0
I0726 01:31:34.637055 1 model_repository_manager.cc:758] successfully loaded 'insight_plan' version 1


**> the model status:**
model_status {
  key: "ensemble_model"
  value {
    config {
      name: "ensemble_model"
      platform: "ensemble"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      max_batch_size: 32
      input {
        name: "INPUT"
        data_type: TYPE_FP32
        format: FORMAT_NCHW
        dims: 3
        dims: 112
        dims: 112
      }
      output {
        name: "Attribute"
        data_type: TYPE_FP32
        dims: 113
        dims: 1
        dims: 1
      }
      ensemble_scheduling {
        step {
          model_name: "attributes_plan"
          model_version: -1
          input_map {
            key: "blob1"
            value: "INPUT"
          }
          output_map {
            key: "cat_blob1"
            value: "Attribute"
          }
        }
      }
    }
    version_status {
      key: -1
      value {
        ready_state: MODEL_UNAVAILABLE
        infer_stats {
          key: 0
          value {
            failed {
              count: 1
              total_time_ns: 109566
            }
          }
        }
      }
    }
  }
}

**Comment by clancylian** [comment]
Hi, 
when I just start the server and not run client, the model status:

> model_status {
  key: "ensemble_model"
  value {
    config {
      name: "ensemble_model"
      platform: "ensemble"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      max_batch_size: 32
      input {
        name: "INPUT"
        data_type: TYPE_FP32
        format: FORMAT_NCHW
        dims: 3
        dims: 112
        dims: 112
      }
      output {
        name: "Attribute"
        data_type: TYPE_FP32
        dims: 113
        dims: 1
        dims: 1
      }
      ensemble_scheduling {
        step {
          model_name: "attributes_plan"
          model_version: -1
          input_map {
            key: "blob1"
            value: "INPUT"
          }
          output_map {
            key: "cat_blob1"
            value: "Attribute"
          }
        }
      }
    }
  }
}



**it seems not version status:**

version_status {
      key: 1
      value {
        ready_state: MODEL_READY
      }
    }

**Comment by GuanLuo** [comment]
Did you create version folder for the ensemble model? TRTIS sees ensemble as the same as other models, so at least one version folder is required. The version folder can be empty as ensemble doesn't require any model file. See [detail](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_repository.html#ensemble-backends)

**Comment by clancylian** [comment]
HI,
It work! 
thanks!
