### ISSUE TITLE
docker installation in c++

### ISSUE THREAD

**Issue by magnanta** [NVIDIA/tensorrt-inference-server#501]
Hi guys can anyone guide me to install tensorrt client in docker . I ran $ docker run -it --rm --net=host tensorrtserver_client this code i entered into workspace docker what i have to do next. I an new to docker and c++ . I run basic code with tensorrt import 
![code](https://user-images.githubusercontent.com/53342641/61954661-f0d71380-afd6-11e9-847d-3f24b54cad8f.png)
![error](https://user-images.githubusercontent.com/53342641/61954662-f16faa00-afd6-11e9-8a72-a834d8afb026.png)
![tree](https://user-images.githubusercontent.com/53342641/61954731-19f7a400-afd7-11e9-8e1e-1516b5af10ac.png)
please find attachments for more details.

**Comment by philipp-schmidt** [comment]
Unfortunately you don't show how you actually compile your code.
I suppose you don't use cmake or make but call the compiler directly somehow?
If you use g++ directly you probably need to add include dirs and link against the request libraries by using the -I (include) and -l (link) options (see [this post as a quick overview](https://stackoverflow.com/questions/6141147/how-do-i-include-a-path-to-libraries-in-g)).

Consider using cmake for this though. You can find how this is done under src/clients/c++/CMakeLists.txt. The easiest way would of course be if you just change any of the exemplary clients and rebuild everything or just duplicate on of the client examples in the cmake and under src/clients/c++/.

If you don't feel comfortable using c++ for this you might also be better off using python where you don't have to care about compiling stuff. There are many examples on how to do this in python in the client docker file.

**Comment by deadeyegoodwin** [comment]
There is example client code in the src/clients directory (both Python and C++). A simple C++ example is here: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/c%2B%2B/simple_client.cc

Also, the documentation has a section on building an running the clients and examples.
