### ISSUE TITLE
Label map query

### ISSUE THREAD

**Issue by bezero** [NVIDIA/tensorrt-inference-server#514]
Is it possible to get all available labels per model/version? Is it possible to provide labels for detection models and get label outputs per detection?

**Comment by deadeyegoodwin** [comment]
Do you mean you want to get the contents of the classification labels file that can be associated with model outputs? There is currently no way to get that via an HTTP/GRPC API.

I don't understand the second part of the question. Can you give more detail.

**Comment by bezero** [comment]
For the first part, yes that is what I wanted to now. For the second part, an example would be a classification layer output for the detected boxes in the detection model. I wanted to know whether it is possible to provide labels for that layer and request results with labels by creating inference context with ```{ output_name : InferContext.ResultFormat.CLASS}```

**Comment by deadeyegoodwin** [comment]
You should be able to associate classification labels with any output in your model (the output may need to be a vector but I don't think so). Did you try it and get a failure?

**Comment by bezero** [comment]
@deadeyegoodwin thanks, I have not tried yet.
