### ISSUE TITLE
Cannot run tensorrtserver with python3

### ISSUE THREAD

**Issue by ThiagoMateo** [NVIDIA/tensorrt-inference-server#517]
when run python 3 with tensorrt, i got this error:
```
ModuleNotFoundError: No module named 'tensorrtserver'
```
(trtis r19.07 clients)

**Comment by bezero** [comment]
@ThiagoMateo how did you install trtis client?

**Comment by ThiagoMateo** [comment]
Hi @bezero I clone tensorrt-inference-server repo and i switch to branch r_19.04 then i build client using this command.
```
git checkout r19.07
docker build -t tensorrtserver_client -f Dockerfile.client .
```

**Comment by CoderHam** [comment]
Are you importing it correctly? The build and import works fine for me.
`from tensorrtserver.api import *`

Also you mentioned 19.04 here, I hope that is a typo and you meant 19.07

> Hi @bezero I clone tensorrt-inference-server repo and i switch to branch r_19.04 then i build client using this command.
> 
> ```
> git checkout r19.07
> docker build -t tensorrtserver_client -f Dockerfile.client .
> ```

**Comment by GuanLuo** [comment]
I assume `tensorrtserver` can be imported in Python2? If so, perhaps it is because the Dockerfile.client installs the package via `pip` and Python2 is the default target for pip.

**Comment by philipp-schmidt** [comment]
@ThiagoMateo 
Run the following inside the client docker container:
'''
apt-get install python3-pip
python3 -m pip install build/dist/dist/tensorrtserver-1.3.0-py2.py3-none-linux_x86_64.whl
'''

**Comment by bezero** [comment]
@ThiagoMateo after building the client container, can you run the container and locate ```/workspace/v$VERSION.clients.tar.gz```. Then, untar it and install using pip3 ```pip3 install --upgrade install/python/tensorrtserver-*.whl```.

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if you are still having issues.
