### ISSUE TITLE
Java client from .proto files

### ISSUE THREAD

**Issue by Uture** [NVIDIA/tensorrt-inference-server#519]
I'm trying to implement a gRPC java client based on the provided .proto files, but I cannot find any possibility to create stubs for the services. Is this something that needs to be implemented by myself? 

If yes, can you guide me on how I could handle this?

**Comment by GuanLuo** [comment]
Have you generated the JAVA code of the `.proto` files? If so, then this post should be useful for the next steps: https://grpc.io/docs/tutorials/basic/java/#client

**Comment by Uture** [comment]
I managed to get the Java classes by compiling the `.proto` files with namely/protoc-all container. But the generated classes seem to have errors:
`[ERROR] GrpcService.java:[2165,42] cannot find symbol
[ERROR]   symbol:   class OneofDescriptor
[ERROR]   location: class com.google.protobuf.Descriptors`
and:
```
[ERROR]   symbol:   class UnusedPrivateParameter
[ERROR]   location: class at.optadata.ai.nvidia.inferenceserver.GrpcService.InferRequest
```

Does this have something to do with the version of protobuf compiler? Which version should I use?

**Comment by deadeyegoodwin** [comment]
We haven't yet tried building a java client using protoc. I would assume that you can use any recent version of protobuf that is compatible with grpc. The protobuf or grpc documentation should describe any limitations or requirements for java.

**Comment by seovchinnikov** [comment]
I've tested grps endpoints via grpc-java client and it works fine.
PR is here https://github.com/NVIDIA/tensorrt-inference-server/pull/966
