### ISSUE TITLE
Cannot compile trtis-clients

### ISSUE THREAD

**Issue by vitcozzolino** [NVIDIA/tensorrt-inference-server#531]
Hi,
I followed the instructions (from here https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/client.html) but the make process fails at this step:

`
[ 46%] Built target grpc-library
/usr/bin/python: No module named grpc_tools
src/core/CMakeFiles/grpc-py-library.dir/build.make:60: recipe for target 'src/core/grpc_service.grpc.py' failed
make[6]: *** [src/core/grpc_service.grpc.py] Error 1
CMakeFiles/Makefile2:186: recipe for target 'src/core/CMakeFiles/grpc-py-library.dir/all' failed
make[5]: *** [src/core/CMakeFiles/grpc-py-library.dir/all] Error 2
make[5]: *** Waiting for unfinished jobs....
[ 58%] Built target request
Makefile:129: recipe for target 'all' failed
make[4]: *** [all] Error 2
CMakeFiles/trtis-clients.dir/build.make:112: recipe for target 'trtis-clients/src/trtis-clients-stamp/trtis-clients-build' failed
make[3]: *** [trtis-clients/src/trtis-clients-stamp/trtis-clients-build] Error 2
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/trtis-clients.dir/all' failed
make[2]: *** [CMakeFiles/trtis-clients.dir/all] Error 2
CMakeFiles/Makefile2:80: recipe for target 'CMakeFiles/trtis-clients.dir/rule' failed
make[1]: *** [CMakeFiles/trtis-clients.dir/rule] Error 2
Makefile:118: recipe for target 'trtis-clients' failed
make: *** [trtis-clients] Error 2
`

I have installed both grpcio and grpcio-tools as pip3 list shows:

`grpcio (1.22.0)`
`grpcio-tools (1.22.0)`

Any suggestions?

**Comment by deadeyegoodwin** [comment]
Do you have both python2 and python3 installed? What is the default (i.e. which runs when you run "python")? The build will use just "python".

**Comment by vitcozzolino** [comment]
I have both python2 and python3 installed but have an `alias` set in .bashrc to set the `python` command to point to `python3`.

How can I change the build process? I looked into most of the Make* and Cmake* files but couldn't find the point where /usr/bin/python is actually selected for the build process.

Is it the header in the python files? `#!/usr/bin/python` ? Shouldn't then be `#!/usr/bin/env python` to be more resilient?

Thanks in advance!

**Comment by deadeyegoodwin** [comment]
Perhaps here: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/CMakeLists.txt#L67

If you run make with VERBOSE=1 then you will be able to see the commandline that was issued that caused the error.

**Comment by vitcozzolino** [comment]
Thanks, using VERBOSE=1 helped me identifying the files I had to change to compile with python3 (CMakeLists.txt and src/clients/python/build_wheel.sh).

As a side note, I had also to change the source code of image_client.cpp as it is not compatible with OpenCV 4.

**Comment by GuanLuo** [comment]
We recently added OpenCV4 support for image_client #442 and it will be included in the 19.08 release
