### ISSUE TITLE
UNIMPLEMENTED endpoints using java grpc

### ISSUE THREAD

**Issue by Uture** [NVIDIA/tensorrt-inference-server#539]
I already tried different versions of the docker image (19.07, 19.06 & 19.04), but whatever endpoint I address, I get the following 'UNIMPLEMENTED' exception:

> Exception in thread "main" io.grpc.StatusRuntimeException: UNIMPLEMENTED
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:235)
ClientCalls.java:235
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:216)
ClientCalls.java:216
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
ClientCalls.java:141
	at at.optadata.ai.nvidia.inferenceserver.GRPCServiceGrpc$GRPCServiceBlockingStub.status(GRPCServiceGrpc.java:613)
GRPCServiceGrpc.java:613
	at at.optadata.ai.main.App.main(App.java:21)

Here is my Java-client code:

```
ManagedChannel channel = ManagedChannelBuilder.forAddress("172.21.14.203", 8007).usePlaintext().build();

        GRPCServiceBlockingStub stub = GRPCServiceGrpc.newBlockingStub(channel);
        StatusRequest.Builder statusRequestBuilder = StatusRequest.newBuilder();
        //statusRequestBuilder.setModelName("fextractor-svnr-2019");
        StatusRequest statusRequest = statusRequestBuilder.build();
        stub.status(statusRequest);
```

What may be causing this?

**Comment by Uture** [comment]
Is it possible that the version of protoc I used to compile the .proto files is responsible for the issue=?

**Comment by nithinkanil** [comment]
We want to use TLS / HTTPS endpoint. Does Tensor RT server support TLS encryption?

**Comment by Uture** [comment]
@deadeyegoodwin thank's for your suggestion, but I changed the port explicitly. Otherwise, the error would suggest that the client cannot connect before throwing any other exceptions.

**Comment by deadeyegoodwin** [comment]
PR #966 implements a Java grpc client. Have a look at that and see if it is helpful.

**Comment by pedroteixeira** [comment]
I've just tried running a grpc client and am seeing the same exception, not sure what's causing it yet. 
Any known common troubleshooting for `io.grpc.StatusRuntimeException: UNIMPLEMENTED` ? Trying different versions of protoc and libraries here to see if it helps.

Python client works with the endpoint I have.

**Comment by pedroteixeira** [comment]
Nevermind, just realized server responds with UNIMPLEMENTED with grpc client doesn't send expected header

my case was actually using triton with seldon core v2, in case it helps anyone, example how to send it:

```java
       // # Create gRPC stub for communicating with the server
        val channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext().build().let {

            // header is required, otherwise will get uninplemented
            val seldonModelHeader = Metadata.Key.of("seldon-model", Metadata.ASCII_STRING_MARSHALLER)
            ClientInterceptors.intercept(it, object : ClientInterceptor {
                override fun <ReqT : Any, RespT : Any> interceptCall(
                    method: MethodDescriptor<ReqT, RespT>,
                    callOptions: CallOptions,
                    next: Channel
                ): ClientCall<ReqT, RespT> {
                    return object : SimpleForwardingClientCall<ReqT, RespT>(next.newCall(method, callOptions)) {
                        override fun start(responseListener: Listener<RespT>, headers: Metadata) {
                            headers.put(seldonModelHeader, modelName)
                            super.start(responseListener, headers)
                        }
                    }
                }
            })
        }

```

**Comment by TernenceZhou** [comment]
ManagedChannel channel = ManagedChannelBuilder.forAddress(host, port).usePlaintext().build();
GRPCInferenceServiceGrpc.GRPCInferenceServiceBlockingStub grpc_stub = GRPCInferenceServiceGrpc.newBlockingStub(channel);
ServerLiveRequest serverLiveRequest = ServerLiveRequest.getDefaultInstance();
ServerLiveResponse r = grpc_stub.serverLive(serverLiveRequest);

Exception information:

Exception in thread "main" io.grpc.StatusRuntimeException: UNIMPLEMENTED
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at com.zeekr.speech.chat.web.protol.inference.GRPCInferenceServiceGrpc$GRPCInferenceServiceBlockingStub.serverLive(GRPCInferenceServiceGrpc.java:1053)
	at com.zeekr.speech.chat.web.protol.client.SimpleJavaClient.main(SimpleJavaClient.java:45)
		
	
Hello, I'm encountering the same issue as well, As follows. 

I've generated the corresponding GrpcService class from grpc_service.proto and used the code from https://github.com/triton-inference-server/client/blob/6748079626925442069c7c5c20bafdc2f527e221/src/grpc_generated/java/examples/src/main/java/clients/SimpleJavaClient.java to test the serverLive method. However, I received the following message. It appears that the service is connected, but the method is not implemented.

My colleague is using Python and calling `triton_client.is_server_ready()` successfully. At the moment, I'm unable to identify the reason for this issue. Do you have any alternative suggestions? Looking forward to your reply, thank you
@Uture @deadeyegoodwin @pedroteixeira

**Comment by WilliamOnVoyage** [comment]
Is there any solution to this? Hitting the same issue. Simple code to reproduce:

```
ManagedChannel channel = ManagedChannelBuilder.forAddress("localhost", 8001).usePlaintext().build();
GRPCInferenceServiceBlockingStub grpc_stub = GRPCInferenceServiceGrpc.newBlockingStub(channel);

ServerLiveRequest serverLiveRequest = ServerLiveRequest.getDefaultInstance();
ServerLiveResponse r = grpc_stub.serverLive(serverLiveRequest);
```

Checked the protos and grpc version is aligned with the triton server.
