### ISSUE TITLE
Shared Memory client fails for batch size != 1

### ISSUE THREAD

**Issue by philipp-schmidt** [NVIDIA/tensorrt-inference-server#544]
Requests with batch size 1 and correct input_byte_size calculation work correctly.

Increasing batch size to two and multiply input_byte_size by two leads to the following exception (modified version of simple_shm_client.cc):

```
int batch_size = 2;
options->SetBatchSize(batch_size);
size_t input_byte_size = 608 * 608 * 3 * sizeof(float) * batch_size;
```
> **failed setting shared memory input: [ 0] INVALID_ARG - The input '000_net' has shared memory of size 8871936 bytes while the expected size is 4435968 bytes**

So the expected size does not take batch size into account.
Matching the expected size then fails during a different sanity check:

```
int batch_size = 2;
options->SetBatchSize(batch_size);
size_t input_byte_size = 608 * 608 * 3 * sizeof(float);
```
> **error: unable to run model: [inference:0 6] INVALID_ARG - unexpected shared-memory size 4435968 for input '000_net', expecting 8871936 for model 'yolov3'**

So now batch size is taken into account for the expected byte size.

**Comment by philipp-schmidt** [comment]
Probably related to #541

**Comment by CoderHam** [comment]
The `input_byte_size` must be the **size of the entire batch** and not just that of one element in the batch since this is the total size in shared memory that will be allocated for that corresponding input. 

In this case you should do:
```
size_t input_byte_size = 2 * 608 * 608 * 3 * sizeof(float) * batch_size;
```

**Comment by philipp-schmidt** [comment]
No matter which size I set, the client side sanity check complains about the shared memory region being too large and tells me it expects a input_byte_size equal to the byte size of batch size 1.

> int batch_size = 2;
options->SetBatchSize(batch_size);
size_t input_byte_size = 608 * 608 * 3 * sizeof(float) * batch_size;

This is equal to the equation you provided, except that the leading 2 is missing, because I'm dealing with a single input and no double input via offsets like the simple_shm_client does.

The error shows, that while I set the correct input_byte_size of the full batch (~8.8MB), the client sanity checks always expect batch size 1 (~4.4MB). I can do the very same for any batch size other than 1.

> **failed setting shared memory input: [ 0] INVALID_ARG - The input '000_net' has shared memory of size 8871936 bytes while the expected size is 4435968 bytes**

My current fix for this is to hardcode the byte size in request_grpc.cc starting from line 849:

```
    // set shared memory
    if (reinterpret_cast<InputImpl*>(io.get())->IsSharedMemory()) {
      auto rshared_memory = rinput->mutable_shared_memory();
      rshared_memory->set_name(
          reinterpret_cast<InputImpl*>(io.get())->GetSharedMemoryName());
      rshared_memory->set_offset(
          reinterpret_cast<InputImpl*>(io.get())->GetSharedMemoryOffset());
      // Hardcoded byte size for exemplary batch size 2:
      rshared_memory->set_byte_size(8871936);
    }
```

And to then disable the client sanity checks in request_common.cc starting from line 244:

```
  // verify byte size of shared memory matches that of expected byte size
  /*if ((int64_t)byte_size != byte_size_) {
    return Error(
        RequestStatusCode::INVALID_ARG,
        "The input '" + Name() + "' has shared memory of size " +
            std::to_string(byte_size) + " bytes while the expected size is " +
            std::to_string(byte_size_) + " bytes");
  }*/
```

This way batch sizes other than 1 work with the server.

**Comment by CoderHam** [comment]
The fix to this is simple. I shall test it and create a new PR for it.

**Comment by philipp-schmidt** [comment]
Thanks, very much appreciated @CoderHam !
