### ISSUE TITLE
Custom Operations with Docker

### ISSUE THREAD

**Issue by ohlr** [NVIDIA/tensorrt-inference-server#545]
I try to add [custom operations](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/custom_operation.html#custom-operations) to a model

Currently I run the Server with [docker](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/run.html#running-the-inference-server):

```
$ nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/path/to/model/repository:/models <tensorrtserver image name> trtserver --model-store=/models
```
From the documentation about custom operations I infer that the combined command looks like:

```
`$ nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/path/to/model/repository:/models <tensorrtserver image name> LD_PRELOAD=libtrtcustom.so trtserver --model-store=/models
```
difference: LD_PRELOAD=libtrtcustom.so added before trtserver

The problem is that the server does not start - it does not find the library.
Where do I have to place the library (in container or outside)? 
Does the approach work with docker or only with manual builds?
How does the correct command to run the server look like?

**Comment by philipp-schmidt** [comment]
Use -eLD_PRELOAD=libtrtcustom.so to create an environment variable in docker.

```
nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/path/to/model/repository:/models -eLD_PRELOAD=libtrtcustom.so trtserver <tensorrtserver image name> --model-store=/models
```

**Comment by GowthamKudupudi** [comment]
That didn't work for me
```
$ nvidia-docker run --gpus=1 --rm -p8000:8000 -p8001:8001 -p8002:8002 -v$(pwd)/model_repository:/model_repository --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -eLD_PRELOAD=/model_repository/sv/1/libkernels.so trtserver nvcr.io/nvidia/tensorrtserver:19.12-py3 --model-repository=/model_repository --log-info 1 --log-warning 1 --log-error 1 --log-verbose 1 --strict-model-config=false
Unable to find image 'trtserver:latest' locally
docker: Error response from daemon: pull access denied for trtserver, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
