### ISSUE TITLE
Header path issues in librequest.so

### ISSUE THREAD

**Issue by philipp-schmidt** [NVIDIA/tensorrt-inference-server#556]
I'm trying to build a standalone c++ client, which should link and make use of librequest.so.
For this, I would like to use the tar file provided in the client docker, e.g. `v1.5.0dev.clients.tar.gz`

The content looks like this:

```
.
|-- bin
|   |-- ensemble_image_client
|   |-- image_client
|   |-- perf_client
|   |-- simple_callback_client
|   |-- simple_client
|   |-- simple_sequence_client
|   |-- simple_shm_client
|   `-- simple_string_client
|-- include
|   |-- api.pb.h
|   |-- model_config.pb.h
|   |-- request.h
|   |-- request_grpc.h
|   |-- request_http.h
|   |-- request_status.pb.h
|   `-- server_status.pb.h
|-- lib
|   `-- librequest.so
|-- python
|   |-- ensemble_image_client.py
|   |-- grpc_image_client.py
|   |-- image_client.py
|   |-- simple_callback_client.py
|   |-- simple_client.py
|   |-- simple_sequence_client.py
|   |-- simple_string_client.py
|   `-- tensorrtserver-1.5.0.dev0-py2.py3-none-linux_x86_64.whl
`-- v1.5.0dev.clients.tar.gz
```

So in my CMakeLists.txt I link and include the library like this:

```cmake
# TRTIS client request library
INCLUDE_DIRECTORIES(/path/to/above/include)
link_directories(/path/to/above/lib)
```

In my main I include `#include "request_grpc.h"`, which is correctly found. But in this "public" library header, I get the following error now:

```bash
In file included from /path/to/main.cpp:32:0:
/path/to/request_grpc.h:30:10: fatal error: src/clients/c++/request.h: No such file or directory
 #include "src/clients/c++/request.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Which makes sense, as those "public" library headers try to include from the path "src/clients/c++/", which of course does not exist in this context.

So how can I use the library headers? Or in more general terms: how would I install and use this library from e.g. /usr/lib and /usr/include?

**Comment by deadeyegoodwin** [comment]
Yes, that is a bug. We should either fix those includes to expect a "flat" include directly like we have, or place them within the same include hierarchy as what they expect. Until we fix you should be able to work-around by re-arranging the includes into the locations they expect.

**Comment by philipp-schmidt** [comment]
As a simple hotfix we use the following script to convert the install/include directory in the client docker file to a flat include hierarchy:

```bash
cd /workspace/install/include
sed -i -e "s/\"src\/core\//\"/" *             
sed -i -e "s/\"src\/clients\/c++\//\"/" *
```
