### ISSUE TITLE
CustomGetNextInput_fn

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/tensorrt-inference-server#565]
In the examples for custom backends (and also in the documentation of the SDK), it is stated that the provided ```CustomGetNextInput_fn``` possibly has to be called multiple times to provide the whole input in contiguous chunks.

In case the custom module has batch_size 1 (or 0), does a single call to the callback suffice?

Edit: And on a related note: would it be possible to make  a ```CustomGetNextInput_fn```  Return pointers to chunks which are aligned in memory, as to facilitate processing via SIMD methods?

**Comment by deadeyegoodwin** [comment]
We don't guarantee this... but currently it is only the HTTP front-end that will return multiple chunks for an input. That chunking is not based on the batch-size (and so does not fall on batch item boundary). The chunking is determined by the way the HTTP front-end is creating its buffers as it reads the HTTP request.

So the general answer is no, you cannot assume anything about if or if-not there will be multiple chunks for an input.

Currently we don't control how HTTP or GRPC aligns its memory blocks... perhaps with is an option we can configure in the future. We will track internally.
