### ISSUE TITLE
Ensemble configuration setup 

### ISSUE THREAD

**Issue by royinx** [NVIDIA/tensorrt-inference-server#590]
I'm going to deploy the ensemble model and I can't find the details about how to setting up the ensemble configuration.

assume there are two models: 
1st model is libtorch  { 1 input , 1 output }
2nd model is TensorRT { 1 input , 3 output }

my question is 
1) how to setup the libtorch config? since after the trace to torch script, every time Netron show different output layer name. (_gen99yn7, _gendv68sj , etc) 

2) how to set up the directory of ensemble model ? 
this is my setting.
```
models
│─ preprocess_libtorch
|    └───1
|    |   └───model.pt
|    └───config.pbtxt
│─ trt_nn
|    └───1
|    |   └───model.plan
|    └───config.pbtxt
└  nn_ensemble
     └───config.pbtxt
```

3) how to set up the ensemble config.pbtxt for 3 output map? 
the server can initialise but cannot test due to Q1.
the config i am using:
```
name: "nn_ensemble"
platform: "ensemble"
max_batch_size: 32
input [
  {
    name: "IMAGE"
    data_type: TYPE_UINT8
    dims: [ 3, 608, 608 ]
  }
]
output [
 {
    name: "convolutional_1"
    data_type: TYPE_FP32
    dims: [ 255, 19, 19 ]
  },
  {
    name: "convolutional_2"
    data_type: TYPE_FP32
    dims: [ 255, 38, 38 ]
  },
  {
    name: "convolutional_3"
    data_type: TYPE_FP32
    dims: [ 255, 76, 76 ]
  }
]
ensemble_scheduling {
  step [
    {
      model_name: "preprocess_libtorch"
      model_version: -1
      input_map {
        key: "RESIZED_IMAGE"
        value: "IMAGE"
      }
      output_map {
        key: "NORMALISED_IMAGE"
        value: "preprocessed_image"
      }
    },
    {
      model_name: "trt_nn"
      model_version: -1
      input_map {
        key: "NORMALISED_IMAGE"
        value: "preprocessed_image"
      }
      output_map {
        key: "convolutional_1"
        value: "convolutional_1"
      }
      output_map {
        key: "convolutional_2"
        value: "convolutional_2"
      }
      output_map {
        key: "convolutional_3"
        value: "convolutional_3"
      }
    }
  ]
}
```

**Comment by royinx** [comment]
For Q1 , finally, i solve it using ONNX to define the input and output layers' name, but still want to know how to set up the libtorch config.

**Comment by GuanLuo** [comment]
For libtorch, you can refer to the [documentation](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_configuration.html#model-configuration) on model config:

> PyTorch Naming Convention: Due to the absence of names for inputs and outputs in the model, the “name” attribute of both the inputs and outputs in the configuration must follow a specific naming convention i.e. “<name>__<index>”. Where <name> can be any string and <index> refers to the position of the corresponding input/output. This means if there are two inputs and two outputs they must be name as: “INPUT__0”, “INPUT__1” and “OUTPUT__0”, “OUTPUT__1” such that “INPUT__0” refers to first input and INPUT__1 refers to the second input.

**Comment by CoderHam** [comment]
With respect to **Q1**, you need to produce a traced model, the names of the layers will not be significant, instead the INPUT/OUTPUT__\<index\> will be the naming convention followed. (As described by @GuanLuo)

**Q2** and **Q3**: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/models_and_schedulers.html#ensemble-models Please refer to the docs here.

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if you still have an issue.
