### ISSUE TITLE
Publish client docker image in NGC

### ISSUE THREAD

**Issue by philipp-schmidt** [NVIDIA/tensorrt-inference-server#609]
Would it be possible to publish the recent version of the client container in NGC alongside TRTIS as well?

When using TRTIS in a docker-compose or kubernetes setup, usually there will be a service which uses the client image. Right now, this image has to be built locally and then named/tagged accordingly. It would be way more elegant if it could be pulled directly from NGC as well.

As the client contains all libraries, it could then be used in a multi-stage docker build to compile the actual client application, without having to build the client docker file locally first.

**Comment by deadeyegoodwin** [comment]
We have been considering this for some time (it is a not uncommon request). Right now we are planning to release a "TRTIS examples" container in 19.10 that will include everything from the client container.
