### ISSUE TITLE
Excessive memory usage for Tensorflow SavedModel

### ISSUE THREAD

**Issue by jonchammer** [NVIDIA/tensorrt-inference-server#610]
Hello!

I'm running into some sort of memory issue with TRTIS. I've loaded three Tensorflow SavedModel models which take up a combined 5gb on one GPU. I then start sending a steady stream of requests to the server using the C++ API. (I expect the perf_client would work similarly, though I haven't tried that.) For TRTIS 19.07, my memory usage (RAM) increases for a few minutes until it stabilizes around 12gb (out of 32gb on this machine). For TRTIS 19.08, memory usage does not seem to stop increasing at all. I observed it increasing to at least 26 GB before I killed the server and the client program. 

I've seen issue #207 and the associated explanation, but I'm not sure it's relevant to my situation, as I'm not explicitly using dynamic batching at all. I am using the asynchronous version of the C++ API, but the configuration for each of my models is generated automatically by setting `--strict-model=false` when I start trtserver. 

More information:
- I'm testing using Nvidia's docker images: `nvcr.io/nvidia/tensorrtserver:19.07-py3` and `nvcr.io/nvidia/tensorrtserver:19.08-py3`. I'm currently using docker-compose and running the server with `trtserver --model-store=/models --strict-model-config=false`.
- I have set `shm_size` to 1GB, as suggested in the documentation.
- My three models are all in the Tensorflow SavedModel format. Each is explicitly versioned and the issue presents itself when no config.pbtxt is provided (since they can be generated using the strict-model-config option). I did see the same behavior when I provided a configuration manually, though.
- It doesn't seem to matter which model I use. With a single model, I see the same behavior, but it takes longer for the memory usage to increase. My hypothesis is that I would see the same issue with any TF SavedModel.
- The test machine has 2 1080Ti's, each with 12GB of GPU memory. The issue persists when the server is only allowed to use 1 GPU by setting `CUDA_VISIBLE_DEVICES=0`.
- The server does work apart from the increased memory usage. I can successfully perform inference requests and process the results. Round trip times from the same machine are completely reasonable for my models (10-50ms depending on the model). 
- Round trip times are not affected by the increased memory usage. The server seems to process requests at the same rate while memory usage continually increases. It looks like the server is continually allocating memory somewhere, but never freeing it. 

My questions:
- Is 12GB of RAM usage for a 5GB set of models expected behavior for TRTIS 19.07? I understand that batching will increase the memory consumption, but 12 GB with batching disabled seems a bit excessive to me.
- Has there been a regression between TRTIS 19.07 and 19.08? As I mentioned earlier, memory usage does eventually stabilize for 19.07, but I have not been able to find an upper limit for 19.08. It could be that there is a higher limit for 19.08 or there is a memory leak somewhere that's causing this issue. 

Please let me know if there's any more information I can provide that would be useful. Thanks for your time!

**Comment by deadeyegoodwin** [comment]
Are you using the GRPC protocol or HTTP? For GRPC we have recently fixed some memory inefficiency and other performance issues with the server's handling of GRPC requests. These fixes will not be available until the 19.09 release but you can try them now by using master.

**Comment by jonchammer** [comment]
I am using the GRPC API, so it's good to know the issue may be fixed already. I'll compile from source and reevaluate. Thanks for the advice!

**Comment by deadeyegoodwin** [comment]
Please let us know what you find.

**Comment by jonchammer** [comment]
It looks like the bug has been fixed in master. Memory usage is stable around 5.6gb under load, which is much more reasonable. Thanks for the help!
