### ISSUE TITLE
Output data got from response body is in binary format when doing inference through http post.

### ISSUE THREAD

**Issue by doruime** [NVIDIA/tensorrt-inference-server#633]
how to get raw output data or how to transform binary output data into raw data?

**Comment by taomiao** [comment]
if float32:
    data = read 4 byte from binary_file
    raw_data = unpack_as_float( pack( data ) )

**Comment by deadeyegoodwin** [comment]
Are you trying to write your own client that uses HTTP? You can look at the HTTP client library provided in the repo. Also, did you look at this doc: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/http_grpc_api.html#inference

**Comment by doruime** [comment]
> Are you trying to write your own client that uses HTTP? You can look at the HTTP client library provided in the repo. Also, did you look at this doc: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/http_grpc_api.html#inference

No, I did not do inference using clients script. I used HTTP api "/api/infer/<model name>" to do inference on postman, the outputs displayed were garbled characters followed by an InferResponseHeader message.

In the doc, it says that ouput tensor values are returned in binary format. How can I decode the binary output?

**Comment by deadeyegoodwin** [comment]
As @taomiao showed in the code snipped above, you need to cast the raw data into the appropriate datatype.  The data is the raw output tensors in row-major order. The response header gives the size and datatype of each output.
