### ISSUE TITLE
[Pytorch] Multiple instance of the model on same GPU provide no speedup

### ISSUE THREAD

**Issue by yunzhongyan0** [NVIDIA/tensorrt-inference-server#634]
when i configure pytorch model as multi instances in the same gpu, but there is no speedup. why? (i know it's implemented by multithread)

**Comment by nieksand** [comment]
see https://github.com/NVIDIA/tensorrt-inference-server/issues/366

**Comment by deadeyegoodwin** [comment]
We believe there is a problem with pytorch in some multi-threaded situations. We are trying to isolate the issue so that we can pursue further with pytorch maintainers. @CoderHam will update this thread if/when we have more information or when we file an issue with the pytorch project.

**Comment by CoderHam** [comment]
PyTorch appears to have an issue with threads that causes it to not properly warm up models if executed by different threads  in succession. This is why when using multi-instances of the model on the same GPU, it does not provide a speedup and in some cases is even slower than a single instance.

I have created an issue for the same here: https://github.com/pytorch/pytorch/issues/27902

**Comment by deadeyegoodwin** [comment]
This is a pytorch bug and the tracking pytorch issue is listed above. Closing.
