### ISSUE TITLE
Skip "/api/status/model"?

### ISSUE THREAD

**Issue by JungukCho** [NVIDIA/tensorrt-inference-server#644]
Hi,

I send request  by using image_client example to TRTIS.
 The image_client example always sends "/api/status/model" and then sends "/api/infer/model" to TRTIS.
Is it a simple way of skipping "api/status/model" step?

**Comment by rmccorm4** [comment]
@JungukCho I believe the ServerStatus is called each time to get the model config. 

This isn't best practice or anything, but if you want to avoid the serverstatus calls and are sure that your model config won't be changing at all in between your Infer calls, you can just save the config and replace the ServerStatus code with one of these:
* hard-code config as a map/dictionary (keys are model_name/version or something)
* read config from a local file

**Comment by JungukCho** [comment]
@rmccorm4  Thank you for response.
I will give a shots.

**Comment by JungukCho** [comment]
As a simple workaround, I just use a loop to send sequential requests after performing only one "ServerStatus" request.
