### ISSUE TITLE
Best practice for custom backend with additional resources

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/tensorrt-inference-server#65]
I am building a custom backend which depends on an external model. This model is serialized to disk. What is the best way to access the model from my libcustom.so? I would like to put next to the libcustom.so in the model repository. How can I read it without knowing the path to the model repository?

**Comment by deadeyegoodwin** [comment]
We've been thinking about a general "parameter" mechanism for custom backends, and this is a good example use case. I will mark this issue as an enhancement request.

For now, depending on your use-case, can you set an environment variable when you launch the server that has the model repository path, and then read that environment variable in your custom backend?

**Comment by mrjackbo** [comment]
> For now, depending on your use-case, can you set an environment variable when you launch the server that has the model repository path, and then read that environment variable in your custom backend?

Thanks, that's what I've been doing for development. For portability of the model store, a parameter mechanism would certainly be very nice.

**Comment by deadeyegoodwin** [comment]
This is now fixed on master and will be in the 19.03 release (late March). There was a change to the custom backend API that will require a source-code update (see CustomInitialize in custom.h).
