### ISSUE TITLE
Basic examples with the gRPC and/or REST API Plzzzzzzzzzzzzzzzzz!

### ISSUE THREAD

**Issue by whillas** [NVIDIA/tensorrt-inference-server#651]
I just built the Docker.client file from this repo and its 2.85GB... so i can make simple REST API/gRPC request...? This seems to be because the server and the client have to be intimately connected via the `tensorrtserver.api` module. We are sacrificing: decoupling, ease of development and deployment, and portability, what do we gain from this?

Isn't the whole idea of REST APIs and gRPC is to completely decouple client from server? All the client examples seem to violate this principle and makes it hard to integrate with existing pipeline.

IS this really necessary and if not can we get an example without the overhead please.

**Comment by deadeyegoodwin** [comment]
What do you mean by "intimately connected"? tensorrtserver.api is the python implementation of the client library. The server itself doesn't use that library in any way. Clients can use that library (or the C++ version which is librequest.so) to make it easier to talk to the server... but you don't have to. For example, you can just use grpc directly as is done in this example: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/grpc_image_client.py

The primary reason that the image is so large is that it includes all the examples as well as all the dependencies needed to run the examples. Python, curl, opencv, etc. These dependencies are what account for most of the size. The intent of the container is to make it easy to build and experiment with the client libraries and examples. But, for example, if you just need the python library you can copy the wheel out of the container and use it elsewhere. The client library, examples, wheel are also available in a tar file along with the github release.

**Comment by whillas** [comment]
https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/grpc_image_client.py

Lines 37 to 40 :
```python
from tensorrtserver.api import api_pb2
from tensorrtserver.api import grpc_service_pb2
from tensorrtserver.api import grpc_service_pb2_grpc
import tensorrtserver.api.model_config_pb2 as model_config
```
Its using the `tensorrtserver.api` isn't it? What i'm asking for is an example which _does not_ used the client API so I _do not_ have to compile it into my conatainer an just use _standard_ gRPC tools like `google.protobuf` say

**Comment by GuanLuo** [comment]
Those are just the Python code generated from the `.proto` files, which defines the gRPC service and protobuf message required to communicate with the server. You will always have to compile at least those `.proto` files to be able to use the defined gRPC service, the example client imports those file from `tensorrtserver.api` just because it knows they are there.

**Comment by whillas** [comment]
Hey thanks, i didn't see the .proto files as they were mixed in with the `.cc` and `.h` files (even though they are not specific to C++. Thanks for the quick replys btw!

**Comment by whillas** [comment]
So I'm trying to build the most simple client example with this Dockerfile:
```Dockerfile
FROM python:3-slim

COPY ./tensorrtserver-*.whl /tmp
RUN python3 -m pip install --upgrade /tmp/tensorrtserver-*.whl

WORKDIR /home/
COPY ./src .
COPY ./requirements.txt .

RUN python3 -m pip install -r requirements.txt

CMD python3 -c "import tensorrtserver.api"
```
and i'm getting this error? 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/tensorrtserver/api/__init__.py", line 54, in <module>
    _request = cdll.LoadLibrary(_request_path)
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurl.so.4: cannot open shared object file: No such file or directory
```
I have copied the wheel to the root of the project. what other dependencies does that wheel have?

**Comment by whillas** [comment]
Perhaps the `.proto` files should be in a separate dir. and a note somewhere in the documentation indicating this possibility? Just a thought.
