### ISSUE TITLE
The result is  inf,  inf,  nan,  nan

### ISSUE THREAD

**Issue by 17702513221** [NVIDIA/tensorrt-inference-server#663]
When i use https://github.com/onnx/models/tree/master/vision/object_detection_segmentation/yolov3
yolo_onnx，i get a result is {'yolonms_layer_1/concat_2:0': [array([[  0,   2, 295],
       [  0,   2, 334],
       [  0,   2, 296],
       [  0,   2, 292],
       [  0,   2, 335],
       [  0,   2, 293]], dtype=int32)], 'yolonms_layer_1/ExpandDims_1:0': [array([[[ inf,  inf,  nan,  nan],
        [ inf,  inf,  nan,  nan],
        [ inf,  inf,  nan,  nan],
        ...,
        [ nan,  nan, -inf, -inf],
        [ nan,  nan, -inf, -inf],
        [ nan,  nan, -inf, -inf]]], dtype=float32)], 'yolonms_layer_1/ExpandDims_3:0': [array([[[0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         6.2749746e-07, 3.3311238e-08, 1.8711241e-08],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         4.4770928e-08, 4.2710724e-09, 1.1641390e-09],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         4.4897325e-07, 7.8852764e-09, 5.7048197e-09],
        ...,
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         5.2795883e-08, 3.2432723e-09, 1.0933263e-09],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         6.7517078e-08, 4.0316763e-09, 1.2484946e-09],
        [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, ...,
         9.8714821e-08, 2.3795792e-09, 1.6869421e-09]]], dtype=float32)]}]
can you help me to deal with this problem

**Comment by GuanLuo** [comment]
Can you provide more information about:
- What TRTIS version that you are using. And how to reproduce the issue, i.e. command to start the server, the config used for the model, the command to run the client, and the input image.
- What is the expected result? Say if you run the model with the same inputs directly on ONNX Runtime, what is the outputs that you get?
