### ISSUE TITLE
HTTP keep-alive

### ISSUE THREAD

**Issue by ligonzheng** [NVIDIA/tensorrt-inference-server#669]
Hello,
    I would like to use jmeter to make a pressure test with trtis but I encounterd this problem : 
    can not assign requested address (Address not available).
    The reason for this problem is because the clients run out of all the ports and a good solution is to make the http use keep-alive. But the server seems to close the keep-alive(I can not find the keep-alive header option). What's the http version for trtis ? 1.0 or 1.1 ?
    So I wonder if there any way to open this property ?
  Thank you very much.

**Comment by deadeyegoodwin** [comment]
The server should not be closing a connection after each request.. we will take a look.

**Comment by ligonzheng** [comment]
@deadeyegoodwin , do you check it ?

**Comment by ligonzheng** [comment]
I had use wireshake to capture a message, It shows the http is 1.1.
Thank you !
