### ISSUE TITLE
Doesn't ModelControlAPI manage unloaded model's GPU memory?

### ISSUE THREAD

**Issue by lazykyama** [NVIDIA/tensorrt-inference-server#675]
This is just a question.

I've tried to use ModelControlAPI and faced an issue that one model loading failed even after unloading another model that requires huge GPU memory.
For example, the GPU has 12GiB memory, model1 requires ~9GiB to run an inference and model2 requires ~4GiB. In this case, after loading model1, trying to load model2 failed due to OutOfMemory. So, I expected that I can load model2 by unloading model1. However, currently failed. Even if unloading model1, GPU memory wasn't released.

Is that an expected behavior? If so, I hope these details are described in the document.

**Comment by deadeyegoodwin** [comment]
What type of model are you using. As we note here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_management.html#model-control-mode-explicit, this mode is experimental because some frameworks have trouble loading/unloading models. We are going to do some more characterization of which frameworks can handle load/unload well and which can't. Right now our suspicion is that both TensorFlow and PyTorch do not manage memory well when you repeatedly load/unload models.

**Comment by lazykyama** [comment]
Thank you for the comment.
Currently, ResNet50 and etc are targets, and right now these models are for evaluation. I know this feature is experimental so please consider more flexible memory management by ModelControlAPI.

**Comment by deadeyegoodwin** [comment]
The model itself (like resnet50) is not the problem. It is the framework backend. We will document our findings once we do more thorough characterization of the frameworks.

**Comment by benjaminhon** [comment]
@deadeyegoodwin however if i convert tensorflow to graphdef, is it still using tensorflow backend?

**Comment by deadeyegoodwin** [comment]
Yes. Saved-model and graphdef are two model formats for Tensorflow. Saved-model has a graphdef embedded within it with additional metadata. Once loaded both model formats are handled the same by TF.

**Comment by benjaminhon** [comment]
@deadeyegoodwin  if i convert the graphdef to TensorRT, but not all the layers can be converted, so it ends up being a mix between tensorflow and TensorRT, is there still going to be a problem with the loading/unloading? 

Also, do you know if the problem of the loading/unloading will lead to a memory leak in which memory cant even be recovered? And the only solution is to restart the triton server?

What i mean is this, if i can unload a 40% of a tensorflow model, when when i load it back i only need to load the remaining 60%. As long as the memory is not leaking and becoming unusable i think its still ok. But if i repeatedly load and unload for eg. m1-m2-m1-m2-m1-m2 , and after 100 tries it OOMs, then this suggests some type of memory leak with is unsafe

**Comment by deadeyegoodwin** [comment]
If you use an offline tool on a TF model to add TensorRT optimization, the resulting model is still a TF model and is managed by the TF framework like any other TF model. We don't know of any memory leak in TF (or other framework) on repeated load/unload and we even have a CI test for it. But as I mentioned in the other ticket TF will not return its memory to the system, even if you unload all TF models. There is a commandline flag to limit how much GPU memory TF can have which can be useful if you want to make sure TF doesn't use all GPU memory.
