### ISSUE TITLE
GDB cannot access memory

### ISSUE THREAD

**Issue by Inujel** [NVIDIA/tensorrt-inference-server#679]
I'm trying to use GDB, but it doesn't seem to work:
$ nvidia-docker run --rm -it --cap-add=ALL --security-opt seccomp=unconfined nvcr.io/nvidia/tensorrt:19.09-py3 
root@ab09931aa139:/workspace# apt -y install gdb
root@ab09931aa139:/workspace# echo "int main() { return 0; }" > app.c
root@ab09931aa139:/workspace# gcc app.c
root@ab09931aa139:/workspace# gdb
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
...
(gdb) file a.out
Reading symbols from a.out...(no debugging symbols found)...done.
(gdb) b main
Breakpoint 1 at 0x5fe
(gdb) run
Starting program: /workspace/a.out
Warning:
Cannot insert breakpoint 1.
Cannot access memory at address 0x5fa

In another image (I tried alpine + apk add gcc gdb), it works as expected:
(gdb) run
Starting program: /a.out

Breakpoint 1, 0x000055555555518e in main ()

**Comment by deadeyegoodwin** [comment]
The TRTIS container doesn't do anything special to either enable or disable gdb. Perhaps you should compile with "gcc -g app.c" so that debug information is included in the build?

**Comment by CoderHam** [comment]
Try deleting all existing breakpoints before adding your own. -> `delete`

**Comment by Inujel** [comment]
> The TRTIS container doesn't do anything special to either enable or disable gdb. 
You're right, I'm posting on the wrong project. My error occurs in the base image nvcr.io/nvidia/tensorrt. Sorry about that.
