### ISSUE TITLE
How to retrieve output tensor values (C++ Api)

### ISSUE THREAD

**Issue by francescooliva** [NVIDIA/tensorrt-inference-server#684]
Hi,
I have my own traced pytorch model with this configuration:
name: "mymodel"
platform: "pytorch_libtorch"
max_batch_size: 32
input[
  {
    name: "input__0"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 256, 456 ]
  }
]
output[
  {
    name: "output__0"
    data_type: TYPE_FP32
    dims: [19, 32, 57 ]
  },
  {
    name: "output__1"
    data_type: TYPE_FP32
    dims: [38, 32, 57  ]
  },
  {
    name: "output__2"
    data_type: TYPE_FP32
    dims: [19, 32, 57 ]
  },
  {
    name: "output__3"
    data_type: TYPE_FP32
    dims: [38, 32, 57  ]
  }
] 

I'd like to get float values from the output tensors above, with libtorch I can do this operation with some simply instructions, i.e:
    auto out0= output[0].toTensor().to(torch::Device(torch::kCPU));
    const float * out0Buffer = out0.data<float>();

I know in the Sdk there is a function  GetRaw(size_t batch_idx, const std::vector<uint8_t> **buf)  but is not clear enough  for me how to get a vector of float, maybe something like this?
    std::map<std::string, std::unique_ptr<nic::InferContext::Result>> results;
    const uint8_t * data_ptr;
    float * out0Buffer;
    size_t data_byte_size;
    results["output__0"]->GetRaw(0, &data_ptr, &data_byte_size);
    std::memcpy(out0Buffer, data_ptr, data_byte_size);

thanks

**Comment by GuanLuo** [comment]
` GetRaw(size_t batch_idx, const std::vector<uint8_t> **buf)` will return the raw data for the specific batch entry in buf, after that, you can get the pointer to the raw data by `buf.data()` (you can cast the pointer to float* since you know your data is in float) and the byte size of the raw data by `buf.size()`.

And your other approach that uses `GetRaw(size_t batch_idx, const uint8_t** buf, size_t* byte_size) ` will also work

**Comment by francescooliva** [comment]
Thank you for you quick response, I'm still struggling to get the expected tensor output values that I get with Libtorch, I'm using GetRaw function this way:
```cpp
        const std::vector<uint8_t> *buff;
	results["output__0"]->GetRaw(0, &buff);
        float *outputBuffer = new float[buff->size()/sizeof(float)];
	std::memcpy(reinterpret_cast<float*>(&outputBuffer[0]), (buff)->data(), buff->size());
```
I don't know if I'm doing something wrong with the code above or maybe I'm messing something in the preprocessing part, to set the input image I basically copy pasted the image_client.cc example from the repo.

To set the options object according to my .pbtxt output I posted before:
```cpp
std::unique_ptr<nic::InferContext::Options> options;  
	err = nic::InferContext::Options::Create(&options);  
	if (!err.IsOk()) {
		std::cerr << "failed initializing infer options: " << err << std::endl;
		exit(1);
	}
	options->SetBatchSize(batch_size);
	std::cout << ctx->Outputs().size() << std::endl;
	for (const auto& output : ctx->Outputs()) {
		options->AddRawResult(output);
	}
	err = ctx->SetRunOptions(*options);
	if (!err.IsOk()) {
		std::cerr << "failed initializing batch size: " << err << std::endl;
		exit(1);
	}```
