### ISSUE TITLE
Can you help me how to freeze_graph right pb

### ISSUE THREAD

**Issue by 17702513221** [NVIDIA/tensorrt-inference-server#704]
I use https://github.com/YunYang1994/tensorflow-yolov3,get a pb model.But the error is 
error: creating server: INVALID_ARG - must specify platform for model 'yolov3pb'

yolov3pb/
1/
model.graphdef/
yolov3_coco.pb

The freeze_graph.py:
import tensorflow as tf
from core.yolov3 import YOLOV3

pb_file = "./yolov3_coco.pb"
ckpt_file = "./checkpoint/yolov3_coco_demo.ckpt"
output_node_names = ["input/input_data", "pred_sbbox/concat_2", "pred_mbbox/concat_2", "pred_lbbox/concat_2"]

with tf.name_scope('input'):
    input_data = tf.placeholder(dtype=tf.float32, name='input_data')

model = YOLOV3(input_data, trainable=False)
print(model.conv_sbbox, model.conv_mbbox, model.conv_lbbox)

sess  = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
saver = tf.train.Saver()
saver.restore(sess, ckpt_file)

converted_graph_def = tf.graph_util.convert_variables_to_constants(sess,
                            input_graph_def  = sess.graph.as_graph_def(),
                            output_node_names = output_node_names)

with tf.gfile.GFile(pb_file, "wb") as f:
    f.write(converted_graph_def.SerializeToString())

**Comment by bezero** [comment]
where is your config file for yolov3pb?

**Comment by 17702513221** [comment]
l use --strict-model-config = false

**Comment by rmccorm4** [comment]
@17702513221 `--strict-model-config=false` isn't guaranteed to work for all models. You can see what TRTIS was able to determine from your model by checking the Status API with `curl localhost:8000/api/status/`

As mentioned in the docs, only **some** TF models will work with this flag: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_configuration.html#generated-model-configuration

I believe this only works when the model's metadata contains all of the required config - and I'm not sure this will happen with frozen_graph/graphdef - you may have better luck with TF SavedModel format instead.

----

You can first try to cut and paste the configuration that TRTIS determined from `--strict-model-config=false` into a `config.pbtxt` file

But then as the error suggests, TRTIS wasn't able to determine the model platform, so you will need to at least add/specify `platform: tensorflow_graphdef` and go from there.

**Comment by 17702513221** [comment]
Thank you

**Comment by rmccorm4** [comment]
@17702513221 Also just wanted to add, I believe the model filename is how TRTIS determines the platform without a config file, so you could also try renaming your model to the default for tensorflow_graphdef which is `model.graphdef` instead of `yolov3_coco.pb` as seen in docs here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_repository.html#tensorflow-models

**Comment by GuanLuo** [comment]
One other thing is that you can turn on verbose logging (`--log-verbose=1`), then the autofill will also log the kinds of backend framework it has been tried, and why if the autofill failed on the framework.
