### ISSUE TITLE
Loading tftrt optimized models

### ISSUE THREAD

**Issue by ohlr** [NVIDIA/tensorrt-inference-server#706]
I try to load models from https://github.com/tensorflow/tensorrt.

To build the models I use the tensorrt 19.02 docker image (last one with Cuda 10.0) from ngc.
And install tensorflow (needs Cuda 10.0) + tf-trt in it.

Loading these images on the currrent trtis image from ngc fails, because of Cuda version missmatch 10.0 vs 10.1. (I guess that's the reason)

The 19.02 image of tensorrt inference-server somehow does not work because it fails with ` /bin/bash: error while loading shared libraries: libcublas.so.10`.

Is there any smart way to align the cuda versions of tensorrt, tensorrt-inference-server and tensorflow? I would like to avoid building everything from scratch.

**Comment by deadeyegoodwin** [comment]
You should be able to run the 19.02 TRTIS container but you need to make sure that your host system has the correct version of CUDA. Release notes are here: https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-02.html#rel_19-02

You can find what is included in each version of the container here: https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html

To generate the TF-TRT model you are using the 19.02 TensorRT container... that's good but do you need to install your own TF into that? There is a specific version of TF that is compatible with 19.02. Is that not already installed in the TensorRT container?

**Comment by ohlr** [comment]
Thanks for the pointer to the documentation. However the Cuda version on the host was actually not the issue (As it says in the release notes: The inference server can now be run on systems without GPUs or that do not have CUDA installed.)

The error was caused by a plugin that i loaded with my docker command. I think 19.02 did not have plugin support yet - my bad.

**Comment by deadeyegoodwin** [comment]
Glad to hear that you figured it out.
