### ISSUE TITLE
Feature request: model warmup

### ISSUE THREAD

**Issue by nieksand** [NVIDIA/tensorrt-inference-server#708]
It would be nice if TRTIS offered an option to warm up  specific models at startup, similar to this TFS feature:

https://www.tensorflow.org/tfx/serving/saved_model_warmup

Two real situations I've encountered where this would help:

1. The first time a Tensorflow SavedModel comes up, there can be a huge latency spike on inference.  (e.g. inference on warm model takes 200ms, inference on cold model takes 10000ms).
2. Using Tensorflow+TRT with Dynamic Shapes, you can get massive compile times.  One of the CNNs we use for semantic segmentation takes over 5 minutes to compile on an AWS g4 instance.  (T4 GPU).

It would be nice if TRTIS stayed in a not-ready state while warming up, making it easier to withhold the instance from a load balancer until it's ready to service requests with reliable latency.

**Comment by deadeyegoodwin** [comment]
In principle I agree, though in practice those using such a feature would need to be aware of. These do not block the feature but would make it likely that it would not be on by default:
1. Some models do not behave well when given random input (which would be needed for warming up).
2. As noted, it could take a long time for the container to become ready for some warmups. A typical deployment would not wait 10+ minutes on a container that was not indicating ready... so the configuration (e.g. kubernetes) would need to be modified to allow that...

**Comment by aleksa2808** [comment]
I would also love to see this as an optional feature, since I had the same issues (especially with TF-TRT models). 

Furthermore, when I have a larger instance_group, each model has a separate compilation delay, which, combined with a non sequential scheduler (eg. sending the first few requests to the first model copy, and only then using and initializing the second one), prolongs the time until the specific model becomes reliable.

Is the best we can do to combat this at the moment sending a bunch of random initial requests and hoping each model copy would get hit?

**Comment by GuanLuo** [comment]
Hi all, PR #791 is for adding model warmup option and it has been merged into master. Please feel free to try it out.

**Comment by whatdhack** [comment]
@GuanLuo @deadeyegoodwin , can you please provide an example of warm up config for a Tensorflow Saved Model ?

**Comment by nieksand** [comment]
```
model_warmup {                                                                        
    name: "4x4 Warmup"
    batch_size: 1                                                                     
    inputs: {                                                                         
        key: "input"                                                                  
        value: {                                                                      
            data_type: TYPE_FP32                                                      
            dims: 1024                                                                
            dims: 1024                                                                
            dims: 3                                                                   
            zero_data: true                                                           
        }                                                                             
    }                                                                                 
}  
```

**Comment by zacharyhorvitz** [comment]
It looks like this link:
 `https://docs.nvidia.com/deeplearning/triton-inference-server/master-user-guide/docs/protobuf_api/model_config.proto.html#_CPPv4N6nvidia15inferenceserver11ModelConfig12model_warmupE`

Is broken, and now links to the licensing info/back to the github repo. The readme does not specify much about model_warmup configs. Is there consolidated info somewhere about warmup configurations (e.g, how we pass in custom data)?

**Comment by deadeyegoodwin** [comment]
That link is outdated, use https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#model-warmup

**Comment by zacharyhorvitz** [comment]
> That link is outdated, use https://github.com/triton-inference-server/server/blob/main/docs/model_configuration.md#model-warmup

The readme does not specify much about model_warmup configs. Are their docs with examples? I've so far been looking through #791.

**Comment by deadeyegoodwin** [comment]
The tests are often a good source for examples: https://github.com/triton-inference-server/server/tree/main/qa/L0_warmup
