### ISSUE TITLE
Issue with simple_string model in the examples

### ISSUE THREAD

**Issue by jhagege** [NVIDIA/tensorrt-inference-server#71]
Hi, when trying to run trtis nvidia-docker image, I get the following error: 
`nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/mnt/workspace/jo/trtis/tensorrt-inference-server/docs/examples/model_repository:/models nvcr.io/nvidia/tensorrtserver:19.01-py3 trtserver --model-store=/models`

> [libprotobuf ERROR external/protobuf_archive/src/google/protobuf/text_format.cc:307] Error parsing text-format nvidia.inferenceserver.ModelConfig: 9:5: Unknown enumeration value of "TYPE_STRING" for field "data_type".
> E0203 11:52:45.284641 1 server.cc:574] Can't parse /models/simple_string/config.pbtxt as text proto
> E0203 11:52:47.226951 1 metrics.cc:238] failed to get energy consumption for GPU 0, NVML_ERROR 3

This is after I downloaded the models with the script.

Thanks

**Comment by jhagege** [comment]
Also, do you know how to fix the following error message ? 

> E0203 11:53:54.811522 1 metrics.cc:238] failed to get energy consumption for GPU 0, NVML_ERROR  3 

I am using a Tesla P100 with following nvidia-smi info:

>  NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0

**Comment by GuanLuo** [comment]
The STRING type support and simple_string example is added in 19.02 version. To try it out, you will need to wait for the release of 19.02 container or build the TRTIS from source with `docker build --pull -t tensorrtserver .`

If you just want to try running the 19.01 container, you can checkout the r19.01 branch and retrieve the models there.

**Comment by deadeyegoodwin** [comment]
> Also, do you know how to fix the following error message ?
> 
> > E0203 11:53:54.811522 1 metrics.cc:238] failed to get energy consumption for GPU 0, NVML_ERROR  3
> 
> I am using a Tesla P100 with following nvidia-smi info:
> 
> > NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0

The energy consumption metric is not available on P100, the other metrics will still be collected. That message should really be a warning... we will fix.

**Comment by deadeyegoodwin** [comment]
Closing. Please reopen if you still have an issue.

**Comment by gitvipin** [comment]
If anyone comes here from documentation (https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/quickstart.html) hoping to run simple example and sees this error one way to get around is to ignore "simple_string" model. 

- I moved simple_string from models directory and my run went moved ahead of this. Essentially with this all but simple_string model would be available for inference. 

- I had tried building inference server from source but it took painfully long time (> 4 hours) for me as my m/c was very basic on Google Cloud (4 GB , 1 vCPU)

**Comment by gitvipin** [comment]
@deadeyegoodwin : HI David, When I run the following command it works well for K80 as well as P100 GPUs. Is it some other power consumption that we collect in metrics ? 

sh_vipin@instance-1:~$ nvidia-smi --query-gpu=power.draw --format=csv
power.draw [W]
59.88 W

**Comment by deadeyegoodwin** [comment]
@gitvipin There are two power/energy related metrics reported by TRTIS. The one questioned in this issue was the energy consumption metric. The instantaneous power metric (which is what I assume you are seeing with power.draw) does seem to be available on K80 and P100 and is reported by TRTIS.

**Comment by jhagege** [comment]
Thanks much for your thorough answer ! It helped much.
