### ISSUE TITLE
Metrics on Jetson TX2 do not contain nv_gpu information

### ISSUE THREAD

**Issue by ohlr** [NVIDIA/tensorrt-inference-server#714]
Hi,

I followed the instructions in PR [#575](https://github.com/NVIDIA/tensorrt-inference-server/pull/575) to build trtis on jetson.

Everything works fine, except the metrics do not contain the `nv_gpu` entries.
I think it is due to the known issue (3) that NVML is not supported on Jetson.

I get the following errors:
On startup:
```
E0821 06:27:34.280622 6 metrics.cc:147] failed to initialize NVML: NVML_ERROR 9
```
When running the inference:
```
E1001 metrics.cc:348 failed to get device from PCI BUS ID:: NVML_ERROR 1
```

With the nvidia tegrastats tool it is possible to obtain information about the gpu usage.

https://github.com/FindHao/tx-utils
https://github.com/rbonghi/jetson_stats

Do you think it is possible to integrate that information from there?

**Comment by deadeyegoodwin** [comment]
Possibly, but why not run those tools in parallel with TRTIS to monitor GPU usage. TRTIS provides the GPU metrics because it is convenient for some use cases, but typically it is better to have a separate monitoring process.

**Comment by ohlr** [comment]
Some arguments:
- convenience (as developer I want to run the same code on jetson and T4) 
- license compatibility (other projects are licensed AGPL or do not even have a license)
- integration with prometheus
But I can understand that trtis is not initially designed for the jetson series and it would add quite some complexity.

**Comment by deadeyegoodwin** [comment]
Closing. Thanks for your feedback.
