### ISSUE TITLE
image_client libopencv_highgui.so error

### ISSUE THREAD

**Issue by jhagege** [NVIDIA/tensorrt-inference-server#72]
When trying to launch image_client (after comping with docker build, and copying the executables to /tmp on host machine, I get the following error:

`./image_client: error while loading shared libraries: libopencv_highgui.so.2.4: cannot open shared object file: No such file or directory`

Happy to get help.
Thanks.

**Comment by GuanLuo** [comment]
Have you installed the additional dependencies needed to run on your host machine?

https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/client.html#building-the-client-libraries-and-examples

**Comment by deadeyegoodwin** [comment]
Closing. Please reopen if your issue is not resolved.
