### ISSUE TITLE
failed to load Tensor shape expected by framework [] doesn't match model configuration shape [-1]

### ISSUE THREAD

**Issue by gr8Adakron** [NVIDIA/tensorrt-inference-server#727]
I am trying to load the model which is text and doesn't have specific input shape this is my config file:
```
name: "model"
platform: "tensorflow_savedmodel"
max_batch_size: 16
input [
  {
    name: "label_ids"
    data_type: TYPE_INT64
    dims: []
  },
  {
    name: "input_ids"
    data_type: TYPE_INT64
    dims: [128]
  },
  {
    name: "input_mask"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [128]
  },
  {
    name: "segment_ids"
    data_type: TYPE_FP32
    format: FORMAT_NHWC
    dims: [128]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1300 ]
  }
]
instance_group [
  {
    count: 1
    gpus: [0]
  }
]
dynamic_batching {
      preferred_batch_size: [ 16 ]
      max_queue_delay_microseconds: 100
    }

```

I know that labels_id doesn't have specific shape, but when I give empty list I get this error:

> **E1003 18:35:18.944193 1 server.cc:137] model input must specify 'dims' for model**

And when I try with **[-1]** I get this error:

> 
**failed to load 'mode' version 1: Invalid argument: unable to load model 'model', tensor 'label_ids' shape expected by framework [] doesn't match model configuration shape [-1]**

Any help?

My command:
`**sudo nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/home/serving/teste/models_trt:/models nvcr.io/nvidia/tensorrtserver:19.06-py3 trtserver --model-store=/models --strict-model-config=false**`

**Comment by gr8Adakron** [comment]
@dougn @swarren @aaronp24 @mkolod

**Comment by deadeyegoodwin** [comment]
You are using --strict-model-config=false but also providing a config.pbtxt? Can you try without supplying a config.pbtxt and then use the /api/status endpoint to see what configuration TRTIS created for you. I think you likely need a reshape in there...

**Comment by gr8Adakron** [comment]
@deadeyegoodwin it's a bug buddy! I tried all of it. What will be the **dims** when that tensor doesn't have any? 
Two issues:

1. empty list [] doesn't work as it thinks something is missing.
2. nor does the [-1] notation of dynamic dim work.

**Comment by deadeyegoodwin** [comment]
The APIs to talk to the server require that all inputs and outputs are tensors with some shape, that is why shape [ ] is not allowed in the model configuration.  But for your model there is a reshape command that you can put in the config file to tell TRTIS that the model is expecting a different shape than what the model config specifies. The auto config generator (--strict-model-config=false)  should generate this for you. 

For the auto config generator to generate your input and output configuration you should not provide config.pbtxt yourself. Can you try that and send the output of /api/status.

**Comment by gr8Adakron** [comment]
@deadeyegoodwin thanks! reshaping worked.
```

 {
    name: "label_ids"
    data_type: TYPE_INT64
    dims: [1]
    reshape: { shape: [] }
  }

```
Closing it!

**Comment by yoonjaecho** [comment]
@deadeyegoodwin 

Hi, I'm trying to use trtis for serving instance segmentation now.

But there is a problem with multiple dynamic variable size in detection masks.

Here is my part of config.pbtxt
~~~
output [
  {   # This part
    name: "output_detection_masks__0"
    data_type: TYPE_BOOL
    dims: [ -1, -1, -1 ]
  },
  {
    name: "output_detection_classes__1"
    data_type: TYPE_INT64
    dims: [ 1 ]
    reshape: { shape: [ ] }
  },
  {
    name: "output_detection_scores__2"
    data_type: TYPE_FP32
    dims: [ 1 ]
    reshape: { shape: [ ] }
  }
]
~~~

where "output_detection_masks__0" returns ( # detected objects, h, w) shape tensor. (they always have a different shape.)

~~~
tensorrtserver.api.InferenceServerException: [inference:0 21] output 'output_detection_masks__0' for model 'solov2' has shape [427,640] but model configuration specifies shape [-1,-1,-1]

tensorrtserver.api.InferenceServerException: [inference:0 21] unexpected shape for output 'output_detection_masks__0', model configuration shape is [1,-1,-1], inference shape is [100,427,640]
~~~

I've tried several combinations ([1, 1, 1] with reshape([]), [-1, 1, 1] with reshape([]).. ) with `--strict-model-config=false` option, but couldn't figure it now.

Could you help me?

**Comment by deadeyegoodwin** [comment]
@yoonjaecho This is an old closed issue. Can you file a new issue with your question and delete your comment from this issue.
