### ISSUE TITLE
trtis loads model but does not detect input/output nodes

### ISSUE THREAD

**Issue by ohlr** [NVIDIA/tensorrt-inference-server#735]
I try to load a tftrt model generated with nvidida tensorflow container. All container versions are 19.02.

Although the optimized model is loaded it does not find input and output nodes. Thus I can't use it for inference.

I tried with different batchsizes and models. Moreover I use strict_config=false. I guess I have to additionaly specify a `config.pbtxt` is that correct? If yes, is there a way to automate that process - at least for the tftrt models?

Output from curl `http://0.0.0.0:8000/api/status/`
```
model_status {
  key: "inception"
  value {
    config {
      name: "inception"
      platform: "tensorflow_graphdef"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      instance_group {
        name: "inception"
        count: 1
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "model.graphdef"
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
      }
    }
  }
}
ready_state: SERVER_READY
```

**Comment by ohlr** [comment]
I set `is_dynamic_op=False` in the `TrtGraphConverter` but the behavior still remains the same.

So my explanation to this is that the models from tftrt are dynamic (code snippet below). Thus the GraphConverter can not create a static model -> trtis does not auto detect input+output nodes.
```
input node:
dtype
{"type":"DT_UINT8"}
shape
{"shape":{"dim":[{"size":-1},{"size":-1},{"size":-1},{"size":3}]}}
```

**Comment by ohlr** [comment]
I fixed the input shape now using `exporter.export_inference_graph` however this still does not change anything.

**Comment by GuanLuo** [comment]
For graphdef, the autofill can't set the inputs and outputs in model config as the graphdef itself doesn't provide sufficient information to set those fields. You will have to provide those fields, or you can try to use the savedmodel format of the model.

**Comment by ohlr** [comment]
Thanks you are right, with the savedmodel format trtis automatically parses all model parameters.

Are there any differences in performance between savedmodel and graphdef?

**Comment by deadeyegoodwin** [comment]
The automatic config generator does not know what the maximum batch size is so it conservatively sets it to 1. You can have a config.pbtxt that sets it to whatever you want and TRTIS will automatically generate the rest of the configuration. There should be no performance different between graphdef and savedmodel. They both execute in the same TF backend. Tensorflow has stated that starting with TF2.0 graphdef is no longer supported. So the future is savedmodel only.
