### ISSUE TITLE
Integration with DALI-based custom backend for preprocessing?

### ISSUE THREAD

**Issue by PJ7668** [NVIDIA/tensorrt-inference-server#736]
I'm looking for the correct way to deploy a model trained with DALI pre-processing (https://github.com/NVIDIA/DALI). My initial thought was that there should be some way to treat the DALI pipeline as a custom backend or as a TensorRT model run as part of an ensemble model. Neither of these are a perfect fit since the DALI pipeline would have been setup to get its data in some other format (e.g. reading jpegs from disk).

I figured that this use case must be common or on the road map but I can't find any examples or documentation mentioning this use case. Is this use case somehow supported between DALI and TRTIS now?

Thanks!

**Comment by PJ7668** [comment]
I realized that this was probably a better question for the DALI project and got an answer on this thread: https://github.com/NVIDIA/DALI/issues/17

**Comment by JanuszL** [comment]
https://github.com/triton-inference-server/dali_backend should fulfil your ask (at least partially).
