### ISSUE TITLE
librequest.so undefined reference to `nvidia::inferenceserver::InferResponse::~InferResponse()' in C++ implementing

### ISSUE THREAD

**Issue by PengfeiGo** [NVIDIA/tensorrt-inference-server#744]
Hello,
My project code is written in C++, and I want to use it in tensorrt-inference-server, 
header file(.h)  include 
#include "request_grpc.h"
#include "request_http.h"

CMakeList flie include librequest.so
FIND_LIBRARY(REQUEST_LIB request ${ThirdLIB_DIR}/lib)
target_link_libraries(myProject ${REQUEST_LIB})

source file include following:
namespace ni = nvidia::inferenceserver;
namespace nic = nvidia::inferenceserver::client;

when I build, there is error pointing that librequest.so undefined reference to
opt/third/lib/librequest.so: undefined reference to `nvidia::inferenceserver::InferResponse::~InferResponse()'
undefined reference to `nvidia::inferenceserver::ServerStatus::Swap(nvidia::inferenceserver::ServerStatus*)'
........
so many undefined reference to 

I use tensorrt-inference-server 1.3.0 and the library is downloaded from release https://github.com/NVIDIA/tensorrt-inference-server/releases

Thank u!

**Comment by GuanLuo** [comment]
These symbols are related to the protobuf files (i.e. [grpc_service](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/grpc_service.proto)). Is gRPC installed in your system?

**Comment by PengfeiGo** [comment]
> These symbols are related to the protobuf files (i.e. [grpc_service](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/grpc_service.proto)). Is gRPC installed in your system?

I solve the problem by following:
I use tensorrt-inference-server 1.3.0 and the library is downloaded in version 1.6.0 from release https://github.com/NVIDIA/tensorrt-inference-server/releases

Interesting, right?
