### ISSUE TITLE
CUDNN_STATUS_MAPPING_ERROR 

### ISSUE THREAD

**Issue by jpark621** [NVIDIA/tensorrt-inference-server#745]
Hi, I am currently deploying a finetuned BERT model on TensorRT server. Most of the time, the server works fine, but every now and then, there is a CUDNN_STATUS_MAPPING_ERROR.

![image](https://user-images.githubusercontent.com/52423081/66464267-82c9b680-ea33-11e9-86ab-cddf03947807.png)

The cuDNN documentations seems to indicate that it is either a memory issue or an internal bug (https://docs.nvidia.com/deeplearning/sdk/cudnn-developer-guide/index.html). Is there anyone else encountering this issue, and if so, is there a proper way to address it? Thank you!

**Comment by GuanLuo** [comment]
This error is logged when a request is sent to the model? Or even when the server is just running? You can try to run the server with `--log-verbose=1` to provide verbose logging.

In addition to that, what TRTIS version that you are using? And what is the framework of your model?

**Comment by jpark621** [comment]
The error occurs when a request is sent. I'll turn on verbose logging.

We're using the TRTIS 19.08 and python3 (FROM nvcr.io/nvidia/tensorrtserver:19.08-py3). Our model framework is TensorRT (model.engine).

**Comment by deadeyegoodwin** [comment]
Another thing to check is to make sure that you generated the TensorRT model using the same version of TensorRT as is included in the 19.08 release. There is a container for TensorRT on NGC as well with that version.

**Comment by jpark621** [comment]
@deadeyegoodwin I just checked and I'm using TensorRT 5.1.5 for both the inference server and the builder.

**Comment by deadeyegoodwin** [comment]
It could be due to sending invalid data to the model. For instance I have observed when using perf_client with this model that sending random data can cause this error but sending zeros (using the -z option) does not.

**Comment by deadeyegoodwin** [comment]
Closing. Let us know if the -z option doesn't work for you. BTW, this is likely not a TRTIS issue.
