### ISSUE TITLE
[Documentation] Build tensorflow library from source lacks needed scripts

### ISSUE THREAD

**Issue by wangguibao** [NVIDIA/tensorrt-inference-server#746]
Hi,

I'm building tensorrt-inference-server from source on a Centos 6.3 server (Building with Docker apparently supports only Centos 7+).

The documentation [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/build.html#tensorflow) seems to suggest building Tensorflow library following the build steps on [Dockerfile found at root of tensorrt-inference-server repo](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/Dockerfile#L38)

At last stage, there's
```
RUN ./nvbuild.sh --python3.6
```

I guess `nvbuild.sh` along with `nvbuildopts` is in `nvcr.io/nvidia/tensorflow:19.09-py3` image. But since I'm on Centos6.3, I cannot install nvidia-docker2, hence cannot pull that image to local.

Is `nvbuild.sh` accessable on github or somewhere else, so that I can use it to continue my source build,  thanks.

**Comment by deadeyegoodwin** [comment]
For pulling and building you don't need to use nvidia-docker, you can just use docker. But perhaps that is not available on Centos6.3 either. Do you have access to another system that does support docker? You can pull the image on that system and then copy out the files you need.

**Comment by wangguibao** [comment]
OK I'll try

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if you encounter more issues.
