### ISSUE TITLE
savemodel error: creating server: INTERNAL - failed to open text file for read /models/pb_version18_batch_FP16_TRT_docker_32/config.pbtxt: No such file or directory

### ISSUE THREAD

**Issue by zfxxfeng** [NVIDIA/tensorrt-inference-server#749]
Hello!
        I  run the example Successfully.(https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/quickstart.html). When I use my own savemodel which export by tensorflow.Using the command and  I get an error.

nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v/data4/dopamine/work/zhangfeng2/project/trt_inference_server/tensorrt-inference-server/docs/examples/models:/models nvcr.io/nvidia/tensorrtserver:19.09-py3 trtserver --model-repository=/models
![image](https://user-images.githubusercontent.com/22147218/66553577-f972cb00-eb7d-11e9-861b-ac29327772c3.png)
error: creating server: INTERNAL - failed to open text file for read /models/pb_version18_batch_FP16_TRT_docker_32/config.pbtxt: No such file or directory
      The  user guide say as follows:
![image](https://user-images.githubusercontent.com/22147218/66552427-e0691a80-eb7b-11e9-8e15-3c26dbc8d2c1.png)
      Can you give me a suggestion. Thanks !

**Comment by nieksand** [comment]
Looking at the docs, you might not even need the config.pbtxt stub if you pass in the `--strict-model-config` flag:

https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/model_configuration.html#section-generated-model-configuration

**Comment by zfxxfeng** [comment]
Thanks for your advice.@nieksand

**Comment by deadeyegoodwin** [comment]
It looks like your TF model is actually a TF-TRT model. That means that TensorRT has been used to optimize parts of the model. TRTIS supports TF-TRT models but you need to make sure that the model was generated with the same version of TensorRT as is being used by TRTIS (because TensorRT models are not compatible across different versions of TensorRT). What version of TRTIS are you using and what version of TensorRT was used to generated the model?

**Comment by zfxxfeng** [comment]
@deadeyegoodwin Thanks for your advice.
I use a docker(nvcr.io/nvidia/tensorflow:19.06-py3 ) to convert savemodel to TF-TRT model so I think the Tensorrt version is 5.1.5.
![image](https://user-images.githubusercontent.com/22147218/66618997-e0195f80-ec0d-11e9-89cb-fe04d88e9f8e.png)
I  use a docker(nvcr.io/nvidia/tensorrtserver:19.09-py3 ) which is TRTIS 1.6.0 before.Now I use docker(nvcr.io/nvidia/tensorrtserver:19.08-py3) which is TRTIS 1.5.0.
I get another error.
![image](https://user-images.githubusercontent.com/22147218/66619427-81ed7c00-ec0f-11e9-9f73-03136fc435a5.png)
When I use savedmodel format or TF-TRT model,the error is same.

**Comment by zfxxfeng** [comment]
Hello.
I change the model dic and the error disappears.Now it output some Strange information.My command is this(nvidia-docker run --rm --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -e CUDA_VISIBLE_DEVICES=5  -p8000:8000 -p8001:8001 -p8002:8002 -v/data4/dopamine/work/zhangfeng2/project/trt_inference_server/tensorrt-inference-server/docs/examples/models_tfserving:/models nvcr.io/nvidia/tensorrtserver:19.06-py3 trtserver --model-store=/models --strict-model-config=false)
I use docker（nvcr.io/nvidia/tensorrtserver:19.06-py3)）which is the same as tftrt（nvcr.io/nvidia/tensorflow:19.06-py3）.
![image](https://user-images.githubusercontent.com/22147218/66624019-faa90400-ec20-11e9-9215-07411619d9ff.png)
![image](https://user-images.githubusercontent.com/22147218/66624040-11e7f180-ec21-11e9-8638-c33204fb250c.png)
I am confusing.

**Comment by zfxxfeng** [comment]
Hello.I add the config.pbtxt like this.
![image](https://user-images.githubusercontent.com/22147218/66629144-7c099200-ec33-11e9-9bb1-c66f33243084.png)
And run a command （curl localhost:8000/api/status）.I get the output.
![image](https://user-images.githubusercontent.com/22147218/66629284-df93bf80-ec33-11e9-8d35-6a52dbcd912c.png)
![image](https://user-images.githubusercontent.com/22147218/66629303-e9b5be00-ec33-11e9-8fc3-3174fc0f9dec.png)
Is it working?

**Comment by zfxxfeng** [comment]
Hello,I use --log-verbose=1 
![image](https://user-images.githubusercontent.com/22147218/66644936-cc451c00-ec54-11e9-8b52-fad4942908e3.png)
My savedmodel export code as follows:
![image](https://user-images.githubusercontent.com/22147218/66645003-ef6fcb80-ec54-11e9-95d1-17ade9d2e164.png)
so that the input reshape is {}
And I write a client.
url="localhost:8000"
model_name="pb_version18_batch_FP16_TRT_docker_32"
batch_size=1
verbose=False
protocol = ProtocolType.from_str("HTTP")
# Request for the model status
ctx = ServerStatusContext(url, protocol, model_name)
server_status = ctx.get_server_status()

# Get config file
status = server_status.model_status[model_name]
config = status.config

# Get input and output names
input_name = config.input[0]
outputs = [output.name for output in config.output]

max_batch_size = config.max_batch_size
# Prepare you images

path = "/data4/dopamine/work/zhangfeng2/project/ter_pol_reg/processdata/test_data_2/"
image_path_list = glob.glob(path + "*.jpg")
input_list=[]
i=1
for image_path in image_path_list:
    if i==9:
        break
    with open(image_path, 'rb') as f:
        image = f.read()

    img = base64.b64encode(image).decode("utf-8")
    input_list.append(img)
    print(input_list)
# Run inference
ctx = InferContext(url, protocol, model_name)
results = ctx.run(
    {input_name: input_list},
    {output: InferContext.ResultFormat.RAW for output in output_names},
    batch_size)
print(results)

Finally,I get a error.
![image](https://user-images.githubusercontent.com/22147218/66645131-3b227500-ec55-11e9-9b9d-5f77eca477c5.png)
Maybe I make a mistake at exporting savemodel. Can you give me some suggestion,Thanks.

**Comment by zfxxfeng** [comment]
Hello，I modify my client.

**Comment by GuanLuo** [comment]
For sending raw images from client, you can take a look at this [Python example](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/ensemble_image_client.py#L126), it is for demonstrating a different kind of model, but the client code should also suit your need.

By the way, the `max_batch_size` in model config should be a non-negative value, there is a PR #755 for adding the check. Thus even though the model doesn't specify maximum batch size allowed, you will still need to specify a positive value
