### ISSUE TITLE
Dynamic batching - don't discard built models

### ISSUE THREAD

**Issue by ohlr** [NVIDIA/tensorrt-inference-server#754]
**Is your feature request related to a problem? Please describe.**
preferred_batch_size: [ 1, 2 ]

If there is only a single request trtis rebuilds the model for batchsize 1 and discards the model for batchsize 2.

This makes dynamic batching inefficient for me as I don't have steady load.

**Describe the solution you'd like**
I would like to have an option to keep models that have been build in memory so I can switch without rebuilding.

**Comment by deadeyegoodwin** [comment]
TRTIS does not build and discard models in the dynamic batcher. The dynamic batcher simply groups together independent requests that are then sent to the backend framework as a single batched inference request. What framework backend are you using? What makes you think that it is rebuilding models?

**Comment by ohlr** [comment]
the problem occurs for` tensorflow savedmodels `with input size `[None, None, None, 3]`.

Everytime the number of clients changes it says something along the lines rebuilding model for input size, which takes around 40 seconds during which no request can be performed.

**Comment by deadeyegoodwin** [comment]
Is it a pure TF model or is optimized with TensorRT?

**Comment by ohlr** [comment]
I create it using the save_model_cli tool - so I assume it at least gets some optimization

    ./saved_model_cli convert --dir /saved_model/ --output_dir /saved-model --tag_set serve tensorrt --precision_mode FP16 --max_batch_size 16 --is_dynamic_op True

**Comment by nieksand** [comment]
TF+TRT has an option for how many compiled versions to cache.  Default is 1.

**Comment by deadeyegoodwin** [comment]
I just got some feedback from TF-TRT engrs. They proposed 2 solutions:
1. Make all the input shapes static before optimizing  with TF-TRT
2. Pass the argument maximum_cached_engines with some larger value. The default is 1.

**Comment by ohlr** [comment]
Thanks @nieksand @deadeyegoodwin.
