### ISSUE TITLE
build error with cmake on version r19.09 

### ISSUE THREAD

**Issue by pwlazy** [NVIDIA/tensorrt-inference-server#760]
Hi,
I am trying to compile r19.09 from source  with CMake version 3.13.4
I followed the instructions from [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/build.html#section-building-the-server-with-cmake) and I get the following error.

```
[100%] Built target evhtp
[ 80%] Performing install step for 'libevhtp'
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
[100%] Built target evhtp
CMake Error at cmake/protobuf.cmake:55 (find_package):
  Could not find a package configuration file provided by "Protobuf" with any
  of the following names:

    ProtobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "Protobuf" to CMAKE_PREFIX_PATH or set
  "Protobuf_DIR" to a directory containing one of the above files.  If
  "Protobuf" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:140 (include)
```

the same error with the version v1.6.0, but it' ok with the version v1.4.0dev
Please help

**Comment by deadeyegoodwin** [comment]
Can you provide information about what system you are building on and the cmake and make command you used.

**Comment by pwlazy** [comment]
OS is Redhat Enterprise Linux Server release 7.2 (Paladin)

cd the install path of tensorrt-inference-server
make cmake-build
cmake ../build
make trtis

i  tried to compile the master(1.8.0dev),it's ok , but it didn't work with r19.09 and v1.6.0 and the error was  as before

**Comment by deadeyegoodwin** [comment]
We do not test RHEL builds so it is not surprising it doesn't work. What the build is looking for is the CMake configuration file for protobuf. It could be a couple of things causing that failure. Can you share the full contents of the builddir/protobuf/lib directory and subdirs.

Unfortunately I don't think I can pull the RHEL container for free. Have you tried on the corresponding CentOS? If you see the same failure there we should be able to reproduce.

**Comment by pwlazy** [comment]
the directory is as below
```
trtis-r19.09/cmake-build/protobuf/lib64/
├── cmake
│   └── protobuf
│       ├── protobuf-config.cmake
│       ├── protobuf-config-version.cmake
│       ├── protobuf-module.cmake
│       ├── protobuf-options.cmake
│       ├── protobuf-targets.cmake
│       └── protobuf-targets-noconfig.cmake
├── libprotobuf.a
├── libprotobuf-lite.a
├── libprotoc.a
└── pkgconfig
    ├── protobuf-lite.pc
    └── protobuf.pc
```

the machine and the os is provided by anothers and no choice for me

**Comment by deadeyegoodwin** [comment]
The likely problem is here: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/build/CMakeLists.txt#L154
And similar lines like it in the CMakeLists.txt file. The definition of _FINDPACKAGE_PROTOBUF_CONFIG_DIR is here: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/build/CMakeLists.txt#L122
Notice that it expects the config in protobug/lib/cmake/protobuf, but you have lib64. So I think you can just edit that line. It would be great if you could determine the cmake define for detecting RHEL system and issue a PR to fix the _FINDPACKAGE_PROTOBUF_CONFIG_DIR assignment.

You may have similar cases where you need to change lib -> lib64.

**Comment by pwlazy** [comment]
Greate! It works!

i had been wondering why it worked with the version 1.8.0dev and did not with r19.09 or v1.6.0

it's different with the CMakeList of both as below

at v1.6.0 
```
$find build -name "*.txt"|xargs grep "_FINDPACKAGE_PROTOBUF_CONFIG_DIR"
build/CMakeLists.txt:  set(_FINDPACKAGE_PROTOBUF_CONFIG_DIR "${CMAKE_CURRENT_BINARY_DIR}/protobuf/cmake")
build/CMakeLists.txt:  set(_FINDPACKAGE_PROTOBUF_CONFIG_DIR "${CMAKE_CURRENT_BINARY_DIR}/protobuf/lib64/cmake/protobuf")
build/CMakeLists.txt:#set(_FINDPACKAGE_PROTOBUF_CONFIG_DIR "${CMAKE_CURRENT_BINARY_DIR}/protobuf/${CMAKE_INSTALL_LIBDIR}/cmake/protobuf")
build/CMakeLists.txt:    -DProtobuf_DIR:PATH=${_FINDPACKAGE_PROTOBUF_CONFIG_DIR}
build/CMakeLists.txt:   ${_FINDPACKAGE_PROTOBUF_CONFIG_DIR})
build/CMakeLists.txt:    -DProtobuf_DIR:PATH=${_FINDPACKAGE_PROTOBUF_CONFIG_DIR}
build/CMakeLists.txt:    -DProtobuf_DIR:PATH=${_FINDPACKAGE_PROTOBUF_CONFIG_DIR}
build/CMakeLists.txt:    -DProtobuf_DIR:PATH=${_FINDPACKAGE_PROTOBUF_CONFIG_DIR}
```

but at 1.8.0dev, it's empty
```
$find ../trtis-1.8dev/build -name "*.txt"|xargs grep "_FINDPACKAGE_PROTOBUF_CONFIG_DIR"
```

but why not both have the similar CMakeList

**Comment by deadeyegoodwin** [comment]
The dev version was an under-development version so perhaps you just got it at a point when we were making some changes.  Good that you have it working now.
