### ISSUE TITLE
Build Error with CMAKE

### ISSUE THREAD

**Issue by Guardian-of-code** [NVIDIA/tensorrt-inference-server#794]
Hi,

I am trying to compile  tensorRT inferencing server from [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/build.html#building-the-server-with-cmake)  
r19.09 with CMAKE.
I run into the following error:

     [ 94%] Performing configure step for 'trtis'
     loading initial cache file /home/ssduser/Documents/tensorRT/new/tensorrt-inference-server/builddir/trtis/tmp/trtis-cache-.cmake
      -- Using CUDA 10.1
      -- Using libevent 2.1.8
      -- Using protobuf 3.6.1
      -- Using gRPC 1.19.0
      -- Using prometheus-cpp 
      CMake Error at /home/ssduser/Documents/tensorRT/new/tensorrt-inference-server/builddir/libevhtp/install/lib/cmake/libevhtp/libevhtpConfig.cmake:29 (find_package):
       By not providing "Findoniguruma.cmake" in CMAKE_MODULE_PATH this project
       has asked CMake to find a package configuration file provided by
       "oniguruma", but CMake did not find one.

    Could not find a package configuration file provided by "oniguruma" with
    any of the following names:

    onigurumaConfig.cmake
    oniguruma-config.cmake

    Add the installation prefix of "oniguruma" to CMAKE_PREFIX_PATH or set
    "oniguruma_DIR" to a directory containing one of the above files.  If
    "oniguruma" provides a separate development package or SDK, be sure it has
    been installed.
       Call Stack (most recent call first):
       /home/ssduser/Documents/tensorRT/new/tensorrt-inference-server/src/servers   /CMakeLists.txt:73 (find_package)

    -- Configuring incomplete, errors occurred!

System Config:
OS: Ubuntu 18.04
GPU: Quadro p2000
 NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1 
tensorRT : 6.0.1 

I have built the dependencies and the backend separately and added them to the path
    
      mkdir builddir
      cd builddir
      cmake -DTRTIS_ENABLE_TENSORRT=ON  -DTRTIS_ENABLE_GPU=ON  ../build
      make -j16 trtis

Can you please help me with this?.

**Comment by deadeyegoodwin** [comment]
Can you try #795 and see if it fixes your issue.

**Comment by Guardian-of-code** [comment]
Great it works!  #795 fixes the issue.
