### ISSUE TITLE
    unknown output name  'OUTPUT__0' for pytorch model  and  ctx.get_server_status() get protobuf error

### ISSUE THREAD

**Issue by laohur** [NVIDIA/tensorrt-inference-server#796]
**Description**

- ctx.get_server_status() error

no matter which model , even api/status ok and infer ok,
once call  

> server_status = ctx.get_server_status()

got 

> input_name, output_name, c, h, w, format, dtype = parse_model(url, protocol, model_name,batch_size, verbose)
File "InnerServer.py", line 178, in parse_model
server_status = ctx.get_server_status()
File "/root/.local/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 548, in get_server_status
status.ParseFromString(status_buf)
File "/usr/local/lib/python3.6/dist-packages/google/protobuf/message.py", line 187, in ParseFromString
return self.MergeFromString(serialized)
File "/usr/local/lib/python3.6/dist-packages/google/protobuf/internal/python_message.py", line 1127, in MergeFromString
if self._InternalParse(serialized, 0, length) != length:
File "/usr/local/lib/python3.6/dist-packages/google/protobuf/internal/python_message.py", line 1163, in InternalParse
(tag_bytes, new_pos) = local_ReadTag(buffer, pos)
File "/usr/local/lib/python3.6/dist-packages/google/protobuf/internal/decoder.py", line 192, in ReadTag
while six.indexbytes(buffer, pos) & 0x80:
NotImplementedError: memoryview: unsupported format <b

- unknown output name error 

well for tensorflow ,but fialed on pytorch script and onnx model

> InferenceServerException: [ 0] unknown output 'OUTPUT__0' for 'simplept' pytorch model

** TRTIS Information **
What version of TRTIS are you using? 19.09
Are you using the TRTIS container or did you build it yourself?
container

> log:I1026 19:10:54.704219 364 model_repository_manager.cc:810] successfully loaded 'simplept' version 1
I1026 19:10:54.704258 364 main.cc:417] Starting endpoints, 'inference:0' listening on
I1026 19:10:54.705479 364 grpc_server.cc:1730] Started GRPCService at 0.0.0.0:8001
I1026 19:10:54.705497 364 http_server.cc:1125] Starting HTTPService at 0.0.0.0:8000
I1026 19:10:54.770781 364 http_server.cc:1139] Starting Metrics Service at 0.0.0.0:8002
===end==
save [script:](https://github.com/laohur/tmp/blob/master/pytorch_save.py)

status

> id: "inference:0"
version: "1.6.0"
uptime_ns: 847831000057
model_status {
  key: "simplept"
  value {
    config {
      name: "simplept"
      platform: "pytorch_libtorch"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      instance_group {
        name: "simplept"
        count: 1
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "model.pt"
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
      }
    }
  }
}
status_stats {
  success {
    count: 6
    total_time_ns: 127809
  }
}
ready_state: SERVER_READY
health_stats {
  success {
    count: 6
    total_time_ns: 64339
  }
}

**To Reproduce**
test ok in tensorflow
save scripts
> traced_script_module = torch.jit.trace(simplept, (INPUT0, INPUT1))

> traced_script_module = torch.jit.trace(simplept, (INPUT0, INPUT1),(OUTPUT0, OUTPUT1))

    inputs = [
        {'INPUT__0': input_list0, 'INPUT__1': input_list1},
        {'INPUT__0': input_list0, 'INPUT__1': input_list1}
    ]
request_output {'OUTPUT__0': (1,), 'OUTPUT__1': (1,)}   for  example [simple](https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/clients/python/simple_client.py)
but got 

>     nvoutputs = infer_ctx.run(nv_inputs, request_output, batch_size=batch_size)

>   File "/root/.local/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 1280, in run
    self._prepare_request(inputs, outputs, flags, batch_size, contiguous_input)
  File "/root/.local/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 963, in _prepare_request
    _crequest_infer_ctx_options_add_raw(self._ctx, options, output_name)))
  File "/root/.local/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 231, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: [ 0] unknown output 'OUTPUT__0' for 'simplept'

no matters config.pbtext 

> platform: "pytorch_libtorch"
max_batch_size: 128
input [
  {
    name: "INPUT__0"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
  {
    name: "INPUT__1"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
  {
    name: "OUTPUT__1"
    data_type: TYPE_FP32
    dims: [ 16 ]
  }
]

**Expected behavior**

no error

and is there any more examples?

@GuanLuo 
@CoderHam 
tried [https://github.com/NVIDIA/tensorrt-inference-server/issues/590](url) and not work,

is there any rules to save pytorch models  in pytorch script or onnx?

**Comment by CoderHam** [comment]
The PyTorch model should be saved in `torchscript` form as described [here](https://pytorch.org/tutorials/advanced/cpp_export.html). 
The error with the server status is not expected. Are you using the master to build the new client as well?

**Comment by laohur** [comment]
> The PyTorch model should be saved in `torchscript` form as described [here](https://pytorch.org/tutorials/advanced/cpp_export.html).
> The error with the server status is not expected. Are you using the master to build the client container as well?

fellowed by this scripts to save. python [script](https://github.com/laohur/tmp/blob/master/torch_script_save.py)
i use docker server 19.09 and prebuild client.reinstall protobuf for some extra error.  docker [file](https://github.com/laohur/tmp/blob/master/Dockerfile)
now got :**MODEL_UNLOADING = 4** error . and  logs are success.

**Comment by CoderHam** [comment]
Check the pytorch version you are using, it should match the version being used by TRTIS. Refer to the release documents for the same. 
Run trtserver using log-verbose and please share the result. It would also be helpful if you could share the exact model.

**Comment by laohur** [comment]
> Check the pytorch version you are using, it should match the version being used by TRTIS. Refer to the release documents for the same.
> Run trtserver using log-verbose and please share the result. It would also be helpful if you could share the exact model.

Yeah, reason is after typing 'pip3 install torch==1.2.0 ' and system install torch==1.3.0 instead.
To generate config.pbtext automaticly, i am trying use
> model = torch.jit.load("model.pt", map_location='cpu')
to detect model messages, but nothing catched. but these informations are what trtis required and exist.
Is there easy way to generate config.pbtext automaticlly ? 
Thanks!

**Comment by CoderHam** [comment]
You should use the same version of pytorch as in the TRTIS container (documented [here](https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_19-10.html#rel_19-10)). Most likely there is a versioning issue and this causes the model loading to fail.

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if you use the same pytorch version and are still having issues.
