### ISSUE TITLE
RNN in ONNX model does not give correct output with batch_size > 1

### ISSUE THREAD

**Issue by daquilnp** [NVIDIA/tensorrt-inference-server#808]
**Description**
I have a simple pytorch bidirectional gru model that I exported to ONNX. It exports successfully. When I load the model into python using onnxruntime-0.5.0 I get the correct result (result matches pytorch output). However, when I put the model in tensorrt-inference-server I get a incorrect result for batch size > 1 (does not match pytorch or onnxruntime output).

**TRTIS Information**
What version of TRTIS are you using? 19.10
Are you using the TRTIS container or did you build it yourself? using TRTIS container
**To Reproduce**
### Simple GRU model
```
name: "simple_rnn"
platform: "onnxruntime_onnx"
max_batch_size : 2000
dynamic_batching {
  preferred_batch_size: [ 100, 500 ]
  max_queue_delay_microseconds: 50
}
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [5]
  }
]
output [
  {
    name: "out"
    data_type: TYPE_FP32
    dims: [ 200 ]
  } 
]
```
### Python Inference Code
```
eval_batch0 = np.array([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845]],dtype=np.float32)
eval_batch1 = np.array([[ 1.2410, -0.5934, -1.1788,  0.2684, -1.3845]],dtype=np.float32)
batch_size=2
batch_res = batch_ctx.run(
            { "input" : [eval_batch0, eval_batch1] },
            { "out" : (InferContext.ResultFormat.RAW) },
            batch_size)


    output0_data = result['out'][0]
    print(output0_data)
```

**Expected behavior**
Should get: [[ 0.05313804 -0.03783077 -0.01000221 -0.06483013  0.01122947 -0.11574925
  -0.1188059   0.00879205  0 **. . .** -0.01771809  0.03329424
  -0.06625719 -0.19090976 -0.16422167 -0.13947284 -0.02236746 -0.05213657
   0.0291802  -0.01893364]]

But instead I get: [[-0.12171305  0.08831704 -0.1299032  -0.04495994 -0.09434152 -0.00348916
  -0.06000247  0.06794671 -0.00264789 **. . .** -0.03702144 -0.00485747
   0.06768323  0.10949556  0.09059966 -0.00926312  0.01789687 -0.03266058
  -0.12896161  0.02893848]]

**Comment by GuanLuo** [comment]
Do you mind to share your model?

**Comment by daquilnp** [comment]
Here is my pytorch model.
```
class SimpleGRU(nn.Module):
    def __init__(self,embedding_dimensions):
        super().__init__()
        # Bidirectional RNN
        self.rnn = nn.GRU(embedding_dimensions, 100, num_layers=1, bidirectional=True,
                                dropout=dropout, batch_first=False)

    def forward(self, embeded_input):
        embeded_input = embeded_input.permute(1,0,2) #(max_len, batch_size, emb_size)

               
        rnn_output, _ = self.rnn(embeded_input) #(max_len, batch_size, 2 * rnn_size)
        rnn_output =rnn_output.permute(1,0,2) #(batch_size, max_len, 2 * rnn_size)

        return rnn_output
```

**Comment by daquilnp** [comment]
Update. If I export the onnx model with a batch size of 1 and do not allow different batch sizes, the tenssorrt-inference-server gives the same output as pytorch and onnxruntime in python. However, I do not understand why.

**Comment by GuanLuo** [comment]
How did you export the model to ONNX? For both the batching case and non-batching case.

**Comment by daquilnp** [comment]
### Non Batching
```
    max_len = 1
    embedding_dims = 5
    batch_size = 1
    rnn_size = 100
    att_size = 2*rnn_size
    rnn_layers=1
    np.random.seed(0)
    torch.manual_seed(0)
    batch = torch.randn([batch_size,max_len,embedding_dims])
  

    print (batch)
    network = SimpleGRU(embedding_dims)

    x = network(batch)
    print ("pytorch: {}".format(x[0,0]))
    network.eval()
    test_onnx_file = "model.onnx"
    torch.onnx.export(network, (batch), test_onnx_file,input_names=['input'],output_names=["out"], verbose=False)
```
### Batching
```
    max_len = 1
    embedding_dims = 5
    batch_size = 100
    rnn_size = 100
    att_size = 2*rnn_size
    rnn_layers=1
    np.random.seed(0)
    torch.manual_seed(0)
    batch = torch.randn([batch_size,max_len,embedding_dims])
  

    print (batch)
    network = SimpleGRU(embedding_dims)

    x = network(batch)
    print ("pytorch: {}".format(x[0,0]))
    network.eval()
    test_onnx_file = "model.onnx"
    torch.onnx.export(network, (batch), test_onnx_file,input_names=['input'],output_names=["out"], verbose=False)
    model = onnx.load(test_onnx_file)
    model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'

    model.graph.output[0].type.tensor_type.shape.dim[0].dim_param = '?'
    print (model.graph.input)
    print (model.graph.output)
    onnx.save(model, test_onnx_file) 
```

**Comment by CoderHam** [comment]
@daquilnp what output do you get with PyTorch if you use the jitted model of the same?

**Comment by daquilnp** [comment]
Sorry I am not familiar with Torchscript. Not entirely sure how it can help us here

**Comment by CoderHam** [comment]
You had to produce the jitted model for TRTIS (it only supports jitted models since it uses libtorch (the Pytorch C++ backend to run). Simply load the model and run the same test.

```
model = torch.jit.load("model_name.pt")
model(input)
```

**Comment by daquilnp** [comment]
Does TRTIS not support ONNX?

**Comment by CoderHam** [comment]
TRTIS supports both ONNX and Pytorch. You mentioned the output was incorrect when using ONNX hence I am suggesting you to use the Pytorch backend (since your model is a pytorch model and the issue may be with conversion to ONNX) instead and see if you see the same behavior.

**Comment by GuanLuo** [comment]
@CoderHam this issue is regarding the ONNX models, here the issue owner is exporting the PyTorch model to ONNX format. Are you suggesting that "jitted model" is needed to export the model to other format?

**Comment by CoderHam** [comment]
No I was suggesting that the export to ONNX format may be broken due to some Pytorch regression and this may be the reason such behavior is observed. 
However I see that this may not be the problem as I note that the converted onnx model works in python successfully outside TRTIS.

**Comment by GuanLuo** [comment]
@daquilnp I couldn't reproduce your issue... See attachments for scripts I used to generate PyTorch model (and evaluate expected result), evaluate in ORT directly, evaluate in TRTIS.
[model_repo.zip](https://github.com/NVIDIA/tensorrt-inference-server/files/3799726/model_repo.zip)
[scripts_and_result.zip](https://github.com/NVIDIA/tensorrt-inference-server/files/3799730/scripts_and_result.zip)

**Comment by daquilnp** [comment]
I updated the the title of the issue to be for batch sizes > 1.

> Update. If I export the onnx model with a batch size of 1 and do not allow different batch sizes, the tenssorrt-inference-server gives the same output as pytorch and onnxruntime in python. However, I do not understand why.

I am able to use batch sizes > 1 in native onnxruntime.

**Comment by GuanLuo** [comment]
@daquilnp Even with batch size > 1, I am still getting expected results from TRTIS.
 
One thing I noticed is that you change your Python Inference Code section to run inference with batch size 2, but that is actually sending the "input_batch" as the first batch, to send multi-batch result, you should do the following:
```Python
eval_batch0 = np.array([[ 1.5410, -0.2934, -2.1788,  0.5684, -1.0845]],dtype=np.float32)
eval_batch1 = np.array([[ 1.2410, -0.5934, -1.1788,  0.2684, -1.3845]],dtype=np.float32)
batch_size=2
batch_res = batch_ctx.run(
            { "input" : [eval_batch0, eval_batch1] },
            { "out" : (InferContext.ResultFormat.RAW) },
            batch_size)
```
Where the input value is a list of batch elements. Although in your code, you should receive error saying shape mismatch or something similar...

**Comment by daquilnp** [comment]
yeah sorry I did not edit that correctly. I have been making a list of numpy arrays like you suggested above. I fixed that now. I will try your code for batch sizes > 1 and get back to you

**Comment by daquilnp** [comment]
Well your examples work with my setup. Still not entirely sure what happened, but this is not a TRTIS bug. Thank you for your help @GuanLuo
