### ISSUE TITLE
Unable to run optimized bert from TensorRT python

### ISSUE THREAD

**Issue by lapolonio** [NVIDIA/tensorrt-inference-server#819]
**Description**

**TRTIS Information**
What version of TRTIS are you using? 19.10
Are you using the TRTIS container or did you build it yourself?
container

**To Reproduce**

Build engine using bert base following instructions here: nvcr.io/nvidia/tensorflow:19.10-py3 https://github.com/NVIDIA/TensorRT/tree/master/demo/BERT/python

copy plan, libcommon.so libbert_plugins.so to tensorrt_server

start server in container: nvcr.io/nvidia/tensorrtserver:19.10-py3
```LD_PRELOAD=/models/plugins/1910/libbert_plugins.so:/models/plugins/1910/libcommon.so trtserver --model-repository=/models/repo --strict-model-config=false```

start perf_client another container: tensorrtserver_client:r19.10
```perf_client -m bertoptimized_plan -p3000 -t4 -v -b 1 -u nvidia-tensorflow-service:8000 --shape input_ids:1,128 --shape segment_ids:1,128 --shape input_mask:1,128```

error on server:
```
E1104 19:12:21.846488 11460 logging.cc:43] ../rtSafe/safeContext.cpp (133) - Cudnn Error in configure: 7 (CUDNN_STATUS_MAPPING_ERROR)
E1104 19:12:21.846623 11460 logging.cc:43] FAILED_EXECUTION: std::exception
E1104 19:12:21.846684 11460 logging.cc:43] ../rtSafe/safeContext.cpp (133) - Cudnn Error in configure: 7 (CUDNN_STATUS_MAPPING_ERROR)
E1104 19:12:21.846696 11460 logging.cc:43] FAILED_EXECUTION: std::exception
E1104 19:12:21.846723 11460 logging.cc:43] ../rtSafe/safeContext.cpp (133) - Cudnn Error in configure: 7 (CUDNN_STATUS_MAPPING_ERROR)
E1104 19:12:21.846753 11460 logging.cc:43] FAILED_EXECUTION: std::exception
```
error on client:
```
*** Measurement Settings ***
  Batch size: 1
  Measurement window: 3000 msec
  Stabilizing using average latency

Request concurrency: 4
Failed to update context stat: [ 0] INTERNAL - Timer not set correctly.
Failed to update context stat: Failed to update context stat: [ Failed to update context stat: [ [ 0] INTERNAL - Timer not set correctly.
0] INTERNAL - Timer not set correctly.
0] INTERNAL - Timer not set correctly.
[ 0] INTERNAL - No valid requests recorded within time interval. Please use a larger time window.
Thread [0] had error: [inference:0 25] INTERNAL - unable to enqueue for inference bertoptimized_plan_0_gpu0
Thread [1] had error: [inference:0 26] INTERNAL - unable to enqueue for inference bertoptimized_plan_0_gpu0
Thread [2] had error: [inference:0 24] INTERNAL - failed to use CUDA copy for tensor 'cls_dense': an illegal memory access was encountered
Thread [3] had error: [inference:0 27] INTERNAL - unable to enqueue for inference bertoptimized_plan_0_gpu0
```
**Expected behavior**
successful requests from client to server with benchmark times

**Comment by deadeyegoodwin** [comment]
Can you try running perf_client with the -z option so that it sends all-zero input values instead of random input values. I believe some of the inputs in bert are offsets/indices where random values cause the error. Or use the perf_client option that allows you to specify exact input data and use a valid set of input data for your attempt.

**Comment by Darshcg** [comment]
Hi @lapolonio,

Can you please let me the solution to this? would be a great help

Thanks

**Comment by lapolonio** [comment]
@Darshcg the repo is now on version 21. I would suggest opening a new issue. I think the solution for me was making sure the artifacts were the same version.
