### ISSUE TITLE
Improve error messages: backend not installed -> Segfault 

### ISSUE THREAD

**Issue by ohlr** [NVIDIA/tensorrt-inference-server#837]
**Is your feature request related to a problem? Please describe.**
If a backend is not installed but a model which uses that backend is loaded the trtis responds with:

`9746 Segmentation fault (core dumped)`

**Describe the solution you'd like**
Improve description: something along the lines:

`the requested backend (tensorflow) is not installed`

**Comment by deadeyegoodwin** [comment]
You are right that it should not segfault. Marking as a bug.

**Comment by CoderHam** [comment]
I tried loading a tensorflow model with the latest master and it does not segfault. Instead I see it reporting the appropriate error (unexpected platform type tensorflow_graphdef for <model_name>). Similar error with 19.10 release.

**Comment by CoderHam** [comment]
Note: if you want the server to continue running when it loads an invalid model such as in this case you can use the `--exit-on-error=false` flag
