### ISSUE TITLE
Warning: Explicit batch network detected and batch size specified, use enqueue without batch size instead.

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/tensorrt-inference-server#859]
**Description**
I created a Tensor RT plan using `NetworkDefinitionCreationFlags::kEXPLICIT_BATCH`, because the current master branch of the TensorRT-ONNX Parser does not allow implicit batch dimension. But there are no wildcards in any of the input dimensions. 

TRTIS 19.10 can load the model, but on every inference the TensorRT Warning
```Warning: Explicit batch network detected and batch size specified, use enqueue without batch size instead.```
is logged. I suppose this is because `IExecutionContext::enqueue` is used instead of `IExecutionContext::enqueueV2`. Is this expected behavior, or am I doing something wrong?

Side question: Disregarding the warning, will this carry a performance penalty? Should I try to make my model use implicit batch dimensions, when not using dynamic input shapes?

**TRTIS Information**
What version of TRTIS are you using?
19.10

Are you using the TRTIS container or did you build it yourself?
NGC container 19.10-py3

**To Reproduce**
Create model with `NetworkDefinitionCreationFlags::EXPLICIT_BATCH`

**Expected behavior**
No warning is emitted.

**Comment by deadeyegoodwin** [comment]
That warning is concerning so we will look into it. The question about performance impacts is probably better asked in the TensorRT project: https://github.com/NVIDIA/TensorRT, but please share the link here.

**Comment by tanmayv25** [comment]
The message makes sense because we don't use new TRT APIs with the fixed shaped tensors. This was done to support networks with fixed tensor shapes and implicit batch size.

The wildcard is being used as a discriminator to decide which API version to invoke. The assumption was users using explicit batch dimension will make it dynamic to utilize TRTIS dynamic scheduler. Is there a reason you are using a fixed batch dimension in your model? 

We can fix it to detect presence of explicit batch dimension and invoke enqueueV2.

**Comment by mrjackbo** [comment]
> Is there a reason you are using a fixed batch dimension in your model?

Yes, I misused the current version of NvOnnxParser. Now I managed to convert my model to explicit batch dimension -1, and everything works as expected.

TRTIS (and TensorRT) could document more clearly the relation between max_batch_size and EXPLICIT_BATCH. What does it mean to have `max_batch_size = n`, but explicit batch dimension 1?
In this situation, I was able to send batches of size `n`, but only the first element of the batch was evaluated correctly, the other `n-1` elements came back as 0.

In the end, I want to use explicit, but dynamic batch dimension, so I am ok with closing this issue. Thanks for the help.

**Comment by tanmayv25** [comment]
So currently, **TRTIS doesn't support having fixed explicit batch dimensions.** It uses the presence of a wildcard to detect  the use of explicit batch dimension. We are awaiting some enhancements in TRT to allow fixed explicit batch dimensions.

**Comment by ZimingLu** [comment]
> > Is there a reason you are using a fixed batch dimension in your model?
> 
> Yes, I misused the current version of NvOnnxParser. Now I managed to convert my model to explicit batch dimension -1, and everything works as expected.
> 
> TRTIS (and TensorRT) could document more clearly the relation between max_batch_size and EXPLICIT_BATCH. What does it mean to have `max_batch_size = n`, but explicit batch dimension 1?
> In this situation, I was able to send batches of size `n`, but only the first element of the batch was evaluated correctly, the other `n-1` elements came back as 0.
> 
> In the end, I want to use explicit, but dynamic batch dimension, so I am ok with closing this issue. Thanks for the help.

hello, could you please explain how do you convert your model to explicit batch dimension -1 and the operations in tensorrt? I met the same problem as you, when I infer with batch, only batch[0] is predicted correctly, the other are 0. Please help me, thx!

**Comment by zhouyuangan** [comment]
@ZimingLu did u solved your problem? I met the same problem.

> hello, could you please explain how do you convert your model to explicit batch dimension -1 and the operations in tensorrt? I met the same problem as you, when I infer with batch, only batch[0] is predicted correctly, the other are 0. Please help me, thx!

**Comment by cong** [comment]
please use executeV2

**Comment by cong** [comment]
please use executeV2
