### ISSUE TITLE
Do you have a web_UI to manage models ?

### ISSUE THREAD

**Issue by taomiao** [NVIDIA/tensorrt-inference-server#868]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by deadeyegoodwin** [comment]
No, we don't provide any UI to manage models.

**Comment by Jackiexiao** [comment]
https://github.com/duydvu/triton-inference-server-web-ui
