### ISSUE TITLE
Parameters support for ensemble model during execution time

### ISSUE THREAD

**Issue by Arun4rangan** [NVIDIA/tensorrt-inference-server#870]
**Problem**
Preprocessing model is used to convert raw image to cv:Mat. But input shape varies from one model to another, and the current `image_preprocess.cc` is able to handle different sizes but is limited by the inital dims set on `config.pbtxt` for that custom model. 

**Request**
A solution would be to use dynamic shape dims on the preprocessing custom model such as `[3, -1, -1]` and the ability to pass in parameters in ensemble model like : 
```
parameters [
  {
    key: "dims"
    value: { string_value: "3,100,100" }
  }
]
```
And be able to get hold of this parameter during `CustomInstance::Execute`.

This would prevent a lot of code replication for preprocessing custom models.

**Comment by deadeyegoodwin** [comment]
image_preprocess.cc is meant to be an example of how an image-preprocessing can be implemented as a custom backend... it is not meant to cover all possible use cases. But did you try changing the config.pbtxt to accept variable-size input tensors and make CustomInstance::Execute handle it correctly? It would be a great PR that you could contribute.

**Comment by deadeyegoodwin** [comment]
Closing. Reopen if you have further questions.

**Comment by scuizhibin** [comment]
how to creat image_preprocess.so ?
there is no model_config.pb.h file.
