### ISSUE TITLE
Can't get hidden layer as output?

### ISSUE THREAD

**Issue by whillas** [NVIDIA/tensorrt-inference-server#874]
**Description**
I'm trying to a hidden layer as an output from an efficientnet model, namely, the `global_pool1 layer as we're using this as an embedding.

**TRTIS Information**
> What version of TRTIS are you using?
> Are you using the TRTIS container or did you build it yourself?

container 19.10-py3

**To Reproduce**

Using a TF SavedModel setup which works fine without a `config.pbtxt` for the expected outputs but since i wanted a hidden layer I created a config and added a `global_pool` to the output which gives the following status:
```
model_status {
  key: "features"
  value {
    config {
      name: "features"
      platform: "tensorflow_savedmodel"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      max_batch_size: 1
      input {
        name: "input"
        data_type: TYPE_FP32
        dims: 240
        dims: 240
        dims: 3
      }
      output {
        name: "logits"
        data_type: TYPE_FP32
        dims: 2878
      }
      output {
        name: "class_ids"
        data_type: TYPE_INT32
        dims: 1
      }
      output {
        name: "probabilities"
        data_type: TYPE_FP32
        dims: 2878
      }
      output {
        name: "global_pool"
        data_type: TYPE_FP32
        dims: 1280
      }
      instance_group {
        name: "features"
        count: 1
        gpus: 0
        kind: KIND_GPU
      }
      default_model_filename: "model.savedmodel"
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_UNAVAILABLE
      }
    }
  }
}
```
**Expected behavior**

Was expecting the layer to be available but I guess this is the wrong approach? Is there something special that needs to be done to the SavedModel before?

Here is the layout which works fine until I add the config
```
models/features/
├── 1
│   └── model.savedmodel
│       ├── saved_model.pb
│       └── variables
│           ├── variables.data-00000-of-00002
│           ├── variables.data-00001-of-00002
│           └── variables.index
└── config.pbtxt

3 directories, 5 files
```

**Comment by anbasile** [comment]
What is the solution to this problem?
