### ISSUE TITLE
network with output dims [ 1 ] ,  how to define config.pbtxt output field 

### ISSUE THREAD

**Issue by taomiao** [NVIDIA/tensorrt-inference-server#877]
**Description**

**TRTIS Information**
What version of TRTIS are you using?
Are you using the TRTIS container or did you build it yourself?

**To Reproduce**

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
There are several examples of creating a config.pbtxt that you can see by following the quickstart. Also you can use --strict-model-config=false to have TRTIS generate the config.pbtxt for you for some type of model frameworks. Let us know if there is some specific issue you are having.
