### ISSUE TITLE
dynamic batch size parameter not recognized by python api

### ISSUE THREAD

**Issue by lapolonio** [NVIDIA/tensorrt-inference-server#880]
**Description**

Note I'm deploying a model plan that contains multiple performance profiles, and I'm trying to select a particular profile using `instance_group`

Error:
> tensorrtserver.api.InferenceServerException: [ 0] run batch-size 8 exceeds maximum batch size 1 allowed for model 'bert_base_f16_384_b1_TRT'

config.pbtext
> id: "inference:0"
> version: "1.7.0"
> uptime_ns: 103182172369
> model_status {
>   key: "bert_base_f16_384_b1_TRT"
>   value {
>     config {
>       name: "bert_base_f16_384_b1_TRT"
>       platform: "tensorrt_plan"
>       version_policy {
>         latest {
>           num_versions: 1
>         }
>       }
>       input {
>         name: "input_ids"
>         data_type: TYPE_INT32
>         dims: -1
>         dims: 384
>       }
>       input {
>         name: "segment_ids"
>         data_type: TYPE_INT32
>         dims: -1
>         dims: 384
>       }
>       input {
>         name: "input_mask"
>         data_type: TYPE_INT32
>         dims: -1
>         dims: 384
>       }
>       output {
>         name: "cls_dense"
>         data_type: TYPE_FP32
>         dims: -1
>         dims: 384
>         dims: 2
>         dims: 1
>         dims: 1
>       }
>       instance_group {
>         name: "multi_prof_max_bs_1"
>         count: 1
>         gpus: 0
>         gpus: 1
>         kind: KIND_GPU
>         profile: "2"
>       }
>       default_model_filename: "model.plan"
>     }
>     version_status {
>       key: 1
>       value {
>         ready_state: MODEL_READY
>       }
>     }
>   }
> }

**TRTIS Information**
What version of TRTIS are you using? 19.10-py3
Are you using the TRTIS container or did you build it yourself? no

**To Reproduce**
deploy trt optimized bert: https://github.com/NVIDIA/TensorRT/tree/release/6.0/demo/BERT/python
Run https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/trtis/scripts/run_trtis.sh

**Expected behavior**
The python client to recognize the dynamic input size of model and allow for batch size > 1

**Comment by deadeyegoodwin** [comment]
I believe the "b1" in the name of the model refers to batch-size 1. You can also see from the model configuration that max_batch_size is not there, which means that it is 0 (zero), which means that the model does not support batching. Perhaps that initial -1 on the tensors is not the batch dimension but is instead just a variable-size dimension?

If the model is meant to support batching and the initial -1 is a batch dimension, then the model configuration file is incorrect and the -1 dimension should not be listed and instead max_batch_size should be set.

**Comment by tanmayv25** [comment]
@lapolonio Can you verify that you are using 19.10-py3? I see 19.06-py3 being launched [here].(https://github.com/NVIDIA/DeepLearningExamples/blob/7d772b8bc9f48d5d955490b1b658335be9085a7b/TensorFlow/LanguageModeling/BERT/trtis/scripts/launch_server.sh#L24)

**Comment by Arun4rangan** [comment]
I am also running into the same issue.
Is it possible to request batch size thats greater than max_batch_size? Would trtis slice the matrix into preferred_batch_size for computation?

**Comment by jiangpinglei** [comment]
@lapolonio I am meeting a same problem with you. @deadeyegoodwin is right, -1 is recognised as a dimension of variable instead of batch_size. 
After I changed input_ids input format  as [(batch_size, 384)] it appears no expeption. But I still don't know how to fix it, and how should we chose the instance profile while calling the api with a specific
batch_size?

**Comment by lapolonio** [comment]
I think the trtis chooses the appropriate available deployed profile based on batch size

**Comment by tanmayv25** [comment]
No. TRTIS doesn't choose the profile automatically, but depend on the user to specify the optimization profile to load for an instance group. Moreover, a model instance can support only a single optimization profile at a time.

@jiangpinglei The profile field of "instance group" in config.pbtxt should be used to select appropriate optimization profile in the model. Please have a look [here](https://github.com/NVIDIA/tensorrt-inference-server/blob/f192895f4b7d08a8be2cad05f0c7ba0c5ad7dc36/src/core/model_config.proto#L166).

The dims specified in the config.pbtxt should not include the first '-1'in the model. TRTIS detects this difference from the model.plan and will then treat the first variable dim in model.plan as a batch dimension. The config.pbtxt should look like:

> 
> id: "inference:0"
> version: "1.7.0"
> uptime_ns: 103182172369
> model_status {
> key: "bert_base_f16_384_b1_TRT"
> value {
> config {
> name: "bert_base_f16_384_b1_TRT"
> platform: "tensorrt_plan"
> max_batch_size: 8
> version_policy {
> latest {
> num_versions: 1
> }
> }
> input {
> name: "input_ids"
> data_type: TYPE_INT32
> dims: 384
> }
> input {
> name: "segment_ids"
> data_type: TYPE_INT32
> dims: 384
> }
> input {
> name: "input_mask"
> data_type: TYPE_INT32
> dims: 384
> }
> output {
> name: "cls_dense"
> data_type: TYPE_FP32
> dims: 384
> dims: 2
> dims: 1
> dims: 1
> }
> instance_group {
> name: "multi_prof_max_bs_1"
> count: 1
> gpus: 0
> gpus: 1
> kind: KIND_GPU
> profile: "2"
> }
> default_model_filename: "model.plan"
> }
> version_status {
> key: 1
> value {
> ready_state: MODEL_READY
> }
> }
> }
> }

**Comment by deadeyegoodwin** [comment]
We have enhanced the optimization profile support on the master branch (will be in 19.12 release). @GuanLuo can you comment on how the new support might apply in this case.

**Comment by GuanLuo** [comment]
The new support now allows users to specify multiple optimization profiles for an instance group, i.e.:
```
instance_group {
name: "multi_prof_max_bs_1"
count: 1
gpus: 0
gpus: 1
kind: KIND_GPU
profile: ["2", "4"]
}
```
When multiple optimization profiles are specified, when the inference requests are sent to the TensorRT model instance, it will select the profile that is the best fit for the input shapes (currently it's the arg min of sum of element-wise difference between opt dims and input shape).

If no optimization profile is specified, then the default profile (0) will be used.

**Comment by deadeyegoodwin** [comment]
@lapolonio Reopen if you still have an issue after trying the new support.
