### ISSUE TITLE
aws s3 model_repository error

### ISSUE THREAD

**Issue by taomiao** [NVIDIA/tensorrt-inference-server#889]
**Description**
when I try to start a server :

./bin/trtserver --model-repository=s3://model-storage/models

get error:
I1116 02:38:41.039330 996 metrics.cc:160] found 1 GPUs supporting NVML metrics
I1116 02:38:41.045581 996 metrics.cc:169]   GPU 0: TITAN Xp
I1116 02:38:41.046139 996 server.cc:110] Initializing TensorRT Inference Server
E1116 02:39:23.217136 996 main.cc:943] error: creating server: INTERNAL - Could not get MetaData for bucket with name model-storage

**TRTIS Information**
What version of TRTIS are you using? 19.09-py3
Are you using the TRTIS container or did you build it yourself? ngc container

**To Reproduce**
1, create a s3 repository
2, init local awscli
3, start trtserver with s3 model-repository

**Expected behavior**

**Comment by deadeyegoodwin** [comment]
Did you upload a model repository to the s3 bucket that you created? It seems to not be finding the bucket.

**Comment by taomiao** [comment]
@deadeyegoodwin I did upload the model_repository, and it worked  well once before I got the error.

**Comment by deadeyegoodwin** [comment]
It worked once? But when you restarted trtserver it didn't work? That is strange. trtserver does not write to the S3 bucket, only reads it, so it should be exactly the same across different invocations of trtserver.

**Comment by deadeyegoodwin** [comment]
Close for inactivity. Reopen if you are still having an issue.

**Comment by Lydia-Lv** [comment]
@taomiao I also get this erro. So how did you solve it?Thx

**Comment by dec14** [comment]
Also having this issue when deploying to an EKS cluster. Any ideas?

**Comment by CoderHam** [comment]
@Lydia-Lv @dec14 are you both using the latest release / master? 
Please check if you S3 credentials work correctly outside Triton by running `aws s3 ls`.

**Comment by dec14** [comment]
@CoderHam I am using 20.09. The IAM service account I'm using for my nodes has access to S3 and I am able to run `aws s3 ls` successfully in the node. Is the server not able to use the EKS IAM service account role? I am not passing in any credentials as environmental variables as it should be "pre-authenticated". 

Here is the error I'm receiving:
error: creating server: Internal - Could not get MetaData for bucket with name <bucket>

**Comment by nsiddharth** [comment]
I am using 20.10 and I see the same exact issue. I am able to do an aws s3 ls on the bucket/model repo from the docker container but running triton server fails with the same message. I checked that the env variables for the credentials are already set. It is not clear what could be causing this. Any help is appreciated,

**Comment by nsiddharth** [comment]
I have figured out the issue here. It seems like SESSION_TOKEN is not being read by tritonserver even though it has been set in the env vars. I have opened a new issue and a PR as well to fix this. I have tested the PR and it seems to fix the issue. Check this PR out if you need a quick fix.

https://github.com/triton-inference-server/server/pull/2290

Issue is mentioned here: https://github.com/triton-inference-server/server/issues/2291

**Comment by CoderHam** [comment]
Thank you @nsiddharth we'll have a look at the PR soon.
