### ISSUE TITLE
Allocations for TensorRT models with dynamic batch size are much too large

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/tensorrt-inference-server#892]
**Description**
When using a TensorRT model with dynamic batch size, e.g. inputs of shape `[-1,c,h,w]`, and `max_batch_size > 1`, TRTIS allocates too much GPU memory for the input and output bindings. The bugs are [here](https://github.com/NVIDIA/tensorrt-inference-server/blob/da4853756feef88358cfe9696f6a6a2309ebb31d/src/backends/tensorrt/plan_backend.cc#L525) and [here](https://github.com/NVIDIA/tensorrt-inference-server/blob/da4853756feef88358cfe9696f6a6a2309ebb31d/src/backends/tensorrt/plan_backend.cc#L706). 

Example: Input shape is `(-1,c,h,w)` with `c,h,w >0`, `max_batch_size=N` and the maximal optimization profile shape is `(M,c,h,w)`. Then TRTIS will allocate a buffer of size                                                              
```N*M*c*h*w*sizeof(datatype)```
for this binding. This is too large, as `N*M > max_batch_size`. Typically, `N=M` and the allocation will be much too large. This leads to real problems...I was trying to use a model with `max_batch_size=512` today, and TRTIS ran out of memory, even though there should have been enough free space on the GPU. Changing the two lines from above to 
```
    byte_size = GetByteSize(dt, maximum_dims);
```
fixes this for me.

**TRTIS Information**
What version of TRTIS are you using?
The allocations are too large in both the 19.10 NGC container, as well as in the master branch.
Are you using the TRTIS container or did you build it yourself?
I tried the 19.10 NGC container, and I built yesterdays master branch from source.

**To Reproduce**
Create a simple model with dynamic batch size:
```
import tensorrt as trt
LOGGER = trt.Logger(trt.Logger.VERBOSE)
builder = trt.Builder(LOGGER)
network = builder.create_network(1 << int(trt.NetworkDefinitionCreationFlag.EXPLICIT_BATCH))
input = network.add_input("INPUT", trt.DataType.FLOAT, (-1,100,100))
identity = network.add_identity(input)
output = identity.get_output(0)
output.name = "OUTPUT"
network.mark_output(output)

cfg = builder.create_builder_config()
profile = builder.create_optimization_profile()
profile.set_shape("input",(1,100,100),(1,100,100),(100,100,100))
builder.max_batch_size = 100
cfg.add_optimization_profile(profile)
engine = builder.build_engine(network,cfg)
with open('test.engine','wb') as f:
    f.write(engine.serialize())
```
and run the model using TRTIS autofill and `--log-verbose true`. The result will look like this:
```
name=test
contexts:
  name=test_0_gpu0, gpu=0, max_batch_size=100
  bindings:
    0: byte_size=400 000 000, buffer=0xb02180000 ]
    1: byte_size=400 000 000, buffer=0xb19f00000 ]
```
Each allocation should be `100*100*100*sizeof(float) bytes = 4 000 000 bytes`.

**Expected behavior**
TRTIS allocates buffers so that a maximal batch precisely fits into them.

**Comment by tanmayv25** [comment]
Thanks @mrjackbo !
The bug is being fixed [here](https://github.com/NVIDIA/tensorrt-inference-server/pull/897).

**Comment by tanmayv25** [comment]
The PR is merged. Closing the issue.
