### ISSUE TITLE
Dynamic batch scheduling in ensemble models

### ISSUE THREAD

**Issue by mrjackbo** [NVIDIA/tensorrt-inference-server#906]
**Description**
I ran into a hard-to-trace bug today. I have an ensemble model looking as follows:
``` A-> B -> C```
where A,C are custom backends executing on the CPU, and B is a TensorRT model. `A` and `C` both have `max_batch_size=0`, and `B` has `max_batch_size=4` and dynamic batch scheduling activated. 

Single inferences of the ensemble model work as expected. But under heavy load, with high concurrency, (think asynchronously submitting 1000s of different requests at once), often some of the outputs of `B` received by `C` are erroneous. 
Turning off dynamic batch scheduling for `B` fixes the problem.

I haven't been able to cook up a minimal example to exhibit the problem yet, but I have reproduced it with two different ensembles. 

**TRTIS Information**
Current master branch.

**Comment by GuanLuo** [comment]
Can you share the model config for each of the models? And can you elaborate more on "some of the outputs of `B` received by `C` are erroneous"

**Comment by mrjackbo** [comment]
Hi, I am still trying to isolate this error.

> And can you elaborate more on "some of the outputs of `B` received by `C` are erroneous"

Some of the inputs are simply wrong, and do not match what the expected outputs of `B` are. I know this by debugging the code of the custom backend `C`.

Here is my testing procedure:
```
import pytest
import tensorrtserver.api as trt
import numpy as np
import os

RAW = trt.InferContext.ResultFormat.RAW
INFERENCE_SERVER = os.environ.get("INFERENCE_SERVER", "localhost:8001")

def test_correctness():
    ctx = trt.InferContext(INFERENCE_SERVER, trt.ProtocolType.GRPC, "ENSEMBLE")

    images = list()
    with open("IMAGE_0", 'rb') as f:
        images.append(np.frombuffer(f.read(),dtype=np.uint8))
    with open("IMAGE_1", 'rb') as f:
        images.append(np.frombuffer(f.read(),dtype=np.uint8))

    ids = list()
    for i in range(1000):
        ids.append((i,ctx.async_run({"INPUT": [images[i%2]]}, {"BOXES": RAW})))

    for i,id  in ids:
        res = ctx.get_async_run_results(id, wait=True)
        if i%2 == 1:
            # we know a priori that IMAGE_1 contains 4 objects
            assert(res['BOXES'][0].shape[0] == 4)
```
It never fails when dynamic batch scheduling of model `B` is turned off. When dynamic batch scheduling is turned on for model `B`, the test does not fail for every iteration, but for quite a few. Interestingly, it is always the same inputs of `C` which receive faulty values, so the error is not completely random.

> Can you share the model config for each of the models? 

The full model configs are long and I am not sure I can share them.
Model C essentially looks like this:
```
name: "MODELC"
platform: "custom"
max_batch_size: 0
input [
{
name: "input_0"
data_type: TYPE_FP16
dims: [8,-1,-1]
},
...
{
name: "input_2"
data_type: TYPE_FP16
dims: [8,-1,-1]
}
]
output [
{
name: "BOXES"
data_type: TYPE_FP32
dims: [-1,6]
}
]
parameters [
...
]
optimization: {
priority: PRIORITY_MAX
}
```
Model `A` is configured in a similar manner. Model `B` is a tensorrt plan with dynamic batch shape, and thus uses a TensorRT optimization profile.
I will try to narrow down the situation to help you debug. My first guess is that there is some synchronization missing in the output mapping of the ensemble.

**Comment by GuanLuo** [comment]
> it is always the same inputs of `C` which receive faulty values

So a set of outputs from B is always correct while the rest is garbage data intermittently?

And you mentioned that you had reproduced the issue with two different ensembles, are those ensembles also uses TensorRT with dynamic batching? Or different frameworks were used?

**Comment by mrjackbo** [comment]
> So a set of outputs from B is always correct while the rest is garbage data intermittently?

In the context of the pytest example from above, yes. 

> And you mentioned that you had reproduced the issue with two different ensembles, are those ensembles also uses TensorRT with dynamic batching? Or different frameworks were used?

Both TensorRT with dynamic batching. I will recheck the second ensemble today, it is possible I made a mistake. 

Also, it is of course possible that I have a bug in the custom backend `C`, but I do not see how such a bug could interact with dynamic batch scheduling of model `B`. 

Sorry that this is all very vague.

**Comment by GuanLuo** [comment]
Do you have models in other frameworks to test with the same schema? Which will give a hint on whether it is specific to TensoRT backend or it is general issue.

**Comment by mrjackbo** [comment]
I am still investigating, I’ll get back to you.

**Comment by mrjackbo** [comment]
I found a subtle bug in the conversion process for  two of my models. This appears to fix the problems. Sorry for the confusion, it didn’t have to do with ensembling after all.

**Comment by riyaj8888** [comment]
how to specify dynamic batching inside ensemble scheduling
