### ISSUE TITLE
image_client.py due to message type error

### ISSUE THREAD

**Issue by JungukCho** [NVIDIA/tensorrt-inference-server#91]
Hi, 
I ran inference servers (using nvcr.io/nvidia/tensorrtserver:19.01-py3) and sent http request using image_client.py without modification (building Dockerfile).

**Sent one request**
$  python3 src/clients/python/image_client.py -m plan_model -s INCEPTION -u 172.17.0.2:8000 /opt/tensorrtserver/qa/images/mug.jpg

**This is part of outputs**
Trying 172.17.0.2...
TCP_NODELAY set
Connected to 172.17.0.2 (172.17.0.2) port 8000 (#0)
POST /api/infer/plan_model?format=binary HTTP/1.1
Host: 172.17.0.2:8000
User-Agent: libcurl-agent/1.0
Accept: */*
Content-Type: application/octet-stream
***NV-InferRequest:batch_size: 1 input { name: "input" dims: 3 dims: 299 dims: 299 } output { name: "InceptionV3/Logits/SpatialSqueeze" cls { count: 1 } }***
Content-Length: 1072812

 We are completely uploaded and fine
 HTTP/1.1 400 Bad Request
 NV-Status: code: INVALID_ARG msg: "unable to parse request for model \'plan_model\'" server_id: "inference:0"
 Content-Type: application/octet-stream
 Date: Thu, 14 Feb 2019 01:50:56 GMT
 Content-Length: 0
 
 Connection #0 to host 172.17.0.2 left intact
Traceback (most recent call last):
  File "src/clients/python/image_client.py", line 304, in <module>
    FLAGS.batch_size))
  File "/usr/local/lib/python3.5/dist-packages/tensorrtserver/api/__init__.py", line 844, in run
    self._last_request_id = _raise_if_error(c_void_p(_crequest_infer_ctx_run(self._ctx)))
  File "/usr/local/lib/python3.5/dist-packages/tensorrtserver/api/__init__.py", line 183, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: [inference:0 0] unable to parse request for model 'plan_model'

**In inference server side, it showed** 
**[libprotobuf ERROR external/protobuf_archive/src/google/protobuf/text_format.cc:307] Error parsing text-format nvidia.inferenceserver.InferRequestHeader: 1:41: Message type "nvidia.inferenceserver.InferRequestHeader.Input" has no field named "dims".
E0214 01:29:37.093842 7363 server_status.cc:374] Unable to collect inference metrics for nullptr servable**

Based on this file (https://github.com/NVIDIA/tensorrt-inference-server/blob/master/src/core/api.proto), there is dims field in Input.

This is my "config.pbtxt" file.
name: "plan_model"
platform: "tensorrt_plan"
max_batch_size: 1
input [
        {
                name: "input"
                data_type: TYPE_FP32
                format: FORMAT_NCHW
                dims: [3, 299, 299]
        }
]
output [
        {
                name: "InceptionV3/Logits/SpatialSqueeze"
                data_type: TYPE_FP32
                dims: [1, 1, 1001]
                label_filename: "imagenet_labels_1001.txt"
        }
]

I guess request format has some issues related to dims part.
However, I am not clear.
Do you have any insight of this problem?

Thanks,

**Comment by GuanLuo** [comment]
Can you try to check out branch r19.01 and modify your "config.pbtxt" file based on that branch? Field "dim" is newly added and it is not in the 19.01 release.

**Comment by JungukCho** [comment]
Hi, GuanLuo

Thank you for a fast response.

In r19.01 examples, they still used "dim" Field in *.pbtxt.
So, I tried with branch r19.01 in a client side and it worked without modifying a inference server side (i.e., do not modify config.pbtxt) file.

However, I am not sure whether the output is correct or not.

When I ran,
**./image_client -m plan_model -s INCEPTION -u 172.17.0.2:8000 -v -c 5 ../qa/images/mug.jpg** 
**This is part of outputs**

HTTP/1.1 200 OK
NV-Status: code: SUCCESS server_id: "inference:0" request_id: 4
Content-Type: application/octet-stream
Date: Thu, 14 Feb 2019 04:41:43 GMT
Content-Length: 159

 Connection #0 to host 172.17.0.2 left intact
Request 0, batch size 1
Image '../qa/images/mug.jpg':
    505 (coffee mug) = 9.27169
    969 (cup) = 7.70286
    968 (espresso) = 3.70387
    726 (pitcher, ewer) = 3.70011
    900 (water jug) = 3.52816

**I expects below results (i.e., each output is less than 1), but they are over 1 in my output.**

Output probabilities:
batch 0: 504 (COFFEE MUG) = 0.777365267277
batch 0: 968 (CUP) = 0.213909029961
batch 0: 967 (ESPRESSO) = 0.00294389552437
Prediction totals:
      cnt=1        (504) COFFEE MUG

Do you have any insight of this problem?

**Comment by SlipknotTN** [comment]
It seems that softmax layer is missing, InceptionV3/Logits/SpatialSqueeze layer output must be passed to a softmax.

**Comment by deadeyegoodwin** [comment]
@JungukCho as @SlipknotTN notes is seems you are taking the wrong output from the model. The inception model TRTIS provides as an example uses InceptionV3/Predictions/Softmax as an output (https://github.com/NVIDIA/tensorrt-inference-server/blob/f64cf7dda0ecdae2e2c0396ca6f85ee5c65eb0e3/docs/examples/model_repository/inception_graphdef/config.pbtxt#L14)

**Comment by JungukCho** [comment]
Hi, 

Thank you for response.

After changing the output in config.pbtxt and updated plan file correctly based on the output, 
I got 
Image '../qa/images/mug.jpg':
    505 (coffee mug) = 0.75413
    969 (cup) = 0.157077
    968 (espresso) = 0.00287988
    726 (pitcher, ewer) = 0.00286906
    900 (water jug) = 0.0024158

Thanks.
