### ISSUE TITLE
Server Queue

### ISSUE THREAD

**Issue by bezero** [NVIDIA/tensorrt-inference-server#914]
I have read the documentation and did not find any place talking about `Server Queue Size`. As far as I understood from the `TRTIS Architecture`, incoming inference requests are queued by `Model Schedulers` and when `Execution Context` is available, the request is passed for inference. I would like to know the Server Queue Size or if possible how to set it. This would help to control the incoming request traffic.

**Comment by deadeyegoodwin** [comment]
The scheduling queue doesn't have a fixed size, it grows to accommodate all pending requests. The latency for these requests will increase dramatically if the server is overloaded. Typically, something "upstream" of TRTIS should notice this increase in latency and scale / load-balance.

If TRTIS implemented a maximum queue size what should happen if the queue exceeds that size? Should requests just be rejected with "server overloaded" error? That is something that could be done.

**Comment by bezero** [comment]
I think it would be helpful to have "server overloaded" status or error, both would work. That way, the client could lower the request rate, or wait for the server for a while. 

It would be helpful to be able to configure queue size as well. For example, I could specify the queue size to be 1GB. Later, an API could be added to request server load status which would return load percentage (e.g. 74% loaded).

**Comment by deadeyegoodwin** [comment]
Marked as enhancement. Can you use the latency of requests as a proxy for server overloaded? The latency will get very long when your queue starts to grow.

**Comment by bezero** [comment]
@deadeyegoodwin Thank you for the update. Yes, for now, I will monitor latency or will try to add alerts to the prometheus latency metrics.

**Comment by dselivanov** [comment]
@deadeyegoodwin would be very useful if server can expose endpoint which reports queue size.

- clients can reduce request rate
- it will be possible/easier to implement autoscaling policy in cloud environments

**Comment by deadeyegoodwin** [comment]
We will consider queue depth as an enhancement to the statistics API. Note that the statistics already report average time that requests spend in the queue which is likely a good substitute.

**Comment by royinx** [comment]
is there any update? 

Actually what we want is **real time** request queue size for auto scaling. 
According to the last reply, average time of requests spend is cumulative , developer cannot obtain the last 15 mins queue size for auto-scaling.  is that the latency is the only way to detect the request loads?

**Comment by deadeyegoodwin** [comment]
Many metrics are reported as cumulative values. You can scrap them at some rate (e.g. once per second) and from that you can determine rate of change. I believe prometheus database can even provide that kind of derived value for you.

**Comment by dhaval24** [comment]
Is there any update on this? It would be very helpful to know the queue size in real time to be able to reduce the load on the server and load balance accordingly.

**Comment by dyastremsky** [comment]
@dhaval24 Please be aware that when commenting on closed tickets, as we are not likely to see or respond. There is a related open enhancement request being tracked here: https://github.com/triton-inference-server/server/issues/5927.

**Comment by dyastremsky** [comment]
As far as the original ask of a max queue size, that's implemented via queue policies, described [here](https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/model_configuration.html#queue-policy).

**Comment by sfc-gh-zhwang** [comment]
@dyastremsky looks like max_queue_size can only be used for dynamic batching? Can we disable dynamic batching while still use the max_queue_size and rejection logic?
