### ISSUE TITLE
Error with Sequence Batch 

### ISSUE THREAD

**Issue by netpcvnn** [NVIDIA/tensorrt-inference-server#915]
Hi All,

When I try the sequence batch with setup as guideline with simple_sequence_client.py.
`sequence_batching {
    max_sequence_idle_microseconds: 5000000
    control_input [
        {
            name: "START"
            control: [
                {
                  kind: CONTROL_SEQUENCE_START
                  fp32_false_true: [ 0, 1 ]
                }
            ]
        },
        {
            name: "READY"
            control: [
                {
                  kind: CONTROL_SEQUENCE_READY
                  fp32_false_true: [ 0, 1 ]
                }
            ]
        }
    ]
}`
I got the error: `Input 'READY' does not follow naming convention i.e. <name>__<index>.` .
When I changed the control input to: READY__0 for example, the model server got segmentation fault and stop immediately.
Do you know how can we setup the sequence batching correctly?
Thank you

**Comment by CoderHam** [comment]
Can you share the entire config file?
Libtorch models need their inputs to follow a specific format. So the naming convention error is expected.

**Comment by netpcvnn** [comment]
Yes, The Segfault occured while I sent the request to the server. 
Because github doesn't allow to upload `pbtxt` file, so I changed the extention to `txt`
[config.txt](https://github.com/NVIDIA/tensorrt-inference-server/files/3899506/config.txt)
Please have a look my config file.
Thank you!

**Comment by CoderHam** [comment]
START AND READY must follow the same naming convention i.e. <name>__<index>
> START -> START__2
> READY -> READY__3

**Comment by CoderHam** [comment]
@netpcvnn could you provide the model you were using to produce this error?

**Comment by CoderHam** [comment]
@netpcvnn I am unable to reproduce a segfault in the server when an inference request for a pytorch sequence model is sent. Can you provide the model you are using and/or a minimal way to reproduce this issue?
