### ISSUE TITLE
Low GPU util without docker

### ISSUE THREAD

**Issue by leerumor** [NVIDIA/tensorrt-inference-server#922]
**Description**
The gpu compute time is 4 times faster when I use docker. (Mainly because of the GPU Util. It's 90%+ with docker and 30-50% with local.)
Concurrency = 100

**TRTIS Information**
What version of TRTIS are you using?
r19.08

Are you using the TRTIS container or did you build it yourself?
I compiled TRTIS and mount it in container 19.08-py3. 
I also try run TRTIS locally but it's slow.

**To Reproduce**
I use exactly the same version of Ubuntu/CUDA/CuDNN/CuBLAS/NCCL and TensorRT dependencies as mentioned in:
https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html

**Expected behavior**
There's maybe a missing library, or the container is optimized. How can I get the same performance without docker?

**Comment by CoderHam** [comment]
Is this something you observe for all backends? It would help to narrow down to the exact dependency that is causing this behavior.

**Comment by leerumor** [comment]
> Is this something you observe for all backends? It would help to narrow down to the exact dependency that is causing this behavior.

I only used TensorRT backend ;)

**Comment by GuanLuo** [comment]
Are you getting the results using perf_client? If so, can you share the reports in two cases? perf_client reports latency at different stages of the inference, which can tell whether the low GPU utilization is completely due to slow on model execution.

**Comment by leerumor** [comment]
> Are you getting the results using perf_client? If so, can you share the reports in two cases? perf_client reports latency at different stages of the inference, which can tell whether the low GPU utilization is completely due to slow on model execution.

Yes. 
The compiled server without docker:
```
====================
        BEGIN
====================
model_name: bert
batch_size: 1
sequence_length: 128
max_threads: 5

*** Measurement Settings ***
  Batch size: 1
  Measurement window: 1000 msec
  Stabilizing using average latency

Request concurrency: 100
  Client:
    Request count: 39
    Throughput: 39 infer/sec
    Avg latency: 1192044 usec (standard deviation 28913 usec)
    p50 latency: 1195848 usec
    p90 latency: 1227959 usec
    p95 latency: 1233345 usec
    p99 latency: 1236743 usec
    Avg HTTP time: 1117202 usec (send/recv 907 usec + response wait 1116295 usec)
  Server:
    Request count: 120
    Avg request latency: 1112375 usec (overhead 21 usec + queue 1103131 usec + compute 9223 usec)
```
The same compiled server with docker:
```
====================
        BEGIN
====================
model_name: bert
batch_size: 1
sequence_length: 128
max_threads: 5

*** Measurement Settings ***
  Batch size: 1
  Measurement window: 1000 msec
  Stabilizing using average latency

Request concurrency: 100
  Client:
    Request count: 306
    Throughput: 306 infer/sec
    Avg latency: 297574 usec (standard deviation 18244 usec)
    p50 latency: 297712 usec
    p90 latency: 317343 usec
    p95 latency: 328639 usec
    p99 latency: 344914 usec
    Avg HTTP time: 287971 usec (send/recv 1393 usec + response wait 286578 usec)
  Server:
    Request count: 394
    Avg request latency: 285041 usec (overhead 19 usec + queue 282057 usec + compute 2965 usec)
```

I didn't change anything except run the same server inside a docker..

**Comment by deadeyegoodwin** [comment]
Can you always share the console output for each case to make sure that TRTIS is seeing the same GPU(s) in each case.

**Comment by leerumor** [comment]
> Can you always share the console output for each case to make sure that TRTIS is seeing the same GPU(s) in each case.

I have only one GPU...

**Comment by deadeyegoodwin** [comment]
@leerumor Do you have any update on this? We have never seen something like this before.

**Comment by leerumor** [comment]
> @leerumor Do you have any update on this? We have never seen something like this before.

no...we decided to use Docker for production
