### ISSUE TITLE
TensorFlow 2 support

### ISSUE THREAD

**Issue by bayandin** [NVIDIA/tensorrt-inference-server#923]
It would be nice to have a Tensorflow 2 support in tensorrt-inference-server to run TensorFlow 2 models. Are there any plans regarding it? 
As far as I can see, a NVIDIA container for TensorFlow 2 has been released this month (nvcr.io/nvidia/tensorflow:19.11-tf2-py3), but tensorrt-inference-server has switched to nvcr.io/nvidia/tensorflow:19.11-tf1-py3.

Thank you!

**Comment by deadeyegoodwin** [comment]
We do plan to support it in the future. Currently TF2 is not as stable as TF1. Can you share your TF2-specific use case to help us prioritize.

**Comment by Arnold1** [comment]
@deadeyegoodwin are there any updates on that?
where can I find a example to run tensorrt with a tensorflow model? does it run on Kubernetes as well? what GPUs are supported?

**Comment by deadeyegoodwin** [comment]
TF2 is still not supported. It would help to have some feedback as to why TF2 is important to you so we can prioritize. 

The quickstart guide in the documentation describes how to run the inference server on any server/system without using kubernetes or similar. Be sure to read the optimization section for tips on how to get the best performance from TRTIS. Pascal (compute capability 6.0) and later are supported. You can find the complete support matrix in the release notes: https://docs.nvidia.com/deeplearning/sdk/inference-release-notes/rel_20-02.html#rel_20-02

**Comment by Arnold1** [comment]
@deadeyegoodwin 
seems both GPUs are supported:
- Nvidia GEFORCE RTX 2070 (Cuda: 7.5)
- Nvidia Tesla V100 (Cude: 7.0)

where can I find infos about using a tensorflow model file by TRTIS?

**Comment by GuanLuo** [comment]
This [section](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_repository.html#tensorflow-models) shows how to organize a model directory for TensorFlow model, you may need to refer [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_configuration.html#model-configuration) to create a proper `config.pbtxt` for the model
