### ISSUE TITLE
tensorrtserver:19.09-py3+tensorflow1.14.0 encounter error

### ISSUE THREAD

**Issue by zxgm** [NVIDIA/tensorrt-inference-server#939]
environment:
python:python3.6.9
g++:7.4.0
tensorflow:1.14.0
docker base image:nvcr.io/nvidia/tensorrtserver:19.09-py3

when import tensorflow as tf,encounter error,error details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/local/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/local/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: **undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE**

Anyone can help me?Thanks a lot.I use ubuntu:18.04_py3_cpu to replace tensorrtserver:19.09-py3, the same environment,that can work .

**Comment by zxgm** [comment]
The dockerfile content:
`#base
#FROM hub.fuxi.netease.com/danlu/ubuntu:18.04_py3_cpu
FROM nvcr.io/nvidia/tensorrtserver:19.09-py3

RUN apt-get update && apt-get install -y aptitude
RUN apt-get -y install python3 python3-pip

RUN pip3 install protobuf==3.10.0 -i https://mirrors.aliyun.com/pypi/simple/
RUN pip3 install protobuf3-to-dict==0.1.5 -i https://mirrors.aliyun.com/pypi/simple/
RUN pip3 install tensorflow==1.14.0 -i https://mirrors.aliyun.com/pypi/simple/

COPY ./test_ubuntu18_04_start.sh /

RUN chmod +x /test_ubuntu18_04_start.sh

CMD ["/test_ubuntu18_04_start.sh"]`

Build completely and run the docker images.
# python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by zxgm** [comment]
The dockerfile content:
`#base
#FROM hub.fuxi.netease.com/danlu/ubuntu:18.04_py3_cpu
FROM nvcr.io/nvidia/tensorrtserver:19.09-py3

RUN apt-get update && apt-get install -y aptitude
RUN apt-get -y install python3 python3-pip

RUN pip3 install protobuf==3.10.0 -i https://mirrors.aliyun.com/pypi/simple/
RUN pip3 install protobuf3-to-dict==0.1.5 -i https://mirrors.aliyun.com/pypi/simple/
RUN pip3 install tensorflow==1.14.0 -i https://mirrors.aliyun.com/pypi/simple/

COPY ./test_ubuntu18_04_start.sh /

RUN chmod +x /test_ubuntu18_04_start.sh

CMD ["/test_ubuntu18_04_start.sh"]`

Build completely and run the docker images.
# python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by deadeyegoodwin** [comment]
I assume you are installing TF into the TRTIS container for your own use (TRTIS doesn't need full TF installed... it already includes the TF shared libraries it needs for inferencing).

The likely source of the problem is that TF is using the TRTIS-specific TF shared libraries instead of the shared libraries installed with the TF package. If you look at LD_LIBRARY_PATH in the container you will see that it includes /opt/tensorrtserver/lib and in that directory are some TF shared libraries. Those shared libraries are only for TRTIS and if you try to use them with TF generally it will not work. You could remove that path from LD_LIBRARY_PATH globally and it should fix (of course you will need to when launching TRTIS itself).

**Comment by zxgm** [comment]
Thank you very mush!The method solve this problem.

**Comment by zxgm** [comment]
Now, I use "import tensorflow as tf" successful.But encounter another problem.
**Env: trtis19.09 + tensorflow1.14.0**
I run docker comamnd execute correctly.I run nvidia-docker command that aim to use gpu,But exception have happended.The error details:

> I1210 11:21:35.837560 124 metrics.cc:160] found 1 GPUs supporting NVML metrics
> 
> I1210 11:21:35.842923 124 metrics.cc:169]   GPU 0: GeForce GTX 1060 5GB
> 
> I1210 11:21:35.843078 124 server.cc:110] Initializing TensorRT Inference Server
> 
> E1210 11:21:35.844464 124 model_repository_manager.cc:100] unable to get number of CUDA devices while building BackendConfigMap: (803) system has unsupported display driver / cuda driver combination
> 
> 2019-12-10 19:21:35.847439: I tensorflow/cc/saved_model/reader.cc:31] Reading SavedModel from: /models/NoName/1/model.savedmodel
> 
> 2019-12-10 19:21:35.858672: I tensorflow/cc/saved_model/reader.cc:54] Reading meta graph with tags { serve }
> 
> 2019-12-10 19:21:35.904083: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192000000 Hz
> 
> 2019-12-10 19:21:35.904581: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55c9cd3b38b0 executing computations on platform Host. Devices:
> 
> 2019-12-10 19:21:35.904598: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
> 
> 2019-12-10 19:21:35.905344: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
> 
> 2019-12-10 19:21:35.905795: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: system has unsupported display driver / cuda driver combination
> 
> 2019-12-10 19:21:35.905814: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: zxgm
> 
> 2019-12-10 19:21:35.905822: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: zxgm
> 
> 2019-12-10 19:21:35.905852: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 418.87.0
> 
> 2019-12-10 19:21:35.905868: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 430.50.0
> 
> 2019-12-10 19:21:35.905874: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 430.50.0 does not match DSO version 418.87.0 -- cannot find working devices in this configuration
> 
> 2019-12-10 19:21:35.965998: I tensorflow/cc/saved_model/loader.cc:204] Restoring SavedModel bundle.
> 
> 2019-12-10 19:21:36.174994: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
> 
> 2019-12-10 19:21:36.238082: I tensorflow/cc/saved_model/loader.cc:332] SavedModel load for tags { serve }; Status: success. Took 390647 microseconds.
> 
> E1210 11:21:36.238162 124 main.cc:943] error: creating server: INTERNAL - unable to get number of CUDA devices: system has unsupported display driver / cuda driver combination
> 

But I use **Env: trtis19.05 + tensorflow1.12.0** execute correct on the same machine.My machine GPU driver version:430.50.The trtis19.09 cuda version:418.87.0

**Comment by zxgm** [comment]
The trtis19.09 + tensorflow1.14 dockfile follow:

> #base
> FROM nvcr.io/nvidia/tensorrtserver:19.09-py3
> 
> RUN apt-get update && apt-get install -y aptitude
> 
> ENV DEBIAN_FRONTEND noninteractive
> RUN apt-get install tzdata
> RUN rm /etc/localtime
> RUN ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
> RUN dpkg-reconfigure -f noninteractive tzdata
> 
> RUN apt-get -y install python3 python3-pip
> 
> RUN apt-get -y install iputils-ping
> 
> RUN pip3 install numpy nvidia-ml-py3 
> 
> RUN pip3 install protobuf3-to-dict==0.1.5
> 
> RUN pip3 install flask requests uwsgi
> 
> RUN pip3 install psutil
> 
> ENV LD_LIBRARY_PATH /usr/local/cuda/compat/lib.real:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
> RUN pip3 install tensorflow==1.14.0
> 
> RUN mkdir /workspace
> 
> COPY . /workspace
> WORKDIR /workspace
> RUN chmod +x /workspace/start_tfsavedmodel.sh
> CMD ["/workspace/start_tfsavedmodel.sh"]

**Comment by deadeyegoodwin** [comment]
The log says that no CUDA is detected and so GPUs won't be used. The model still loaded and will run on CPUs. So it will be slow but usable. Do you find that inferencing doesn't work?
TRTIS supports running on systems without GPUs (and/or without CUDA). See https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/run.html#running-the-inference-server-on-a-system-without-a-gpu
