### ISSUE TITLE
load error when signature changed

### ISSUE THREAD

**Issue by rankeey** [NVIDIA/tensorrt-inference-server#94]
I  load savedmodel with signature key "predict_object", error come out as fellow,  it seems trtis only support "serving_default", is it a bug?
E0215 02:09:14.236638 1 aspired_versions_manager.cc:358] Servable {name: resnet_v1_50_graphdef version: 1} cannot be loaded: Invalid argument: unable to load model 'resnet_v1_50_graphdef', expected 'serving_default' signature

**Comment by deadeyegoodwin** [comment]
I'm not sure I would say it is a bug... perhaps a missing feature. Why are you not using "serving_default"?

**Comment by rankeey** [comment]
Thank you for your response.
Just because someone written the codes using "predict_object", I copied the codes. It's OK to change signature key to "serving_default".

**Comment by deadeyegoodwin** [comment]
The documentation lists some methods for saving (graphdef and savedmodel formats) what use the correct signatures, etc. They are here: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_repository.html#tensorflow-models

Closing this issue. Re-open if you still have issues after saving with the serving key.
