### ISSUE TITLE
No Active Model

### ISSUE THREAD

**Issue by anmol039w** [NVIDIA/tensorrt-inference-server#963]
Hi, I'm trying to build the inference server from Cmake, i have copied the compiled binariues for tensorflow from the trtis docker, and placed them inside build/trtis/install/lib and then using "make" compilled the server, the server is running succesfully but while serving the models from docs/examples/model_repositiory it shows the following error 
root@7e694f77a0a3:/workspace/tensorrt-inference-server/build/trtis/install/bin# ./trtserver --model-repository=/workspace/tensorrt-inference-server/docs/examples/model_repository/simple/
1/            config.pbtxt  
root@7e694f77a0a3:/workspace/tensorrt-inference-server/build/trtis/install/bin# ./trtserver --model-repository=/workspace/tensorrt-inference-server/docs/examples/model_repository/simple/
I1217 04:35:14.061772 35397 metrics.cc:160] found 8 GPUs supporting NVML metrics
I1217 04:35:14.068587 35397 metrics.cc:169]   GPU 0: Tesla V100-SXM2-16GB
I1217 04:35:14.075971 35397 metrics.cc:169]   GPU 1: Tesla V100-SXM2-16GB
I1217 04:35:14.083228 35397 metrics.cc:169]   GPU 2: Tesla V100-SXM2-16GB
I1217 04:35:14.090709 35397 metrics.cc:169]   GPU 3: Tesla V100-SXM2-16GB
I1217 04:35:14.098154 35397 metrics.cc:169]   GPU 4: Tesla V100-SXM2-16GB
I1217 04:35:14.105762 35397 metrics.cc:169]   GPU 5: Tesla V100-SXM2-16GB
I1217 04:35:14.113739 35397 metrics.cc:169]   GPU 6: Tesla V100-SXM2-16GB
I1217 04:35:14.121818 35397 metrics.cc:169]   GPU 7: Tesla V100-SXM2-16GB
I1217 04:35:14.122189 35397 server.cc:112] Initializing TensorRT Inference Server
E1217 04:35:16.127523 35397 server.cc:139] failed to enable peer access for some device pairs
E1217 04:35:16.128120 35397 model_repository_manager.cc:1453] failed to open text file for read /workspace/tensorrt-inference-server/docs/examples/model_repository/simple/1/config.pbtxt: No such file or directory

or the following error 
root@7e694f77a0a3:/workspace/tensorrt-inference-server/build/trtis/install/bin# ./trtserver --model-repository=/workspace/tensorrt-inference-server/docs/examples/model_repository/resnet50_netdef/
I1217 06:22:20.409081 35408 metrics.cc:160] found 8 GPUs supporting NVML metrics
I1217 06:22:20.415617 35408 metrics.cc:169]   GPU 0: Tesla V100-SXM2-16GB
I1217 06:22:20.422636 35408 metrics.cc:169]   GPU 1: Tesla V100-SXM2-16GB
I1217 06:22:20.429639 35408 metrics.cc:169]   GPU 2: Tesla V100-SXM2-16GB
I1217 06:22:20.436719 35408 metrics.cc:169]   GPU 3: Tesla V100-SXM2-16GB
I1217 06:22:20.443891 35408 metrics.cc:169]   GPU 4: Tesla V100-SXM2-16GB
I1217 06:22:20.451274 35408 metrics.cc:169]   GPU 5: Tesla V100-SXM2-16GB
I1217 06:22:20.458836 35408 metrics.cc:169]   GPU 6: Tesla V100-SXM2-16GB
I1217 06:22:20.466542 35408 metrics.cc:169]   GPU 7: Tesla V100-SXM2-16GB
I1217 06:22:20.466983 35408 server.cc:112] Initializing TensorRT Inference Server
E1217 06:22:22.427508 35408 server.cc:139] failed to enable peer access for some device pairs
E1217 06:22:22.427941 35408 model_repository_manager.cc:1453] failed to open text file for read /workspace/tensorrt-inference-server/docs/examples/model_repository/resnet50_netdef/1/config.pbtxt: No such file or directory
E1217 06:22:22.427980 35408 main.cc:1097] error: creating server: INTERNAL - failed to load all models

Are there any steps which i have missed

Thanks in Advance

**Comment by GuanLuo** [comment]
You should set `--model-repository` to be the path until "model_repository", i.e. `--model-repository=/workspace/tensorrt-inference-server/docs/examples/model_repository`. In the polling model control mode (default mode), TRTIS will serve all models within the model repository.
