### ISSUE TITLE
libopencv_imgcodecs.so.3.2 was not found when I tried Example Custom Backend

### ISSUE THREAD

**Issue by hnishi** [NVIDIA/tensorrt-inference-server#964]
**Is your feature request related to a problem? Please describe.**

I tried tutorial of [example-custom-backend](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_repository.html#example-custom-backend).

The custom model was successfully built but Error occured during docker run with the following error message.

```
E1216 08:28:34.583877 1 model_repository_manager.cc:810] failed to load 'image_preprocess_nchw_3x224x224_inception' version 1: Not found: unable to load custom library: libopencv_imgcodecs.so.3.2: cannot open shared object file: No such file or directory
```

**Describe the solution you'd like**

I believe that the default Dockerfile should include opencv libraries for a tutorial of example custom backend.

**Describe alternatives you've considered**

I did not find any documentation about requirements of installing opencv libraries to try example custom backend.
At least, it should be desciribed in the documents for beginners.

**Additional context**

Environment:

- [NVIDIA/tensorrt-inference-server:r19.10](https://github.com/NVIDIA/tensorrt-inference-server/tree/r19.10)
- [Dockerfile](https://github.com/NVIDIA/tensorrt-inference-server/blob/r19.10/Dockerfile) was used to launch TRT server
- [Dockerfile.custombackend](https://github.com/NVIDIA/tensorrt-inference-server/blob/r19.10/Dockerfile.custombackend) was used to build the example custom backend
- CUDA10.1

I solved this problem by installing opencv libraries during docker run.

```
nvidia-docker run --rm \
  --shm-size=1g \
  --ulimit memlock=-1 \
  --ulimit stack=67108864 \
  -p8000:8000 -p8001:8001 -p8002:8002 \
  -e DEBIAN_FRONTEND=noninteractive \
  -v /path/to/ensemble_model_repository:/models \
  tensorrtserver:r19.10 \
  bash -c "apt-get install -y libopencv-dev libopencv-core-dev && trtserver --model-repository=/models"
```

**Comment by GuanLuo** [comment]
Only the server and its dependencies are included in the TRTIS base image. In the example, the OpenCV dependency is introduced by the custom backend rather than the server, so I don't think the OpenCV should not be included in the base image. Instead, I would suggest that we should improve the custom backend documentation to mention that users should ensure that the custom backend's dependencies are satisfied to use the custom backend.

**Comment by deadeyegoodwin** [comment]
I agree with @GuanLuo. If you need additional shared libraries for your custom backend then you should include them along with your custom backend, either by static linking, or by "shipping" shared libraries you need along with the custom backend... or you can always build your own server container based on the official one (it is a simple dockerfile to add some dependencies to an existing container).
