### ISSUE TITLE
Unexpected size for input

### ISSUE THREAD

**Issue by blizda** [NVIDIA/tensorrt-inference-server#967]
I get error from the model during inference 

ailed to update context stat: [inference:0 10] INVALID_ARG - unexpected size for input 'sentence_map', expecting 1 bytes for model 'bert_coref'
Traceback (most recent call last):
  File "test_serving.py", line 147, in <module>
    0)
  File ".conda/envs/tensorflow_1_14_cuda/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 1411, in run
    self._last_request_id = _raise_if_error(c_void_p(_crequest_infer_ctx_run(self._ctx)))
  File ".conda/envs/tensorflow_1_14_cuda/lib/python3.6/site-packages/tensorrtserver/api/__init__.py", line 250, in _raise_if_error
    raise ex
tensorrtserver.api.InferenceServerException: [inference:0 10] unexpected size for input 'sentence_map', expecting 1 bytes for model 'bert_coref'

I start tensorrt inference server with --log-verbose=1 and get same error from the server side

I1217 12:37:53.282247 1 http_server.cc:1106] Infer failed: unexpected size for input 'sentence_map', expecting 1 bytes for model 'bert_coref'

model don't support batching 

model config:

name: "bert_coref"
platform: "tensorflow_savedmodel"
max_batch_size: 0
input [
{
  name: "is_training"
  data_type: TYPE_BOOL
  dims: 1
},
{
  name: "input_ids"
  data_type: TYPE_INT32
  dims: -1
  dims: -1
},
{
  name: "input_mask"
  data_type: TYPE_INT32
  dims: -1
  dims: -1
},
{
  name: "gener"
  data_type: TYPE_INT32
  dims: 1
},
{

  name: "cluster_ids"
  data_type: TYPE_INT32
  dims: -1
},
{
  name: "text_lengths"
  data_type: TYPE_INT32
  dims: -1
},
{
  name: "gold_starts"
  data_type: TYPE_INT32
  dims: -1
}
]
output [
{
  name: "top_span_ends"
  data_type: TYPE_INT32
  dims: -1
},
{
  name: "plasehold_3"
  data_type: TYPE_FP32
  dims: -1
},
{
  name: "plasehold_2"
  data_type: TYPE_INT32
  dims: -1
},
{
  name: "top_span_starts"
  data_type: TYPE_INT32
  dims: -1
},
{
  name: "plasehold_1"
  data_type: TYPE_INT32
  dims: -1
},
{
  name: "top_antecedents"
  data_type: TYPE_INT32
  dims: -1
  dims: -1
},
{
  name: "top_antecedent_scores"
  data_type: TYPE_FP32
  dims: -1
  dims: -1
}
]

original tensorflow inputs:

(tf.int32, [None, None]) # input_ids.
(tf.int32, [None, None]) # input_mask
(tf.int32, [None]) # Text lengths.
(tf.int32, [None, None]) # Speaker IDs.
(tf.int32, []) # Genre.
(tf.bool, []) # Is training.
(tf.int32, [None]) # Gold starts.
(tf.int32, [None]) # Gold ends.
(tf.int32, [None]) # Cluster ids.
(tf.int32, [None]) # Sentence Map

Also, if I try to feed "is_training" or "gener" field to model, I also get error:

tensorrtserver.api.InferenceServerException: [ 0] invalid size 1 bytes for input 'is_training', expects 0 bytes

but, without any errors on server side.

I using TensorRT Inference Server 19.11, and client python library same version.  
How can I resolve this problem?

**Comment by GuanLuo** [comment]
Is `is_training` a scalar instead of a tensor?

**Comment by blizda** [comment]
Tensor, with datatype bool and shape ()

**Comment by blizda** [comment]
> Is `is_training` a scalar instead of a tensor?

Tensor, with datatype bool and shape ()

**Comment by GuanLuo** [comment]
Right, in TensorFlow, a tensor with [rank-0 shape](https://www.tensorflow.org/guide/tensor#rank) (empty shape) is also referring to a scalar. Currently TRTIS only recognize tensor with non-empty shape, see discussion [here](https://github.com/NVIDIA/tensorrt-inference-server/issues/775#issuecomment-544752553) for possible workaround.

**Comment by blizda** [comment]
Thank for help, when i resolve issue with scalars, it also resolve another problems.
