### ISSUE TITLE
Curl request error in tensorrt-inference-server (Infer failed: unexpected size for input 'im_info', expecting 12 bytes for model 'ssd_model2)

### ISSUE THREAD

**Issue by YogeshNain** [NVIDIA/tensorrt-inference-server#975]
**Description**
Getting below error while sending inference request through curl to inference server.

 **### Infer failed: unexpected size for input 'im_info', expecting 12 bytes for model 'ssd_model2'**

Curl Request:

**### curl -X POST localhost:8000/api/infer/ssd_model2 -H "Content-Type: application/octet-stream" -H 'NV-InferRequest:batch_size: 1 input { name: "data" dims:3 dims: 375 dims: 500 } input  { name: "im_info" dims:1 dims: 1 dims: 3 } output { name:     "rois" cls {count:1200} } output { name:     "bbox_pred" cls {count:33200} } output { name:     "cls_prob" cls {count:6300} }' --data-binary "@10.binaryimage"**

Model Api Status:

curl localhost:8000/api/status/ssd_model2
id: "inference:0"
uptime_ns: 7410944210312
model_status {
  key: "ssd_model2"
  value {
    config {
      name: "ssd_model2"
      platform: "tensorrt_plan"
      version_policy {
        latest {
          num_versions: 1
        }
      }
      max_batch_size: 5
      input {
        name: "data"
        data_type: TYPE_FP32
        dims: 3
        dims: 375
        dims: 500
      }
      input {
        name: "im_info"
        data_type: TYPE_FP32
        dims: 1
        dims: 1
        dims: 3
      }
      output {
        name: "rois"
        data_type: TYPE_FP32
        dims: 1
        dims: 300
        dims: 4
      }
      output {
        name: "bbox_pred"
        data_type: TYPE_FP32
        dims: 300
        dims: 84
        dims: 1
        dims: 1
      }
      output {
        name: "cls_prob"
        data_type: TYPE_FP32
        dims: 300
        dims: 21
        dims: 1
        dims: 1
      }
      instance_group {
        name: "ssd_model2"
        count: 1
        gpus: 0
        gpus: 1
        kind: KIND_GPU
      }
      default_model_filename: "model.plan"
    }
    version_status {
      key: 1
      value {
        ready_state: MODEL_READY
      }
    }
  }
}
ready_state: SERVER_READY

How to send im_info data in curl request.

**Comment by zxgm** [comment]
I encounter the same error.But i use the model that support variable size input and batch processing. Request input is support batch processing.I have no ideas about the error.

**Comment by GuanLuo** [comment]
Notice that to send request using CURL directly, you need to construct the HTTP request in the expected form (see documentation [here](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/http_grpc_api.html#inference) for detail).

In short, you need to include the data for all inputs in your request body (for "data" and "im_info"), in your request body, I only see the data for the input "data" and the data for "im_info" is missing.
