### ISSUE TITLE
Does the model support two variable size input dimensions(exclude batch dimension)?

### ISSUE THREAD

**Issue by zxgm** [NVIDIA/tensorrt-inference-server#976]
Does the model by trtis allow only one variable size input dimension (exclude batch dimensions). If the model have two variable size input , the program cannot calculate the size of the other dimensions.Is this correct?

**Comment by GuanLuo** [comment]
TRTIS supports arbitrary number of variable size inputs. TRTIS doesn't try to calculate the shapes of the inputs, in the case of variable size inputs, users need to specify the input dimensions in the infer request header.

**Comment by zxgm** [comment]
How to specify the input dimensions in the infer request header?The documents not discrible the case,only to discrible response output shape

**Comment by zxgm** [comment]
I find the use case in github,Link:https://github.com/Yorwxue/trt_experence/blob/b04591e7f65de72bed922104fe42df6fdc7186a0/trt_client.py. Thank you very much.
