### ISSUE TITLE
/api/status call before initialization causes segfault?

### ISSUE THREAD

**Issue by allenc97** [NVIDIA/tensorrt-inference-server#979]
Hi,

I've recently run into a weird issue where /api/status calls before all the models are initialized in TRTIS causes docker to exit with a segfault. Any idea what might be happening or if I'm doing something wrong?

**Comment by GuanLuo** [comment]
Can you provide a simple steps to reproduce it?

**Comment by CoderHam** [comment]
@allenc97 please re-open this ticket if you are able to reproduce the error. It would be helpful if you share the steps to reproduce the error with us.
