### ISSUE TITLE
The size of the input dimensions that correspand  for each batch  must be equal?

### ISSUE THREAD

**Issue by zxgm** [NVIDIA/tensorrt-inference-server#981]
My request json is follow:
>    model_param = {
>         "inputs": [
>             { # first batch
>                 "user_id": [10],
>                 "item_id": [216],
>                 "hist_i": [285, 43, 8],
>                 "hist_t": [2., 23, 9],
>                 "sl": [14]
>             },
>             { # second batch
>                 "user_id": [100],
>                 "item_id": [21],
>                 "hist_i": [11],
>                 "hist_t": [22.],
>                 "sl": [1]
>             }
>         ]
>     }

The inputs size is batch size, so batch size is 2.First batch input name 'hist_i' dimensions must be equal to second batch input name 'hist_i'? I try write first batch 'hist_i' size is difference with second batch 'hist_i' size,when i execute predict,the error happend.My model support variable size input,the input 'hist_i' and 'hist_t' supports variable size.

> {"error": "code: INVALID_ARG msg: \"unexpected size for input \\'hist_t\\', expecting 8 bytes for model \\'simple\\'\" server_id: \"inference:0\" request_id: 82"}

The nvRequst header is 

> batch_size: 2 input { name: 'user_id' dims: 1} input { name: 'item_id' dims: 1} input { name: 'hist_i' dims: 3} input { name: 'hist_t' dims: 3} input { name: 'sl' dims: 1} output { name: 'eval_logits' }

**Comment by GuanLuo** [comment]
What is your model config? I think at least one of the request is not valid for your model config. Notice that for "hist_i" and "hist_t", the largest difference is that their numbers of tensor dimensions don't matches. TRTIS allows variable shape tensor in the sense that the number of tensor dimensions is fixed while the number of entries in each dimension can vary. The information you provided is not this case...

**Comment by zxgm** [comment]
Yes,the second request is invalid.The result by call status interface is follow:

> id: "inference:0"
> version: "1.6.0"
> uptime_ns: 38681762877
> model_status {
>   key: "saved_model"
>   value {
>     config {
>       name: "saved_model"
>       platform: "tensorflow_savedmodel"
>       version_policy {
>         latest {
>           num_versions: 1
>         }
>       }
>       max_batch_size: 128
>       input {
>         name: "hist_i"
>         data_type: TYPE_INT32
>         dims: -1
>       }
>       input {
>         name: "user_id"
>         data_type: TYPE_INT64
>         dims: 1
>         reshape {
>         }
>       }
>       input {
>         name: "item_id"
>         data_type: TYPE_INT32
>         dims: 1
>         reshape {
>         }
>       }
>       input {
>         name: "hist_t"
>         data_type: TYPE_INT32
>         dims: -1
>       }
>       input {
>         name: "sl"
>         data_type: TYPE_INT32
>         dims: 1
>         reshape {
>         }
>       }
>       output {
>         name: "eval_logits"
>         data_type: TYPE_FP32
>         dims: 1
>         reshape {
>         }
>       }
>       instance_group {
>         name: "saved_model_0"
>         count: 1
>         gpus: 0
>         kind: KIND_GPU
>       }
>       default_model_filename: "model.savedmodel"
>       dynamic_batching {
>         preferred_batch_size: 8
>         max_queue_delay_microseconds: 1000
>       }
>     }
>     version_status {
>       key: 1
>       value {
>         ready_state: MODEL_READY
>       }
>     }
>   }
> }
> status_stats {
>   success {
>     count: 2
>     total_time_ns: 31569130
>   }
> }
> ready_state: SERVER_READY
I read the source of tensorrt-inference -server,the found error msg in 843 line of http_server.cc.First allocate the total memory block bytes by nvRequest header=batch_size*(sizeof(firstinput_data_type)*firstinput_dims+sizeof(secondinput_data_type)*secondinput_dims+...),
the above case,the actual total memory block bytes is less than calculate block bytes, so error have happended.So i must make sure the second batch dims is equal to first batch dims?

**Comment by GuanLuo** [comment]
Yes, for batched requests, the dimensions for all batch entries must be identical. Since you have dynamic batching enabled, you can just send the requests separately and let the dynamic batcher handling the batching for you

**Comment by zxgm** [comment]
OK,I understand.Thank you very much.
