### ISSUE TITLE
Questions Regarding Failures

### ISSUE THREAD

**Issue by JulianOrteil** [NVIDIA/tensorrt-inference-server#982]
Good morning.

The company I work for is currently on a technological revamp and AI is one of the main focuses of it. I have a few questions regarding the reliability of TRTIS that hopefully some of you might be able to answer?

We are wondering:
What does the server do when it it receives more requests than it can handle? Are the extra requests dropped?
Will the server be able to automatically "reboot" (per se) if it becomes overloaded and locks up?
How often should the server be restarted to clear caches and RAM?
If we have two physical servers, one primary and one secondary, will the primary failover to the secondary if an issue occurs? (Or is this a programming thing that the client should handle)

We really like the idea of having TRTIS run AI on our production floor, we just would like to know the software thoroughly before we deploy it.

Thanks!
Jules

**Comment by deadeyegoodwin** [comment]
TRTIS does not drop requests (though there have been asks for TRTIS to allow individual requests to specify a timeout... we have not implemented anything like that yet). For each model there is a queue that holds all requests for that model. These queues do not have a maximum size. When the server is overloaded the latency for individual requests will grow dramatically and the expectation is that some outside "agent" will load-balance/scale as necessary. In addition to request latency TRTIS also provides some prometheus metrics that can be used to detect overloaded https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/metrics.html

TRTIS does not have any capability to auto-reboot. Here again we expect an outside "agent" to monitor and restart TRTIS when necessary (for example kubernetes). In general we have not found TRTIS to be overly prone to hanging or aborting.

We don't have any specific guidance for "how often to restart". TRTIS is somewhat at the mercy of the framework backends as to how efficiently and correctly they use memory. For example, we have found some issues with PyTorch around memory usage and when we do we file bugs with the upstream project. We do have some stress testing where we repeatedly load/unload models a large number of times for each framework and we haven't found any persistent bad behavior that would require a standard restart policy. But we'd be interesting in learning if you have a specific requirement.

Fallover / failover would be something that would need to be handled by the orchestration / deployment environment you were using with TRTIS (e.g. kubernetes). TRTIS does provide the metrics as well as health endpoints (https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/http_grpc_api.html#section-api-health) to aid the orchestrator. We are always interested in learning if there is some additional support that TRTIS could provide to enable easier implementation of uses like failover.

We have a large number of stress and other testing that we use with TRTIS (and provided on github) that gives us good confidence in its robustness. You can run these locally in your deployment as well to perform some local stress-testing. Many users also use the perf_client tool along with their own models to stress-test and evaluate TRTIS within their own deployments. https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/optimization.html#perf-client

**Comment by JulianOrteil** [comment]
Excellent, thank you very much for the information.
