### ISSUE TITLE
What is the reason not to use the tensorflow serving?

### ISSUE THREAD

**Issue by sihanwang-pinterest** [NVIDIA/tensorrt-inference-server#987]
Hi,
I am learning the TensorRT code, i find that TensorRT gets rid of the tensorflow serving in v1.3.0, could someone help to explain what is the technical reason that the backend need to be rebuilt? Any limitations in tensorflow serving?

Thank you
Sihan

**Comment by GuanLuo** [comment]
When using TensorFlow Serving, it introduce a dependency on TensorFlow, and that causes TRTIS to always build with TensorFlow. This is slow to build and mandatory even you are intended to use TRTIS to serve models in other framework. With the backend rebuilt, TensorFlow now became a build option and the TRTIS build itself is light-weight

**Comment by deadeyegoodwin** [comment]
TFServing and TRTIS are completely different inference servers. Initially TRTIS was built "on top of" TFServing but that connection was removed some time ago. 

Are you asking what features and advantages TRTIS provides compared to TFServing?

**Comment by sihanwang-pinterest** [comment]
Thank you @GuanLuo for providing the information.

Hi @deadeyegoodwin, It would be very helpful if you can provide some high level comparison about the features in TRTIS compared to TFServing.

Sihan

**Comment by deadeyegoodwin** [comment]
The primary difference is that TFServing supports only TensorFlow models. TRTIS supports TF, PyTorch, ONNX, TensorRT and Caffe2; and also has the ability for you to provide "custom" models that can be implemented with arbitrary C/C++ code.

TRTIS has a large number of features focused on performance, especially performance on GPUs but for the most part applicable to CPUs as well. The README lists many of these features: https://github.com/NVIDIA/tensorrt-inference-server/blob/master/README.rst

Is there some specific requirements that you have that are most important for you to compare?

**Comment by deadeyegoodwin** [comment]
See also this FAQ: https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-guide/docs/faq.html#what-are-the-advantages-of-running-a-model-with-tensorrt-inference-server-compared-to-running-directly-using-the-model-s-framework-api

**Comment by Robbie-Palmer** [comment]
@deadeyegoodwin I think it's good to clarify that TFServing can support models from other ML Frameworks, but this support isn't available out of the box, it will be like providing those custom models for TRTIS
From the [TFServing README](https://github.com/tensorflow/serving/blob/master/README.md#tensorflow-serving):
> Supports many servables: Tensorflow models, embeddings, vocabularies, feature transformations and even non-Tensorflow-based machine learning models
