### ISSUE TITLE
Ensembling : Python custom operation

### ISSUE THREAD

**Issue by Narasimha1997** [NVIDIA/tensorrt-inference-server#988]
Hey community, I was working with Tensor-RT inference server. I came across Custom Operations where we can create our own pre-processing blocks. The example states about using C++ to write a Pre-Processor. Is it possible with Python ? If yes, can somone provide an example. 

Thank you

**Comment by GuanLuo** [comment]
For ensemble, the building blocks are in terms of individual models, you would need to create a custom backend which is implemented over the [C interface API](https://docs.nvidia.com/deeplearning/sdk/tensorrt-inference-server-master-branch-guide/docs/model_repository.html#custom-backend-api).
If your preprocess task must be done in Python, you may be able to wrap the Python script execution in the custom backend, and feel free to provide such example if feasible.
