### ISSUE TITLE
kInvalidBinNum error

### ISSUE THREAD

**Issue by bezero** [NVIDIA/tensorrt-inference-server#99]
Currently I am running tensorrtserver:19.01-py3 and I got following error message and stopped working:
`E0213 17:49:43.688371 1 bfc_allocator.cc:458] Check failed: c->in_use() && (c->bin_num == kInvalidBinNum)`

What is the source of this error? Can it be avoided somewhat? 
If possible, can you tell when nvcr.io/nvidia/tensorrtserver:19.02-py3 image will be available?

**Comment by nieksand** [comment]
This looks similar:
* https://github.com/tensorflow/serving/issues/1206

That thread points to this:
* https://github.com/tensorflow/tensorflow/issues/22581
