### ISSUE TITLE
Is tensorrt-inference-server support savedmodel model that include sparse tensor input?

### ISSUE THREAD

**Issue by zxgm** [NVIDIA/tensorrt-inference-server#991]
Is tensorrt-inference-server support savedmodel model that include sparse tensor input??The details:https://github.com/NVIDIA/tensorrt-inference-server/issues/989

**Comment by deadeyegoodwin** [comment]
The TRTIS API (REST/GRPC/shared-library) do not support sparse tensors. You must send full tensor data for for input tensor. Do you have a TF model that specifically requires a sparse tensor as input?

**Comment by zxgm** [comment]
Yes, I have a TF .pb format model that requires a sparse tensor as input.I can use the TF API convert sparse tensor to dense tensor,Then save .pb model,but the calculate sparse tensor will consume more memory and low efficiency.Can you give me some other ideas?

**Comment by deadeyegoodwin** [comment]
Right now TRTIS API doesn't support sparse tensors. Have you tried running with non-sparse tensors to see what the perf difference is? We will add a feature request for sparse tensor support and so maybe in the future we can support directly.
