### ISSUE TITLE
How to send integer string to inference server by http?

### ISSUE THREAD

**Issue by zxgm** [NVIDIA/tensorrt-inference-server#999]
Now,i send integer string to inference server by http that in order to calculate integer.It has two input name, INPUT0:["123456"],INPUT1:["23456"],and exptected output result  is ["146912"],and NVRequestHeader follow:

> batch_size: 1 input { name: 'INPUT0' dims: 1 batch_byte_size: 6} input { name: 'INPUT1' dims: 1 batch_byte_size: 5} output { name: 'OUTPUT0' } output { name: 'OUTPUT1' }

The NVRequestBody content must be raw binary, i convert string to bytes by string_data.encode(encoding="utf-8") ,then called predict interface,but hit a tensorflow error:

> {"error": "code: INTERNAL msg: \"2 root error(s) found.\\n  (0) Invalid argument: StringToNumberOp could not correctly convert string: \\n\\t [[{{node StringToNumber_1}}]]\\n\\t [[StringToNumber_1/_3]]\\n  (1) Invalid argument: StringToNumberOp could not correctly convert string: \\n\\t [[{{node StringToNumber_1}}]]\\n0 successful operations.\\n0 derived errors ignored.\" server_id: \"inference:0\" request_id: 25"}

I think trtis  have't use decode() function to convert bytes to string that cause the decode string is not integer string.So i want to know how to convert string to bytes?And trtis how to convert bytes to string?

**Comment by deadeyegoodwin** [comment]
Are you using the TRTIS client library or are you creating the HTTP request yourself? I would guess that you are doing it yourself and encoding the strings incorrectly in the body. A string element in a tensor must be encoded as 4-byte string length followed by the actual string bytes.

The current  HTTP/REST protocol is not well documented. We are working on a V2 of the HTTP/REST protocol that is JSON-based and must easier to use and well documented.

**Comment by zxgm** [comment]
I tried the method that you told on my program,that is work.Thank you very much!!

**Comment by SuoSiFire** [comment]
> Are you using the TRTIS client library or are you creating the HTTP request yourself? I would guess that you are doing it yourself and encoding the strings incorrectly in the body. A string element in a tensor must be encoded as 4-byte string length followed by the actual string bytes.
> 
> The current HTTP/REST protocol is not well documented. We are working on a V2 of the HTTP/REST protocol that is JSON-based and must easier to use and well documented.

@deadeyegoodwin 
"A string element in a tensor must be encoded as 4-byte string length followed by the actual string bytes."

What is the generation method of the first 4-byte? Are there any encoding and decoding codes? thanks.
